<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="Transfer"
    targetNamespace="http://www.globus.org/transfer" 
    xmlns:tns="http://www.globus.org/transfer" 
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <wsdl:types>
    <xs:schema>
      <xs:import
        namespace="http://www.globus.org/transfer"
        schemaLocation="transfer.xsd" />

    </xs:schema>
  </wsdl:types>

  <wsdl:message name="EmptyMessage">
    <wsdl:part name="Body" type="tns:emptyType"/>
  </wsdl:message>

  <wsdl:message name="AnyXmlMessage">
    <wsdl:part name="Body" type="tns:AnyXmlType"/>
  </wsdl:message>

  <wsdl:portType name="Resource">
    <wsdl:documentation>
      This port type defines a resource that may be read, written, and deleted.
    </wsdl:documentation>

    <wsdl:operation name="Get">
      <wsdl:input
          message="tns:EmptyMessage" 
          wsa:Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get" />


      <wsdl:output
          message="tns:AnyXmlMessage"
          wsa:Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse" />
    </wsdl:operation>

  </wsdl:portType>

</wsdl:definitions>
