<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Transfer" targetNamespace="http://www.globus.org/transfer/bindings" xmlns:porttype="http://www.globus.org/transfer" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.globus.org/transfer" location="transfer_port_type.wsdl"/>
  <wsdl:binding name="ResourceSOAPBinding" type="porttype:Resource">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Get">
      <soap:operation soapAction="http://www.globus.org/transfer/Resource/GetRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
