package gov.nih.nci.caxchange.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.caxchange.stubs.CaXchangeConsumerServicePortType;
import gov.nih.nci.caxchange.stubs.service.CaXchangeConsumerServiceAddressingLocator;
import gov.nih.nci.caxchange.common.CaXchangeConsumerServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.4
 */
public class CaXchangeConsumerServiceClient extends CaXchangeConsumerServiceClientBase implements CaXchangeConsumerServiceI {	

	public CaXchangeConsumerServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public CaXchangeConsumerServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public CaXchangeConsumerServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public CaXchangeConsumerServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(CaXchangeConsumerServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  CaXchangeConsumerServiceClient client = new CaXchangeConsumerServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public messaging.ConsumerResponseMessage process(messaging.Message caXchangeRequestMessage) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"process");
    gov.nih.nci.caxchange.stubs.ProcessRequest params = new gov.nih.nci.caxchange.stubs.ProcessRequest();
    gov.nih.nci.caxchange.stubs.ProcessRequestCaXchangeRequestMessage caXchangeRequestMessageContainer = new gov.nih.nci.caxchange.stubs.ProcessRequestCaXchangeRequestMessage();
    caXchangeRequestMessageContainer.setCaXchangeRequestMessage(caXchangeRequestMessage);
    params.setCaXchangeRequestMessage(caXchangeRequestMessageContainer);
    gov.nih.nci.caxchange.stubs.ProcessResponse boxedResult = portType.process(params);
    return boxedResult.getCaXchangeConsumerResponse();
    }
  }

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

}
