insert into CATISSUE_SPECIMEN_EVENT_PARAM (select * from catissuecore.CATISSUE_SPECIMEN_EVENT_PARAMETERS);
insert into CATISSUE_PROCEDURE_EVENT_PARAM (select * from catissuecore.CATISSUE_PROCEDURE_EVENT_PARAMETERS);
insert into CATISSUE_DISPOSAL_EVENT_PARAM (select * from catissuecore.CATISSUE_DISPOSAL_EVENT_PARAMETERS);
insert into CATISSUE_TRANSFER_EVENT_PARAM (select * from catissuecore.CATISSUE_TRANSFER_EVENT_PARAMETER);
insert into CATISSUE_RECEIVED_EVENT_PARAM (select * from catissuecore.CATISSUE_RECEIVED_EVENT_PARAMETERS);
insert into CATISSUE_FIXED_EVENT_PARAM (select * from catissuecore.CATISSUE_FIXED_EVENT_PARAMETERS);
insert into CATISSUE_FROZEN_EVENT_PARAM (select * from catissuecore.CATISSUE_FROZEN_EVENT_PARAMETERS);
insert into CATISSUE_EMBEDDED_EVENT_PARAM (select * from catissuecore.CATISSUE_EMBEDDED_EVENT_PARAMETERS);
insert into CATISSUE_EVENT_PARAM (select * from catissuecore.CATISSUE_REVIEW_EVENT_PARAMETERS);
insert into CATISSUE_COLL_EVENT_PARAM (select * from catissuecore.CATISSUE_COLLECTION_EVENT_PARAMETERS);
insert into CATISSUE_COLL_PROT_REG (select * from catissuecore.CATISSUE_COLLECTION_PROTOCOL_REGISTRATION);
insert into CATISSUE_COLL_SPECIMEN_REQ (select * from catissuecore.CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT);
insert into CATISSUE_SPECIMEN_BIOHZ_REL (select * from catissuecore.CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP);
insert into CATISSUE_COLL_COORDINATORS (select * from catissuecore.CATISSUE_COLLECTION_COORDINATORS);
insert into CATISSUE_CELL_SPE_REVIEW_PARAM (select * from catissuecore.CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS);
insert into CATISSUE_STORAGE_CONT_CAPACITY (select * from catissuecore.CATISSUE_STORAGE_CONTAINER_CAPACITY);
insert into CATISSUE_SPECIMEN_CHAR (select * from catissuecore.CATISSUE_SPECIMEN_CHARACTERISTICS);
insert into CATISSUE_COLL_DISTRIBUTION_REL (select * from catissuecore.CATISSUE_COLLECTION_DISTRIBUTION_RELATION);
insert into CATISSUE_SPECIMEN_COLL_GROUP (select * from catissuecore.CATISSUE_SPECIMEN_COLLECTION_GROUP);
insert into CATISSUE_MOL_SPE_REVIEW_PARAM (select * from catissuecore.CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS);
insert into CATISSUE_IN_OUT_EVENT_PARAM (select * from catissuecore.CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER);
insert into CATISSUE_STORAGE_CONT_DETAILS (select * from catissuecore.CATISSUE_STORAGE_CONTAINER_DETAILS);
insert into CATISSUE_QUERY_TABLE_DATA (select * from catissuecore.CATISSUE_QUERY_INTERFACE_TABLE_DATA);
insert into CATISSUE_PART_MEDICAL_ID (select * from catissuecore.CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER);
insert into CATISSUE_TIS_SPE_EVENT_PARAM (select * from catissuecore.CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS);
insert into CATISSUE_COLL_PROT_EVENT (select * from catissuecore.CATISSUE_COLLECTION_PROTOCOL_EVENT);
insert into CATISSUE_INTERFACE_COLUMN_DATA (select * from catissuecore.CATISSUE_QUERY_INTERFACE_COLUMN_DATA);
insert into CATISSUE_FLUID_SPE_EVENT_PARAM (select * from catissuecore.CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS);
insert into CATISSUE_DISTRIBUTION_SPE_REQ (select * from catissuecore. CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT);
/*----*/
insert into CATISSUE_SPUN_EVENT_PARAMETERS ( select * from catissuecore.CATISSUE_SPUN_EVENT_PARAMETERS);
insert into CATISSUE_PERMISSIBLE_VALUE ( select * from catissuecore.CATISSUE_PERMISSIBLE_VALUE);
insert into CATISSUE_CANCER_RESEARCH_GROUP ( select * from catissuecore.CATISSUE_CANCER_RESEARCH_GROUP);
insert into CATISSUE_COLLECTION_PROTOCOL ( select * from catissuecore.CATISSUE_COLLECTION_PROTOCOL);
insert into CATISSUE_STORAGE_TYPE ( select * from catissuecore.CATISSUE_STORAGE_TYPE);
insert into CATISSUE_SITE ( select * from catissuecore.CATISSUE_SITE);
insert into CATISSUE_CDE ( select * from catissuecore.CATISSUE_CDE);
insert into CATISSUE_SPECIMEN_REQUIREMENT ( select * from catissuecore.CATISSUE_SPECIMEN_REQUIREMENT);
insert into CATISSUE_INSTITUTION ( select * from catissuecore.CATISSUE_INSTITUTION);
insert into CATISSUE_AUDIT_EVENT ( select * from catissuecore.CATISSUE_AUDIT_EVENT);
insert into CATISSUE_SPECIMEN_PROTOCOL ( select * from catissuecore.CATISSUE_SPECIMEN_PROTOCOL);
insert into CATISSUE_BIOHAZARD ( select * from catissuecore.CATISSUE_BIOHAZARD);
insert into CATISSUE_CLINICAL_REPORT ( select * from catissuecore.CATISSUE_CLINICAL_REPORT);
insert into CATISSUE_ADDRESS ( select * from catissuecore.CATISSUE_ADDRESS);
insert into CATISSUE_REPORTED_PROBLEM ( select * from catissuecore.CATISSUE_REPORTED_PROBLEM);
insert into CATISSUE_DISTRIBUTED_ITEM ( select * from catissuecore.CATISSUE_DISTRIBUTED_ITEM);
insert into CATISSUE_PARTICIPANT ( select * from catissuecore.CATISSUE_PARTICIPANT);
insert into CATISSUE_AUDIT_EVENT_LOG ( select * from catissuecore.CATISSUE_AUDIT_EVENT_LOG);
insert into CATISSUE_STORAGE_CONTAINER ( select * from catissuecore.CATISSUE_STORAGE_CONTAINER);
insert into CATISSUE_DISTRIBUTION ( select * from catissuecore.CATISSUE_DISTRIBUTION);
insert into CATISSUE_AUDIT_EVENT_DETAILS ( select * from catissuecore.CATISSUE_AUDIT_EVENT_DETAILS);
insert into CATISSUE_DISTRIBUTION_PROTOCOL ( select * from catissuecore.CATISSUE_DISTRIBUTION_PROTOCOL);
insert into CATISSUE_DEPARTMENT ( select * from catissuecore.CATISSUE_DEPARTMENT);
insert into CATISSUE_EXTERNAL_IDENTIFIER ( select * from catissuecore.CATISSUE_EXTERNAL_IDENTIFIER);
insert into CATISSUE_THAW_EVENT_PARAMETERS ( select * from catissuecore.CATISSUE_THAW_EVENT_PARAMETERS);
insert into CATISSUE_SPECIMEN ( select * from catissuecore.CATISSUE_SPECIMEN);
insert into CATISSUE_USER ( select * from catissuecore.CATISSUE_USER);
insert into CATISSUE_TABLE_RELATION (select * from catissuecore.CATISSUE_TABLE_RELATION);
insert into CATISSUE_SEARCH_DISPLAY_DATA (select * from catissuecore.CATISSUE_SEARCH_DISPLAY_DATA);
insert into CATISSUE_RELATED_TABLES_MAP (select * from catissuecore.CATISSUE_RELATED_TABLES_MAP);

Insert into CSM_APPLICATION (select * from catissuecore.CSM_APPLICATION);
Insert into CSM_GROUP (select * from catissuecore.CSM_GROUP);
Insert into CSM_PG_PE (select * from catissuecore.CSM_PG_PE);
Insert into CSM_PRIVILEGE (select * from catissuecore.CSM_PRIVILEGE);
Insert into CSM_PROTECTION_ELEMENT (select * from catissuecore.CSM_PROTECTION_ELEMENT);
Insert into CSM_PROTECTION_GROUP (select * from catissuecore.CSM_PROTECTION_GROUP);
Insert into CSM_ROLE (select * from catissuecore.CSM_ROLE);
Insert into CSM_ROLE_PRIVILEGE (select * from catissuecore.CSM_ROLE_PRIVILEGE);
Insert into CSM_USER (select * from catissuecore.CSM_USER);
Insert into CSM_USER_GROUP (select * from catissuecore.CSM_USER_GROUP);
Insert into CSM_USER_GROUP_ROLE_PG (select * from catissuecore.CSM_USER_GROUP_ROLE_PG);
Insert into CSM_USER_PE (select * from catissuecore.CSM_USER_PE);

#update the alias name
update csm_protection_element set OBJECT_ID='edu.wustl.catissuecore.action.SimpleQueryInterfaceAction_CollectionProtReg' where PROTECTION_ELEMENT_ID = 264;