/*************** RELATIONSHIP QUERIES FOR SpecimenEventParameters and User RELATIONSHIP *******************/
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID) values (107,23,63);
INSERT INTO CATISSUE_RELATED_TABLES_MAP(FIRST_TABLE_ID,SECOND_TABLE_ID,FIRST_TABLE_JOIN_COLUMN,SECOND_TABLE_JOIN_COLUMN) VALUES(23,63,'IDENTIFIER','USER_ID');
