Drop DATABASE if exists @@STAGING_DB_NAME@@;    

CREATE DATABASE @@STAGING_DB_NAME@@;

use @@STAGING_DB_NAME@@;

GRANT ALL PRIVILEGES ON @@STAGING_DB_NAME@@.* TO '@@STAGING_DB_USER_NAME@@'@'localhost' IDENTIFIED BY '@@STAGING_DB_PASSWORD@@' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON @@STAGING_DB_NAME@@.* TO '@@STAGING_DB_USER_NAME@@'@'%' IDENTIFIED BY '@@STAGING_DB_PASSWORD@@' WITH GRANT OPTION;

commit;