alter table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS drop constraint FK1A13AD3DBC7298A9
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION drop constraint FK9FAF7E1B48304401
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION drop constraint FK9FAF7E1B87E5ADC7
alter table CATISSUE_COLLECTION_PROTOCOL drop constraint FK32DC439DBC7298A9
alter table CATISSUE_TISSUE_SPECIMEN drop constraint FKB9860FA6BC7298A9
alter table CATISSUE_CELL_SPECIMEN_REQUIREMENT drop constraint FK4407C9ADBC7298A9
alter table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT drop constraint FKD0AC7D37BC7298A9
alter table CATISSUE_STORAGE_TYPE drop constraint FKE9A0629A5F7CB0FE
alter table CATISSUE_SITE drop constraint FKB024C3436CD94566
alter table CATISSUE_SITE drop constraint FKB024C3432206F20F
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop constraint FK4645C5AC3C2DAC61
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop constraint FK4645C5ACBC7298A9
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop constraint FK4645C5AC99DF0A92
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP drop constraint FK108D68F860773DB2
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP drop constraint FK108D68F8F398D480
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT drop constraint FK20ECDAF1BE10F0CE
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT drop constraint FK20ECDAF153B01F66
alter table CATISSUE_FLUID_SPECIMEN drop constraint FK461E42F9BC7298A9
alter table CATISSUE_AUDIT_EVENT drop constraint FKACAF697A2206F20F
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop constraint FK92169759DCC1E13B
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop constraint FK92169759A7F77D13
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop constraint FK921697594CE21DDA
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop constraint FK9216975953B01F66
alter table CATISSUE_SPECIMEN_PROTOCOL drop constraint FKB8481373870EB740
alter table CATISSUE_SPUN_EVENT_PARAMETERS drop constraint FK312D77BCBC7298A9
alter table CATISSUE_FLUID_SPECIMEN_REQUIREMENT drop constraint FK3F2563DDBC7298A9
alter table CATISSUE_DISPOSAL_EVENT_PARAMETERS drop constraint FK66A78F21BC7298A9
alter table CATISSUE_CLINICAL_REPORT drop constraint FK54A4264DEED9EFB
alter table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS drop constraint FKE42CFF45BC7298A9
alter table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER drop constraint FK88A378F9BC7298A9
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION drop constraint FKE2E444726B1F36E7
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION drop constraint FKE2E4447248304401
alter table CATISSUE_COLLECTION_COORDINATORS drop constraint FK96FACDC848304401
alter table CATISSUE_COLLECTION_COORDINATORS drop constraint FK96FACDC82206F20F
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT drop constraint FK9FE639CB6B1F36E7
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT drop constraint FK9FE639CBBE10F0CE
alter table CATISSUE_DISTRIBUTED_ITEM drop constraint FKA7C3ED4B60773DB2
alter table CATISSUE_DISTRIBUTED_ITEM drop constraint FKA7C3ED4BF8278B6
alter table CATISSUE_RECEIVED_EVENT_PARAMETERS drop constraint FKC3D728F1BC7298A9
alter table CATISSUE_FROZEN_EVENT_PARAMETERS drop constraint FKDD06C312BC7298A9
alter table CATISSUE_AUDIT_EVENT_LOG drop constraint FK8BB672DF77F0B904
alter table CATISSUE_PROCEDURE_EVENT_PARAMETERS drop constraint FK6612CBD7BC7298A9
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER drop constraint FKD081FCDFA7F77D13
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER drop constraint FKD081FCDF87E5ADC7
alter table CATISSUE_STORAGE_CONTAINER_DETAILS drop constraint FK66CE30E4B3DFB11D
alter table CATISSUE_MOLECULAR_SPECIMEN drop constraint FKDD4D1353BC7298A9
alter table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS drop constraint FKD9ABD790BC7298A9
alter table CATISSUE_STORAGE_CONTAINER drop constraint FK28429D015F7CB0FE
alter table CATISSUE_STORAGE_CONTAINER drop constraint FK28429D01A7F77D13
alter table CATISSUE_STORAGE_CONTAINER drop constraint FK28429D0159A3CE5C
alter table CATISSUE_STORAGE_CONTAINER drop constraint FK28429D01DB097B2E
alter table CATISSUE_DISTRIBUTION drop constraint FK542766806B1F36E7
alter table CATISSUE_DISTRIBUTION drop constraint FK542766801DBE834F
alter table CATISSUE_DISTRIBUTION drop constraint FK54276680BC7298A9
alter table CATISSUE_DISTRIBUTION drop constraint FK54276680FB9AE97E
alter table CATISSUE_EMBEDDED_EVENT_PARAMETERS drop constraint FK1AE03F68BC7298A9
alter table CATISSUE_AUDIT_EVENT_DETAILS drop constraint FK5C07745D34FFD77F
alter table CATISSUE_COLLECTION_PROTOCOL_EVENT drop constraint FKF6A1375848304401
alter table CATISSUE_DISTRIBUTION_PROTOCOL drop constraint FKC8999977BC7298A9
alter table CATISSUE_REVIEW_EVENT_PARAMETERS drop constraint FK621FE55ABC7298A9
alter table CATISSUE_EXTERNAL_IDENTIFIER drop constraint FK5CF2FA2160773DB2
alter table CATISSUE_THAW_EVENT_PARAMETERS drop constraint FKD8890A48BC7298A9
alter table CATISSUE_FIXED_EVENT_PARAMETERS drop constraint FK82DC0356BC7298A9
alter table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS drop constraint FKE2FE9B3BBC7298A9
alter table CATISSUE_SPECIMEN drop constraint FK1674810456906F39
alter table CATISSUE_SPECIMEN drop constraint FK1674810433BF33C5
alter table CATISSUE_SPECIMEN drop constraint FK16748104B189E99D
alter table CATISSUE_SPECIMEN drop constraint FK1674810432B31EAB
alter table CATISSUE_USER drop constraint FKB025CFC71792AD22
alter table CATISSUE_USER drop constraint FKB025CFC7FFA96920
alter table CATISSUE_USER drop constraint FKB025CFC76CD94566
alter table CATISSUE_USER drop constraint FKB025CFC7F30C2528
alter table CATISSUE_CELL_SPECIMEN drop constraint FKCD8EE0C9BC7298A9
alter table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT drop constraint FK67C6950ABC7298A9
alter table CATISSUE_COLLECTION_EVENT_PARAMETERS drop constraint FKFB1108D4BC7298A9
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS drop constraint FK2C72A2AA60773DB2
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS drop constraint FK2C72A2AA2206F20F
drop table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION cascade constraints
drop table CATISSUE_CANCER_RESEARCH_GROUP cascade constraints
drop table CATISSUE_COLLECTION_PROTOCOL cascade constraints
drop table CATISSUE_SPECIMEN_CHARACTERISTICS cascade constraints
drop table CATISSUE_TISSUE_SPECIMEN cascade constraints
drop table CATISSUE_CELL_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_STORAGE_TYPE cascade constraints
drop table CATISSUE_SITE cascade constraints
drop table CATISSUE_TRANSFER_EVENT_PARAMETER cascade constraints
drop table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP cascade constraints
drop table CATISSUE_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_INSTITUTION cascade constraints
drop table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_FLUID_SPECIMEN cascade constraints
drop table CATISSUE_AUDIT_EVENT cascade constraints
drop table CATISSUE_SPECIMEN_COLLECTION_GROUP cascade constraints
drop table CATISSUE_SPECIMEN_PROTOCOL cascade constraints
drop table CATISSUE_BIOHAZARD cascade constraints
drop table CATISSUE_SPUN_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_FLUID_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_DISPOSAL_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_CLINICAL_REPORT cascade constraints
drop table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS cascade constraints
drop table CATISSUE_ADDRESS cascade constraints
drop table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER cascade constraints
drop table CATISSUE_REPORTED_PROBLEM cascade constraints
drop table CATISSUE_COLLECTION_DISTRIBUTION_RELATION cascade constraints
drop table CATISSUE_COLLECTION_COORDINATORS cascade constraints
drop table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_DISTRIBUTED_ITEM cascade constraints
drop table CATISSUE_RECEIVED_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_PARTICIPANT cascade constraints
drop table CATISSUE_FROZEN_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_AUDIT_EVENT_LOG cascade constraints
drop table CATISSUE_PROCEDURE_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER cascade constraints
drop table CATISSUE_STORAGE_CONTAINER_DETAILS cascade constraints
drop table CATISSUE_MOLECULAR_SPECIMEN cascade constraints
drop table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_STORAGE_CONTAINER cascade constraints
drop table CATISSUE_DISTRIBUTION cascade constraints
drop table CATISSUE_EMBEDDED_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_AUDIT_EVENT_DETAILS cascade constraints
drop table CATISSUE_COLLECTION_PROTOCOL_EVENT cascade constraints
drop table CATISSUE_DISTRIBUTION_PROTOCOL cascade constraints
drop table CATISSUE_REVIEW_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_EXTERNAL_IDENTIFIER cascade constraints
drop table CATISSUE_DEPARTMENT cascade constraints
drop table CATISSUE_THAW_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_FIXED_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS cascade constraints
drop table CATISSUE_SPECIMEN cascade constraints
drop table CATISSUE_USER cascade constraints
drop table CATISSUE_CELL_SPECIMEN cascade constraints
drop table CATISSUE_STORAGE_CONTAINER_CAPACITY cascade constraints
drop table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT cascade constraints
drop table CATISSUE_COLLECTION_EVENT_PARAMETERS cascade constraints
drop table CATISSUE_SPECIMEN_EVENT_PARAMETERS cascade constraints
drop sequence hibernate_sequence
create table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   NEOPLASTIC_CELLULARITY_PERCENTAGE double precision,
   NECROSIS_PERCENTAGE double precision,
   LYMPHOCYTIC_PERCENTAGE double precision,
   TOTAL_CELLULARITY_PERCENTAGE double precision,
   HISTOLOGICAL_QUALITY varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION (
   IDENTIFIER number(19,0) not null,
   PROTOCOL_PARTICIPANT_IDENTIFIER varchar2(50),
   REGISTRATION_DATE date,
   PARTICIPANT_ID number(19,0),
   COLLECTION_PROTOCOL_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_CANCER_RESEARCH_GROUP (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50) not null unique,
   primary key (IDENTIFIER)
)
create table CATISSUE_COLLECTION_PROTOCOL (
   IDENTIFIER number(19,0) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN_CHARACTERISTICS (
   IDENTIFIER number(19,0) not null,
   TISSUE_SITE varchar2(50),
   TISSUE_SIDE varchar2(50),
   PATHOLOGICAL_STATUS varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_TISSUE_SPECIMEN (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_GRAM double precision,
   AVAILABLE_QUANTITY_IN_GRAM double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_CELL_SPECIMEN_REQUIREMENT (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_CELL_COUNT number(10,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_MICRO_GRAM double precision,
   CONCENTRATION_IN_MICROGRAM_PER_MICROLITER double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_STORAGE_TYPE (
   IDENTIFIER number(19,0) not null,
   TYPE varchar2(50) not null unique,
   DEFAULT_TEMPERATURE_IN_CENTIGRADE double precision,
   STORAGE_CONTAINER_CAPACITY_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_SITE (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50),
   TYPE varchar2(50),
   EMAIL_ADDRESS varchar2(150) not null unique,
   USER_ID number(19,0),
   ACTIVITY_STATUS varchar2(50),
   ADDRESS_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_TRANSFER_EVENT_PARAMETER (
   IDENTIFIER number(19,0) not null,
   FROM_POSITION_DIMENSION_ONE number(10,0),
   FROM_POSITION_DIMENSION_TWO number(10,0),
   TO_POSITION_DIMENSION_ONE number(10,0),
   TO_POSITION_DIMENSION_TWO number(10,0),
   TO_STORAGE_CONTAINER_ID number(19,0),
   FROM_STORAGE_CONTAINER_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP (
   BIOHAZARD_ID number(19,0) not null,
   SPECIMEN_ID number(19,0) not null,
   primary key (SPECIMEN_ID, BIOHAZARD_ID)
)
create table CATISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER number(19,0) not null,
   SPECIMEN_TYPE varchar2(50),
   TISSUE_SITE varchar2(50),
   TISSUE_SIDE varchar2(50),
   PATHOLOGY_STATUS varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_INSTITUTION (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50) not null unique,
   primary key (IDENTIFIER)
)
create table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT (
   COLLECTION_PROTOCOL_EVENT_ID number(19,0) not null,
   SPECIMEN_REQUIREMENT_ID number(19,0) not null,
   primary key (COLLECTION_PROTOCOL_EVENT_ID, SPECIMEN_REQUIREMENT_ID)
)
create table CATISSUE_FLUID_SPECIMEN (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_MILILITER double precision,
   AVAILABLE_QUANTITY_IN_MILILITER double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER number(19,0) not null,
   IP_ADDRESS varchar2(20),
   EVENT_TIMESTAMP date,
   USER_ID number(19,0),
   COMMENTS varchar2(500),
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN_COLLECTION_GROUP (
   IDENTIFIER number(19,0) not null,
   CLINICAL_DIAGNOSIS varchar2(50),
   CLINICAL_STATUS varchar2(50),
   ACTIVITY_STATUS varchar2(50),
   SITE_ID number(19,0),
   COLLECTION_PROTOCOL_EVENT_ID number(19,0),
   CLINICAL_REPORT_ID number(19,0),
   COLLECTION_PROTOCOL_REGISTRATION_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN_PROTOCOL (
   IDENTIFIER number(19,0) not null,
   PRINCIPAL_INVESTIGATOR_ID number(19,0),
   TITLE varchar2(50) not null unique,
   SHORT_TITLE varchar2(50),
   IRB_IDENTIFIER varchar2(50),
   START_DATE date,
   END_DATE date,
   ENROLLMENT number(10,0),
   DESCRIPTION_URL varchar2(200),
   ACTIVITY_STATUS varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_BIOHAZARD (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50),
   COMMENTS varchar2(500),
   TYPE varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_SPUN_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   GFORCE double precision,
   DURATION_IN_MINUTES number(10,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_FLUID_SPECIMEN_REQUIREMENT (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_MILILITER double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_DISPOSAL_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   REASON varchar2(50) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_CLINICAL_REPORT (
   IDENTIFIER number(19,0) not null,
   SURGICAL_PATHOLOGICAL_NUMBER varchar2(50),
   PARTICIPENT_MEDICAL_IDENTIFIER_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   GEL_IMAGE_URL varchar2(200),
   QUALITY_INDEX varchar2(50),
   LANE_NUMBER varchar2(50),
   GEL_NUMBER number(10,0),
   ABSORBANCE_AT_260 double precision,
   ABSORBANCE_AT_280 double precision,
   RATIO_28S_TO_18S double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_ADDRESS (
   IDENTIFIER number(19,0) not null,
   STREET varchar2(50),
   CITY varchar2(50),
   STATE varchar2(50),
   COUNTRY varchar2(50),
   ZIPCODE varchar2(30),
   PHONE_NUMBER varchar2(50),
   FAX_NUMBER varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER (
   IDENTIFIER number(19,0) not null,
   STORAGE_STATUS varchar2(100) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_REPORTED_PROBLEM (
   SYSTEM_IDENTIFIER number(19,0) not null,
   REPORTERS_EMAIL_ID varchar2(50) not null,
   MESSAGE_BODY varchar2(200) not null,
   SUBJECT varchar2(100),
   REPORTED_DATE date,
   ACTIVITY_STATUS varchar2(100),
   COMMENTS varchar2(2000),
   primary key (SYSTEM_IDENTIFIER)
)
create table CATISSUE_COLLECTION_DISTRIBUTION_RELATION (
   COLLECTION_PROTOCOL_ID number(19,0) not null,
   DISTRIBUTION_PROTOCOL_ID number(19,0) not null,
   primary key (COLLECTION_PROTOCOL_ID, DISTRIBUTION_PROTOCOL_ID)
)
create table CATISSUE_COLLECTION_COORDINATORS (
   COLLECTION_PROTOCOL_ID number(19,0) not null,
   USER_ID number(19,0) not null,
   primary key (COLLECTION_PROTOCOL_ID, USER_ID)
)
create table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT (
   DISTRIBUTION_PROTOCOL_ID number(19,0) not null,
   SPECIMEN_REQUIREMENT_ID number(19,0) not null,
   primary key (DISTRIBUTION_PROTOCOL_ID, SPECIMEN_REQUIREMENT_ID)
)
create table CATISSUE_DISTRIBUTED_ITEM (
   IDENTIFIER number(19,0) not null,
   QUANTITY double precision,
   SPECIMEN_ID number(19,0),
   DISTRIBUTION_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_RECEIVED_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   RECEIVED_QUALITY varchar2(255),
   primary key (IDENTIFIER)
)
create table CATISSUE_PARTICIPANT (
   IDENTIFIER number(19,0) not null,
   LAST_NAME varchar2(50),
   FIRST_NAME varchar2(50),
   MIDDLE_NAME varchar2(50),
   BIRTH_DATE date,
   GENDER varchar2(20),
   RACE varchar2(50),
   ETHNICITY varchar2(50),
   SOCIAL_SECURITY_NUMBER varchar2(50) unique,
   ACTIVITY_STATUS varchar2(20),
   primary key (IDENTIFIER)
)
create table CATISSUE_FROZEN_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   METHOD varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER number(19,0) not null,
   OBJECT_IDENTIFIER number(19,0),
   OBJECT_NAME varchar2(50),
   EVENT_TYPE varchar2(50),
   AUDIT_EVENT_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_PROCEDURE_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   URL varchar2(200) not null,
   NAME varchar2(50) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER (
   IDENTIFIER number(19,0) not null,
   MEDICAL_RECORD_NUMBER varchar2(50),
   SITE_ID number(19,0),
   PARTICIPANT_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_STORAGE_CONTAINER_DETAILS (
   IDENTIFIER number(19,0) not null,
   ARAMETER_NAME varchar2(50),
   VALUE varchar2(50),
   STORAGE_CONTAINER_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_MOLECULAR_SPECIMEN (
   IDENTIFIER number(19,0) not null,
   CONCENTRATION_IN_MICROGRAM_PER_MICROLITER double precision,
   QUANTITY_IN_MICROGRAM double precision,
   AVAILABLE_QUANTITY_IN_MICROGRAM double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   CELL_COUNT double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_STORAGE_CONTAINER (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50),
   TEMPERATURE double precision,
   IS_CONTAINER_FULL number(1,0),
   BARCODE varchar2(50) unique,
   ACTIVITY_STATUS varchar2(30),
   STORAGE_TYPE_ID number(19,0),
   SITE_ID number(19,0),
   PARENT_CONTAINER_ID number(19,0),
   STORAGE_CONTAINER_CAPACITY_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_DISTRIBUTION (
   IDENTIFIER number(19,0) not null,
   TO_SITE_ID number(19,0),
   FROM_SITE_ID number(19,0),
   DISTRIBUTION_PROTOCOL_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_EMBEDDED_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   EMBEDDING_MEDIUM varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER number(19,0) not null,
   ELEMENT_NAME varchar2(50),
   PREVIOUS_VALUE varchar2(50),
   CURRENT_VALUE varchar2(50),
   AUDIT_EVENT_LOG_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_COLLECTION_PROTOCOL_EVENT (
   IDENTIFIER number(19,0) not null,
   CLINICAL_STATUS varchar2(50),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_DISTRIBUTION_PROTOCOL (
   IDENTIFIER number(19,0) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_EXTERNAL_IDENTIFIER (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50),
   VALUE varchar2(50),
   SPECIMEN_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_DEPARTMENT (
   IDENTIFIER number(19,0) not null,
   NAME varchar2(50) not null unique,
   primary key (IDENTIFIER)
)
create table CATISSUE_THAW_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_FIXED_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   FIXATION_TYPE varchar2(50) not null,
   DURATION_IN_MINUTES number(10,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   NEOPLASTIC_CELLULARITY_PERCENTAGE double precision,
   VIABLE_CELL_PERCENTAGE double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN (
   IDENTIFIER number(19,0) not null,
   TYPE varchar2(50),
   AVAILABLE number(1,0),
   POSITION_DIMENSION_ONE number(10,0),
   POSITION_DIMENSION_TWO number(10,0),
   BARCODE varchar2(50),
   COMMENTS varchar2(200),
   ACTIVITY_STATUS varchar2(50),
   PARENT_SPECIMEN_ID number(19,0),
   STORAGE_CONTAINER_IDENTIFIER number(19,0),
   SPECIMEN_COLLECTION_GROUP_ID number(19,0),
   SPECIMEN_CHARACTERISTICS_ID number(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_USER (
   IDENTIFIER number(19,0) not null,
   LAST_NAME varchar2(50),
   FIRST_NAME varchar2(50),
   LOGIN_NAME varchar2(50) not null unique,
   PASSWORD varchar2(50),
   DATE_ADDED date,
   ACTIVITY_STATUS varchar2(50),
   DEPARTMENT_ID number(19,0),
   CANCER_RESEARCH_GROUP_ID number(19,0),
   INSTITUTION_ID number(19,0),
   ADDRESS_ID number(19,0),
   STATUS_COMMENT varchar2(2000),
   primary key (IDENTIFIER)
)
create table CATISSUE_CELL_SPECIMEN (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_CELL_COUNT number(10,0),
   AVAILABLE_QUANTITY_IN_CELL_COUNT number(10,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_STORAGE_CONTAINER_CAPACITY (
   IDENTIFIER number(19,0) not null,
   ONE_DIMENSION_CAPACITY number(10,0),
   TWO_DIMENSION_CAPACITY number(10,0),
   ONE_DIMENSION_LABEL varchar2(50),
   TWO_DIMENSION_LABEL varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER number(19,0) not null,
   QUANTITY_IN_GRAM double precision,
   primary key (IDENTIFIER)
)
create table CATISSUE_COLLECTION_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   COLLECTION_PROCEDURE varchar2(50),
   CONTAINER varchar2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN_EVENT_PARAMETERS (
   IDENTIFIER number(19,0) not null,
   SPECIMEN_ID number(19,0),
   EVENT_TIMESTAMP date,
   USER_ID number(19,0),
   COMMENTS varchar2(500),
   primary key (IDENTIFIER)
)
alter table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS add constraint FK1A13AD3DBC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION add constraint FK9FAF7E1B48304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION add constraint FK9FAF7E1B87E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT
alter table CATISSUE_COLLECTION_PROTOCOL add constraint FK32DC439DBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL
alter table CATISSUE_TISSUE_SPECIMEN add constraint FKB9860FA6BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN
alter table CATISSUE_CELL_SPECIMEN_REQUIREMENT add constraint FK4407C9ADBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT
alter table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT add constraint FKD0AC7D37BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT
alter table CATISSUE_STORAGE_TYPE add constraint FKE9A0629A5F7CB0FE foreign key (STORAGE_CONTAINER_CAPACITY_ID) references CATISSUE_STORAGE_CONTAINER_CAPACITY
alter table CATISSUE_SITE add constraint FKB024C3436CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS
alter table CATISSUE_SITE add constraint FKB024C3432206F20F foreign key (USER_ID) references CATISSUE_USER
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add constraint FK4645C5AC3C2DAC61 foreign key (TO_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add constraint FK4645C5ACBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add constraint FK4645C5AC99DF0A92 foreign key (FROM_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP add constraint FK108D68F860773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP add constraint FK108D68F8F398D480 foreign key (BIOHAZARD_ID) references CATISSUE_BIOHAZARD
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT add constraint FK20ECDAF1BE10F0CE foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT add constraint FK20ECDAF153B01F66 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLLECTION_PROTOCOL_EVENT
alter table CATISSUE_FLUID_SPECIMEN add constraint FK461E42F9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN
alter table CATISSUE_AUDIT_EVENT add constraint FKACAF697A2206F20F foreign key (USER_ID) references CATISSUE_USER
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add constraint FK92169759DCC1E13B foreign key (COLLECTION_PROTOCOL_REGISTRATION_ID) references CATISSUE_COLLECTION_PROTOCOL_REGISTRATION
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add constraint FK92169759A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add constraint FK921697594CE21DDA foreign key (CLINICAL_REPORT_ID) references CATISSUE_CLINICAL_REPORT
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add constraint FK9216975953B01F66 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLLECTION_PROTOCOL_EVENT
alter table CATISSUE_SPECIMEN_PROTOCOL add constraint FKB8481373870EB740 foreign key (PRINCIPAL_INVESTIGATOR_ID) references CATISSUE_USER
alter table CATISSUE_SPUN_EVENT_PARAMETERS add constraint FK312D77BCBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_FLUID_SPECIMEN_REQUIREMENT add constraint FK3F2563DDBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT
alter table CATISSUE_DISPOSAL_EVENT_PARAMETERS add constraint FK66A78F21BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_CLINICAL_REPORT add constraint FK54A4264DEED9EFB foreign key (PARTICIPENT_MEDICAL_IDENTIFIER_ID) references CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER
alter table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS add constraint FKE42CFF45BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS
alter table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER add constraint FK88A378F9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION add constraint FKE2E444726B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION add constraint FKE2E4447248304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL
alter table CATISSUE_COLLECTION_COORDINATORS add constraint FK96FACDC848304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL
alter table CATISSUE_COLLECTION_COORDINATORS add constraint FK96FACDC82206F20F foreign key (USER_ID) references CATISSUE_USER
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT add constraint FK9FE639CB6B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT add constraint FK9FE639CBBE10F0CE foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT
alter table CATISSUE_DISTRIBUTED_ITEM add constraint FKA7C3ED4B60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_DISTRIBUTED_ITEM add constraint FKA7C3ED4BF8278B6 foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION
alter table CATISSUE_RECEIVED_EVENT_PARAMETERS add constraint FKC3D728F1BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_FROZEN_EVENT_PARAMETERS add constraint FKDD06C312BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_AUDIT_EVENT_LOG add constraint FK8BB672DF77F0B904 foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT
alter table CATISSUE_PROCEDURE_EVENT_PARAMETERS add constraint FK6612CBD7BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER add constraint FKD081FCDFA7F77D13 foreign key (SITE_ID) references CATISSUE_SITE
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER add constraint FKD081FCDF87E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT
alter table CATISSUE_STORAGE_CONTAINER_DETAILS add constraint FK66CE30E4B3DFB11D foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER
alter table CATISSUE_MOLECULAR_SPECIMEN add constraint FKDD4D1353BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN
alter table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS add constraint FKD9ABD790BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS
alter table CATISSUE_STORAGE_CONTAINER add constraint FK28429D015F7CB0FE foreign key (STORAGE_CONTAINER_CAPACITY_ID) references CATISSUE_STORAGE_CONTAINER_CAPACITY
alter table CATISSUE_STORAGE_CONTAINER add constraint FK28429D01A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE
alter table CATISSUE_STORAGE_CONTAINER add constraint FK28429D0159A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE
alter table CATISSUE_STORAGE_CONTAINER add constraint FK28429D01DB097B2E foreign key (PARENT_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER
alter table CATISSUE_DISTRIBUTION add constraint FK542766806B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL
alter table CATISSUE_DISTRIBUTION add constraint FK542766801DBE834F foreign key (TO_SITE_ID) references CATISSUE_SITE
alter table CATISSUE_DISTRIBUTION add constraint FK54276680BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_DISTRIBUTION add constraint FK54276680FB9AE97E foreign key (FROM_SITE_ID) references CATISSUE_SITE
alter table CATISSUE_EMBEDDED_EVENT_PARAMETERS add constraint FK1AE03F68BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_AUDIT_EVENT_DETAILS add constraint FK5C07745D34FFD77F foreign key (AUDIT_EVENT_LOG_ID) references CATISSUE_AUDIT_EVENT_LOG
alter table CATISSUE_COLLECTION_PROTOCOL_EVENT add constraint FKF6A1375848304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL
alter table CATISSUE_DISTRIBUTION_PROTOCOL add constraint FKC8999977BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL
alter table CATISSUE_REVIEW_EVENT_PARAMETERS add constraint FK621FE55ABC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_EXTERNAL_IDENTIFIER add constraint FK5CF2FA2160773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_THAW_EVENT_PARAMETERS add constraint FKD8890A48BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_FIXED_EVENT_PARAMETERS add constraint FK82DC0356BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS add constraint FKE2FE9B3BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS
alter table CATISSUE_SPECIMEN add constraint FK1674810456906F39 foreign key (SPECIMEN_CHARACTERISTICS_ID) references CATISSUE_SPECIMEN_CHARACTERISTICS
alter table CATISSUE_SPECIMEN add constraint FK1674810433BF33C5 foreign key (SPECIMEN_COLLECTION_GROUP_ID) references CATISSUE_SPECIMEN_COLLECTION_GROUP
alter table CATISSUE_SPECIMEN add constraint FK16748104B189E99D foreign key (PARENT_SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_SPECIMEN add constraint FK1674810432B31EAB foreign key (STORAGE_CONTAINER_IDENTIFIER) references CATISSUE_STORAGE_CONTAINER
alter table CATISSUE_USER add constraint FKB025CFC71792AD22 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION
alter table CATISSUE_USER add constraint FKB025CFC7FFA96920 foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP
alter table CATISSUE_USER add constraint FKB025CFC76CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS
alter table CATISSUE_USER add constraint FKB025CFC7F30C2528 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT
alter table CATISSUE_CELL_SPECIMEN add constraint FKCD8EE0C9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN
alter table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT add constraint FK67C6950ABC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT
alter table CATISSUE_COLLECTION_EVENT_PARAMETERS add constraint FKFB1108D4BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS add constraint FK2C72A2AA60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS add constraint FK2C72A2AA2206F20F foreign key (USER_ID) references CATISSUE_USER
create sequence hibernate_sequence
