alter table CATISSUE_REPORTED_PROBLEM drop constraint FK85DD190FA88D6358
alter table CATISSUE_STUDY drop constraint FK5478A92DA88D6358
alter table CATISSUE_STUDY drop constraint FK5478A92D3BD4943A
alter table CATISSUE_STUDY drop constraint FK5478A92D617D1538
alter table BiospecimenDistribution drop constraint FK9713DA94F8278B6
alter table CATISSUE_SEGMENT drop constraint FKFE98ED97A88D6358
alter table CATISSUE_SEGMENT drop constraint FKFE98ED976E8E0D2E
alter table CATISSUE_SEGMENT drop constraint FKFE98ED9760773DB2
alter table CATISSUE_BOX drop constraint FKAAD7A62F88CB665C
alter table CATISSUE_BOX drop constraint FKAAD7A62FDAC76C0
alter table CATISSUE_BOX drop constraint FKAAD7A62FA88D6358
alter table CATISSUE_PARTICIPANT drop constraint FK6D4D6397A88D6358
alter table CATISSUE_UNIT drop constraint FKB025BD80DD9294A1
alter table CATISSUE_UNIT drop constraint FKB025BD80A88D6358
alter table CATISSUE_UNIT drop constraint FKB025BD80DAC76C0
alter table CATISSUE_UNIT drop constraint FKB025BD80BA5C59F4
alter table CATISSUE_INSTITUTE drop constraint FK1F49FB796CD94566
alter table CATISSUE_COLLECTION drop constraint FK1E63999ADAC76C0
alter table CATISSUE_COLLECTION drop constraint FK1E63999A19B7FDB6
alter table CATISSUE_COLLECTION drop constraint FK1E63999AA88D6358
alter table CATISSUE_AUDIT drop constraint FK537B373F2206F20F
alter table CATISSUE_EVENTLOG drop constraint FKA629706668D3EC1F
alter table CATISSUE_PROTOCOL_REQUIREMENT drop constraint FKE3969CF8A1CEE4FF
alter table CATISSUE_DISTRIBUTION drop constraint FK54276680F6FD9EDD
alter table CATISSUE_DISTRIBUTION drop constraint FK54276680A1CEE4FF
alter table CATISSUE_DISTRIBUTION drop constraint FK54276680B5A4660C
alter table CATISSUE_DISTRIBUTION drop constraint FK54276680CEB68F93
alter table CATISSUE_SAMPLE drop constraint FK398D46A6A88D6358
alter table CATISSUE_SAMPLE drop constraint FK398D46A660773DB2
alter table CATISSUE_SAMPLE drop constraint FK398D46A66E8E0D2E
alter table CATISSUE_SAMPLE drop constraint FK398D46A65D2605C7
alter table CATISSUE_SITE drop constraint FKB024C343EFE6CF10
alter table CATISSUE_SITE drop constraint FKB024C343FA2863A5
alter table CATISSUE_SITE drop constraint FKB024C343A88D6358
alter table CATISSUE_SITE drop constraint FKB024C3436CD94566
alter table CATISSUE_PROTOCOL drop constraint FK5AA00C943BD4943A
alter table CATISSUE_PROTOCOL drop constraint FK5AA00C94A88D6358
alter table CATISSUE_PROTOCOL drop constraint FK5AA00C94EFE6CF10
alter table CATISSUE_SPECIMEN drop constraint FK16748104A88D6358
alter table CATISSUE_SPECIMEN drop constraint FK167481042756F736
alter table CATISSUE_SPECIMEN drop constraint FK16748104D1B0179F
alter table CATISSUE_USER drop constraint FKB025CFC7A88D6358
alter table CATISSUE_USER drop constraint FKB025CFC76CD94566
alter table CATISSUE_USER drop constraint FKB025CFC7FA2863A5
alter table CATISSUE_USER drop constraint FKB025CFC77CDD9984
alter table CATISSUE_USER drop constraint FKB025CFC7F30C2528
alter table CATISSUE_BIOSPECIMEN_STORAGE drop constraint FK6AA82D9077FEC3BD
alter table CATISSUE_STUDY_REQUIREMENT drop constraint FK3DB41C11A1CEE4FF
alter table CATISSUE_ACCESSION drop constraint FK9F097988EB5465E6
alter table CATISSUE_ACCESSION drop constraint FK9F09798846ED155
alter table CATISSUE_ACCESSION drop constraint FK9F0979882FB3B75
alter table CATISSUE_ACCESSION drop constraint FK9F097988EB66552D
drop table CATISSUE_ADDRESS cascade constraints
drop table CATISSUE_REPORTED_PROBLEM cascade constraints
drop table CATISSUE_STUDY cascade constraints
drop table BiospecimenDistribution cascade constraints
drop table CATISSUE_SEGMENT cascade constraints
drop table CATISSUE_ROLE cascade constraints
drop table CATISSUE_BOX cascade constraints
drop table CATISSUE_PARTICIPANT cascade constraints
drop table CATISSUE_UNIT cascade constraints
drop table CATISSUE_INSTITUTE cascade constraints
drop table CATISSUE_COLLECTION cascade constraints
drop table CATISSUE_AUDIT cascade constraints
drop table CATISSUE_PROTOCOL_STUDY cascade constraints
drop table CATISSUE_EVENTLOG cascade constraints
drop table CATISSUE_PROTOCOL_REQUIREMENT cascade constraints
drop table CATISSUE_CAPACITY cascade constraints
drop table CATISSUE_DISTRIBUTION cascade constraints
drop table CATISSUE_SAMPLE cascade constraints
drop table CATISSUE_SITE cascade constraints
drop table CATISSUE_ACCESSION_INFECTION cascade constraints
drop table CATISSUE_PROTOCOL cascade constraints
drop table CATISSUE_INFECTION_AGENT cascade constraints
drop table CATISSUE_DEPARTMENT cascade constraints
drop table CATISSUE_SPECIMEN cascade constraints
drop table CATISSUE_USER cascade constraints
drop table CATISSUE_BIOSPECIMEN_STORAGE cascade constraints
drop table CATISSUE_STUDY_REQUIREMENT cascade constraints
drop table CATISSUE_ACTIVITY_STATUS cascade constraints
drop table CATISSUE_ACCESSION cascade constraints
drop sequence hibernate_sequence
create table CATISSUE_ADDRESS (
   IDENTIFIER NUMBER(19,0) not null,
   STREET VARCHAR2(50),
   CITY VARCHAR2(50),
   STATE VARCHAR2(50),
   COUNTRY VARCHAR2(50),
   ZIP VARCHAR2(50),
   PHONE VARCHAR2(50),
   FAX VARCHAR2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_REPORTED_PROBLEM (
   IDENTIFIER NUMBER(19,0) not null,
   REPORTERS_EMAIL_ID VARCHAR2(50) not null,
   MESSAGE_BODY VARCHAR2(200) not null,
   SUBJECT VARCHAR2(100),
   REPORTED_DATE DATE,
   ACTIVITY_STATUS_ID NUMBER(19,0),
   COMMENTS VARCHAR2(2000),
   primary key (IDENTIFIER)
)
create table CATISSUE_STUDY (
   IDENTIFIER NUMBER(19,0) not null,
   PRINCIPAL_INVESTIGATOR NUMBER(19,0),
   COORDINATOR_IDENTIFIER NUMBER(19,0),
   TITLE VARCHAR2(200),
   SHORT_TITLE VARCHAR2(100),
   IRB_IDENTIFIER VARCHAR2(100),
   START_DATE DATE,
   END_DATE DATE,
   ACTIVITY_STATUS_ID NUMBER(19,0),
   ENROLLMENT NUMBER(10,0),
   DESCRIPTION_URL VARCHAR2(100),
   primary key (IDENTIFIER)
)
create table BiospecimenDistribution (
   IDENTIFIER NUMBER(19,0) not null,
   BIOSPECIMEN_TYPE VARCHAR2(50),
   BIOSPECIMEN_IDENTIFIER NUMBER(19,0),
   QUANTITY DOUBLE PRECISION,
   QUANITY_UNIT VARCHAR2(50),
   DISTRIBUTION_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_SEGMENT (
   IDENTIFIER NUMBER(19,0) not null,
   CREATION_DATE DATE,
   CREATED_BY NUMBER(19,0),
   QUANTITY DOUBLE PRECISION,
   QUANTITY_UNIT VARCHAR2(50),
   AVAILABLE NUMBER(1,0),
   AVAILABLE_QUANTITY DOUBLE PRECISION,
   ACTIVITY_STATUS_ID NUMBER(19,0),
   BARCODE VARCHAR2(50),
   SPECIMEN_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_ROLE (
   IDENTIFIER NUMBER(19,0) not null,
   NAME VARCHAR2(50) not null unique,
   primary key (IDENTIFIER)
)
create table CATISSUE_BOX (
   IDENTIFIER NUMBER(19,0) not null,
   TYPE VARCHAR2(50),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   BAR_CODE VARCHAR2(100),
   CAPACITY_ID NUMBER(19,0),
   COLLECTION_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_PARTICIPANT (
   IDENTIFIER NUMBER(19,0) not null,
   LAST_NAME VARCHAR2(50),
   FIRST_NAME VARCHAR2(50),
   MIDDLE_NAME VARCHAR2(50),
   DATE_OF_BIRTH DATE,
   GENDER VARCHAR2(20),
   SOCIAL_SECURITY_NUMBER VARCHAR2(50) unique,
   UNIQUE_MEDICAL_RECORD_NUMBER VARCHAR2(50) unique,
   RACE VARCHAR2(20),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_UNIT (
   IDENTIFIER NUMBER(19,0) not null,
   TYPE VARCHAR2(50),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   BAR_CODE VARCHAR2(100),
   CAPACITY_ID NUMBER(19,0),
   ADDRESS_IDENTIFIER NUMBER(19,0),
   SITE_IDENTIFIER NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_INSTITUTE (
   IDENTIFIER NUMBER(19,0) not null,
   NAME VARCHAR2(50) not null,
   TYPE VARCHAR2(50),
   ADDRESS_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_COLLECTION (
   IDENTIFIER NUMBER(19,0) not null,
   TYPE VARCHAR2(50),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   BAR_CODE VARCHAR2(100),
   CAPACITY_ID NUMBER(19,0),
   UNIT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_AUDIT (
   IDENTIFIER NUMBER(19,0) not null,
   AUDIT_TIMESTAMP DATE,
   USER_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_PROTOCOL_STUDY (
   PROTOCOL_ID NUMBER(19,0) not null,
   STUDY_ID NUMBER(19,0) not null,
   primary key (PROTOCOL_ID)
)
create table CATISSUE_EVENTLOG (
   IDENTIFIER NUMBER(19,0) not null,
   OBJECT_ID NUMBER(19,0),
   OBJECT_TYPE VARCHAR2(50),
   ELEMENT_NAME VARCHAR2(50),
   EVENT_TYPE VARCHAR2(50),
   PREVIOUS_VALUE VARCHAR2(50),
   CURRENT_VALUE VARCHAR2(50),
   AUDIT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_PROTOCOL_REQUIREMENT (
   IDENTIFIER NUMBER(19,0) not null,
   SPECIMEN_TYPE VARCHAR2(50),
   QUANTITY DOUBLE PRECISION,
   QUANTITY_UNIT VARCHAR2(50),
   DISEASE_STATUS VARCHAR2(50),
   STUDY_IDENTIFIER NUMBER(19,0),
   PROTOCOL_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_CAPACITY (
   IDENTIFIER NUMBER(19,0) not null,
   DIMENSION_ONE NUMBER(10,0),
   DIMENSION_TWO NUMBER(10,0),
   DIMENSION_THREE NUMBER(10,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_DISTRIBUTION (
   IDENTIFIER NUMBER(19,0) not null,
   DISTRIBUTION_DATE DATE,
   DISTRIBUTED_BY NUMBER(19,0),
   TRACK_NUMBER VARCHAR2(50),
   DISTRIBUTION_MODE VARCHAR2(50),
   TO_SITE_IDENTIFIER NUMBER(19,0),
   STUDY_IDENTIFIER NUMBER(19,0),
   FROM_SITE_IDENTIFIER NUMBER(19,0),
   DISTRIBUTION_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_SAMPLE (
   IDENTIFIER NUMBER(19,0) not null,
   CREATION_DATE DATE,
   CREATED_BY NUMBER(19,0),
   TYPE VARCHAR2(50),
   QUALITY VARCHAR2(50),
   GEL_IMAGE_URL VARCHAR2(100),
   LANE_NUMBER VARCHAR2(50),
   QUANTITY DOUBLE PRECISION,
   QUANTITY_UNIT VARCHAR2(50),
   CONCENTRATION DOUBLE PRECISION,
   AVAILABLE NUMBER(1,0),
   AVAILABLE_QUANTITY DOUBLE PRECISION,
   ACTIVITY_STATUS_ID NUMBER(19,0),
   BARCODE VARCHAR2(50),
   SEGMENT_ID NUMBER(19,0),
   SPECIMEN_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_SITE (
   IDENTIFIER NUMBER(19,0) not null,
   NAME VARCHAR2(50),
   TYPE VARCHAR2(50),
   DEPARTMENT VARCHAR2(50),
   SHIPPING_ADDRESS VARCHAR2(50),
   COORDINATOR NUMBER(19,0),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   ADDRESS_ID NUMBER(19,0),
   INSTITUTE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_ACCESSION_INFECTION (
   INFECTION_ID NUMBER(19,0) not null,
   ACCESSION_ID NUMBER(19,0) not null,
   primary key (INFECTION_ID, ACCESSION_ID)
)
create table CATISSUE_PROTOCOL (
   IDENTIFIER NUMBER(19,0) not null,
   TITLE VARCHAR2(50),
   SHORT_TITLE VARCHAR2(50),
   START_DATE DATE,
   END_DATE DATE,
   IRB_IDENTIFIER VARCHAR2(50),
   ENROLLMENT NUMBER(10,0),
   COLLECTION NUMBER(1,0),
   MULTIPLE_SIDE NUMBER(1,0),
   DESCRIPTION_URL VARCHAR2(100),
   PRINCIPAL_INVESTIGATOR NUMBER(19,0),
   COORDINATOR NUMBER(19,0),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_INFECTION_AGENT (
   IDENTIFIER NUMBER(19,0) not null,
   NAME VARCHAR2(50),
   primary key (IDENTIFIER)
)
create table CATISSUE_DEPARTMENT (
   IDENTIFIER NUMBER(19,0) not null,
   NAME VARCHAR2(50) not null,
   primary key (IDENTIFIER)
)
create table CATISSUE_SPECIMEN (
   IDENTIFIER NUMBER(19,0) not null,
   TISSUE_SITE VARCHAR2(50),
   TISSUE_SIDE VARCHAR2(50),
   SPECIMEN_TYPE VARCHAR2(50),
   PROCESS_IDENTIFIER VARCHAR2(50),
   RECEIVED_QUANTITY DOUBLE PRECISION,
   QUANTITY_UNIT DOUBLE PRECISION,
   RECEIVED_QUALITY VARCHAR2(50),
   REVIEWED NUMBER(1,0),
   REVIEWED_DATE DATE,
   REVIEWED_BY NUMBER(19,0),
   NEOPLASTIC_CELLULARITY_PERCENT DOUBLE PRECISION,
   NECROSIS_PERCENT DOUBLE PRECISION,
   LYMPHOCYTIC_PERCENT DOUBLE PRECISION,
   TOTAL_CELLULARITY_PERCENT DOUBLE PRECISION,
   HISTOLOGICAL_QUALITY VARCHAR2(50),
   SAMPLE_DERIVED NUMBER(1,0),
   AVAILABLE NUMBER(1,0),
   AVAILABLE_QUANTITY DOUBLE PRECISION,
   COMMENTS VARCHAR2(200),
   ACTIVITY_STATUS_ID NUMBER(19,0),
   BARCODE VARCHAR2(50),
   ACCESSION_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_USER (
   IDENTIFIER NUMBER(19,0) not null,
   LAST_NAME VARCHAR2(50),
   FIRST_NAME VARCHAR2(50),
   INSTITUTE_ID NUMBER(19,0),
   DEPARTMENT_ID NUMBER(19,0),
   ADDRESS_ID NUMBER(19,0),
   LOGIN VARCHAR2(50) not null unique,
   ACTIVITY_STATUS_ID NUMBER(19,0),
   DATE_ADDED DATE,
   MEMBER_SINCE DATE,
   PASSWORD VARCHAR2(50),
   EMAIL VARCHAR2(50) not null unique,
   ROLE_ID NUMBER(19,0),
   STATUSCOMMENT VARCHAR2(2000),
   primary key (IDENTIFIER)
)
create table CATISSUE_BIOSPECIMEN_STORAGE (
   IDENTIFIER NUMBER(19,0) not null,
   TYPE VARCHAR2(50),
   BIOSPECIMEN_IDENTIFIER NUMBER(19,0),
   POSITION_DIMENSION_ONE NUMBER(19,0),
   POSITION_DIMENSION_TWO NUMBER(19,0),
   POSITION_DIMENSION_THREE NUMBER(19,0),
   BOX_IDENTIFIER NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_STUDY_REQUIREMENT (
   IDENTIFIER NUMBER(19,0) not null,
   TYPE VARCHAR2(50),
   BIOSPECIMEN_SUB_TYPE VARCHAR2(50),
   QUANTITY DOUBLE PRECISION,
   QUANTITY_UNIT VARCHAR2(50),
   DISEASE_STATUS VARCHAR2(50),
   STUDY_IDENTIFIER NUMBER(19,0),
   STUDY_REQUIREMENT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
create table CATISSUE_ACTIVITY_STATUS (
   IDENTIFIER NUMBER(19,0) not null,
   STATUS VARCHAR2(50) not null unique,
   primary key (IDENTIFIER)
)
create table CATISSUE_ACCESSION (
   IDENTIFIER NUMBER(19,0) not null,
   PROTOCOL_NUMBER NUMBER(19,0),
   MEDICAL_RECORD_NUMBER VARCHAR2(50),
   MEDICAL_REPORT_URL VARCHAR2(100),
   CLINICAL_DIAGNOSIS VARCHAR2(50),
   DISEASE_STATUS VARCHAR2(50),
   SURGICAL_PATHOLOGY_NUMBER VARCHAR2(50),
   SURGICAL_PATHOLOGY_REPORT_URL VARCHAR2(100),
   COLLECTION_TIME DATE,
   COLLECTED_BY NUMBER(19,0),
   RECEIVED_MODE VARCHAR2(50),
   RECEIVED_TRACK_NUMBER VARCHAR2(50),
   RECEIVED_TIME DATE,
   RECEIVED_BY NUMBER(19,0),
   ACTIVITY_STATUS_IDENTIFIER NUMBER(19,0),
   PARTICIPANT_IDENTIFIER NUMBER(19,0),
   PROTOCOL_ID NUMBER(19,0),
   primary key (IDENTIFIER)
)
alter table CATISSUE_REPORTED_PROBLEM add constraint FK85DD190FA88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_STUDY add constraint FK5478A92DA88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_STUDY add constraint FK5478A92D3BD4943A foreign key (PRINCIPAL_INVESTIGATOR) references CATISSUE_USER
alter table CATISSUE_STUDY add constraint FK5478A92D617D1538 foreign key (COORDINATOR_IDENTIFIER) references CATISSUE_USER
alter table BiospecimenDistribution add constraint FK9713DA94F8278B6 foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION
alter table CATISSUE_SEGMENT add constraint FKFE98ED97A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_SEGMENT add constraint FKFE98ED976E8E0D2E foreign key (CREATED_BY) references CATISSUE_USER
alter table CATISSUE_SEGMENT add constraint FKFE98ED9760773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_BOX add constraint FKAAD7A62F88CB665C foreign key (COLLECTION_ID) references CATISSUE_COLLECTION
alter table CATISSUE_BOX add constraint FKAAD7A62FDAC76C0 foreign key (CAPACITY_ID) references CATISSUE_CAPACITY
alter table CATISSUE_BOX add constraint FKAAD7A62FA88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_PARTICIPANT add constraint FK6D4D6397A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_UNIT add constraint FKB025BD80DD9294A1 foreign key (SITE_IDENTIFIER) references CATISSUE_SITE
alter table CATISSUE_UNIT add constraint FKB025BD80A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_UNIT add constraint FKB025BD80DAC76C0 foreign key (CAPACITY_ID) references CATISSUE_CAPACITY
alter table CATISSUE_UNIT add constraint FKB025BD80BA5C59F4 foreign key (ADDRESS_IDENTIFIER) references CATISSUE_ADDRESS
alter table CATISSUE_INSTITUTE add constraint FK1F49FB796CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS
alter table CATISSUE_COLLECTION add constraint FK1E63999ADAC76C0 foreign key (CAPACITY_ID) references CATISSUE_CAPACITY
alter table CATISSUE_COLLECTION add constraint FK1E63999A19B7FDB6 foreign key (UNIT_ID) references CATISSUE_UNIT
alter table CATISSUE_COLLECTION add constraint FK1E63999AA88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_AUDIT add constraint FK537B373F2206F20F foreign key (USER_ID) references CATISSUE_USER
alter table CATISSUE_EVENTLOG add constraint FKA629706668D3EC1F foreign key (AUDIT_ID) references CATISSUE_AUDIT
alter table CATISSUE_PROTOCOL_REQUIREMENT add constraint FKE3969CF8A1CEE4FF foreign key (STUDY_IDENTIFIER) references CATISSUE_STUDY
alter table CATISSUE_DISTRIBUTION add constraint FK54276680F6FD9EDD foreign key (TO_SITE_IDENTIFIER) references CATISSUE_SITE
alter table CATISSUE_DISTRIBUTION add constraint FK54276680A1CEE4FF foreign key (STUDY_IDENTIFIER) references CATISSUE_STUDY
alter table CATISSUE_DISTRIBUTION add constraint FK54276680B5A4660C foreign key (FROM_SITE_IDENTIFIER) references CATISSUE_SITE
alter table CATISSUE_DISTRIBUTION add constraint FK54276680CEB68F93 foreign key (DISTRIBUTED_BY) references CATISSUE_USER
alter table CATISSUE_SAMPLE add constraint FK398D46A6A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_SAMPLE add constraint FK398D46A660773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN
alter table CATISSUE_SAMPLE add constraint FK398D46A66E8E0D2E foreign key (CREATED_BY) references CATISSUE_USER
alter table CATISSUE_SAMPLE add constraint FK398D46A65D2605C7 foreign key (SEGMENT_ID) references CATISSUE_SEGMENT
alter table CATISSUE_SITE add constraint FKB024C343EFE6CF10 foreign key (COORDINATOR) references CATISSUE_USER
alter table CATISSUE_SITE add constraint FKB024C343FA2863A5 foreign key (INSTITUTE_ID) references CATISSUE_INSTITUTE
alter table CATISSUE_SITE add constraint FKB024C343A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_SITE add constraint FKB024C3436CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS
alter table CATISSUE_PROTOCOL add constraint FK5AA00C943BD4943A foreign key (PRINCIPAL_INVESTIGATOR) references CATISSUE_USER
alter table CATISSUE_PROTOCOL add constraint FK5AA00C94A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_PROTOCOL add constraint FK5AA00C94EFE6CF10 foreign key (COORDINATOR) references CATISSUE_USER
alter table CATISSUE_SPECIMEN add constraint FK16748104A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_SPECIMEN add constraint FK167481042756F736 foreign key (ACCESSION_ID) references CATISSUE_ACCESSION
alter table CATISSUE_SPECIMEN add constraint FK16748104D1B0179F foreign key (REVIEWED_BY) references CATISSUE_USER
alter table CATISSUE_USER add constraint FKB025CFC7A88D6358 foreign key (ACTIVITY_STATUS_ID) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_USER add constraint FKB025CFC76CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS
alter table CATISSUE_USER add constraint FKB025CFC7FA2863A5 foreign key (INSTITUTE_ID) references CATISSUE_INSTITUTE
alter table CATISSUE_USER add constraint FKB025CFC77CDD9984 foreign key (ROLE_ID) references CATISSUE_ROLE
alter table CATISSUE_USER add constraint FKB025CFC7F30C2528 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT
alter table CATISSUE_BIOSPECIMEN_STORAGE add constraint FK6AA82D9077FEC3BD foreign key (BOX_IDENTIFIER) references CATISSUE_BOX
alter table CATISSUE_STUDY_REQUIREMENT add constraint FK3DB41C11A1CEE4FF foreign key (STUDY_IDENTIFIER) references CATISSUE_STUDY
alter table CATISSUE_ACCESSION add constraint FK9F097988EB5465E6 foreign key (ACTIVITY_STATUS_IDENTIFIER) references CATISSUE_ACTIVITY_STATUS
alter table CATISSUE_ACCESSION add constraint FK9F09798846ED155 foreign key (PARTICIPANT_IDENTIFIER) references CATISSUE_PARTICIPANT
alter table CATISSUE_ACCESSION add constraint FK9F0979882FB3B75 foreign key (RECEIVED_BY) references CATISSUE_USER
alter table CATISSUE_ACCESSION add constraint FK9F097988EB66552D foreign key (COLLECTED_BY) references CATISSUE_USER
create sequence hibernate_sequence
