Drop DATABASE if exists {DATABASE_NAME};

CREATE DATABASE {DATABASE_NAME};

GRANT ALL PRIVILEGES ON {DATABASE_NAME}.* TO '{USERNAME}'@'localhost' IDENTIFIED BY '{PASSWORD}' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON {DATABASE_NAME}.* TO '{USERNAME}'@'%' IDENTIFIED BY '{PASSWORD}' WITH GRANT OPTION;

USE mysql;

UPDATE  User SET File_priv = 'Y' where User='{USERNAME}';

FLUSH PRIVILEGES;