CREATE DATABASE DATABASE_NAME;

GRANT ALL PRIVILEGES ON DATABASE_NAME TO ‘USERNAME'@'HOST’ IDENTIFIED BY 'PASSWORD' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON DATABASE_NAME TO ' USERNAME'@'%' IDENTIFIED BY 'PASSWORD' WITH GRANT OPTION;
