alter table CATISSUE_AUDIT_EVENT drop foreign key FKACAF697A2EBCB751;
alter table CATISSUE_AUDIT_EVENT_DETAILS drop foreign key FK5C07745D327012CD;
alter table CATISSUE_AUDIT_EVENT_LOG drop foreign key FK8BB672DF44C83C7A;
alter table CATISSUE_CELL_SPECIMEN drop foreign key FKCD8EE0C9D388F9A8;
alter table CATISSUE_CELL_SPECIMEN_REQUIREMENT drop foreign key FK4407C9ADCBA71E6D;
alter table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS drop foreign key FKE2FE9B3BD4DBC9BE;
alter table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER drop foreign key FK88A378F9AFE2B1CE;
alter table CATISSUE_CLINICAL_REPORT drop foreign key FK54A42644AE4A6D9;
alter table CATISSUE_COLLECTION_COORDINATORS drop foreign key FK96FACDC82EBCB751;
alter table CATISSUE_COLLECTION_COORDINATORS drop foreign key FK96FACDC835BFF08E;
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION drop foreign key FKE2E44472D677CF9A;
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION drop foreign key FKE2E4447235BFF08E;
alter table CATISSUE_COLLECTION_EVENT_PARAMETERS drop foreign key FKFB1108D4AFE2B1CE;
alter table CATISSUE_COLLECTION_PROTOCOL drop foreign key FK32DC439D9D8C7D60;
alter table CATISSUE_COLLECTION_PROTOCOL_EVENT drop foreign key FKF6A1375835BFF08E;
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION drop foreign key FK9FAF7E1BC67C9F83;
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION drop foreign key FK9FAF7E1B35BFF08E;
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT drop foreign key FK20ECDAF1996DF672;
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT drop foreign key FK20ECDAF110346953;
alter table CATISSUE_DISPOSAL_EVENT_PARAMETERS drop foreign key FK66A78F21AFE2B1CE;
alter table CATISSUE_DISTRIBUTED_ITEM drop foreign key FKA7C3ED4BBBA029B1;
alter table CATISSUE_DISTRIBUTED_ITEM drop foreign key FKA7C3ED4B14237EB1;
alter table CATISSUE_DISTRIBUTION drop foreign key FK54276680ACD6AA3C;
alter table CATISSUE_DISTRIBUTION drop foreign key FK54276680D677CF9A;
alter table CATISSUE_DISTRIBUTION drop foreign key FK542766803C2F400D;
alter table CATISSUE_DISTRIBUTION drop foreign key FK54276680AFE2B1CE;
alter table CATISSUE_DISTRIBUTION_PROTOCOL drop foreign key FKC89999779D8C7D60;
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT drop foreign key FK9FE639CB996DF672;
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT drop foreign key FK9FE639CBD677CF9A;
alter table CATISSUE_EMBEDDED_EVENT_PARAMETERS drop foreign key FK1AE03F68AFE2B1CE;
alter table CATISSUE_EXTERNAL_IDENTIFIER drop foreign key FK5CF2FA2114237EB1;
alter table CATISSUE_FIXED_EVENT_PARAMETERS drop foreign key FK82DC0356AFE2B1CE;
alter table CATISSUE_FLUID_SPECIMEN drop foreign key FK461E42F9D388F9A8;
alter table CATISSUE_FLUID_SPECIMEN_REQUIREMENT drop foreign key FK3F2563DDCBA71E6D;
alter table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS drop foreign key FKD9ABD790D4DBC9BE;
alter table CATISSUE_FROZEN_EVENT_PARAMETERS drop foreign key FKDD06C312AFE2B1CE;
alter table CATISSUE_MOLECULAR_SPECIMEN drop foreign key FKDD4D1353D388F9A8;
alter table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT drop foreign key FKD0AC7D37CBA71E6D;
alter table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS drop foreign key FKE42CFF45D4DBC9BE;
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER drop foreign key FKD081FCDFB4AC35D1;
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER drop foreign key FKD081FCDFC67C9F83;
alter table CATISSUE_PERMISSIBLE_VALUE drop foreign key FK57DDCE11F55618;
alter table CATISSUE_PERMISSIBLE_VALUE drop foreign key FK57DDCE1C6D9C7E1;
alter table CATISSUE_PROCEDURE_EVENT_PARAMETERS drop foreign key FK6612CBD7AFE2B1CE;
alter table CATISSUE_QUERY_INTERFACE_COLUMN_DATA drop foreign key FK7C0448FA155B2093;
alter table CATISSUE_RECEIVED_EVENT_PARAMETERS drop foreign key FKC3D728F1AFE2B1CE;
alter table CATISSUE_REVIEW_EVENT_PARAMETERS drop foreign key FK621FE55AAFE2B1CE;
alter table CATISSUE_SIGNUP_USER drop foreign key FK92418716610741AD;
alter table CATISSUE_SIGNUP_USER drop foreign key FK92418716DBD280B1;
alter table CATISSUE_SIGNUP_USER drop foreign key FK924187165D955563;
alter table CATISSUE_SITE drop foreign key FKB024C3432EBCB751;
alter table CATISSUE_SITE drop foreign key FKB024C3437CA89863;
alter table CATISSUE_SPECIMEN drop foreign key FK1674810473EAFF27;
alter table CATISSUE_SPECIMEN drop foreign key FK16748104AB0FAA52;
alter table CATISSUE_SPECIMEN drop foreign key FK16748104CAD975A8;
alter table CATISSUE_SPECIMEN drop foreign key FK167481048671369C;
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP drop foreign key FK108D68F81EEAD863;
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP drop foreign key FK108D68F814237EB1;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK92169759B4AC35D1;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK9216975942148B8;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK921697595FFBBF21;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK9216975910346953;
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS drop foreign key FK2C72A2AA2EBCB751;
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS drop foreign key FK2C72A2AA14237EB1;
alter table CATISSUE_SPECIMEN_PROTOCOL drop foreign key FKB84813737D3C1CA2;
alter table CATISSUE_SPUN_EVENT_PARAMETERS drop foreign key FK312D77BCAFE2B1CE;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D01B4AC35D1;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D01656F1455;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D018A710D7A;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D01AE96B64B;
alter table CATISSUE_STORAGE_CONTAINER_DETAILS drop foreign key FK66CE30E47BA7B81A;
alter table CATISSUE_STORAGE_TYPE drop foreign key FKE9A0629A656F1455;
alter table CATISSUE_THAW_EVENT_PARAMETERS drop foreign key FKD8890A48AFE2B1CE;
alter table CATISSUE_TISSUE_SPECIMEN drop foreign key FKB9860FA6D388F9A8;
alter table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT drop foreign key FK67C6950ACBA71E6D;
alter table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS drop foreign key FK1A13AD3DD4DBC9BE;
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop foreign key FK4645C5AC7ECD098F;
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop foreign key FK4645C5AC1AE02F5E;
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop foreign key FK4645C5ACAFE2B1CE;
alter table CATISSUE_USER drop foreign key FKB025CFC7610741AD;
alter table CATISSUE_USER drop foreign key FKB025CFC7DBD280B1;
alter table CATISSUE_USER drop foreign key FKB025CFC77CA89863;
alter table CATISSUE_USER drop foreign key FKB025CFC75D955563;
drop table if exists CATISSUE_ADDRESS;
drop table if exists CATISSUE_AUDIT_EVENT;
drop table if exists CATISSUE_AUDIT_EVENT_DETAILS;
drop table if exists CATISSUE_AUDIT_EVENT_LOG;
drop table if exists CATISSUE_BIOHAZARD;
drop table if exists CATISSUE_CANCER_RESEARCH_GROUP;
drop table if exists CATISSUE_CDE;
drop table if exists CATISSUE_CELL_SPECIMEN;
drop table if exists CATISSUE_CELL_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS;
drop table if exists CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER;
drop table if exists CATISSUE_CLINICAL_REPORT;
drop table if exists CATISSUE_COLLECTION_COORDINATORS;
drop table if exists CATISSUE_COLLECTION_DISTRIBUTION_RELATION;
drop table if exists CATISSUE_COLLECTION_EVENT_PARAMETERS;
drop table if exists CATISSUE_COLLECTION_PROTOCOL;
drop table if exists CATISSUE_COLLECTION_PROTOCOL_EVENT;
drop table if exists CATISSUE_COLLECTION_PROTOCOL_REGISTRATION;
drop table if exists CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_DEPARTMENT;
drop table if exists CATISSUE_DISPOSAL_EVENT_PARAMETERS;
drop table if exists CATISSUE_DISTRIBUTED_ITEM;
drop table if exists CATISSUE_DISTRIBUTION;
drop table if exists CATISSUE_DISTRIBUTION_PROTOCOL;
drop table if exists CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_EMBEDDED_EVENT_PARAMETERS;
drop table if exists CATISSUE_EXTERNAL_IDENTIFIER;
drop table if exists CATISSUE_FIXED_EVENT_PARAMETERS;
drop table if exists CATISSUE_FLUID_SPECIMEN;
drop table if exists CATISSUE_FLUID_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS;
drop table if exists CATISSUE_FROZEN_EVENT_PARAMETERS;
drop table if exists CATISSUE_INSTITUTION;
drop table if exists CATISSUE_MOLECULAR_SPECIMEN;
drop table if exists CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS;
drop table if exists CATISSUE_PARTICIPANT;
drop table if exists CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER;
drop table if exists CATISSUE_PERMISSIBLE_VALUE;
drop table if exists CATISSUE_PROCEDURE_EVENT_PARAMETERS;
drop table if exists CATISSUE_QUERY_INTERFACE_COLUMN_DATA;
drop table if exists CATISSUE_QUERY_INTERFACE_TABLE_DATA;
drop table if exists CATISSUE_RECEIVED_EVENT_PARAMETERS;
drop table if exists CATISSUE_REPORTED_PROBLEM;
drop table if exists CATISSUE_REVIEW_EVENT_PARAMETERS;
drop table if exists CATISSUE_SIGNUP_USER;
drop table if exists CATISSUE_SITE;
drop table if exists CATISSUE_SPECIMEN;
drop table if exists CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP;
drop table if exists CATISSUE_SPECIMEN_CHARACTERISTICS;
drop table if exists CATISSUE_SPECIMEN_COLLECTION_GROUP;
drop table if exists CATISSUE_SPECIMEN_EVENT_PARAMETERS;
drop table if exists CATISSUE_SPECIMEN_PROTOCOL;
drop table if exists CATISSUE_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_SPUN_EVENT_PARAMETERS;
drop table if exists CATISSUE_STORAGE_CONTAINER;
drop table if exists CATISSUE_STORAGE_CONTAINER_CAPACITY;
drop table if exists CATISSUE_STORAGE_CONTAINER_DETAILS;
drop table if exists CATISSUE_STORAGE_TYPE;
drop table if exists CATISSUE_THAW_EVENT_PARAMETERS;
drop table if exists CATISSUE_TISSUE_SPECIMEN;
drop table if exists CATISSUE_TISSUE_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS;
drop table if exists CATISSUE_TRANSFER_EVENT_PARAMETER;
drop table if exists CATISSUE_USER;
create table CATISSUE_ADDRESS (
   IDENTIFIER bigint not null auto_increment,
   STREET varchar(50),
   CITY varchar(50),
   STATE varchar(50),
   COUNTRY varchar(50),
   ZIPCODE varchar(30),
   PHONE_NUMBER varchar(50),
   FAX_NUMBER varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER bigint not null auto_increment,
   IP_ADDRESS varchar(20),
   EVENT_TIMESTAMP date,
   USER_ID bigint,
   COMMENTS text,
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER bigint not null auto_increment,
   ELEMENT_NAME varchar(50),
   PREVIOUS_VALUE varchar(50),
   CURRENT_VALUE varchar(50),
   AUDIT_EVENT_LOG_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER bigint not null auto_increment,
   OBJECT_IDENTIFIER bigint,
   OBJECT_NAME varchar(50),
   EVENT_TYPE varchar(50),
   AUDIT_EVENT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_BIOHAZARD (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50),
   COMMENTS text,
   TYPE varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_CANCER_RESEARCH_GROUP (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_CDE (
   PUBLIC_ID varchar(30) not null,
   LONG_NAME varchar(200),
   DEFINITION text,
   VERSION varchar(50),
   primary key (PUBLIC_ID)
);
create table CATISSUE_CELL_SPECIMEN (
   IDENTIFIER bigint not null,
   QUANTITY_IN_CELL_COUNT integer,
   AVAILABLE_QUANTITY_IN_CELL_COUNT integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_CELL_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_CELL_COUNT integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PERCENTAGE double precision,
   VIABLE_CELL_PERCENTAGE double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER (
   IDENTIFIER bigint not null,
   STORAGE_STATUS varchar(100) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_CLINICAL_REPORT (
   IDENTIFIER bigint not null auto_increment,
   SURGICAL_PATHOLOGICAL_NUMBER varchar(50),
   PARTICIPENT_MEDICAL_IDENTIFIER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_COORDINATORS (
   COLLECTION_PROTOCOL_ID bigint not null,
   USER_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_ID, USER_ID)
);
create table CATISSUE_COLLECTION_DISTRIBUTION_RELATION (
   COLLECTION_PROTOCOL_ID bigint not null,
   DISTRIBUTION_PROTOCOL_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_ID, DISTRIBUTION_PROTOCOL_ID)
);
create table CATISSUE_COLLECTION_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   COLLECTION_PROCEDURE varchar(50),
   CONTAINER varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL_EVENT (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_STATUS varchar(50),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION (
   IDENTIFIER bigint not null auto_increment,
   PROTOCOL_PARTICIPANT_IDENTIFIER varchar(50),
   REGISTRATION_DATE date,
   PARTICIPANT_ID bigint,
   COLLECTION_PROTOCOL_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT (
   COLLECTION_PROTOCOL_EVENT_ID bigint not null,
   SPECIMEN_REQUIREMENT_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_EVENT_ID, SPECIMEN_REQUIREMENT_ID)
);
create table CATISSUE_DEPARTMENT (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISPOSAL_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   REASON varchar(50) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTED_ITEM (
   IDENTIFIER bigint not null auto_increment,
   QUANTITY double precision,
   SPECIMEN_ID bigint,
   DISTRIBUTION_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION (
   IDENTIFIER bigint not null,
   TO_SITE_ID bigint,
   FROM_SITE_ID bigint,
   DISTRIBUTION_PROTOCOL_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION_PROTOCOL (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT (
   DISTRIBUTION_PROTOCOL_ID bigint not null,
   SPECIMEN_REQUIREMENT_ID bigint not null,
   primary key (DISTRIBUTION_PROTOCOL_ID, SPECIMEN_REQUIREMENT_ID)
);
create table CATISSUE_EMBEDDED_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   EMBEDDING_MEDIUM varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_EXTERNAL_IDENTIFIER (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50),
   VALUE varchar(50),
   SPECIMEN_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_FIXED_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   FIXATION_TYPE varchar(50) not null,
   DURATION_IN_MINUTES integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_FLUID_SPECIMEN (
   IDENTIFIER bigint not null,
   QUANTITY_IN_MILILITER double precision,
   AVAILABLE_QUANTITY_IN_MILILITER double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_FLUID_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_MILILITER double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   CELL_COUNT double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_FROZEN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   METHOD varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_INSTITUTION (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_MOLECULAR_SPECIMEN (
   IDENTIFIER bigint not null,
   CONCENTRATION_IN_MICROGRAM_PER_MICROLITER double precision,
   QUANTITY_IN_MICROGRAM double precision,
   AVAILABLE_QUANTITY_IN_MICROGRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_MICRO_GRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS (
   IDENTIFIER bigint not null,
   GEL_IMAGE_URL varchar(200),
   QUALITY_INDEX varchar(50),
   LANE_NUMBER varchar(50),
   GEL_NUMBER integer,
   ABSORBANCE_AT_260 double precision,
   ABSORBANCE_AT_280 double precision,
   RATIO_28S_TO_18S double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_PARTICIPANT (
   IDENTIFIER bigint not null auto_increment,
   LAST_NAME varchar(50),
   FIRST_NAME varchar(50),
   MIDDLE_NAME varchar(50),
   BIRTH_DATE date,
   GENDER varchar(20),
   GENOTYPE varchar(20),
   RACE varchar(50),
   ETHNICITY varchar(50),
   SOCIAL_SECURITY_NUMBER varchar(50) unique,
   ACTIVITY_STATUS varchar(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER (
   IDENTIFIER bigint not null auto_increment,
   MEDICAL_RECORD_NUMBER varchar(50),
   SITE_ID bigint,
   PARTICIPANT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_PERMISSIBLE_VALUE (
   IDENTIFIER bigint not null auto_increment,
   CONCEPT_CODE varchar(20),
   DEFINITION text,
   EVS_CODE text,
   PARENT_IDENTIFIER bigint,
   VALUE varchar(100),
   PUBLIC_ID varchar(30),
   primary key (IDENTIFIER)
);
create table CATISSUE_PROCEDURE_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   URL varchar(200) not null,
   NAME varchar(50) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_QUERY_INTERFACE_COLUMN_DATA (
   IDENTIFIER bigint not null,
   TABLE_ID bigint,
   COLUMN_NAME varchar(50),
   DISPLAY_NAME varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_QUERY_INTERFACE_TABLE_DATA (
   TABLE_ID bigint not null,
   DISPLAY_NAME varchar(50),
   TABLE_NAME varchar(50),
   primary key (TABLE_ID)
);
create table CATISSUE_RECEIVED_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   RECEIVED_QUALITY varchar(255),
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORTED_PROBLEM (
   SYSTEM_IDENTIFIER bigint not null auto_increment,
   AFFILIATION varchar(200) not null,
   NAME_OF_REPORTER varchar(200) not null,
   REPORTERS_EMAIL_ID varchar(50) not null,
   MESSAGE_BODY varchar(200) not null,
   SUBJECT varchar(100),
   REPORTED_DATE date,
   ACTIVITY_STATUS varchar(100),
   COMMENTS text,
   primary key (SYSTEM_IDENTIFIER)
);
create table CATISSUE_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_SIGNUP_USER (
   IDENTIFIER bigint not null auto_increment,
   FIRST_NAME varchar(50),
   LAST_NAME varchar(50),
   LOGIN_NAME varchar(50) not null unique,
   EMAIL_ADDRESS varchar(50) not null unique,
   START_DATE date,
   ACTIVITY_STATUS varchar(50),
   DEPARTMENT_ID bigint,
   STREET varchar(50),
   CITY varchar(50),
   STATE varchar(50),
   COUNTRY varchar(50),
   ZIPCODE varchar(30),
   PHONE_NUMBER varchar(50),
   FAX_NUMBER varchar(50),
   CANCER_RESEARCH_GROUP_ID bigint,
   INSTITUTION_ID bigint,
   STATUS_COMMENT text,
   primary key (IDENTIFIER)
);
create table CATISSUE_SITE (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50),
   TYPE varchar(50),
   EMAIL_ADDRESS varchar(150),
   USER_ID bigint,
   ACTIVITY_STATUS varchar(50),
   ADDRESS_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN (
   IDENTIFIER bigint not null auto_increment,
   TYPE varchar(50),
   AVAILABLE bit,
   POSITION_DIMENSION_ONE integer,
   POSITION_DIMENSION_TWO integer,
   BARCODE varchar(50),
   COMMENTS varchar(200),
   ACTIVITY_STATUS varchar(50),
   PARENT_SPECIMEN_ID bigint,
   STORAGE_CONTAINER_IDENTIFIER bigint,
   SPECIMEN_COLLECTION_GROUP_ID bigint,
   SPECIMEN_CHARACTERISTICS_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP (
   BIOHAZARD_ID bigint not null,
   SPECIMEN_ID bigint not null,
   primary key (SPECIMEN_ID, BIOHAZARD_ID)
);
create table CATISSUE_SPECIMEN_CHARACTERISTICS (
   IDENTIFIER bigint not null auto_increment,
   TISSUE_SITE varchar(50),
   TISSUE_SIDE varchar(50),
   PATHOLOGICAL_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_COLLECTION_GROUP (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_DIAGNOSIS varchar(50),
   CLINICAL_STATUS varchar(50),
   ACTIVITY_STATUS varchar(50),
   SITE_ID bigint,
   COLLECTION_PROTOCOL_EVENT_ID bigint,
   CLINICAL_REPORT_ID bigint,
   COLLECTION_PROTOCOL_REGISTRATION_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null auto_increment,
   SPECIMEN_ID bigint,
   EVENT_TIMESTAMP date,
   USER_ID bigint,
   COMMENTS text,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_PROTOCOL (
   IDENTIFIER bigint not null auto_increment,
   PRINCIPAL_INVESTIGATOR_ID bigint,
   TITLE varchar(50) not null unique,
   SHORT_TITLE varchar(50),
   IRB_IDENTIFIER varchar(50),
   START_DATE date,
   END_DATE date,
   ENROLLMENT integer,
   DESCRIPTION_URL varchar(200),
   ACTIVITY_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null auto_increment,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(50),
   PATHOLOGY_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPUN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   GFORCE double precision,
   DURATION_IN_MINUTES integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50),
   TEMPERATURE double precision,
   IS_CONTAINER_FULL bit,
   BARCODE varchar(50) unique,
   ACTIVITY_STATUS varchar(30),
   STORAGE_TYPE_ID bigint,
   SITE_ID bigint,
   PARENT_CONTAINER_ID bigint,
   STORAGE_CONTAINER_CAPACITY_ID bigint,
   POSITION_DIMENSION_ONE integer,
   POSITION_DIMENSION_TWO integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER_CAPACITY (
   IDENTIFIER bigint not null auto_increment,
   ONE_DIMENSION_CAPACITY integer,
   TWO_DIMENSION_CAPACITY integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER_DETAILS (
   IDENTIFIER bigint not null auto_increment,
   PARAMETER_NAME varchar(50),
   VALUE varchar(50),
   STORAGE_CONTAINER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_TYPE (
   IDENTIFIER bigint not null auto_increment,
   TYPE varchar(50) not null unique,
   DEFAULT_TEMPERATURE_IN_CENTIGRADE double precision,
   ONE_DIMENSION_LABEL varchar(50),
   TWO_DIMENSION_LABEL varchar(50),
   STORAGE_CONTAINER_CAPACITY_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_THAW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_TISSUE_SPECIMEN (
   IDENTIFIER bigint not null,
   QUANTITY_IN_GRAM double precision,
   AVAILABLE_QUANTITY_IN_GRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_GRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PERCENTAGE double precision,
   NECROSIS_PERCENTAGE double precision,
   LYMPHOCYTIC_PERCENTAGE double precision,
   TOTAL_CELLULARITY_PERCENTAGE double precision,
   HISTOLOGICAL_QUALITY varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_TRANSFER_EVENT_PARAMETER (
   IDENTIFIER bigint not null,
   FROM_POSITION_DIMENSION_ONE integer,
   FROM_POSITION_DIMENSION_TWO integer,
   TO_POSITION_DIMENSION_ONE integer,
   TO_POSITION_DIMENSION_TWO integer,
   TO_STORAGE_CONTAINER_ID bigint,
   FROM_STORAGE_CONTAINER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_USER (
   IDENTIFIER bigint not null,
   ACTIVITY_STATUS varchar(50),
   DEPARTMENT_ID bigint,
   CANCER_RESEARCH_GROUP_ID bigint,
   INSTITUTION_ID bigint,
   ADDRESS_ID bigint,
   STATUS_COMMENT text,
   primary key (IDENTIFIER)
);
alter table CATISSUE_AUDIT_EVENT add index FKACAF697A2EBCB751 (USER_ID), add constraint FKACAF697A2EBCB751 foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_DETAILS add index FK5C07745D327012CD (AUDIT_EVENT_LOG_ID), add constraint FK5C07745D327012CD foreign key (AUDIT_EVENT_LOG_ID) references CATISSUE_AUDIT_EVENT_LOG (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_LOG add index FK8BB672DF44C83C7A (AUDIT_EVENT_ID), add constraint FK8BB672DF44C83C7A foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN add index FKCD8EE0C9D388F9A8 (IDENTIFIER), add constraint FKCD8EE0C9D388F9A8 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN_REQUIREMENT add index FK4407C9ADCBA71E6D (IDENTIFIER), add constraint FK4407C9ADCBA71E6D foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS add index FKE2FE9B3BD4DBC9BE (IDENTIFIER), add constraint FKE2FE9B3BD4DBC9BE foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER add index FK88A378F9AFE2B1CE (IDENTIFIER), add constraint FK88A378F9AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_CLINICAL_REPORT add index FK54A42644AE4A6D9 (PARTICIPENT_MEDICAL_IDENTIFIER_ID), add constraint FK54A42644AE4A6D9 foreign key (PARTICIPENT_MEDICAL_IDENTIFIER_ID) references CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER (IDENTIFIER);
alter table CATISSUE_COLLECTION_COORDINATORS add index FK96FACDC82EBCB751 (USER_ID), add constraint FK96FACDC82EBCB751 foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_COLLECTION_COORDINATORS add index FK96FACDC835BFF08E (COLLECTION_PROTOCOL_ID), add constraint FK96FACDC835BFF08E foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION add index FKE2E44472D677CF9A (DISTRIBUTION_PROTOCOL_ID), add constraint FKE2E44472D677CF9A foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION add index FKE2E4447235BFF08E (COLLECTION_PROTOCOL_ID), add constraint FKE2E4447235BFF08E foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_EVENT_PARAMETERS add index FKFB1108D4AFE2B1CE (IDENTIFIER), add constraint FKFB1108D4AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL add index FK32DC439D9D8C7D60 (IDENTIFIER), add constraint FK32DC439D9D8C7D60 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL_EVENT add index FKF6A1375835BFF08E (COLLECTION_PROTOCOL_ID), add constraint FKF6A1375835BFF08E foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION add index FK9FAF7E1BC67C9F83 (PARTICIPANT_ID), add constraint FK9FAF7E1BC67C9F83 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION add index FK9FAF7E1B35BFF08E (COLLECTION_PROTOCOL_ID), add constraint FK9FAF7E1B35BFF08E foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT add index FK20ECDAF1996DF672 (SPECIMEN_REQUIREMENT_ID), add constraint FK20ECDAF1996DF672 foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT add index FK20ECDAF110346953 (COLLECTION_PROTOCOL_EVENT_ID), add constraint FK20ECDAF110346953 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLLECTION_PROTOCOL_EVENT (IDENTIFIER);
alter table CATISSUE_DISPOSAL_EVENT_PARAMETERS add index FK66A78F21AFE2B1CE (IDENTIFIER), add constraint FK66A78F21AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add index FKA7C3ED4BBBA029B1 (DISTRIBUTION_ID), add constraint FKA7C3ED4BBBA029B1 foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add index FKA7C3ED4B14237EB1 (SPECIMEN_ID), add constraint FKA7C3ED4B14237EB1 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK54276680ACD6AA3C (FROM_SITE_ID), add constraint FK54276680ACD6AA3C foreign key (FROM_SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK54276680D677CF9A (DISTRIBUTION_PROTOCOL_ID), add constraint FK54276680D677CF9A foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK542766803C2F400D (TO_SITE_ID), add constraint FK542766803C2F400D foreign key (TO_SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK54276680AFE2B1CE (IDENTIFIER), add constraint FK54276680AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_PROTOCOL add index FKC89999779D8C7D60 (IDENTIFIER), add constraint FKC89999779D8C7D60 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT add index FK9FE639CB996DF672 (SPECIMEN_REQUIREMENT_ID), add constraint FK9FE639CB996DF672 foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT add index FK9FE639CBD677CF9A (DISTRIBUTION_PROTOCOL_ID), add constraint FK9FE639CBD677CF9A foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_EMBEDDED_EVENT_PARAMETERS add index FK1AE03F68AFE2B1CE (IDENTIFIER), add constraint FK1AE03F68AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_EXTERNAL_IDENTIFIER add index FK5CF2FA2114237EB1 (SPECIMEN_ID), add constraint FK5CF2FA2114237EB1 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_FIXED_EVENT_PARAMETERS add index FK82DC0356AFE2B1CE (IDENTIFIER), add constraint FK82DC0356AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN add index FK461E42F9D388F9A8 (IDENTIFIER), add constraint FK461E42F9D388F9A8 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN_REQUIREMENT add index FK3F2563DDCBA71E6D (IDENTIFIER), add constraint FK3F2563DDCBA71E6D foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS add index FKD9ABD790D4DBC9BE (IDENTIFIER), add constraint FKD9ABD790D4DBC9BE foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_FROZEN_EVENT_PARAMETERS add index FKDD06C312AFE2B1CE (IDENTIFIER), add constraint FKDD06C312AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN add index FKDD4D1353D388F9A8 (IDENTIFIER), add constraint FKDD4D1353D388F9A8 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT add index FKD0AC7D37CBA71E6D (IDENTIFIER), add constraint FKD0AC7D37CBA71E6D foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS add index FKE42CFF45D4DBC9BE (IDENTIFIER), add constraint FKE42CFF45D4DBC9BE foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER add index FKD081FCDFB4AC35D1 (SITE_ID), add constraint FKD081FCDFB4AC35D1 foreign key (SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER add index FKD081FCDFC67C9F83 (PARTICIPANT_ID), add constraint FKD081FCDFC67C9F83 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT (IDENTIFIER);
alter table CATISSUE_PERMISSIBLE_VALUE add index FK57DDCE11F55618 (PARENT_IDENTIFIER), add constraint FK57DDCE11F55618 foreign key (PARENT_IDENTIFIER) references CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER);
alter table CATISSUE_PERMISSIBLE_VALUE add index FK57DDCE1C6D9C7E1 (PUBLIC_ID), add constraint FK57DDCE1C6D9C7E1 foreign key (PUBLIC_ID) references CATISSUE_CDE (PUBLIC_ID);
alter table CATISSUE_PROCEDURE_EVENT_PARAMETERS add index FK6612CBD7AFE2B1CE (IDENTIFIER), add constraint FK6612CBD7AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_QUERY_INTERFACE_COLUMN_DATA add index FK7C0448FA155B2093 (TABLE_ID), add constraint FK7C0448FA155B2093 foreign key (TABLE_ID) references CATISSUE_QUERY_INTERFACE_TABLE_DATA (TABLE_ID);
alter table CATISSUE_RECEIVED_EVENT_PARAMETERS add index FKC3D728F1AFE2B1CE (IDENTIFIER), add constraint FKC3D728F1AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_REVIEW_EVENT_PARAMETERS add index FK621FE55AAFE2B1CE (IDENTIFIER), add constraint FK621FE55AAFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_SIGNUP_USER add index FK92418716610741AD (CANCER_RESEARCH_GROUP_ID), add constraint FK92418716610741AD foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP (IDENTIFIER);
alter table CATISSUE_SIGNUP_USER add index FK92418716DBD280B1 (DEPARTMENT_ID), add constraint FK92418716DBD280B1 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT (IDENTIFIER);
alter table CATISSUE_SIGNUP_USER add index FK924187165D955563 (INSTITUTION_ID), add constraint FK924187165D955563 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION (IDENTIFIER);
alter table CATISSUE_SITE add index FKB024C3432EBCB751 (USER_ID), add constraint FKB024C3432EBCB751 foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_SITE add index FKB024C3437CA89863 (ADDRESS_ID), add constraint FKB024C3437CA89863 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK1674810473EAFF27 (SPECIMEN_COLLECTION_GROUP_ID), add constraint FK1674810473EAFF27 foreign key (SPECIMEN_COLLECTION_GROUP_ID) references CATISSUE_SPECIMEN_COLLECTION_GROUP (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK16748104AB0FAA52 (SPECIMEN_CHARACTERISTICS_ID), add constraint FK16748104AB0FAA52 foreign key (SPECIMEN_CHARACTERISTICS_ID) references CATISSUE_SPECIMEN_CHARACTERISTICS (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK16748104CAD975A8 (STORAGE_CONTAINER_IDENTIFIER), add constraint FK16748104CAD975A8 foreign key (STORAGE_CONTAINER_IDENTIFIER) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK167481048671369C (PARENT_SPECIMEN_ID), add constraint FK167481048671369C foreign key (PARENT_SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP add index FK108D68F81EEAD863 (BIOHAZARD_ID), add constraint FK108D68F81EEAD863 foreign key (BIOHAZARD_ID) references CATISSUE_BIOHAZARD (IDENTIFIER);
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP add index FK108D68F814237EB1 (SPECIMEN_ID), add constraint FK108D68F814237EB1 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK92169759B4AC35D1 (SITE_ID), add constraint FK92169759B4AC35D1 foreign key (SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK9216975942148B8 (CLINICAL_REPORT_ID), add constraint FK9216975942148B8 foreign key (CLINICAL_REPORT_ID) references CATISSUE_CLINICAL_REPORT (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK921697595FFBBF21 (COLLECTION_PROTOCOL_REGISTRATION_ID), 
add constraint FK921697595FFBBF21 foreign key (COLLECTION_PROTOCOL_REGISTRATION_ID) references CATISSUE_COLLECTION_PROTOCOL_REGISTRATION (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK9216975910346953 (COLLECTION_PROTOCOL_EVENT_ID), add constraint FK9216975910346953 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLLECTION_PROTOCOL_EVENT (IDENTIFIER);
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS add index FK2C72A2AA2EBCB751 (USER_ID), add constraint FK2C72A2AA2EBCB751 foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS add index FK2C72A2AA14237EB1 (SPECIMEN_ID), add constraint FK2C72A2AA14237EB1 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN_PROTOCOL add index FKB84813737D3C1CA2 (PRINCIPAL_INVESTIGATOR_ID), add constraint FKB84813737D3C1CA2 foreign key (PRINCIPAL_INVESTIGATOR_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_SPUN_EVENT_PARAMETERS add index FK312D77BCAFE2B1CE (IDENTIFIER), add constraint FK312D77BCAFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D01B4AC35D1 (SITE_ID), add constraint FK28429D01B4AC35D1 foreign key (SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D01656F1455 (STORAGE_CONTAINER_CAPACITY_ID), add constraint FK28429D01656F1455 foreign key (STORAGE_CONTAINER_CAPACITY_ID) references CATISSUE_STORAGE_CONTAINER_CAPACITY (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D018A710D7A (STORAGE_TYPE_ID), add constraint FK28429D018A710D7A foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D01AE96B64B (PARENT_CONTAINER_ID), add constraint FK28429D01AE96B64B foreign key (PARENT_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER_DETAILS add index FK66CE30E47BA7B81A (STORAGE_CONTAINER_ID), add constraint FK66CE30E47BA7B81A foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_STORAGE_TYPE add index FKE9A0629A656F1455 (STORAGE_CONTAINER_CAPACITY_ID), add constraint FKE9A0629A656F1455 foreign key (STORAGE_CONTAINER_CAPACITY_ID) references CATISSUE_STORAGE_CONTAINER_CAPACITY (IDENTIFIER);
alter table CATISSUE_THAW_EVENT_PARAMETERS add index FKD8890A48AFE2B1CE (IDENTIFIER), add constraint FKD8890A48AFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_TISSUE_SPECIMEN add index FKB9860FA6D388F9A8 (IDENTIFIER), add constraint FKB9860FA6D388F9A8 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT add index FK67C6950ACBA71E6D (IDENTIFIER), add constraint FK67C6950ACBA71E6D foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS add index FK1A13AD3DD4DBC9BE (IDENTIFIER), add constraint FK1A13AD3DD4DBC9BE foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add index FK4645C5AC7ECD098F (FROM_STORAGE_CONTAINER_ID), add constraint FK4645C5AC7ECD098F foreign key (FROM_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add index FK4645C5AC1AE02F5E (TO_STORAGE_CONTAINER_ID), add constraint FK4645C5AC1AE02F5E foreign key (TO_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add index FK4645C5ACAFE2B1CE (IDENTIFIER), add constraint FK4645C5ACAFE2B1CE foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC7610741AD (CANCER_RESEARCH_GROUP_ID), add constraint FKB025CFC7610741AD foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC7DBD280B1 (DEPARTMENT_ID), add constraint FKB025CFC7DBD280B1 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC77CA89863 (ADDRESS_ID), add constraint FKB025CFC77CA89863 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC75D955563 (INSTITUTION_ID), add constraint FKB025CFC75D955563 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION (IDENTIFIER);
