INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1208);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1226);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1317);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1436);


