<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Enumeration" targetNamespace="http://enumeration.com/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://enumeration.com/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://enumeration.com/bindings" location="enumeration_bindings.wsdl"/>
  <wsdl:service name="EnumerationService">
    <wsdl:port name="EnumerationPortTypePort" binding="binding:EnumerationPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
