DROP USER devuser CASCADE;

CREATE USER devuser PROFILE "DEFAULT" IDENTIFIED BY devuser123 DEFAULT TABLESPACE "catissuecore_test1" TEMPORARY TABLESPACE "TEMP" QUOTA UNLIMITED ON "catissuecore_test1";

GRANT CONNECT, RESOURCE TO devuser;

GRANT DBA TO devuser;

ALTER USER devuser DEFAULT ROLE ALL;