DROP TABLE IF EXISTS `CSM_FILTER_CLAUSE`;

CREATE TABLE `CSM_FILTER_CLAUSE` (
	FILTER_CLAUSE_ID BIGINT AUTO_INCREMENT  NOT NULL,
	CLASS_NAME VARCHAR(100) NOT NULL,
	FILTER_CHAIN VARCHAR(2000) NOT NULL,
	TARGET_CLASS_NAME VARCHAR (100) NOT NULL,
	TARGET_CLASS_ATTRIBUTE_NAME VARCHAR (100) NOT NULL,
	TARGET_CLASS_ATTRIBUTE_TYPE VARCHAR (100) NOT NULL,
	TARGET_CLASS_ALIAS VARCHAR (100),
	TARGET_CLASS_ATTRIBUTE_ALIAS VARCHAR (100),
	GENERATED_SQL VARCHAR (4000) NOT NULL,
	APPLICATION_ID BIGINT NOT NULL,
	UPDATE_DATE DATE NOT NULL,
	PRIMARY KEY(FILTER_CLAUSE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE CSM_PROTECTION_ELEMENT ADD ( ATTRIBUTE_VALUE VARCHAR(100) );
ALTER TABLE CSM_PROTECTION_ELEMENT DROP INDEX UQ_PE_PE_NAME_ATTRIBUTE_APP_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD CONSTRAINT UQ_PE_PE_NAME_ATTRIBUTE_VALUE_APP_ID UNIQUE (OBJECT_ID, ATTRIBUTE, ATTRIBUTE_VALUE, APPLICATION_ID);
ALTER TABLE CSM_USER MODIFY COLUMN LOGIN_NAME VARCHAR(500);
ALTER TABLE CSM_USER ADD COLUMN MIGRATED_FLAG BOOL NOT NULL DEFAULT 0;
ALTER TABLE CSM_USER ADD COLUMN PREMGRT_LOGIN_NAME VARCHAR(100) ;
ALTER TABLE CSM_PG_PE MODIFY COLUMN UPDATE_DATE DATE DEFAULT '0000-00-00';
ALTER TABLE CSM_ROLE_PRIVILEGE DROP COLUMN UPDATE_DATE;
ALTER TABLE CSM_USER_PE DROP COLUMN UPDATE_DATE;
ALTER TABLE CSM_FILTER_CLAUSE CHANGE GENERATED_SQL GENERATED_SQL_USER VARCHAR (4000) NOT NULL;
ALTER TABLE CSM_FILTER_CLAUSE ADD COLUMN GENERATED_SQL_GROUP VARCHAR (4000) NOT NULL;

DROP TABLE IF EXISTS `CSM_MAPPING`;

CREATE TABLE `CSM_MAPPING` (
  MAPPING_ID bigint(20) NOT NULL auto_increment,
  APPLICATION_ID bigint(20) NOT NULL,
  OBJECT_NAME varchar(100) NOT NULL,
  ATTRIBUTE_NAME varchar(100) NOT NULL,
  OBJECT_PACKAGE_NAME varchar(100),
  TABLE_NAME varchar(100),
  TABLE_NAME_GROUP varchar(100),
  TABLE_NAME_USER varchar(100),
  VIEW_NAME_GROUP varchar(100),
  VIEW_NAME_USER varchar(100),
  ACTIVE_FLAG tinyint(1) NOT NULL default '0',
  MAINTAINED_FLAG tinyint(1) NOT NULL default '0',
  UPDATE_DATE date default '0000-00-00',
  PRIMARY KEY(MAPPING_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE CSM_MAPPING ADD CONSTRAINT FK_PE_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES csm_application (APPLICATION_ID) ON DELETE CASCADE;
ALTER TABLE CSM_MAPPING ADD CONSTRAINT UQ_MP_OBJ_NAME_ATTRI_NAME_APP_ID UNIQUE (OBJECT_NAME,ATTRIBUTE_NAME,APPLICATION_ID);
ALTER TABLE CSM_APPLICATION ADD COLUMN CSM_VERSION VARCHAR(20);
