catissue_audit_event_details;select ELEMENT_NAME,CURRENT_VALUE from catissue_audit_event_details where ELEMENT_NAME='RECEIVED_QUALITY'
catissue_audit_event;select EVENT_TYPE from catissue_audit_event
