LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/ASSOCIATION.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE ASSOCIATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ASSOCIATION_ID NULLIF ASSOCIATION_ID='\\N',ASSOCIATION_TYPE NULLIF ASSOCIATION_TYPE='\\N')