LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/CATEGORIAL_ATTRIBUTE.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE CATEGORIAL_ATTRIBUTE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ID NULLIF ID='\\N',CATEGORIAL_CLASS_ID NULLIF CATEGORIAL_CLASS_ID='\\N',DE_CATEGORY_ATTRIBUTE_ID NULLIF DE_CATEGORY_ATTRIBUTE_ID='\\N',DE_SOURCE_CLASS_ATTRIBUTE_ID NULLIF DE_SOURCE_CLASS_ATTRIBUTE_ID='\\N')