LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/CATEGORY.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE CATEGORY 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ID NULLIF ID='\\N',DE_ENTITY_ID NULLIF DE_ENTITY_ID='\\N',PARENT_CATEGORY_ID NULLIF PARENT_CATEGORY_ID='\\N',ROOT_CATEGORIAL_CLASS_ID NULLIF ROOT_CATEGORIAL_CLASS_ID='\\N')