LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/CATEGORY.csv' 
APPEND 
INTO TABLE CATEGORY 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ID NULLIF ID='\\N',DE_ENTITY_ID NULLIF DE_ENTITY_ID='\\N',PARENT_CATEGORY_ID NULLIF PARENT_CATEGORY_ID='\\N',ROOT_CATEGORIAL_CLASS_ID NULLIF ROOT_CATEGORIAL_CLASS_ID='\\N')