LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/CURATED_PATH_TO_PATH.csv' 
APPEND 
INTO TABLE CURATED_PATH_TO_PATH 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(CURATED_PATH_ID NULLIF CURATED_PATH_ID='\\N',PATH_ID NULLIF PATH_ID='\\N')