LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/CURATED_PATH.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE CURATED_PATH 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(CURATED_PATH_ID NULLIF CURATED_PATH_ID='\\N',ENTITY_IDS NULLIF ENTITY_IDS='\\N',SELECTED NULLIF SELECTED='\\N')