LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/CURATED_PATH.csv' 
APPEND 
INTO TABLE CURATED_PATH 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(CURATED_PATH_ID NULLIF CURATED_PATH_ID='\\N',ENTITY_IDS NULLIF ENTITY_IDS='\\N',SELECTED NULLIF SELECTED='\\N')