LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/CURATED_PATH_TO_PATH.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE CURATED_PATH_TO_PATH 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(CURATED_PATH_ID NULLIF CURATED_PATH_ID='\\N',PATH_ID NULLIF PATH_ID='\\N')