LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DE_COLL_ATTR_RECORD_VALUES.csv' 
APPEND 
INTO TABLE DE_COLL_ATTR_RECORD_VALUES 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',RECORD_VALUE NULLIF RECORD_VALUE='\\N',COLLECTION_ATTR_RECORD_ID NULLIF COLLECTION_ATTR_RECORD_ID='\\N')