LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DE_FILE_ATTR_RECORD_VALUES.csv' 
APPEND 
INTO TABLE DE_FILE_ATTR_RECORD_VALUES 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CONTENT_TYPE NULLIF CONTENT_TYPE='\\N',FILE_CONTENT NULLIF FILE_CONTENT='\\N',FILE_NAME NULLIF FILE_NAME='\\N',RECORD_ID NULLIF RECORD_ID='\\N')