LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DE_OBJECT_ATTR_RECORD_VALUES.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DE_OBJECT_ATTR_RECORD_VALUES 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CLASS_NAME NULLIF CLASS_NAME='\\N',OBJECT_CONTENT NULLIF OBJECT_CONTENT='\\N',RECORD_ID NULLIF RECORD_ID='\\N')