LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_TAGGED_VALUE.csv' 
APPEND 
INTO TABLE DYEXTN_TAGGED_VALUE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',T_KEY NULLIF T_KEY='\\N',T_VALUE NULLIF T_VALUE='\\N',ABSTRACT_METADATA_ID NULLIF ABSTRACT_METADATA_ID='\\N')