LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_LIST_BOX.csv' 
APPEND 
INTO TABLE DYEXTN_LIST_BOX 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',MULTISELECT NULLIF MULTISELECT='\\N')