LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CONTAINMENT_CONTROL.csv' 
APPEND 
INTO TABLE DYEXTN_CONTAINMENT_CONTROL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',DISPLAY_CONTAINER_ID NULLIF DISPLAY_CONTAINER_ID='\\N')