LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_DATE_CONCEPT_VALUE.csv' 
APPEND 
INTO TABLE DYEXTN_DATE_CONCEPT_VALUE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',VALUE DATE 'YYYY-MM-DD' NULLIF VALUE='\\N')