LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ENTITY_MAP.csv' 
APPEND 
INTO TABLE DYEXTN_ENTITY_MAP 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CONTAINER_ID NULLIF CONTAINER_ID='\\N',STATUS NULLIF STATUS='\\N',STATIC_ENTITY_ID NULLIF STATIC_ENTITY_ID='\\N',CREATED_DATE DATE 'YYYY-MM-DD' NULLIF CREATED_DATE='\\N',CREATED_BY NULLIF CREATED_BY='\\N')