LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_FILE_EXTENSIONS.csv' 
APPEND 
INTO TABLE DYEXTN_FILE_EXTENSIONS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',FILE_EXTENSION NULLIF FILE_EXTENSION='\\N',ATTRIBUTE_ID NULLIF ATTRIBUTE_ID='\\N')