LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CADSR_VALUE_DOMAIN_INFO.csv' 
APPEND 
INTO TABLE DYEXTN_CADSR_VALUE_DOMAIN_INFO 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',DATATYPE NULLIF DATATYPE='\\N',NAME NULLIF NAME='\\N',TYPE NULLIF TYPE='\\N',PRIMITIVE_ATTRIBUTE_ID NULLIF PRIMITIVE_ATTRIBUTE_ID='\\N')