LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_SELECT_CONTROL.csv' 
APPEND 
INTO TABLE DYEXTN_SELECT_CONTROL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',SEPARATOR_STRING NULLIF SEPARATOR_STRING='\\N')