LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CADSRDE.csv' 
APPEND 
INTO TABLE DYEXTN_CADSRDE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',PUBLIC_ID NULLIF PUBLIC_ID='\\N')