LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ABSTRACT_METADATA.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_ABSTRACT_METADATA 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CREATED_DATE DATE 'YYYY-MM-DD' NULLIF CREATED_DATE='\\N',DESCRIPTION NULLIF DESCRIPTION='\\N',LAST_UPDATED DATE 'YYYY-MM-DD' NULLIF LAST_UPDATED='\\N',NAME NULLIF NAME='\\N',PUBLIC_ID NULLIF PUBLIC_ID='\\N')