LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_STRING_TYPE_INFO.csv' 
APPEND 
INTO TABLE DYEXTN_STRING_TYPE_INFO 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',MAX_SIZE NULLIF MAX_SIZE='\\N')