LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ASSOCIATION.csv' 
APPEND 
INTO TABLE DYEXTN_ASSOCIATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',DIRECTION NULLIF DIRECTION='\\N',TARGET_ENTITY_ID NULLIF TARGET_ENTITY_ID='\\N',SOURCE_ROLE_ID NULLIF SOURCE_ROLE_ID='\\N',TARGET_ROLE_ID NULLIF TARGET_ROLE_ID='\\N',IS_SYSTEM_GENERATED NULLIF IS_SYSTEM_GENERATED='\\N')