LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ENTITY_MAP_RECORD.csv' 
APPEND 
INTO TABLE DYEXTN_ENTITY_MAP_RECORD 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',FORM_CONTEXT_ID NULLIF FORM_CONTEXT_ID='\\N',STATIC_ENTITY_RECORD_ID NULLIF STATIC_ENTITY_RECORD_ID='\\N',STATUS NULLIF STATUS='\\N',DYNAMIC_ENTITY_RECORD_ID NULLIF DYNAMIC_ENTITY_RECORD_ID='\\N',MODIFIED_DATE DATE 'YYYY-MM-DD' NULLIF MODIFIED_DATE='\\N',CREATED_DATE DATE 'YYYY-MM-DD' NULLIF CREATED_DATE='\\N',CREATED_BY NULLIF CREATED_BY='\\N')