LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_FILE_UPLOAD.csv' 
APPEND 
INTO TABLE DYEXTN_FILE_UPLOAD 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',NO_OF_COLUMNS NULLIF NO_OF_COLUMNS='\\N')