LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CONTROL.csv' 
APPEND 
INTO TABLE DYEXTN_CONTROL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CAPTION NULLIF CAPTION='\\N',CSS_CLASS NULLIF CSS_CLASS='\\N',HIDDEN,NAME NULLIF NAME='\\N',SEQUENCE_NUMBER NULLIF SEQUENCE_NUMBER='\\N',TOOLTIP NULLIF TOOLTIP='\\N',ABSTRACT_ATTRIBUTE_ID NULLIF ABSTRACT_ATTRIBUTE_ID='\\N',CONTAINER_ID NULLIF CONTAINER_ID='\\N')