LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_PRIMITIVE_ATTRIBUTE.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_PRIMITIVE_ATTRIBUTE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',IS_COLLECTION NULLIF IS_COLLECTION='\\N',IS_IDENTIFIED NULLIF IS_IDENTIFIED='\\N',IS_PRIMARY_KEY NULLIF IS_PRIMARY_KEY='\\N',IS_NULLABLE NULLIF IS_NULLABLE='\\N')