LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CONTAINER.csv' 
APPEND 
INTO TABLE DYEXTN_CONTAINER 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',BUTTON_CSS NULLIF BUTTON_CSS='\\N',CAPTION NULLIF CAPTION='\\N',ENTITY_ID NULLIF ENTITY_ID='\\N',MAIN_TABLE_CSS NULLIF MAIN_TABLE_CSS='\\N',REQUIRED_FIELD_INDICATOR NULLIF REQUIRED_FIELD_INDICATOR='\\N',REQUIRED_FIELD_WARNING_MESSAGE NULLIF REQUIRED_FIELD_WARNING_MESSAGE='\\N',TITLE_CSS NULLIF TITLE_CSS='\\N',BASE_CONTAINER_ID NULLIF BASE_CONTAINER_ID='\\N',ENTITY_GROUP_ID NULLIF ENTITY_GROUP_ID='\\N',VIEW_ID NULLIF VIEW_ID='\\N')