LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ASSO_DISPLAY_ATTR.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_ASSO_DISPLAY_ATTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',SEQUENCE_NUMBER NULLIF SEQUENCE_NUMBER='\\N',DISPLAY_ATTRIBUTE_ID NULLIF DISPLAY_ATTRIBUTE_ID='\\N',SELECT_CONTROL_ID NULLIF SELECT_CONTROL_ID='\\N')