LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ROLE.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_ROLE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',ASSOCIATION_TYPE NULLIF ASSOCIATION_TYPE='\\N',MAX_CARDINALITY NULLIF MAX_CARDINALITY='\\N',MIN_CARDINALITY NULLIF MIN_CARDINALITY='\\N',NAME NULLIF NAME='\\N')