LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CONTROL.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_CONTROL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CAPTION NULLIF CAPTION='\\N',CSS_CLASS NULLIF CSS_CLASS='\\N',HIDDEN,NAME NULLIF NAME='\\N',SEQUENCE_NUMBER NULLIF SEQUENCE_NUMBER='\\N',TOOLTIP NULLIF TOOLTIP='\\N',ABSTRACT_ATTRIBUTE_ID NULLIF ABSTRACT_ATTRIBUTE_ID='\\N',CONTAINER_ID NULLIF CONTAINER_ID='\\N')