LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_FORM_CONTEXT.csv' 
APPEND 
INTO TABLE DYEXTN_FORM_CONTEXT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',IS_INFINITE_ENTRY NULLIF IS_INFINITE_ENTRY='\\N',ENTITY_MAP_ID NULLIF ENTITY_MAP_ID='\\N',STUDY_FORM_LABEL NULLIF STUDY_FORM_LABEL='\\N',NO_OF_ENTRIES NULLIF NO_OF_ENTRIES='\\N')