LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_NUMERIC_TYPE_INFO.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_NUMERIC_TYPE_INFO 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',MEASUREMENT_UNITS NULLIF MEASUREMENT_UNITS='\\N',DECIMAL_PLACES NULLIF DECIMAL_PLACES='\\N',NO_DIGITS NULLIF NO_DIGITS='\\N')