LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_NUMERIC_TYPE_INFO.csv' 
APPEND 
INTO TABLE DYEXTN_NUMERIC_TYPE_INFO 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',MEASUREMENT_UNITS NULLIF MEASUREMENT_UNITS='\\N',DECIMAL_PLACES NULLIF DECIMAL_PLACES='\\N',NO_DIGITS NULLIF NO_DIGITS='\\N')