LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_SEMANTIC_PROPERTY.csv' 
APPEND 
INTO TABLE DYEXTN_SEMANTIC_PROPERTY 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CONCEPT_CODE NULLIF CONCEPT_CODE='\\N',TERM NULLIF TERM='\\N',THESAURAS_NAME NULLIF THESAURAS_NAME='\\N',SEQUENCE_NUMBER NULLIF SEQUENCE_NUMBER='\\N',CONCEPT_DEFINITION NULLIF CONCEPT_DEFINITION='\\N',ABSTRACT_METADATA_ID NULLIF ABSTRACT_METADATA_ID='\\N',ABSTRACT_VALUE_ID NULLIF ABSTRACT_VALUE_ID='\\N')