LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ENTITY_GROUP_REL.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE DYEXTN_ENTITY_GROUP_REL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ENTITY_GROUP_ID NULLIF ENTITY_GROUP_ID='\\N',ENTITY_ID NULLIF ENTITY_ID='\\N')