LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_DATA_ELEMENT.csv' 
APPEND 
INTO TABLE DYEXTN_DATA_ELEMENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',ATTRIBUTE_TYPE_INFO_ID NULLIF ATTRIBUTE_TYPE_INFO_ID='\\N')