LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ENTITY.csv' 
APPEND 
INTO TABLE DYEXTN_ENTITY 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',DATA_TABLE_STATE NULLIF DATA_TABLE_STATE='\\N',IS_ABSTRACT NULLIF IS_ABSTRACT='\\N',PARENT_ENTITY_ID NULLIF PARENT_ENTITY_ID='\\N',INHERITANCE_STRATEGY NULLIF INHERITANCE_STRATEGY='\\N',DISCRIMINATOR_COLUMN_NAME NULLIF DISCRIMINATOR_COLUMN_NAME='\\N',DISCRIMINATOR_VALUE NULLIF DISCRIMINATOR_VALUE='\\N')