LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_ENTITY_GROUP_REL.csv' 
APPEND 
INTO TABLE DYEXTN_ENTITY_GROUP_REL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ENTITY_GROUP_ID NULLIF ENTITY_GROUP_ID='\\N',ENTITY_ID NULLIF ENTITY_ID='\\N')