LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_CONSTRAINT_PROPERTIES.csv' 
APPEND 
INTO TABLE DYEXTN_CONSTRAINT_PROPERTIES 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',SOURCE_ENTITY_KEY NULLIF SOURCE_ENTITY_KEY='\\N',TARGET_ENTITY_KEY NULLIF TARGET_ENTITY_KEY='\\N',ASSOCIATION_ID NULLIF ASSOCIATION_ID='\\N')