LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/DYEXTN_RULE_PARAMETER.csv' 
APPEND 
INTO TABLE DYEXTN_RULE_PARAMETER 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',NAME NULLIF NAME='\\N',VALUE NULLIF VALUE='\\N',RULE_ID NULLIF RULE_ID='\\N')