LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/INTER_MODEL_ASSOCIATION.csv' 
APPEND 
INTO TABLE INTER_MODEL_ASSOCIATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ASSOCIATION_ID NULLIF ASSOCIATION_ID='\\N',LEFT_ENTITY_ID NULLIF LEFT_ENTITY_ID='\\N',LEFT_ATTRIBUTE_ID NULLIF LEFT_ATTRIBUTE_ID='\\N',RIGHT_ENTITY_ID NULLIF RIGHT_ENTITY_ID='\\N',RIGHT_ATTRIBUTE_ID NULLIF RIGHT_ATTRIBUTE_ID='\\N')