LOAD DATA INFILE 'H://caTissue//work//workspace//catissuecoreNew/SQL/DBUpgrade/Common/CAModelCSVs/INTRA_MODEL_ASSOCIATION.csv' 
APPEND 
INTO TABLE INTRA_MODEL_ASSOCIATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ASSOCIATION_ID NULLIF ASSOCIATION_ID='\\N',DE_ASSOCIATION_ID NULLIF DE_ASSOCIATION_ID='\\N')