LOAD DATA INFILE 'D://Nightly_Build//projects//catissuecore/SQL/DBUpgrade/Common/CAModelCSVs/INTRA_MODEL_ASSOCIATION.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE INTRA_MODEL_ASSOCIATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(ASSOCIATION_ID NULLIF ASSOCIATION_ID='\\N',DE_ASSOCIATION_ID NULLIF DE_ASSOCIATION_ID='\\N')