//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.23 at 12:30:40 CDT 
//


package edu.wustl.cider.jaxb.domain.impl;

public class SpecimenCollectionTypeImpl implements edu.wustl.cider.jaxb.domain.SpecimenCollectionType, com.sun.xml.bind.JAXBObject, edu.wustl.cider.jaxb.domain.impl.runtime.UnmarshallableObject, edu.wustl.cider.jaxb.domain.impl.runtime.XMLSerializable, edu.wustl.cider.jaxb.domain.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _Specimen;
    public final static java.lang.Class version = (edu.wustl.cider.jaxb.domain.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (edu.wustl.cider.jaxb.domain.SpecimenCollectionType.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getSpecimen() {
        if (_Specimen == null) {
            _Specimen = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Specimen;
    }

    public java.util.List getSpecimen() {
        return _getSpecimen();
    }

    public edu.wustl.cider.jaxb.domain.impl.runtime.UnmarshallingEventHandler createUnmarshaller(edu.wustl.cider.jaxb.domain.impl.runtime.UnmarshallingContext context) {
        return new edu.wustl.cider.jaxb.domain.impl.SpecimenCollectionTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(edu.wustl.cider.jaxb.domain.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Specimen == null)? 0 :_Specimen.size());
        while (idx1 != len1) {
            context.startElement("", "Specimen");
            int idx_0 = idx1;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Specimen.get(idx_0 ++)), "Specimen");
            context.endNamespaceDecls();
            int idx_1 = idx1;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Specimen.get(idx_1 ++)), "Specimen");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Specimen.get(idx1 ++)), "Specimen");
            context.endElement();
        }
    }

    public void serializeAttributes(edu.wustl.cider.jaxb.domain.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Specimen == null)? 0 :_Specimen.size());
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public void serializeURIs(edu.wustl.cider.jaxb.domain.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Specimen == null)? 0 :_Specimen.size());
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (edu.wustl.cider.jaxb.domain.SpecimenCollectionType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.s"
+"un.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expt\u0000 Lcom/sun/msv/gram"
+"mar/Expression;xr\u0000\u001ecom.sun.msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002"
+"L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000"
+"~\u0000\u0002xpppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.m"
+"sv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttribute"
+"sL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sr\u0000\u001fcom.sun.msv.grammar.Sequen"
+"ceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002"
+"L\u0000\u0004exp1q\u0000~\u0000\u0002L\u0000\u0004exp2q\u0000~\u0000\u0002xq\u0000~\u0000\u0003ppsq\u0000~\u0000\u0006pp\u0000sr\u0000\u001dcom.sun.msv.gra"
+"mmar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u000bppsq\u0000~\u0000\u0000sr\u0000\u0011java.lang.Boolean"
+"\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0007xq\u0000~\u0000\u0003q\u0000~\u0000\u0012psr\u00002com.su"
+"n.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0003sq\u0000~\u0000\u0011\u0001psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001d"
+"com.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gr"
+"ammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0017psr\u0000"
+"#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet"
+"\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001exq\u0000~\u0000\u0019t\u0000(edu.wustl.c"
+"ider.jaxb.domain.SpecimenTypet\u0000+http://java.sun.com/jaxb/xjc"
+"/dummy-elementssq\u0000~\u0000\u000eppsq\u0000~\u0000\u0013q\u0000~\u0000\u0012psr\u0000\u001bcom.sun.msv.grammar.D"
+"ataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006e"
+"xceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000"
+"\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.ms"
+"v.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.d"
+"atatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype."
+"xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\u001eL\u0000\btypeName"
+"q\u0000~\u0000\u001eL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpacePro"
+"cessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com."
+"sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"psr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tloc"
+"alNameq\u0000~\u0000\u001eL\u0000\fnamespaceURIq\u0000~\u0000\u001expq\u0000~\u0000/q\u0000~\u0000.sq\u0000~\u0000\u001dt\u0000\u0004typet\u0000)h"
+"ttp://www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000\u001csq\u0000~\u0000\u001dt\u0000\bSpecim"
+"ent\u0000\u0000sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexp"
+"Tablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000"
+"-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005"
+"countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Expres"
+"sionPool;xp\u0000\u0000\u0000\u0005\u0001pq\u0000~\u0000\u0010q\u0000~\u0000\u0005q\u0000~\u0000\u000fq\u0000~\u0000\"q\u0000~\u0000\fx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends edu.wustl.cider.jaxb.domain.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(edu.wustl.cider.jaxb.domain.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(edu.wustl.cider.jaxb.domain.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return edu.wustl.cider.jaxb.domain.impl.SpecimenCollectionTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("Specimen" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  1 :
                        if (("SpecimenEvents" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("SpecimenPosition" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("SpecimenCharacteristics" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("isAvailable" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("activityStatus" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("quantity" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("pathologicalStatus" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("type" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("className" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("id" == ___local)&&("" == ___uri)) {
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                        return ;
                    case  0 :
                        if (("Specimen" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromLeaveElement((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname)));
                        return ;
                    case  2 :
                        if (("Specimen" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromEnterAttribute((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname)));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromLeaveAttribute((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, ___uri, ___local, ___qname)));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            _getSpecimen().add(((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl) spawnChildFromText((edu.wustl.cider.jaxb.domain.impl.SpecimenTypeImpl.class), 2, value)));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
