DECLARE
   EVENTID NUMBER;
   EVENTTYPE VARCHAR(20);

BEGIN
DECLARE CURSOR INV_CUR IS
		 SELECT DISTINCT AUDIT_EVENT_ID,EVENT_TYPE 
                 FROM CATISSUE_AUDIT_EVENT_LOG ORDER BY AUDIT_EVENT_ID ;					   
BEGIN
   OPEN INV_CUR;
   FETCH INV_CUR INTO EVENTID,EVENTTYPE;
   LOOP
     IF INV_CUR%NOTFOUND THEN
	 	EXIT;
	 END IF;
	UPDATE CATISSUE_AUDIT_EVENT SET EVENT_TYPE = EVENTTYPE WHERE 
                IDENTIFIER = EVENTID ;
	 FETCH INV_CUR INTO EVENTID,EVENTTYPE;
   END LOOP;
   CLOSE INV_CUR;
   commit;
END;
END; 
/