
CREATE TABLE DYEXTN_OBJECT_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_COLUMN_PROPERTIES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   PRIMITIVE_ATTRIBUTE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_USERDEFINED_DE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CONSTRAINT_PROPERTIES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   SOURCE_ENTITY_KEY VARCHAR2(255),
   TARGET_ENTITY_KEY VARCHAR2(255),
   ASSOCIATION_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_PERMISSIBLE_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DESCRIPTION VARCHAR2(255),
   ATTRIBUTE_TYPE_INFO_ID NUMBER(19,0),
   USER_DEF_DE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CHECK_BOX (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_TABLE_PROPERTIES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   ENTITY_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ENTITY_MAP_CONDNS (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   STATIC_RECORD_ID NUMBER(19,0),
   TYPE_ID NUMBER(19,0),
   FORM_CONTEXT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_INTEGER_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE NUMBER(10,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_STRING_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_BOOLEAN_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_BOOLEAN_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE NUMBER(1,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DE_FILE_ATTR_RECORD_VALUES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONTENT_TYPE VARCHAR2(255),
   FILE_CONTENT blob,
   FILE_NAME VARCHAR2(255),
   RECORD_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ABSTRACT_METADATA (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CREATED_DATE DATE,
   DESCRIPTION VARCHAR2(1000),
   LAST_UPDATED DATE,
   NAME VARCHAR2(1000),
   PUBLIC_ID VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_STRING_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   MAX_SIZE NUMBER(10,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_SHORT_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE NUMBER(5,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_FLOAT_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_FILE_UPLOAD (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NO_OF_COLUMNS NUMBER(10,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_BARR_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ENTITY (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DATA_TABLE_STATE NUMBER(10,0),
   IS_ABSTRACT NUMBER(1,0),
   PARENT_ENTITY_ID NUMBER(19,0),
   INHERITANCE_STRATEGY NUMBER(10,0),
   DISCRIMINATOR_COLUMN_NAME VARCHAR2(255),
   DISCRIMINATOR_VALUE VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_INTEGER_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_TAGGED_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   T_KEY VARCHAR2(255),
   T_VALUE VARCHAR2(255),
   ABSTRACT_METADATA_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DE_OBJECT_ATTR_RECORD_VALUES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CLASS_NAME VARCHAR2(255),
   OBJECT_CONTENT blob,
   RECORD_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_COMBOBOX (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CADSR_VALUE_DOMAIN_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DATATYPE VARCHAR2(255),
   NAME VARCHAR2(255),
   TYPE VARCHAR2(255),
   PRIMITIVE_ATTRIBUTE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_PRIMITIVE_ATTRIBUTE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   IS_COLLECTION NUMBER(1,0),
   IS_IDENTIFIED NUMBER(1,0),
   IS_PRIMARY_KEY NUMBER(1,0),
   IS_NULLABLE NUMBER(1,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ASSOCIATION (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DIRECTION VARCHAR2(255),
   TARGET_ENTITY_ID NUMBER(19,0),
   SOURCE_ROLE_ID NUMBER(19,0),
   TARGET_ROLE_ID NUMBER(19,0),
   IS_SYSTEM_GENERATED NUMBER(1,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ENTITY_MAP (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONTAINER_ID NUMBER(19,0),
   STATUS VARCHAR2(10),
   STATIC_ENTITY_ID NUMBER(19,0),
   CREATED_DATE DATE,
   CREATED_BY VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CADSRDE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   PUBLIC_ID VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DOUBLE_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_SELECT_CONTROL (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   SEPARATOR_STRING VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ENTITY_GROUP_REL (
   ENTITY_GROUP_ID NUMBER(19,0) NOT NULL,
   ENTITY_ID NUMBER(19,0) NOT NULL,
   primary key (ENTITY_ID, ENTITY_GROUP_ID)
);
CREATE TABLE DYEXTN_DATABASE_PROPERTIES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NAME VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_FILE_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   MAX_FILE_SIZE FLOAT,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_FILE_EXTENSIONS (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   FILE_EXTENSION VARCHAR2(255),
   ATTRIBUTE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_LONG_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_FLOAT_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE FLOAT,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_TEXTFIELD (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NO_OF_COLUMNS NUMBER(10,0),
   IS_PASSWORD NUMBER(1,0),
   IS_URL NUMBER(1,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ROLE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   ASSOCIATION_TYPE VARCHAR2(255),
   MAX_CARDINALITY NUMBER(10,0),
   MIN_CARDINALITY NUMBER(10,0),
   NAME VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_RULE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NAME VARCHAR2(255),
   ATTRIBUTE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DATE_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   FORMAT VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ATTRIBUTE_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   PRIMITIVE_ATTRIBUTE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ENTITY_MAP_RECORD (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   FORM_CONTEXT_ID NUMBER(19,0),
   STATIC_ENTITY_RECORD_ID NUMBER(19,0),
   STATUS VARCHAR2(10),
   DYNAMIC_ENTITY_RECORD_ID NUMBER(19,0),
   MODIFIED_DATE DATE,
   CREATED_DATE DATE,
   CREATED_BY VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ASSO_DISPLAY_ATTR (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   SEQUENCE_NUMBER NUMBER(10,0),
   DISPLAY_ATTRIBUTE_ID NUMBER(19,0),
   SELECT_CONTROL_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_TEXTAREA (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   TEXTAREA_COLUMNS NUMBER(10,0),
   TEXTAREA_ROWS NUMBER(10,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ENTITY_GROUP (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   LONG_NAME VARCHAR2(255),
   SHORT_NAME VARCHAR2(255),
   VERSION VARCHAR2(255),
   IS_SYSTEM_GENERATED NUMBER(1,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DATA_ELEMENT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   ATTRIBUTE_TYPE_INFO_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DOUBLE_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE double precision,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_LIST_BOX (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   MULTISELECT NUMBER(1,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CONTAINMENT_CONTROL (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DISPLAY_CONTAINER_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CONTROL (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CAPTION VARCHAR2(255),
   CSS_CLASS VARCHAR2(255),
   HIDDEN NUMBER(1,0),
   NAME VARCHAR2(255),
   SEQUENCE_NUMBER NUMBER(10,0),
   TOOLTIP VARCHAR2(255),
   ABSTRACT_ATTRIBUTE_ID NUMBER(19,0),
   CONTAINER_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_LONG_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_FORM_CONTEXT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   IS_INFINITE_ENTRY NUMBER(1,0),
   ENTITY_MAP_ID NUMBER(19,0),
   STUDY_FORM_LABEL VARCHAR2(255),
   NO_OF_ENTRIES NUMBER(10,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ATTRIBUTE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   ENTIY_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_RULE_PARAMETER (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NAME VARCHAR2(255),
   VALUE VARCHAR2(255),
   RULE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DATE_CONCEPT_VALUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   VALUE DATE,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_VIEW (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NAME VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_BYTE_ARRAY_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONTENT_TYPE VARCHAR2(255),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_SEMANTIC_PROPERTY (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONCEPT_CODE VARCHAR2(255),
   TERM VARCHAR2(255),
   THESAURAS_NAME VARCHAR2(255),
   SEQUENCE_NUMBER NUMBER(10,0),
   CONCEPT_DEFINITION VARCHAR2(255),
   ABSTRACT_METADATA_ID NUMBER(19,0),
   ABSTRACT_VALUE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_ATTRIBUTE_RECORD (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   ENTITY_ID NUMBER(19,0),
   ATTRIBUTE_ID NUMBER(19,0),
   RECORD_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DATA_GRID (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DE_COLL_ATTR_RECORD_VALUES (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   RECORD_VALUE VARCHAR2(4000),
   COLLECTION_ATTR_RECORD_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_NUMERIC_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   MEASUREMENT_UNITS VARCHAR2(255),
   DECIMAL_PLACES NUMBER(10,0),
   NO_DIGITS NUMBER(10,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_SHORT_TYPE_INFO (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_CONTAINER (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   BUTTON_CSS VARCHAR2(255),
   CAPTION VARCHAR2(255),
   ENTITY_ID NUMBER(19,0),
   MAIN_TABLE_CSS VARCHAR2(255),
   REQUIRED_FIELD_INDICATOR VARCHAR2(255),
   REQUIRED_FIELD_WARNING_MESSAGE VARCHAR2(255),
   TITLE_CSS VARCHAR2(255),
   BASE_CONTAINER_ID NUMBER(19,0),
   ENTITY_GROUP_ID NUMBER(19,0),
   VIEW_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_RADIOBUTTON (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE DYEXTN_DATEPICKER (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);

ALTER TABLE DYEXTN_OBJECT_TYPE_INFO ADD constraint FK74819FB0BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_COLUMN_PROPERTIES ADD constraint FK8FCE2B3FBC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
ALTER TABLE DYEXTN_COLUMN_PROPERTIES ADD constraint FK8FCE2B3FB4C15A36 foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
ALTER TABLE DYEXTN_USERDEFINED_DE ADD constraint FK630761FFBC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT;
ALTER TABLE DYEXTN_CONSTRAINT_PROPERTIES ADD constraint FK82886CD8BC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
ALTER TABLE DYEXTN_CONSTRAINT_PROPERTIES ADD constraint FK82886CD8927B15B9 foreign key (ASSOCIATION_ID) references DYEXTN_ASSOCIATION;
ALTER TABLE DYEXTN_PERMISSIBLE_VALUE ADD constraint FK136264E08C8D972A foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_PERMISSIBLE_VALUE ADD constraint FK136264E03D51114B foreign key (USER_DEF_DE_ID) references DYEXTN_USERDEFINED_DE;
ALTER TABLE DYEXTN_CHECK_BOX ADD constraint FK4EFF9257BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_TABLE_PROPERTIES ADD constraint FKE608E08179F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_TABLE_PROPERTIES ADD constraint FKE608E081BC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
ALTER TABLE DYEXTN_ENTITY_MAP_CONDNS ADD constraint FK2A9D602969F17C26 foreign key (FORM_CONTEXT_ID) references DYEXTN_FORM_CONTEXT;
ALTER TABLE DYEXTN_INTEGER_CONCEPT_VALUE ADD constraint FKFBA33B3CBC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_STRING_CONCEPT_VALUE ADD constraint FKADE7D889BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_BOOLEAN_TYPE_INFO ADD constraint FK28F1809FBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_BOOLEAN_CONCEPT_VALUE ADD constraint FK57B6C4A6BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DE_FILE_ATTR_RECORD_VALUES ADD constraint FKE68334E7E150DFC9 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
ALTER TABLE DYEXTN_STRING_TYPE_INFO ADD constraint FKDA35FE02BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_SHORT_CONCEPT_VALUE ADD constraint FKC1945ABABC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_FLOAT_TYPE_INFO ADD constraint FK7E1C0693BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
ALTER TABLE DYEXTN_FILE_UPLOAD ADD constraint FK2FAD41E7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_BARR_CONCEPT_VALUE ADD constraint FK89D27DF7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_ENTITY ADD constraint FK8B243640450711A2 foreign key (PARENT_ENTITY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_ENTITY ADD constraint FK8B243640BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
ALTER TABLE DYEXTN_INTEGER_TYPE_INFO ADD constraint FK5F9CB235BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
ALTER TABLE DYEXTN_TAGGED_VALUE ADD constraint FKF79D055B7D7A9B8E foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA;
ALTER TABLE DE_OBJECT_ATTR_RECORD_VALUES ADD constraint FK504EADC4E150DFC9 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
ALTER TABLE DYEXTN_COMBOBOX ADD constraint FKABBC649ABC7298A9 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
ALTER TABLE DYEXTN_CADSR_VALUE_DOMAIN_INFO ADD constraint FK1C9AA364B4C15A36 foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
ALTER TABLE DYEXTN_PRIMITIVE_ATTRIBUTE ADD constraint FKA9F765C7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE;
ALTER TABLE DYEXTN_ASSOCIATION ADD constraint FK104684243AC5160 foreign key (SOURCE_ROLE_ID) references DYEXTN_ROLE;
ALTER TABLE DYEXTN_ASSOCIATION ADD constraint FK10468424F60C84D6 foreign key (TARGET_ROLE_ID) references DYEXTN_ROLE;
ALTER TABLE DYEXTN_ASSOCIATION ADD constraint FK104684246315C5C9 foreign key (TARGET_ENTITY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_ASSOCIATION ADD constraint FK10468424BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE;
ALTER TABLE DYEXTN_CADSRDE ADD constraint FK588A2509BC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT;
ALTER TABLE DYEXTN_DOUBLE_TYPE_INFO ADD constraint FKC83869C2BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
ALTER TABLE DYEXTN_SELECT_CONTROL ADD constraint FKDFEBB657BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_ENTITY_GROUP_REL ADD constraint FK5A0D835A992A67D7 foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP;
ALTER TABLE DYEXTN_ENTITY_GROUP_REL ADD constraint FK5A0D835A79F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_FILE_TYPE_INFO ADD constraint FKA00F0EDBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_FILE_EXTENSIONS ADD constraint FKD49834FA4D87D1BE foreign key (ATTRIBUTE_ID) references DYEXTN_FILE_TYPE_INFO;
ALTER TABLE DYEXTN_LONG_TYPE_INFO ADD constraint FK257281EDBC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
ALTER TABLE DYEXTN_FLOAT_CONCEPT_VALUE ADD constraint FK6785309ABC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_TEXTFIELD ADD constraint FKF9AFC850BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_RULE ADD constraint FKC27E0994D87D1BE foreign key (ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE;
ALTER TABLE DYEXTN_DATE_TYPE_INFO ADD constraint FKFBA549FBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_ATTRIBUTE_TYPE_INFO ADD constraint FK62596D53B4C15A36 foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
ALTER TABLE DYEXTN_ENTITY_MAP_RECORD ADD constraint FK43A4501369F17C26 foreign key (FORM_CONTEXT_ID) references DYEXTN_FORM_CONTEXT;
ALTER TABLE DYEXTN_ASSO_DISPLAY_ATTR ADD constraint FKD12FD3823B3AAE3B foreign key (DISPLAY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
ALTER TABLE DYEXTN_ASSO_DISPLAY_ATTR ADD constraint FKD12FD382F7AA8E80 foreign key (SELECT_CONTROL_ID) references DYEXTN_SELECT_CONTROL;
ALTER TABLE DYEXTN_TEXTAREA ADD constraint FK946EE257BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_ENTITY_GROUP ADD constraint FK105DE7A0BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
ALTER TABLE DYEXTN_DATA_ELEMENT ADD constraint FKB1153E48C8D972A foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_DOUBLE_CONCEPT_VALUE ADD constraint FKB94E6449BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_LIST_BOX ADD constraint FK208395A7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
ALTER TABLE DYEXTN_CONTAINMENT_CONTROL ADD constraint FK3F9D4AD3F7798636 foreign key (DISPLAY_CONTAINER_ID) references DYEXTN_CONTAINER;
ALTER TABLE DYEXTN_CONTAINMENT_CONTROL ADD constraint FK3F9D4AD3BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_CONTROL ADD constraint FK70FB5E80A67822BB foreign key (ABSTRACT_ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE;
ALTER TABLE DYEXTN_CONTROL ADD constraint FK70FB5E809C6A9B9 foreign key (CONTAINER_ID) references DYEXTN_CONTAINER;
ALTER TABLE DYEXTN_LONG_CONCEPT_VALUE ADD constraint FK3E1A6EF4BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_FORM_CONTEXT ADD constraint FKE56CCDB111B8FADA foreign key (ENTITY_MAP_ID) references DYEXTN_ENTITY_MAP;
ALTER TABLE DYEXTN_ATTRIBUTE ADD constraint FK37F1E2FFB15CD09F foreign key (ENTIY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_ATTRIBUTE ADD constraint FK37F1E2FFBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
ALTER TABLE DYEXTN_RULE_PARAMETER ADD constraint FK22567363871AAD3E foreign key (RULE_ID) references DYEXTN_RULE;
ALTER TABLE DYEXTN_DATE_CONCEPT_VALUE ADD constraint FK45F598A6BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_BYTE_ARRAY_TYPE_INFO ADD constraint FK18BDA73BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_SEMANTIC_PROPERTY ADD constraint FKD2A0B5B13BAB5E46 foreign key (ABSTRACT_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE;
ALTER TABLE DYEXTN_SEMANTIC_PROPERTY ADD constraint FKD2A0B5B17D7A9B8E foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA;
ALTER TABLE DYEXTN_ATTRIBUTE_RECORD ADD constraint FK9B20ED9179F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_ATTRIBUTE_RECORD ADD constraint FK9B20ED914D87D1BE foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
ALTER TABLE DYEXTN_DATA_GRID ADD constraint FK233EB73EBC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DE_COLL_ATTR_RECORD_VALUES ADD constraint FK847DA577355836BC foreign key (COLLECTION_ATTR_RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
ALTER TABLE DYEXTN_NUMERIC_TYPE_INFO ADD constraint FK4DEC9544BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
ALTER TABLE DYEXTN_SHORT_TYPE_INFO ADD constraint FK99540B3BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
ALTER TABLE DYEXTN_CONTAINER ADD constraint FK1EAB84E4A1257067 foreign key (BASE_CONTAINER_ID) references DYEXTN_CONTAINER;
ALTER TABLE DYEXTN_CONTAINER ADD constraint FK1EAB84E479F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
ALTER TABLE DYEXTN_CONTAINER ADD constraint FK1EAB84E4992A67D7 foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP;
ALTER TABLE DYEXTN_CONTAINER ADD constraint FK1EAB84E445DEFCF5 foreign key (VIEW_ID) references DYEXTN_VIEW;
ALTER TABLE DYEXTN_RADIOBUTTON ADD constraint FK16F5BA90BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_DATEPICKER ADD constraint FKFEADD199BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
CREATE sequence DYEXTN_PERMISSIBLEVAL_SEQ;
CREATE sequence DYEXTN_SEMANTIC_PROPERTY_SEQ;
CREATE sequence DYEXTN_ATTRIBUTE_TYPE_INFO_SEQ;
CREATE sequence DYEXTN_RULE_PARAMETER_SEQ;
CREATE sequence DYEXTN_ABSTRACT_METADATA_SEQ;
CREATE sequence DE_FILE_ATTR_REC_VALUES_SEQ;
CREATE sequence DE_OBJECT_ATTR_REC_VALUES_SEQ;
CREATE sequence DYEXTN_VIEW_SEQ;
CREATE sequence DYEXTN_CONTROL_SEQ;
CREATE sequence DYEXTN_RULE_SEQ;
CREATE sequence DYEXTN_FORM_CONTEXT_SEQ;
CREATE sequence DYEXTN_DATA_ELEMENT_SEQ;
CREATE sequence DYEXTN_VALUE_DOMAIN_SEQ;
CREATE sequence DYEXTN_ENTITY_MAP_SEQ;
CREATE sequence DE_ATTR_REC_SEQ;
CREATE sequence DYEXTN_ENTITY_MAP_CONDN_SEQ;
CREATE sequence DYEXTN_CONTAINER_SEQ;
CREATE sequence DYEXTN_FILE_EXTN_SEQ;
CREATE sequence DYEXTN_ASSO_DISPLAY_ATTR_SEQ;
CREATE sequence DYEXTN_DATABASE_PROPERTIES_SEQ;
CREATE sequence DYEXTN_ROLE_SEQ;
CREATE sequence DYEXTN_TAGGED_VALUE_SEQ;
CREATE sequence DYEXTN_ENTITY_RECORD_SEQ;
CREATE sequence DE_COLL_ATTR_REC_VALUES_SEQ;
commit;
