CREATE OR REPLACE TRIGGER SPECIMEN_BARCODE_FOR_DFCI 
AFTER INSERT 
ON catissue_specimen 
BEGIN 
 UPDATE catissue_specimen SET BARCODE = IDENTIFIER;
END;
/
CREATE OR REPLACE TRIGGER CPR_BARCODE_FOR_DFCI 
AFTER INSERT 
ON  catissue_specimen_coll_group
BEGIN 
 UPDATE catissue_specimen_coll_group SET BARCODE = IDENTIFIER;
END;
/
CREATE OR REPLACE TRIGGER ST_CONTAINER_BARCODE_FOR_DFCI 
BEFORE INSERT  
ON catissue_storage_container 
BEGIN 
 UPDATE catissue_container SET BARCODE = IDENTIFIER;
END;
/
CREATE OR REPLACE TRIGGER SHIPPING_BARCODE_FOR_DFCI 
AFTER INSERT  
ON catissue_shipment 
BEGIN 
 UPDATE catissue_shipment SET BARCODE = IDENTIFIER;
END;
/