/****** Inserts generic collection protocol required for caTIES   *******/
INSERT INTO CATISSUE_SPECIMEN_PROTOCOL VALUES (CATISSUE_SPECIMEN_PROTOCOL_SEQ.NEXTVAL,1,'@@COLL_PROT_TITLE@@','generic collection protocol','',TO_DATE('2007-02-16','yyyy-mm-dd'),NULL,NULL,'','Active');

INSERT INTO CATISSUE_COLLECTION_PROTOCOL VALUES((SELECT identifier from CATISSUE_SPECIMEN_PROTOCOL where TITLE='@@COLL_PROT_TITLE@@'),0,'',0);

INSERT INTO CATISSUE_COLL_PROT_EVENT VALUES (CATISSUE_COLL_PROT_EVENT_SEQ.NEXTVAL,'New Diagnosis','TestGCP',1,(select identifier from catissue_specimen_protocol where title='@@COLL_PROT_TITLE@@'));

INSERT INTO CATISSUE_QUANTITY VALUES (CATISSUE_QUANTITY_SEQ.NEXTVAL,0);

INSERT INTO CATISSUE_SPECIMEN_REQUIREMENT VALUES (CATISSUE_SPECIMEN_REQ_SEQ.NEXTVAL,'Tissue','Fixed Tissue','Abdomen, NOS', 'Malignant',(select max(identifier) from catissue_quantity));

INSERT INTO CATISSUE_COLL_SPECIMEN_REQ VALUES ((SELECT max(identifier) FROM CATISSUE_COLL_PROT_EVENT),(SELECT max(identifier) FROM CATISSUE_SPECIMEN_REQUIREMENT));