<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TestCounter" targetNamespace="http://www.globus.org/test/counter/bindings" xmlns:porttype="http://www.globus.org/test/counter" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.globus.org/test/counter" location="test_counter_port_type.wsdl"/>
  <wsdl:binding name="TestCounterSOAPBinding" type="porttype:TestCounter">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="create">
      <soap:operation soapAction="http://www.globus.org/test/counter/TestCounter/createRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getCounterValue">
      <soap:operation soapAction="http://www.globus.org/test/counter/TestCounter/getCounterValueRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
