CREATE OR REPLACE FUNCTION CATISSUE_LABEL_TO_NUM(str IN VARCHAR2) RETURN NUMBER IS
res NUMBER(19);
BEGIN
    res := TO_NUMBER(str);
    RETURN res;
EXCEPTION
WHEN OTHERS THEN
        RETURN NULL;
END;
/