ALTER TABLE catissue_institution ADD  DIRTY_EDIT_FLAG NUMBER(1,0) NULL;
ALTER TABLE catissue_institution ADD  REMOTE_IDENTIFIER NUMBER(19,0) NULL;
ALTER TABLE catissue_institution ADD  REMOTE_MANAGED_FLAG NUMBER(1,0);
ALTER TABLE catissue_institution add constraint INSTITUTION_UK1 UNIQUE (REMOTE_IDENTIFIER);

ALTER TABLE catissue_user ADD DIRTY_EDIT_FLAG  NUMBER(1,0) NULL;
ALTER TABLE catissue_user ADD REMOTE_IDENTIFIER  NUMBER(19,0) NULL;
ALTER TABLE catissue_user ADD REMOTE_MANAGED_FLAG  NUMBER(1,0) NULL;
ALTER TABLE catissue_user add constraint USER_UK1 UNIQUE (REMOTE_IDENTIFIER);

ALTER TABLE catissue_collection_protocol ADD DIRTY_EDIT_FLAG  NUMBER(1,0) NULL;
ALTER TABLE catissue_collection_protocol ADD REMOTE_IDENTIFIER  NUMBER(19,0) NULL;
ALTER TABLE catissue_collection_protocol ADD REMOTE_MANAGED_FLAG  NUMBER(1,0) NULL;
ALTER TABLE catissue_collection_protocol add constraint COLLECTION_PROTOCOL_UK1 UNIQUE (REMOTE_IDENTIFIER);