insert into catissue_user (IDENTIFIER, ACTIVITY_STATUS, CSM_USER_ID, EMAIL_ADDRESS,LOGIN_NAME,FIRST_NAME,LAST_NAME,PASSWORD) values (1,'Active',1,'admin@admin.com','admin@admin.com','Admin','Admin','6c416f576765696c6e63316f326d3365');
ALTER TABLE CATISSUE_COLL_PROT_REG ADD CONSTRAINT  PART_ID_TO_COLL_PROT_ID UNIQUE (PARTICIPANT_ID,COLLECTION_PROTOCOL_ID);
ALTER TABLE CATISSUE_COLL_PROT_REG ADD CONSTRAINT  PROT_PART_ID_TO_COLL_PROT_ID UNIQUE (PROTOCOL_PARTICIPANT_ID,COLLECTION_PROTOCOL_ID);
ALTER TABLE CATISSUE_PART_MEDICAL_ID ADD constraint mrn_site_unique UNIQUE key (MEDICAL_RECORD_NUMBER,SITE_ID);
commit;