/*Indexes for Participant*/
CREATE INDEX INDX_PARTICIPANT_LNAME ON CATISSUE_PARTICIPANT (LAST_NAME);
CREATE INDEX INDX_PARTICIPANT_FNAME ON CATISSUE_PARTICIPANT (FIRST_NAME);
CREATE INDEX INDX_PARTICIPANT_MNAME ON CATISSUE_PARTICIPANT (MIDDLE_NAME);
CREATE INDEX INDX_PARTICIPANT_BDATE ON CATISSUE_PARTICIPANT (BIRTH_DATE);
CREATE INDEX INDX_PARTICIPANT_DDATE ON CATISSUE_PARTICIPANT (DEATH_DATE);
CREATE INDEX INDX_PARTICIPANT_VSTATUS ON CATISSUE_PARTICIPANT (VITAL_STATUS);
CREATE INDEX INDX_PARTICIPANT_GENDER ON CATISSUE_PARTICIPANT (GENDER);
CREATE INDEX INDX_PARTICIPANT_GENOTYPE ON CATISSUE_PARTICIPANT (GENOTYPE);
CREATE INDEX INDX_RACE_NAME ON CATISSUE_RACE (RACE_NAME);
CREATE INDEX INDX_PARTICIPANT_ETHNICITY ON CATISSUE_PARTICIPANT (ETHNICITY);
/*CREATE INDEX INDX_PARTICIPANT_SSN ON CATISSUE_PARTICIPANT (SOCIAL_SECURITY_NUMBER);*/
CREATE INDEX INDX_PART_MEDICAL_RECNO ON CATISSUE_PART_MEDICAL_ID (MEDICAL_RECORD_NUMBER);


/* Indexes for Collection Protocol*/
CREATE INDEX INDX_USER_LNAME ON CATISSUE_USER (LAST_NAME);
CREATE INDEX INDX_USER_FNAME ON CATISSUE_USER (FIRST_NAME);
/*CREATE INDEX INDX_SPECIMEN_PROTOCOL_TITLE ON CATISSUE_SPECIMEN_PROTOCOL (TITLE);*/
CREATE INDEX INDX_SP_PR_SHORT_TITLE ON CATISSUE_SPECIMEN_PROTOCOL (SHORT_TITLE);
CREATE INDEX INDX_SP_PR_IRB_ID ON CATISSUE_SPECIMEN_PROTOCOL (IRB_IDENTIFIER);
CREATE INDEX INDX_SP_PR_START_DATE ON CATISSUE_SPECIMEN_PROTOCOL (START_DATE);
CREATE INDEX INDX_SP_PR_END_DATE ON CATISSUE_SPECIMEN_PROTOCOL (END_DATE);

CREATE INDEX INDX_COLL_PROT_REGID ON CATISSUE_COLL_PROT_REG (PROTOCOL_PARTICIPANT_ID);
CREATE INDEX INDX_COLL_PROT_REG_DATE ON CATISSUE_COLL_PROT_REG (REGISTRATION_DATE);


/* Indexes for Specimen Collection Group*/
/*CREATE INDEX INDX_SP_COL_GR_NAME ON CATISSUE_SPECIMEN_COLL_GROUP (NAME);*/
CREATE INDEX INDX_SP_COL_GR_DIGNOSIS ON CATISSUE_SPECIMEN_COLL_GROUP (CLINICAL_DIAGNOSIS);
CREATE INDEX INDX_SP_COL_GR_CLIN_STATUS ON CATISSUE_SPECIMEN_COLL_GROUP (CLINICAL_STATUS);
CREATE INDEX INDX_CLIN_REPO_PATH_NO ON CATISSUE_CLINICAL_REPORT (SURGICAL_PATHOLOGICAL_NUMBER);
/*CREATE INDEX INDX_SITE_NAME ON CATISSUE_SITE (NAME);*/
CREATE INDEX INDX_COLPROTO_EVNT_CAL ON CATISSUE_COLL_PROT_EVENT (STUDY_CALENDAR_EVENT_POINT);

/* Indexes for Specimen*/
CREATE INDEX INDX_CATISSUE_SPECIMEN_CLASS ON CATISSUE_SPECIMEN (SPECIMEN_CLASS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_TYPE ON CATISSUE_SPECIMEN (TYPE);
CREATE INDEX INDX_CATISSUE_SPECIMEN_PATH ON CATISSUE_SPECIMEN (PATHOLOGICAL_STATUS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_CONC ON CATISSUE_SPECIMEN (CONCENTRATION);
CREATE INDEX INDX_CATISSUE_SPECIMEN_AVQTY ON CATISSUE_SPECIMEN (AVAILABLE_QUANTITY);
CREATE INDEX INDX_CATISSUE_SPECIMEN_QTY ON CATISSUE_SPECIMEN (QUANTITY);

/*CREATE INDEX INDX_CATISSUE_BIOHAZARD_NAME ON CATISSUE_BIOHAZARD (NAME);*/
CREATE INDEX INDX_CATISSUE_BIOHAZARD_TYPE ON CATISSUE_BIOHAZARD (TYPE);

CREATE INDEX INDX_CATISSUE_SP_CHAR_TSITE ON CATISSUE_SPECIMEN_CHAR (TISSUE_SITE);
CREATE INDEX INDX_CATISSUE_SP_CHAR_TSIDE ON CATISSUE_SPECIMEN_CHAR (TISSUE_SIDE);
