update CATISSUE_SEARCH_DISPLAY_DATA set DISPLAY_NAME='Post Code' where RELATIONSHIP_ID=7 and COL_ID=6;
update CATISSUE_SEARCH_DISPLAY_DATA set DISPLAY_NAME='Post Code' where RELATIONSHIP_ID=23 and COL_ID=6;

update CATISSUE_SEARCH_DISPLAY_DATA set DISPLAY_NAME='Ethics Number' where RELATIONSHIP_ID=13 and COL_ID=226;
update CATISSUE_SEARCH_DISPLAY_DATA set DISPLAY_NAME='Ethics Number' where RELATIONSHIP_ID=18 and COL_ID=226;


delete from CATISSUE_SEARCH_DISPLAY_DATA where RELATIONSHIP_ID=27 and COL_ID=122;
delete from CATISSUE_SEARCH_DISPLAY_DATA where RELATIONSHIP_ID=27 and COL_ID=124;
delete from CATISSUE_SEARCH_DISPLAY_DATA where RELATIONSHIP_ID=27 and COL_ID=125;

