---- Ordering system  related alter table script Vaishali

--ALTER TABLE CATISSUE_EXISTING_SP_ORD_ITEM DROP FOREIGN KEY FKF8B855EEBC7298A9;
--ALTER TABLE CATISSUE_EXISTING_SP_ORD_ITEM DROP FOREIGN KEY FKF8B855EE60773DB2;
--ALTER TABLE CATISSUE_PATH_CASE_ORDER_ITEM DROP FOREIGN KEY FKBD5029D5F69249F7;
--ALTER TABLE CATISSUE_PATH_CASE_ORDER_ITEM DROP FOREIGN KEY FKBD5029D5BC7298A9;
--ALTER TABLE CATISSUE_ORDER_ITEM DROP FOREIGN KEY FKB501E88060975C0B;
--ALTER TABLE CATISSUE_ORDER_ITEM DROP FOREIGN KEY FKB501E880783867CC;
--ALTER TABLE CATISSUE_DERIEVED_SP_ORD_ITEM DROP FOREIGN KEY FK3742152BBC7298A9;
--ALTER TABLE CATISSUE_DERIEVED_SP_ORD_ITEM DROP FOREIGN KEY FK3742152B60773DB2;
--ALTER TABLE CATISSUE_ORDER DROP FOREIGN KEY FK543F22B26B1F36E7;
--ALTER TABLE CATISSUE_DISTRIBUTION DROP FOREIGN KEY FK54276680783867CC;
--ALTER TABLE CATISSUE_DISTRIBUTED_ITEM DROP FOREIGN KEY FKA7C3ED4BC4A3C438;
--ALTER TABLE CATISSUE_SP_ARRAY_ORDER_ITEM DROP FOREIGN KEY FKE3823170BC7298A9;
--ALTER TABLE CATISSUE_SP_ARRAY_ORDER_ITEM DROP FOREIGN KEY FKE3823170C4A3C438;
--ALTER TABLE CATISSUE_SPECIMEN_ORDER_ITEM DROP FOREIGN KEY FK48C3B39FBC7298A9;
--ALTER TABLE CATISSUE_SPECIMEN_ORDER_ITEM DROP FOREIGN KEY FK48C3B39F83505A30;
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM DROP FOREIGN KEY FKC5C92CCBCE5FBC3A;
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM DROP FOREIGN KEY FKC5C92CCBBC7298A9;
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM DROP FOREIGN KEY FKC5C92CCBC4A3C438;



--------- ordering system relate tables----


 
DROP TABLE IF EXISTS CATISSUE_EXISTING_SP_ORD_ITEM;
DROP TABLE IF EXISTS CATISSUE_PATH_CASE_ORDER_ITEM;
DROP TABLE IF EXISTS CATISSUE_ORDER_ITEM;
DROP TABLE IF EXISTS CATISSUE_DERIEVED_SP_ORD_ITEM;
DROP TABLE IF EXISTS CATISSUE_ORDER;
DROP TABLE IF EXISTS CATISSUE_SP_ARRAY_ORDER_ITEM;
DROP TABLE IF EXISTS CATISSUE_SPECIMEN_ORDER_ITEM;
DROP TABLE IF EXISTS CATISSUE_NEW_SP_AR_ORDER_ITEM;

CREATE TABLE CATISSUE_EXISTING_SP_ORD_ITEM (
   IDENTIFIER BIGINT NOT NULL,
   SPECIMEN_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_PATH_CASE_ORDER_ITEM (
   IDENTIFIER BIGINT NOT NULL,
   PATHOLOGICAL_STATUS VARCHAR(255),
   TISSUE_SITE VARCHAR(255),
   SPECIMEN_CLASS VARCHAR(255),
   SPECIMEN_TYPE VARCHAR(255),
   SPECIMEN_COLL_GROUP_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_ORDER_ITEM (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   DESCRIPTION TEXT,
   DISTRIBUTED_ITEM_ID BIGINT,
   STATUS VARCHAR(50),
   REQUESTED_QUANTITY DOUBLE PRECISION,
   ORDER_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_DERIEVED_SP_ORD_ITEM (
   IDENTIFIER BIGINT NOT NULL,
   SPECIMEN_CLASS VARCHAR(255),
   SPECIMEN_TYPE VARCHAR(255),
   SPECIMEN_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_ORDER (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   COMMENTS TEXT,
   DISTRIBUTION_PROTOCOL_ID BIGINT,
   NAME TEXT,
   REQUESTED_DATE DATETIME,
   STATUS VARCHAR(50),
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_SPECIMEN_ORDER_ITEM (
   IDENTIFIER BIGINT NOT NULL,
   ARRAY_ORDER_ITEM_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

--------------Array order item tables.
CREATE TABLE CATISSUE_SP_ARRAY_ORDER_ITEM (
   IDENTIFIER BIGINT NOT NULL,
   SPECIMEN_ARRAY_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM (
   IDENTIFIER BIGINT NOT NULL,
   ARRAY_TYPE_ID BIGINT,
   NAME VARCHAR(255),
   SPECIMEN_ARRAY_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);


-- extra for catissue_distribution */
 ALTER TABLE CATISSUE_DISTRIBUTION ADD COLUMN `ORDER_ID` BIGINT   NULL;
 ALTER TABLE CATISSUE_DISTRIBUTED_ITEM ADD COLUMN `SPECIMEN_ARRAY_ID` BIGINT   NULL;  
-- extra finished */
 
ALTER TABLE CATISSUE_EXISTING_SP_ORD_ITEM ADD INDEX FKF8B855EEBC7298A9 (IDENTIFIER), ADD CONSTRAINT FKF8B855EEBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_EXISTING_SP_ORD_ITEM ADD INDEX FKF8B855EE60773DB2 (SPECIMEN_ID), ADD CONSTRAINT FKF8B855EE60773DB2 FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN (IDENTIFIER);
ALTER TABLE CATISSUE_PATH_CASE_ORDER_ITEM ADD INDEX FKBD5029D5F69249F7 (SPECIMEN_COLL_GROUP_ID), ADD CONSTRAINT FKBD5029D5F69249F7 FOREIGN KEY (SPECIMEN_COLL_GROUP_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_PATH_CASE_ORDER_ITEM ADD INDEX FKBD5029D5BC7298A9 (IDENTIFIER), ADD CONSTRAINT FKBD5029D5BC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_ORDER_ITEM ADD INDEX FKB501E88060975C0B (DISTRIBUTED_ITEM_ID), ADD CONSTRAINT FKB501E88060975C0B FOREIGN KEY (DISTRIBUTED_ITEM_ID) REFERENCES CATISSUE_DISTRIBUTED_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_ORDER_ITEM ADD INDEX FKB501E880783867CC (ORDER_ID), ADD CONSTRAINT FKB501E880783867CC FOREIGN KEY (ORDER_ID) REFERENCES CATISSUE_ORDER (IDENTIFIER);
ALTER TABLE CATISSUE_DISTRIBUTION ADD INDEX FK54276680783867CC (ORDER_ID), ADD CONSTRAINT FK54276680783867CC FOREIGN KEY (ORDER_ID) REFERENCES CATISSUE_ORDER (IDENTIFIER);
ALTER TABLE CATISSUE_DISTRIBUTED_ITEM ADD INDEX FKA7C3ED4BC4A3C438 (SPECIMEN_ARRAY_ID), ADD CONSTRAINT FKA7C3ED4BC4A3C438 FOREIGN KEY (SPECIMEN_ARRAY_ID) REFERENCES CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);
ALTER TABLE CATISSUE_DERIEVED_SP_ORD_ITEM ADD INDEX FK3742152BBC7298A9 (IDENTIFIER), ADD CONSTRAINT FK3742152BBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_DERIEVED_SP_ORD_ITEM ADD INDEX FK3742152B60773DB2 (SPECIMEN_ID), ADD CONSTRAINT FK3742152B60773DB2 FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN (IDENTIFIER);
ALTER TABLE CATISSUE_ORDER ADD INDEX FK543F22B26B1F36E7 (DISTRIBUTION_PROTOCOL_ID), ADD CONSTRAINT FK543F22B26B1F36E7 FOREIGN KEY (DISTRIBUTION_PROTOCOL_ID) REFERENCES CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
ALTER TABLE CATISSUE_SP_ARRAY_ORDER_ITEM ADD INDEX FKE3823170BC7298A9 (IDENTIFIER), ADD CONSTRAINT FKE3823170BC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_SP_ARRAY_ORDER_ITEM ADD INDEX FKE3823170C4A3C438 (SPECIMEN_ARRAY_ID), ADD CONSTRAINT FKE3823170C4A3C438 FOREIGN KEY (SPECIMEN_ARRAY_ID) REFERENCES CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);
ALTER TABLE CATISSUE_SPECIMEN_ORDER_ITEM ADD INDEX FK48C3B39FBC7298A9 (IDENTIFIER), ADD CONSTRAINT FK48C3B39FBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_SPECIMEN_ORDER_ITEM ADD INDEX FK48C3B39F83505A30 (ARRAY_ORDER_ITEM_ID), ADD CONSTRAINT FK48C3B39F83505A30 FOREIGN KEY (ARRAY_ORDER_ITEM_ID) REFERENCES CATISSUE_NEW_SP_AR_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD INDEX FKC5C92CCBCE5FBC3A (ARRAY_TYPE_ID), ADD CONSTRAINT FKC5C92CCBCE5FBC3A FOREIGN KEY (ARRAY_TYPE_ID) REFERENCES CATISSUE_SPECIMEN_ARRAY_TYPE (IDENTIFIER);
ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD INDEX FKC5C92CCBBC7298A9 (IDENTIFIER), ADD CONSTRAINT FKC5C92CCBBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ORDER_ITEM (IDENTIFIER);
ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD INDEX FKC5C92CCBC4A3C438 (SPECIMEN_ARRAY_ID), ADD CONSTRAINT FKC5C92CCBC4A3C438 FOREIGN KEY (SPECIMEN_ARRAY_ID) REFERENCES CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);


-- csm_catissuecore.sql */
-------Ordering System------*/
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Order','Order Object','edu.wustl.catissuecore.domain.OrderDetails',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'OrderItem','OrderItem Object','edu.wustl.catissuecore.domain.OrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Derived Specimen Order Item','Derived Specimen Order Item Object','edu.wustl.catissuecore.domain.DerivedSpecimenOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Existing Specimen Array Order Item','Existing Specimen Array Order Item Object','edu.wustl.catissuecore.domain.ExistingSpecimenArrayOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Existing Specimen Order Item','Existing Specimen Order Item Object','edu.wustl.catissuecore.domain.ExistingSpecimenOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'New Specimen Array Order Item','New Specimen Array Order Item Object','edu.wustl.catissuecore.domain.NewSpecimenArrayOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'New Specimen Order Item','New Specimen Order Item Object','edu.wustl.catissuecore.domain.NewSpecimenOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Pathological Case Order Item','Pathological Case Order Item Object','edu.wustl.catissuecore.domain.PathologicalCaseOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Specimen Array Order Item','Specimen Array Order Item Object','edu.wustl.catissuecore.domain.SpecimenArrayOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Specimen Order Item','Specimen Order Item Object','edu.wustl.catissuecore.domain.SpecimenOrderItem',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;



-------------Ordering System Permissions----Ashish 4/1/06
INSERT INTO CSM_ROLE(ROLE_NAME,ROLE_DESCRIPTION,APPLICATION_ID) VALUES ('CREATE_ONLY','Create only role',1);
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(B.ROLE_PRIVILEGE_ID)+1,MAX(A.ROLE_ID),1,'2007-01-04' FROM CSM_ROLE_PRIVILEGE B,CSM_ROLE A;

INSERT INTO CSM_PROTECTION_GROUP(PROTECTION_GROUP_NAME,APPLICATION_ID) VALUES ('SCIENTIST_PROTECTION_GROUP',1);

INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Order'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='OrderItem'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,MAX(PG.PROTECTION_GROUP_ID),(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),'2007-01-04' FROM CSM_PG_PE,CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_USER_GROUP_ROLE_PG SELECT MAX(USER_GROUP_ROLE_PG_ID)+1,NULL,4,12,MAX(PG.PROTECTION_GROUP_ID),NULL FROM CSM_PROTECTION_GROUP PG,CSM_USER_GROUP_ROLE_PG;

INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'edu.wustl.catissuecore.action.RequestListAction','edu.wustl.catissuecore.action.RequestListAction','edu.wustl.catissuecore.action.RequestListAction',NULL,NULL,1,'2007-01-04' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.RequestListAction'),'2007-01-04' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.RequestListAction'),'2007-01-04' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.RequestListAction'),'2007-01-04' FROM CSM_PG_PE;

INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Order'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Order'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Order'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='OrderItem'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='OrderItem'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='OrderItem'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),'2006-11-27' FROM CSM_PG_PE;


-- cde_dummydata_common.sql */


--******Ordering System******/
INSERT INTO CATISSUE_CDE VALUES ( '4284','Request Status','Statuses for the ordered requests',1.0,NULL);
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5000,'All',NULL,'4284');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5001,'New',NULL,'4284');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5002,'Pending',NULL,'4284');

INSERT INTO CATISSUE_CDE VALUES ( '4285','Requested Items Status','Statuses for the individual elements in the ordered request',1.0,NULL);
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5005,'New',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5006,'Pending - Protocol Review',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5007,'Pending - For Distribution',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5012,'Distributed',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5008,'Pending - Specimen Preparation',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5009,'Rejected - Inappropriate Request',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5010,'Rejected - Specimen Unavailable',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5011,'Rejected - Unable to Create',NULL,'4285');


-- initDB_inser_Common.sql */
--Ordering System*/
INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID) VALUES ( 76, 'CATISSUE_ORDER', 'Order', 'OrderDetails', 2);



-- extra for catissue_distribution */
 --alter table catissue_distribution add column `ORDER_ID` bigint   NULL;
 --alter table catissue_distributed_item add column `SPECIMEN_ARRAY_ID` bigint   NULL;  
-- extra finished */
-------ordering changes finish

----------Consent Tracking-------*/
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Consent Tier','ConsentTier Object','edu.wustl.catissuecore.domain.ConsentTier',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Consent Tier Response','Consent Tier Response Object','edu.wustl.catissuecore.domain.ConsentTierResponse',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Consent Tier Status','Consent Tier Status Object','edu.wustl.catissuecore.domain.ConsentTierStatus',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status'),'2006-11-27' FROM CSM_PG_PE;

DROP TABLE IF EXISTS CATISSUE_CONSENT_TIER_RESPONSE;
DROP TABLE IF EXISTS CATISSUE_CONSENT_TIER_STATUS;
DROP TABLE IF EXISTS CATISSUE_CONSENT_TIER;

CREATE TABLE CATISSUE_CONSENT_TIER_RESPONSE(
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   RESPONSE VARCHAR(20),
   CONSENT_TIER_ID BIGINT,
   COLL_PROT_REG_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_CONSENT_TIER_STATUS (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   CONSENT_TIER_ID BIGINT,
   STATUS VARCHAR(255),
   SPECIMEN_ID BIGINT,
   SPECIMEN_COLL_GROUP_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_CONSENT_TIER (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   STATEMENT TEXT,
   COLL_PROTOCOL_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE CATISSUE_CONSENT_TIER_RESPONSE ADD INDEX FKFB1995FD4AD77FCB (COLL_PROT_REG_ID), ADD CONSTRAINT FKFB1995FD4AD77FCB FOREIGN KEY (COLL_PROT_REG_ID) REFERENCES CATISSUE_COLL_PROT_REG (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_RESPONSE ADD INDEX FKFB1995FD17B9953 (CONSENT_TIER_ID), ADD CONSTRAINT FKFB1995FD17B9953 FOREIGN KEY (CONSENT_TIER_ID) REFERENCES CATISSUE_CONSENT_TIER (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS ADD INDEX FKF74E94AEF69249F7 (SPECIMEN_COLL_GROUP_ID), ADD CONSTRAINT FKF74E94AEF69249F7 FOREIGN KEY (SPECIMEN_COLL_GROUP_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS ADD INDEX FKF74E94AE60773DB2 (SPECIMEN_ID), ADD CONSTRAINT FKF74E94AE60773DB2 FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS ADD INDEX FKF74E94AE17B9953 (CONSENT_TIER_ID), ADD CONSTRAINT FKF74E94AE17B9953 FOREIGN KEY (CONSENT_TIER_ID) REFERENCES CATISSUE_CONSENT_TIER (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER ADD INDEX FK51725303E36A4B4F (COLL_PROTOCOL_ID), ADD CONSTRAINT FK51725303E36A4B4F FOREIGN KEY (COLL_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

------caTissue tables changed for consent tracking----- */
ALTER TABLE CATISSUE_COLL_PROT_REG DROP FOREIGN KEY FK5EB25F13A0FF79D4;
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL ADD COLUMN UNSIGNED_CONSENT_DOC_URL TEXT;
ALTER TABLE CATISSUE_COLL_PROT_REG ADD COLUMN (CONSENT_SIGN_DATE DATETIME,CONSENT_DOC_URL TEXT,CONSENT_WITNESS BIGINT);
ALTER TABLE CATISSUE_COLL_PROT_REG ADD INDEX FK5EB25F13A0FF79D4 (CONSENT_WITNESS), ADD CONSTRAINT FK5EB25F13A0FF79D4 FOREIGN KEY (CONSENT_WITNESS) REFERENCES CATISSUE_USER (IDENTIFIER);

----bug 3003-----Ashish ---7/12/06-----*/
ALTER TABLE CATISSUE_ORDER_ITEM MODIFY DESCRIPTION TEXT;

------Added association ---Ashish 7/12/06 -----*/
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM DROP FOREIGN KEY FKC5C92CCBC4A3C438;
-- ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD COLUMN SPECIMEN_ARRAY_ID BIGINT;
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD INDEX FKC5C92CCBC4A3C438 (SPECIMEN_ARRAY_ID), ADD CONSTRAINT FKC5C92CCBC4A3C438 FOREIGN KEY (SPECIMEN_ARRAY_ID) REFERENCES CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);


---------------New Table entry For ConsentWithdrawal ---------- Mandar : 18-Jan-07 -------------start
INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI) VALUES ( 79, 'CATISSUE_RETURN_EVENT_PARAM', 'Return Event Parameters', 'ReturnEventParameters',2,2);
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA (  TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES (  79, 'IDENTIFIER', 'bigint');

CREATE TABLE CATISSUE_RETURN_EVENT_PARAM 
(
   IDENTIFIER BIGINT NOT NULL,
   PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE CATISSUE_RETURN_EVENT_PARAM ADD INDEX FKD8890A48BC7298A91 (IDENTIFIER), ADD CONSTRAINT FKD8890A48BC7298A91 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN_EVENT_PARAM (IDENTIFIER);

INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'ReturnEventParameters','ReturnEventParameters Class','edu.wustl.catissuecore.domain.ReturnEventParameters',NULL,NULL,1,'2007-01-17' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='ReturnEventParameters'),'2006-11-27' FROM CSM_PG_PE;
-------------------------New Table entry For ConsentWithdrawal ---------- Mandar : 18-Jan-07 -------------end


-------------------------New Column Entry For ConsentWaived ---------- Mandar : 25-Jan-07 -------------start
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL ADD COLUMN CONSENTS_WAIVED BIT;
UPDATE CATISSUE_COLLECTION_PROTOCOL SET  CONSENTS_WAIVED='0' WHERE  CONSENTS_WAIVED IS NULL;
-------------------------New Column Entry For ConsentWaived ---------- Mandar : 25-Jan-07 -------------end

-------------------------New Column Entry For Participant ---------- Sachin : 13-Mar-07 -------------start
ALTER TABLE CATISSUE_PARTICIPANT ADD COLUMN MARITAL_STATUS VARCHAR(50);
-------------------------New Column Entry For Participant ---------- Sachin : 13-Mar-07 -------------end

--***caTIES Realated Tables - start**********/

--ALTER TABLE CATISSUE_REPORT_TEXTCONTENT DROP FOREIGN KEY FKD74882FD91092806;
--ALTER TABLE CATISSUE_REPORT_TEXTCONTENT DROP FOREIGN KEY FKD74882FDBC7298A9;
--ALTER TABLE CATISSUE_IDENTIFIED_REPORT DROP FOREIGN KEY FK6A2246DCBC7298A9;
--ALTER TABLE CATISSUE_IDENTIFIED_REPORT DROP FOREIGN KEY FK6A2246DC752DD177;
--ALTER TABLE CATISSUE_IDENTIFIED_REPORT DROP FOREIGN KEY FK6A2246DC91741663;
--ALTER TABLE CATISSUE_CONCEPT_REFERENT DROP FOREIGN KEY FK799CCA7E9F96B363;
--ALTER TABLE CATISSUE_REVIEW_PARAMS DROP FOREIGN KEY FK5311FFF62206F20F;
--ALTER TABLE CATISSUE_REVIEW_PARAMS DROP FOREIGN KEY FK5311FFF691092806;
--ALTER TABLE CATISSUE_REPORT_BICONTENT DROP FOREIGN KEY FK8A9A4EE391092806;
--ALTER TABLE CATISSUE_REPORT_BICONTENT DROP FOREIGN KEY FK8A9A4EE3BC7298A9;
--ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT DROP FOREIGN KEY FKCDD0DF7BBC7298A9;
--ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT DROP FOREIGN KEY FKCDD0DF7B91741663;
--ALTER TABLE CATISSUE_QUARANTINE_PARAMS DROP FOREIGN KEY FK3C12AE3B2206F20F;
--ALTER TABLE CATISSUE_QUARANTINE_PARAMS DROP FOREIGN KEY FK3C12AE3B3EEC14E3;
--ALTER TABLE CATISSUE_PATHOLOGY_REPORT DROP FOREIGN KEY FK904EC9F040DCD7BF;
--ALTER TABLE CATISSUE_REPORT_XMLCONTENT DROP FOREIGN KEY FK4597C9F1BC7298A9;
--ALTER TABLE CATISSUE_REPORT_XMLCONTENT DROP FOREIGN KEY FK4597C9F191092806;
--ALTER TABLE CATISSUE_REPORT_QUEUE DROP FOREIGN KEY FK214246228CA560D1;
--ALTER TABLE CATISSUE_CONCEPT_REFERENT DROP FOREIGN KEY FK799CCA7EA9816272;
--ALTER TABLE CATISSUE_CONCEPT_REFERENT DROP FOREIGN KEY FK799CCA7E72C371DD;
--ALTER TABLE CATISSUE_CONCEPT DROP FOREIGN KEY FKC1A3C8CC7F0C2C7;

DROP TABLE IF EXISTS CATISSUE_REPORT_TEXTCONTENT;
DROP TABLE IF EXISTS CATISSUE_IDENTIFIED_REPORT;
DROP TABLE IF EXISTS CATISSUE_CONCEPT_REFERENT;
DROP TABLE IF EXISTS CATISSUE_REPORT_CONTENT;
DROP TABLE IF EXISTS CATISSUE_REVIEW_PARAMS;
DROP TABLE IF EXISTS CATISSUE_REPORT_BICONTENT;
DROP TABLE IF EXISTS CATISSUE_REPORT_SECTION;
DROP TABLE IF EXISTS CATISSUE_DEIDENTIFIED_REPORT;
DROP TABLE IF EXISTS CATISSUE_PATHOLOGY_REPORT;
DROP TABLE IF EXISTS CATISSUE_REPORT_XMLCONTENT;
DROP TABLE IF EXISTS CATISSUE_REPORT_QUEUE;
DROP TABLE IF EXISTS CATISSUE_REPORT_PARTICIP_REL;
DROP TABLE IF EXISTS CATISSUE_CONCEPT;
DROP TABLE IF EXISTS CATISSUE_SEMANTIC_TYPE;
DROP TABLE IF EXISTS CATISSUE_CONCEPT_CLASSIFICATN;


CREATE TABLE CATISSUE_REPORT_TEXTCONTENT (
   IDENTIFIER BIGINT NOT NULL,
   REPORT_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_IDENTIFIED_REPORT (
   IDENTIFIER BIGINT NOT NULL,
   DEID_REPORT BIGINT,
   SCG_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_CONCEPT_REFERENT (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   CONCEPT_ID BIGINT,
   CONCEPT_CLASSIFICATION_ID BIGINT,
   DEIDENTIFIED_REPORT_ID BIGINT,
   END_OFFSET BIGINT,
   IS_MODIFIER BIT,
   IS_NEGATED BIT,
   START_OFFSET BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_CONTENT (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   REPORT_DATA TEXT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_REVIEW_PARAMS (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   REVIEWER_ROLE VARCHAR(100),
   REPORT_ID BIGINT,
   EVENT_TIMESTAMP DATETIME,
   USER_ID BIGINT,
   COMMENTS TEXT,
   STATUS VARCHAR(100),
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_BICONTENT (
   IDENTIFIER BIGINT NOT NULL,
   REPORT_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_SECTION (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   DOCUMENT_FRAGMENT TEXT,
   END_OFFSET INTEGER,
   NAME VARCHAR(100),
   START_OFFSET INTEGER,
   TEXT_CONTENT_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_DEIDENTIFIED_REPORT (
   IDENTIFIER BIGINT NOT NULL,
   STATUS VARCHAR(100),
   SCG_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_QUARANTINE_PARAMS (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   DEID_REPORT_ID BIGINT,
   IS_QUARANTINED BIT,
   EVENT_TIMESTAMP DATETIME,
   USER_ID BIGINT,
   COMMENTS TEXT,
   STATUS VARCHAR(100),
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_PATHOLOGY_REPORT (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   ACTIVITY_STATUS VARCHAR(100),
   REVIEW_FLAG BIT,
   SOURCE_ID BIGINT,
   REPORT_STATUS VARCHAR(100),
   COLLECTION_DATE_TIME DATE,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_REPORT_XMLCONTENT (
   IDENTIFIER BIGINT NOT NULL,
   REPORT_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_QUEUE (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   STATUS VARCHAR(50),
   SURGICAL_PATHOLOGY_NUMBER VARCHAR(50),
   PARTICIPANT_NAME VARCHAR(255),
   SITE_NAME VARCHAR(255),
   REPORT_LOADED_DATE DATE,
   REPORT_TEXT TEXT,
   SPECIMEN_COLL_GRP_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_REPORT_PARTICIP_REL(
   PARTICIPANT_ID BIGINT,
   REPORT_ID BIGINT
);
CREATE TABLE CATISSUE_CONCEPT (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   CONCEPT_UNIQUE_ID VARCHAR(30),
   NAME TEXT,
   SEMANTIC_TYPE_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_SEMANTIC_TYPE (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   LABEL TEXT,
   PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE CATISSUE_CONCEPT_CLASSIFICATN (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   NAME TEXT,
   PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE CATISSUE_REPORT_TEXTCONTENT ADD INDEX FKD74882FD91092806 (REPORT_ID), ADD CONSTRAINT FKD74882FD91092806 FOREIGN KEY (REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_TEXTCONTENT ADD INDEX FKD74882FDBC7298A9 (IDENTIFIER), ADD CONSTRAINT FKD74882FDBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_REPORT_CONTENT (IDENTIFIER);
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD INDEX FK6A2246DCBC7298A9 (IDENTIFIER), ADD CONSTRAINT FK6A2246DCBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD INDEX FK6A2246DC752DD177 (DEID_REPORT), ADD CONSTRAINT FK6A2246DC752DD177 FOREIGN KEY (DEID_REPORT) REFERENCES CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD INDEX FK6A2246DC91741663 (SCG_ID), ADD CONSTRAINT FK6A2246DC91741663 FOREIGN KEY (SCG_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD INDEX FK799CCA7E9F96B363 (DEIDENTIFIED_REPORT_ID), ADD CONSTRAINT FK799CCA7E9F96B363 FOREIGN KEY (DEIDENTIFIED_REPORT_ID) REFERENCES CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REVIEW_PARAMS ADD INDEX FK5311FFF62206F20F (USER_ID), ADD CONSTRAINT FK5311FFF62206F20F FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_REVIEW_PARAMS ADD INDEX FK5311FFF691092806 (REPORT_ID), ADD CONSTRAINT FK5311FFF691092806 FOREIGN KEY (REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_BICONTENT ADD INDEX FK8A9A4EE391092806 (REPORT_ID), ADD CONSTRAINT FK8A9A4EE391092806 FOREIGN KEY (REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_BICONTENT ADD INDEX FK8A9A4EE3BC7298A9 (IDENTIFIER), ADD CONSTRAINT FK8A9A4EE3BC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_REPORT_CONTENT (IDENTIFIER);
ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT ADD INDEX FKCDD0DF7BBC7298A9 (IDENTIFIER), ADD CONSTRAINT FKCDD0DF7BBC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT ADD INDEX FKCDD0DF7B91741663 (SCG_ID), ADD CONSTRAINT FKCDD0DF7B91741663 FOREIGN KEY (SCG_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_QUARANTINE_PARAMS ADD INDEX FK3C12AE3B2206F20F (USER_ID), ADD CONSTRAINT FK3C12AE3B2206F20F FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_QUARANTINE_PARAMS ADD INDEX FK3C12AE3B3EEC14E3 (DEID_REPORT_ID), ADD CONSTRAINT FK3C12AE3B3EEC14E3 FOREIGN KEY (DEID_REPORT_ID) REFERENCES CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_PATHOLOGY_REPORT ADD INDEX FK904EC9F040DCD7BF (SOURCE_ID), ADD CONSTRAINT FK904EC9F040DCD7BF FOREIGN KEY (SOURCE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_XMLCONTENT ADD INDEX FK4597C9F1BC7298A9 (IDENTIFIER), ADD CONSTRAINT FK4597C9F1BC7298A9 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_REPORT_CONTENT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_XMLCONTENT ADD INDEX FK4597C9F191092806 (REPORT_ID), ADD CONSTRAINT FK4597C9F191092806 FOREIGN KEY (REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_QUEUE ADD INDEX FK214246228CA560D1 (SPECIMEN_COLL_GRP_ID), ADD CONSTRAINT FK214246228CA560D1 FOREIGN KEY (SPECIMEN_COLL_GRP_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT ADD INDEX FKC1A3C8CC7F0C2C7 (SEMANTIC_TYPE_ID), ADD CONSTRAINT FKC1A3C8CC7F0C2C7 FOREIGN KEY (SEMANTIC_TYPE_ID) REFERENCES CATISSUE_SEMANTIC_TYPE (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD INDEX FK799CCA7EA9816272 (CONCEPT_ID), ADD CONSTRAINT FK799CCA7EA9816272 FOREIGN KEY (CONCEPT_ID) REFERENCES CATISSUE_CONCEPT (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD INDEX FK799CCA7E72C371DD (CONCEPT_CLASSIFICATION_ID), ADD CONSTRAINT FK799CCA7E72C371DD FOREIGN KEY (CONCEPT_CLASSIFICATION_ID) REFERENCES CATISSUE_CONCEPT_CLASSIFICATN (IDENTIFIER);

INSERT INTO CSM_PROTECTION_ELEMENT SELECT MAX(PROTECTION_ELEMENT_ID)+1,'IdentifiedSurgicalPathologyReport','IdentifiedSurgicalPathologyReport Object','edu.wustl.catissuecore.domain.pathology.IdentifiedSurgicalPathologyReport',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT MAX(PROTECTION_ELEMENT_ID)+1,'DeidentifiedSurgicalPathologyReport','DeidentifiedSurgicalPathologyReport Object','edu.wustl.catissuecore.domain.pathology.DeidentifiedSurgicalPathologyReport',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT MAX(PROTECTION_ELEMENT_ID)+1,'ReportLoaderQueue','ReportLoaderQueue Object','edu.wustl.catissuecore.domain.pathology.ReportLoaderQueue',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Review Comments','PathologyReportReviewParameter Object','edu.wustl.catissuecore.domain.pathology.PathologyReportReviewParameter',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Quarantine Comments','QuarantineEventParameter Object','edu.wustl.catissuecore.domain.pathology.QuarantineEventParameter',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,20,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='IdentifiedSurgicalPathologyReport'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,20,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='DeidentifiedSurgicalPathologyReport'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,20,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='ReportLoaderQueue'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,20,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Review Comments'),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,20,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Quarantine Comments'),'2006-11-27' FROM CSM_PG_PE;

DELETE FROM CATISSUE_QUERY_TABLE_DATA WHERE TABLE_ID=26;
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER=44;
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER=45;
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER=46;
DELETE FROM CATISSUE_TABLE_RELATION WHERE RELATIONSHIP_ID=47;
DELETE FROM CATISSUE_RELATED_TABLES_MAP WHERE FIRST_TABLE_ID=26 AND SECOND_TABLE_ID=35;
UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET COLUMN_NAME='SURGICAL_PATHOLOGY_NUMBER' WHERE IDENTIFIER=215;

ALTER TABLE CATISSUE_CLINICAL_REPORT DROP FOREIGN KEY FK54A4264515246F7;
ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP DROP FOREIGN KEY FKDEBAF1674CE21DDA;
DROP TABLE CATISSUE_CLINICAL_REPORT;

ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP DROP COLUMN CLINICAL_REPORT_ID;
ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP ADD COLUMN SURGICAL_PATHOLOGY_NUMBER VARCHAR(50);

--caTIES Realated Tables - end --------
---------Query Wizard start---------------
INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,APPLICATION_ID)VALUES('edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction','edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction','edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction',1);
INSERT INTO CSM_PG_PE (PROTECTION_GROUP_ID,PROTECTION_ELEMENT_ID) VALUES (24,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID='edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction'));

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,APPLICATION_ID)VALUES('edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction','edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction','edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction',1);
INSERT INTO CSM_PG_PE (PROTECTION_GROUP_ID,PROTECTION_ELEMENT_ID) VALUES (24,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID='edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction'));

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,APPLICATION_ID)VALUES('edu.wustl.catissuecore.action.querysuite.PathFinderAction','edu.wustl.catissuecore.action.querysuite.PathFinderAction','edu.wustl.catissuecore.action.querysuite.PathFinderAction',1);
INSERT INTO CSM_PG_PE (PROTECTION_GROUP_ID,PROTECTION_ELEMENT_ID) VALUES (24,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID='edu.wustl.catissuecore.action.querysuite.PathFinderAction'));

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,APPLICATION_ID)VALUES('edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction','edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction','edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction',1);
INSERT INTO CSM_PG_PE (PROTECTION_GROUP_ID,PROTECTION_ELEMENT_ID) VALUES (24,(SELECT MAX(PROTECTION_ELEMENT_ID) FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID='edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction'));
---------Query Wizard End---------------
/* LOCAL EXTENSION  */
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Local Extensions','Local Extensions class','edu.common.dynamicextensions.domain.integration.EntityMap',NULL,NULL,1,'2007-01-17' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` SELECT MAX(PROTECTION_ELEMENT_ID)+1,'edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction','edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction','edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction',NULL,NULL,1,'2007-01-17' FROM CSM_PROTECTION_ELEMENT;
/* LOCAL EXTENSION  */
INSERT INTO `CSM_PG_PE` SELECT MAX(PG_PE_ID)+1,17,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID='edu.common.dynamicextensions.domain.integration.EntityMap'),'0000-00-00' FROM CSM_PG_PE;
INSERT INTO `CSM_PG_PE` SELECT MAX(PG_PE_ID)+1,17,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID='edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction'),'0000-00-00'  FROM CSM_PG_PE;