alter table CATISSUE_SPECIMEN_PROTOCOL add column LABEL_FORMAT varchar(255) default null;

alter table CATISSUE_SPECIMEN_PROTOCOL add column DERIV_LABEL_FORMAT varchar(255) default null;
alter table CATISSUE_SPECIMEN_PROTOCOL add column ALIQUOT_LABEL_FORMAT varchar(255) default null;

CREATE TABLE KEY_SEQ_GENERATOR
   (	IDENTIFIER bigint(20) NOT NULL auto_increment,
	KEY_VALUE VARCHAR(50) NOT NULL,
	KEY_SEQUENCE_ID VARCHAR(50) NOT NULL,
	KEY_TYPE VARCHAR(255) NOT NULL,
	 PRIMARY KEY (IDENTIFIER)
	 );