/*Create table and constraints*/
create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER BIGINT not null auto_increment,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER,
	primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER BIGINT not null auto_increment,
	SPECIMEN_ID BIGINT,
	CONTAINER_ID BIGINT,
	primary key (IDENTIFIER),
	index FK_SPECIMEN_POSITION (IDENTIFIER),
	constraint FK_SPECIMEN_POSITION foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_POSITION (IDENTIFIER),
	index FK_SPECIMEN (SPECIMEN_ID),
	constraint FK_SPECIMEN foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER),
	index FK_STORAGE_CONTAINER (CONTAINER_ID),
	constraint FK_STORAGE_CONTAINER foreign key (CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER BIGINT not null auto_increment,
	PARENT_CONTAINER_ID bigint,
	CONTAINER_ID BIGINT,
	primary key (IDENTIFIER),
	index FK_CONTAINER_POSITION (IDENTIFIER), 
	constraint FK_CONTAINER_POSITION foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_POSITION (IDENTIFIER),
	index FK_CONTAINER (CONTAINER_ID),
	constraint FK_CONTAINER foreign key (CONTAINER_ID) references CATISSUE_CONTAINER (IDENTIFIER),
	index FK_OCCUPIED_CONTAINER (PARENT_CONTAINER_ID),
	constraint FK_OCCUPIED_CONTAINER foreign key (PARENT_CONTAINER_ID) references CATISSUE_CONTAINER (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all SPECIMEN_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD SPECIMEN_ID BIGINT;
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID BIGINT;
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD IS_SPECIMEN BIGINT;

/**Insert data of specimen*/
insert into CATISSUE_ABSTRACT_POSITION(SPECIMEN_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) select identifier,storage_container_identifier,position_dimension_one,position_dimension_two,1 from catissue_specimen where is_coll_prot_req=0 and activity_status in ('Active','Closed') and storage_container_identifier is not null and POSITION_DIMENSION_ONE is not null and POSITION_DIMENSION_TWO is not null ;
insert into CATISSUE_SPECIMEN_POSITION(IDENTIFIER,SPECIMEN_ID,CONTAINER_ID) select IDENTIFIER,SPECIMEN_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION;


/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP SPECIMEN_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP CONTAINER_ID;


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all CONTAINER_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD PARENT_CONTAINER_ID BIGINT;
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID BIGINT;

/*insert Storage container*/
insert into CATISSUE_ABSTRACT_POSITION(PARENT_CONTAINER_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) select a.parent_container_id,a.identifier,a.position_dimension_one,a.position_dimension_two,0 from catissue_container a join catissue_storage_container b on a.identifier=b.identifier where activity_status in ('Active','Closed') and POSITION_DIMENSION_ONE is not null and POSITION_DIMENSION_TWO is not null and PARENT_CONTAINER_ID is not null;
insert into CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) select IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION where IS_SPECIMEN=0;


/*insert Specimen array*/
insert into CATISSUE_ABSTRACT_POSITION(CONTAINER_ID,PARENT_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) select a.identifier,b.storage_container_id,position_dimension_one,position_dimension_two,2 from catissue_container a, catissue_specimen_array b where a.identifier=b.identifier and a.activity_status in ('Active','Closed')and a.POSITION_DIMENSION_ONE is not null and a.POSITION_DIMENSION_TWO is not null and b.storage_container_id is not null;
insert into CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) select IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION where IS_SPECIMEN=2;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP IS_SPECIMEN;

/*Drop columns from existing table*/
ALTER TABLE CATISSUE_CONTAINER DROP foreign key FK49B8DE5DB097B2E;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP foreign key FKECBF8B3EB3DFB11D;
ALTER TABLE CATISSUE_SPECIMEN DROP foreign key FK1674810432B31EAB;

--Insert CSM scripts
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'AbstractPosition','AbstractPosition Object','edu.wustl.catissuecore.domain.AbstractPosition',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'SpecimenPosition','SpecimenPosition Object','edu.wustl.catissuecore.domain.SpecimenPosition',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'ContainerPosition','ContainerPosition Object','edu.wustl.catissuecore.domain.ContainerPosition',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractPosition'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='SpecimenPosition'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ContainerPosition'),'2008-05-28' from CSM_PG_PE;

/*Distribution Protocol*/
create table CATISSUE_DISTRIBUTION_SPEC_REQ (
   IDENTIFIER bigint not null auto_increment,
   SPECIMEN_CLASS varchar(255) not null,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   QUANTITY double precision,
   DISTRIBUTION_PROTOCOL_ID bigint,
   CONSTRAINT `fk_distribution_protocol` FOREIGN KEY (`DISTRIBUTION_PROTOCOL_ID`) REFERENCES `CATISSUE_DISTRIBUTION_PROTOCOL` (`IDENTIFIER`),
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO CATISSUE_DISTRIBUTION_SPEC_REQ (SPECIMEN_CLASS,SPECIMEN_TYPE,TISSUE_SITE,PATHOLOGY_STATUS,QUANTITY,DISTRIBUTION_PROTOCOL_ID) select sp.IDENTIFIER, 
sp.SPECIMEN_CLASS, sp.SPECIMEN_TYPE, sp.PATHOLOGY_STATUS, q.QUANTITY, dsp.DISTRIBUTION_PROTOCOL_ID from CATISSUE_SPECIMEN_REQUIREMENT sp,
CATISSUE_DISTRIBUTION_SPE_REQ dsp, CATISSUE_QUANTITY q where sp.IDENTIFIER=dsp.SPECIMEN_REQUIREMENT_ID and sp.QUANTITY_ID=q.IDENTIFIER;

ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT ADD INITIAL_QUANTITY double precision;

UPDATE CATISSUE_SPECI_ARRAY_CONTENT sac set INITIAL_QUANTITY=(select QUANTITY from CATISSUE_QUANTITY q where sac.INITIAL_QUANTITY_ID=q.IDENTIFIER);

ALTER TABLE CATISSUE_DISTRIBUTION_SPE_REQ DROP foreign key FKE34A3688BE10F0CE;
ALTER TABLE CATISSUE_DISTRIBUTION_SPE_REQ DROP foreign key FKE34A36886B1F36E7;
ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT DROP foreign key FKBEA9D45892AB74B4;

ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT DROP INITIAL_QUANTITY_ID;
DROP TABLE CATISSUE_DISTRIBUTION_SPE_REQ;

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'DistributionSpecimenRequirement','DistributionSpecimenRequirement Object','edu.wustl.catissuecore.domain.DistributionSpecimenRequirement',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='DistributionSpecimenRequirement'),'2008-05-28' from CSM_PG_PE;

/** Specimen Model Related Change */

CREATE TABLE `CATISSUE_ABSTRACT_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
     `SPECIMEN_CLASS` varchar(50) NOT NULL default '',
     `SPECIMEN_TYPE` varchar(50) default NULL,                                                                                                                
     `LINEAGE` varchar(50) default NULL,                                                                                                              
     `PATHOLOGICAL_STATUS` varchar(50) default NULL,                                                                                                  
     `PARENT_SPECIMEN_ID` bigint(20) default NULL,                                                                                                    
     `SPECIMEN_CHARACTERISTICS_ID` bigint(20) default NULL,                                                                                           
     `INITIAL_QUANTITY` double default NULL,                                                                                                        
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      KEY `FK1674810456906G39` (`SPECIMEN_CHARACTERISTICS_ID`),                                                                                        
      CONSTRAINT `FK1674810456906G39` FOREIGN KEY (`SPECIMEN_CHARACTERISTICS_ID`) REFERENCES `catissue_specimen_char` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_CP_REQ_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,      
     `STORAGE_TYPE` varchar(255) NOT NULL default '',      
	 `COLLECTION_PROTOCOL_EVENT_ID` bigint(20) default NULL,
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      KEY `FK111110456906F39` (`COLLECTION_PROTOCOL_EVENT_ID`),                                                                                        
      CONSTRAINT `FK111110456906F39` FOREIGN KEY (`COLLECTION_PROTOCOL_EVENT_ID`) REFERENCES `catissue_coll_prot_event` (`IDENTIFIER`),
	  CONSTRAINT `FK_PARENT_CP_REQ_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_ABSTRACT_SPECIMEN` (`IDENTIFIER`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_MOL_REQ_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,   
	 `CONCENTRATION` double default NULL,
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_MOL_REQ_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_CP_REQ_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_FLUID_REQ_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_FLUID_REQ_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_CP_REQ_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_CELL_REQ_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_CELL_REQ_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_CP_REQ_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_TISSUE_REQ_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_TISSUE_REQ_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_CP_REQ_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_MOLECULAR_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,  
     `CONCENTRATION` double default NULL,
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_MOLECULAR_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_FLUID_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_FLUID_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_CELL_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_CELL_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CATISSUE_TISSUE_SPECIMEN`
(                                                                                                                 
     `IDENTIFIER` bigint(20) NOT NULL auto_increment,       
      PRIMARY KEY  (`IDENTIFIER`),                                                                                                                     
      CONSTRAINT `FK_TISSUE_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_SPECIMEN` (`IDENTIFIER`)                 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `CATISSUE_ABSTRACT_SPECIMEN`(IDENTIFIER,SPECIMEN_CLASS,SPECIMEN_TYPE,LINEAGE,PATHOLOGICAL_STATUS,PARENT_SPECIMEN_ID,SPECIMEN_CHARACTERISTICS_ID,INITIAL_QUANTITY) SELECT 
IDENTIFIER,SPECIMEN_CLASS,TYPE,LINEAGE,PATHOLOGICAL_STATUS,PARENT_SPECIMEN_ID,SPECIMEN_CHARACTERISTICS_ID,QUANTITY FROM 
CATISSUE_SPECIMEN;

SET FOREIGN_KEY_CHECKS=0;

update CATISSUE_SPECIMEN set POSITION_DIMENSION_ONE = 0 where POSITION_DIMENSION_ONE is null;
INSERT INTO `CATISSUE_CP_REQ_SPECIMEN`(IDENTIFIER,STORAGE_TYPE,COLLECTION_PROTOCOL_EVENT_ID) SELECT 
IDENTIFIER,POSITION_DIMENSION_ONE,SPECIMEN_COLLECTION_GROUP_ID FROM  CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1;

SET FOREIGN_KEY_CHECKS=1;

UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Virtual' where STORAGE_TYPE=0;
UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Auto'  where STORAGE_TYPE=1;
UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Manual' where STORAGE_TYPE=2;

INSERT INTO `CATISSUE_MOL_REQ_SPECIMEN`(IDENTIFIER,CONCENTRATION) SELECT IDENTIFIER,CONCENTRATION FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Molecular' AND IS_COLL_PROT_REQ = 1;
INSERT INTO `CATISSUE_FLUID_REQ_SPECIMEN`(IDENTIFIER) SELECT  IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Fluid' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO `CATISSUE_CELL_REQ_SPECIMEN`(IDENTIFIER) SELECT  IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Cell' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO `CATISSUE_TISSUE_REQ_SPECIMEN`(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Tissue' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO `CATISSUE_MOLECULAR_SPECIMEN`(IDENTIFIER,CONCENTRATION) SELECT IDENTIFIER,CONCENTRATION FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Molecular' AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO `CATISSUE_FLUID_SPECIMEN`(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Fluid'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO `CATISSUE_CELL_SPECIMEN`(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Cell'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO `CATISSUE_TISSUE_SPECIMEN`(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Tissue'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;


SET FOREIGN_KEY_CHECKS=0;
DELETE FROM  CATISSUE_EXTERNAL_IDENTIFIER WHERE SPECIMEN_ID IN(SELECT identifier FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1);

CREATE TABLE temp_specimen (                         
               `ID` bigint(20) NOT NULL 
	            ) ENGINE=InnoDB DEFAULT CHARSET=latin1;             

Insert into temp_specimen (ID)SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1;

UPDATE CATISSUE_SPECIMEN set ACTIVITY_STATUS = 'Disabled' where IDENTIFIER IN
(SELECT SPECIMEN_ID FROM CATISSUE_EXISTING_SP_ORD_ITEM WHERE SPECIMEN_ID IN 
(SELECT ID FROM temp_specimen ));

UPDATE CATISSUE_SPECIMEN set ACTIVITY_STATUS = 'Disabled' where IDENTIFIER IN
(Select SPECIMEN_ID from CATISSUE_DERIEVED_SP_ORD_ITEM  WHERE SPECIMEN_ID IN 
(SELECT ID FROM temp_specimen ));

drop table temp_specimen;

DELETE FROM `CATISSUE_SPECIMEN` WHERE IS_COLL_PROT_REQ = 1 and ACTIVITY_STATUS = 'ACTIVE';

alter table CATISSUE_SPECIMEN_EVENT_PARAM drop index FK753F33AD60773DB2; 
alter table CATISSUE_SPECIMEN_EVENT_PARAM DROP Foreign KEY FK753F33AD60773DB2;
alter table CATISSUE_SPECIMEN_EVENT_PARAM add index FK753F33AD60773DB2 (SPECIMEN_ID); 
alter table CATISSUE_SPECIMEN_EVENT_PARAM add constraint FK753F33AD60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_ABSTRACT_SPECIMEN (IDENTIFIER);

ALTER TABLE `CATISSUE_SPECIMEN` DROP Foreign KEY FK16748104B189E99D;
ALTER TABLE `CATISSUE_SPECIMEN` DROP Foreign KEY FK1674810456906F39;

ALTER TABLE `CATISSUE_SPECIMEN` DROP KEY INDX_CATISSUE_SPECIMEN_CLASS; 
ALTER TABLE `CATISSUE_SPECIMEN` DROP KEY INDX_CATISSUE_SPECIMEN_TYPE ; 
ALTER TABLE `CATISSUE_SPECIMEN` DROP KEY INDX_CATISSUE_SPECIMEN_PATH ; 
ALTER TABLE `CATISSUE_SPECIMEN` DROP KEY INDX_CATISSUE_SPECIMEN_CONC; 
ALTER TABLE `CATISSUE_SPECIMEN` DROP KEY INDX_CATISSUE_SPECIMEN_QTY; 
ALTER TABLE `CATISSUE_SPECIMEN` DROP KEY INDX_CATISSUE_SPECIMEN_AVQTY;


ALTER TABLE `CATISSUE_SPECIMEN` ADD (`REQ_SPECIMEN_ID` bigint(20) default NULL);

ALTER TABLE `CATISSUE_SPECIMEN` DROP COLUMN  IS_COLL_PROT_REQ , DROP COLUMN POSITION_DIMENSION_ONE, 
DROP COLUMN POSITION_DIMENSION_TWO , DROP COLUMN SPECIMEN_CLASS ,
DROP COLUMN STORAGE_CONTAINER_IDENTIFIER,DROP COLUMN TYPE ,DROP COLUMN LINEAGE ,
DROP COLUMN PATHOLOGICAL_STATUS, DROP COLUMN PARENT_SPECIMEN_ID, DROP COLUMN SPECIMEN_CHARACTERISTICS_ID,
DROP COLUMN QUANTITY , DROP COLUMN CONCENTRATION;

ALTER TABLE CATISSUE_CONTAINER DROP POSITION_DIMENSION_ONE;
ALTER TABLE CATISSUE_CONTAINER DROP POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_CONTAINER DROP PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP STORAGE_CONTAINER_ID;



UPDATE CATISSUE_SPECIMEN_COLL_GROUP scg SET Collection_Protocol_Event_Id = 
( SELECT Specimen_Coll_req_Group_Id FROM CATISSUE_COLL_PROT_EVENT scrg WHERE 
  scg.Collection_Protocol_Event_Id = scrg.identifier
);
SET FOREIGN_KEY_CHECKS=1;	

CREATE TABLE `catissue_coll_prot_event_tmp`
(                                                                                                                     
    `IDENTIFIER` bigint(20) NOT NULL auto_increment,                                                                                                            
    `CLINICAL_STATUS` varchar(50) default NULL,                                                                                                                 
    `COLLECTION_POINT_LABEL` varchar(255) default NULL,                                                                                                         
    `STUDY_CALENDAR_EVENT_POINT` double default NULL,                                                                                                           
    `COLLECTION_PROTOCOL_ID` bigint(20) default NULL,                                                                                                           
    PRIMARY KEY  (`IDENTIFIER`),                                                                                                                                
    UNIQUE KEY `COLLECTION_PROTOCOL_ID` (`COLLECTION_PROTOCOL_ID`,`COLLECTION_POINT_LABEL`),                                                                    
    KEY `FK17AE7715948304401` (`COLLECTION_PROTOCOL_ID`),                                                                                                        
    CONSTRAINT `FK17AE7715948304401` FOREIGN KEY (`COLLECTION_PROTOCOL_ID`) REFERENCES `catissue_collection_protocol` (`IDENTIFIER`),
    CONSTRAINT `FK_PARENT_COLL_PROTEVENT` FOREIGN KEY (`IDENTIFIER`) REFERENCES `catissue_abs_speci_coll_group` (`IDENTIFIER`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into catissue_coll_prot_event_tmp(IDENTIFIER,CLINICAL_STATUS,                                                                                                                 
     COLLECTION_POINT_LABEL,STUDY_CALENDAR_EVENT_POINT,                                                                                                           
    COLLECTION_PROTOCOL_ID)
select SPECIMEN_COLL_REQ_GROUP_ID,CLINICAL_STATUS,                                                                                                                 
     COLLECTION_POINT_LABEL,STUDY_CALENDAR_EVENT_POINT,                                                                                                           
    COLLECTION_PROTOCOL_ID from catissue_coll_prot_event;

SET FOREIGN_KEY_CHECKS=0;
drop table catissue_coll_prot_event;
SET FOREIGN_KEY_CHECKS=1;
rename table catissue_coll_prot_event_tmp to catissue_coll_prot_event;

DROP TABLE CATISSUE_SPECI_COLL_REQ_GROUP;

INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'AbstractSpecimen','AbstractSpecimen Object','edu.wustl.catissuecore.domain.AbstractSpecimen',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'RequirementSpecimen','RequirementSpecimen Object','edu.wustl.catissuecore.domain.SpecimenRequirement',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'MolReqSpecimen','MolReqSpecimen Object','edu.wustl.catissuecore.domain.MolecularSpecimenRequirement',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'FluidReqSpecimen','FluidReqSpecimen Object','edu.wustl.catissuecore.domain.FluidSpecimenRequirement',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'CellReqSpecimen','CellReqSpecimen Object','edu.wustl.catissuecore.domain.CellSpecimenRequirement',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'TissueReqSpecimen','TissueReqSpecimen Object','edu.wustl.catissuecore.domain.TissueSpecimenRequirement',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractSpecimen'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='RequirementSpecimen'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='MolReqSpecimen'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='FluidReqSpecimen'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='CellReqSpecimen'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='TissueReqSpecimen'),'2008-05-28' from CSM_PG_PE;


CREATE INDEX INDX_CATISSUE_SPECIMEN_CLASS ON CATISSUE_ABSTRACT_SPECIMEN (SPECIMEN_CLASS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_TYPE ON CATISSUE_ABSTRACT_SPECIMEN (SPECIMEN_TYPE);
CREATE INDEX INDX_CATISSUE_SPECIMEN_PATH ON CATISSUE_ABSTRACT_SPECIMEN (PATHOLOGICAL_STATUS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_QTY ON CATISSUE_ABSTRACT_SPECIMEN (INITIAL_QUANTITY);
CREATE INDEX INDX_CATISSUE_SPECIMEN_AVQTY ON CATISSUE_SPECIMEN (AVAILABLE_QUANTITY);
CREATE INDEX INDX_MOL_REQ_SPECIMEN_CONC ON CATISSUE_MOL_REQ_SPECIMEN (CONCENTRATION);
CREATE INDEX INDX_MOLECULAR_SPECIMEN_CONC ON CATISSUE_MOLECULAR_SPECIMEN (CONCENTRATION);

Alter table catissue_specimen add KEY FK_REQ_SPECIMEN_ID(REQ_SPECIMEN_ID);
SET FOREIGN_KEY_CHECKS=0;
Alter table catissue_specimen add CONSTRAINT `FK_REQ_SPECIMEN_ID` FOREIGN KEY (`REQ_SPECIMEN_ID`) REFERENCES `CATISSUE_CP_REQ_SPECIMEN` (`IDENTIFIER`);
Alter table catissue_specimen add CONSTRAINT `FK_PARENT_SPECIMEN` FOREIGN KEY (`IDENTIFIER`) REFERENCES `CATISSUE_ABSTRACT_SPECIMEN` (`IDENTIFIER`);
SET FOREIGN_KEY_CHECKS=1;


INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
values(93, 'CATISSUE_ABSTRACT_POSITION', 'Abstract Position', 'AbstractPosition',2,NULL);
INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
values(94, 'CATISSUE_SPECIMEN_POSITION', 'Specimen Position', 'SpecimenPosition',2,1);
INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
values(95, 'CATISSUE_CONTAINER_POSITION', 'Container Position', 'ContainerPosition',2,1);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 96, 'catissue_tissue_specimen', 'Tissue Specimen', 'Tissue Specimen',2,NULL);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 97, 'catissue_cell_specimen', 'Cell Specimen', 'Cell Specimen',2,NULL);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 98, 'catissue_fluid_specimen', 'Fluid Specimen', 'Fluid Specimen',2,NULL);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 99, 'catissue_molecular_specimen', 'Molecular Specimen', 'Molecular Specimen',2,NULL);

/*Metadata updation of Simple Query due to model changes*/

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (331,94,'IDENTIFIER','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (332,94,'SPECIMEN_ID','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (333,94,'CONTAINER_ID','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (334,95,'IDENTIFIER','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (335,95,'CONTAINER_ID','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (336,93,'IDENTIFIER','bigint');

DELETE from CATISSUE_INTERFACE_COLUMN_DATA where IDENTIFIER = 194;
DELETE from CATISSUE_INTERFACE_COLUMN_DATA where IDENTIFIER = 195;

UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET TABLE_ID = 93 WHERE IDENTIFIER IN (249,250);
UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET table_id = 94 WHERE IDENTIFIER IN (200);
UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET table_id = 95 WHERE IDENTIFIER IN (247);

INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(138,94,93,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(139,95,93,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(140,33,94,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(141,72,95,70);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(142,21,95,70);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(143,94,94,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(144,95,95,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(145,21,94,NULL);

INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 93 , 94 , 'IDENTIFIER','IDENTIFIER');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 93 , 95 , 'IDENTIFIER','IDENTIFIER');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 33 , 94 , 'IDENTIFIER','SPECIMEN_ID');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 72 , 95 , 'IDENTIFIER','CONTAINER_ID');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 21 , 94 , 'IDENTIFIER','CONTAINER_ID');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 21 , 95 , 'IDENTIFIER','CONTAINER_ID');

DELETE FROM CATISSUE_RELATED_TABLES_MAP where FIRST_TABLE_ID = 21 AND SECOND_TABLE_ID = 33;

DELETE FROM CATISSUE_SEARCH_DISPLAY_DATA where COL_ID in (194,195);
DELETE FROM CATISSUE_SEARCH_DISPLAY_DATA where COL_ID in (249,250);

INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(138, 249, 'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(138, 250, 'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(139, 249, 'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(139, 250, 'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(34,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(34,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(140,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(140,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(141,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(141,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(142,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(142,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(110,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(110,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(114,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(114,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(144,247,'Parent Container Id',1,3);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(143,333,'Parent Container Id',1,3);

/* race changes */
alter table CATISSUE_RACE add column IDENTIFIER bigint(20) auto_increment,add primary key(IDENTIFIER);
/* race changes finish */

/*Metadata for Specimen due to model changes*/

INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
VALUES(100,'CATISSUE_ABSTRACT_SPECIMEN','Abstract Specimen','AbstractSpecimen',2,NULL);

INSERT INTO CATISSUE_RELATED_TABLES_MAP values(100,33,'IDENTIFIER','IDENTIFIER');

UPDATE CATISSUE_INTERFACE_COLUMN_DATA set TABLE_ID = 100 where IDENTIFIER in (202,199,322,192,102,208,103);

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
VALUES(337,100,'IDENTIFIER','bigint');

INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH)
VALUES(146,33,100,NULL);

UPDATE CATISSUE_SEARCH_DISPLAY_DATA set RELATIONSHIP_ID = 146 where RELATIONSHIP_ID = 34 AND COL_ID in (192,208,199,102,103,322);

UPDATE CATISSUE_INTERFACE_COLUMN_DATA set COLUMN_NAME = 'SPECIMEN_TYPE' where IDENTIFIER = 192;
UPDATE CATISSUE_INTERFACE_COLUMN_DATA set COLUMN_NAME = 'INITIAL_QUANTITY' where IDENTIFIER = 103;

DELETE from CATISSUE_INTERFACE_COLUMN_DATA where IDENTIFIER = 105;
DELETE from CATISSUE_SEARCH_DISPLAY_DATA where COL_ID = 105;

UPDATE CATISSUE_RELATED_TABLES_MAP set SECOND_TABLE_ID = 100 where FIRST_TABLE_ID = 34 and SECOND_TABLE_ID = 33;

UPDATE CATISSUE_RELATED_TABLES_MAP set SECOND_TABLE_ID = 100 where FIRST_TABLE_ID = 33 and SECOND_TABLE_ID = 33;
UPDATE CATISSUE_RELATED_TABLES_MAP set FIRST_TABLE_ID = 100 where FIRST_TABLE_ID = 33 and SECOND_TABLE_ID = 100;

/*Removing Quantity table and all data associate with it*/

DELETE from CATISSUE_QUERY_TABLE_DATA where TABLE_ID = 74;

DELETE from CATISSUE_RELATED_TABLES_MAP where FIRST_TABLE_ID = 12 and SECOND_TABLE_ID = 74;

DELETE from CATISSUE_INTERFACE_COLUMN_DATA where TABLE_ID = 74;

DELETE from CATISSUE_TABLE_RELATION where RELATIONSHIP_ID in (119,120);

DELETE from CATISSUE_SEARCH_DISPLAY_DATA where RELATIONSHIP_ID = 120;

ALTER TABLE CATISSUE_SPECIMEN_REQUIREMENT DROP foreign key FK39AFE96861A1C94F;
DROP table CATISSUE_SPECIMEN_REQUIREMENT;
DROP table CATISSUE_QUANTITY;

/** MSR changes : Start **/

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE '%ACTION%';

INSERT INTO CSM_PRIVILEGE VALUES(13,'USER_PROVISIONING','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR USER CREATION AND ASSIGNING PRIVILEGES TO THAT USER','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(14,'REPOSITORY_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT SITES','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(15,'STORAGE_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT STORAGE TYPES AND CONTAINERS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(16,'PROTOCOL_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT COLLECTION AS WELL AS DISTRIBUTION PROTOCOLS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(17,'DEFINE_ANNOTATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT ANNOTATIONS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(18,'REGISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR REGISTERING PARTICIPANT AND CONSENTS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(20,'SPECIMEN_ACCESSION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT SPECIMEN,SPECIMEN COLLECTION GROUP AND CONSENTS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(21,'DISTRIBUTION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR DISTRIBUTION','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(22,'QUERY','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR QUERY','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(23,'PHI_ACCESS','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR VIEWING PHI DATA','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(24,'PARTICIPANT_SCG_ANNOTATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT ANNOTATION TO PARTICIPANT OR SCG','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(25,'SPECIMEN_ANNOTATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR FOR ADD EDIT SPECIMEN ANNOTATION','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(26,'SPECIMEN_PROCESSING','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT ALIQUOT, DERIVATIVE, EVENTS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(27,'SPECIMEN_STORAGE','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT STORAGE AND TRANSFER EVENTS','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(28,'GENERAL_SITE_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT SITES','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(29,'GENERAL_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT DEPARTMENT,INSTITUTION,CANCER RESEARCH GROUP','2008-06-19');
INSERT INTO CSM_PRIVILEGE VALUES(30,'SHIPMENT_PROCESSING','THIS PRIVILEGE GRANTS PERMISSION TO A USER TO PROCESS SHIPMENTS','2008-08-20');

INSERT INTO CSM_ROLE VALUES(13,'SUPERADMINISTRATOR','SUPER ADMINISTRATOR ROLE',1,0,'2008-06-19');

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,13,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,17,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,14,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,15,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,16,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,18,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,20,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,21,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,22,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,23,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,24,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,25,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,26,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,27,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,28,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,29,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,13,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,14,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,15,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,16,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,18,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,20,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,21,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,22,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,23,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,24,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,25,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,26,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,27,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,28,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,18,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,20,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,21,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,22,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,23,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,24,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,25,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,26,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,27,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,21,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,22,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,25,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,26,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,27,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,7,22,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;

CREATE TABLE CATISSUE_SITE_USERS (
   SITE_ID BIGINT ,
   USER_ID BIGINT ,
   PRIMARY KEY (SITE_ID, USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE CATISSUE_SITE_CP(
   SITE_ID BIGINT ,
   COLLECTION_PROTOCOL_ID BIGINT ,
   PRIMARY KEY (SITE_ID,COLLECTION_PROTOCOL_ID)
 )ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE CATISSUE_USER_CP(
  USER_ID BIGINT ,
  COLLECTION_PROTOCOL_ID BIGINT ,
  PRIMARY KEY (USER_ID,COLLECTION_PROTOCOL_ID)
 )ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE CATISSUE_SITE_USERS ADD INDEX FK1 (USER_ID), ADD CONSTRAINT FK1 FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_USERS ADD INDEX FK2 (SITE_ID), ADD CONSTRAINT FK2 FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);

ALTER TABLE CATISSUE_SITE_CP ADD INDEX FK3 (SITE_ID), ADD CONSTRAINT FK3 FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_CP ADD INDEX FK4 (COLLECTION_PROTOCOL_ID), ADD CONSTRAINT FK4 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

ALTER TABLE CATISSUE_USER_CP ADD INDEX FK5 (USER_ID), ADD CONSTRAINT FK5 FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_USER_CP ADD INDEX FK6 (COLLECTION_PROTOCOL_ID), ADD CONSTRAINT FK6 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) select max(PROTECTION_ELEMENT_ID)+1,'ADMIN_PROTECTION_ELEMENT','ADMIN_PROTECTION_ELEMENT Object','ADMIN_PROTECTION_ELEMENT',NULL,NULL,1,'2008-07-22' from CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ADMIN_PROTECTION_ELEMENT'),'2008-07-22' from CSM_PG_PE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,29,'2008-07-22' FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,18,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,26,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,21,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,23,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,24,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,25,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,18,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,26,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,21,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,23,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,24,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,25,'2008-06-19' FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,30,'2008-08-20' FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,30,'2008-08-20' FROM CSM_ROLE_PRIVILEGE;

/** MSR changes : End **/


/** Upgrading MySQL 4.1.19 to MySQL 5.0.45  : changing data Type tinyInt to bit **/

ALTER TABLE catissue_user  CHANGE  FIRST_TIME_LOGIN  FIRST_TIME_LOGIN bit;
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL  CHANGE  ALIQUOT_IN_SAME_CONTAINER  ALIQUOT_IN_SAME_CONTAINER bit;
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL  CHANGE  CONSENTS_WAIVED  CONSENTS_WAIVED bit;
ALTER TABLE CATISSUE_CONTAINER  CHANGE  FULL  FULL bit;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY  CHANGE  AVAILABLE  AVAILABLE bit;
ALTER TABLE CATISSUE_CONCEPT_REFERENT  CHANGE  IS_MODIFIER  IS_MODIFIER bit;
ALTER TABLE CATISSUE_CONCEPT_REFERENT  CHANGE  IS_NEGATED  IS_NEGATED bit;
ALTER TABLE CATISSUE_QUARANTINE_PARAMS  CHANGE  IS_QUARANTINED  IS_QUARANTINED bit;
ALTER TABLE CATISSUE_PATHOLOGY_REPORT  CHANGE  REVIEW_FLAG  REVIEW_FLAG bit;

/** Upgrading MySQL 4.1.19 to MySQL 5.0.45   : End**/

INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5013,'Distributed And Close',NULL,'4285');
/** Barcode related changes  start **/
ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP ADD BARCODE varchar(255) unique;
ALTER TABLE CATISSUE_COLL_PROT_REG ADD BARCODE varchar(255) unique;

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
VALUES (338,35,'BARCODE','varchar');
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
VALUES(30,338,'Barcode',0,2);

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
VALUES (339,27,'BARCODE','varchar');
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
VALUES(29,339,'Barcode',0,8);
/** Barcode related changes  end **/

/** Added encounter date and time **/
ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP ADD ENCOUNTER_TIMESTAMP datetime;

ALTER TABLE `CATISSUE_SPECIMEN` ,change `BARCODE` `BARCODE` varchar (255) BINARY;
ALTER TABLE `CATISSUE_SPECIMEN_COLL_GROUP` ,change `BARCODE` `BARCODE` varchar (255) BINARY ;
ALTER TABLE `CATISSUE_CONTAINER` ,change `BARCODE` `BARCODE` varchar (255) BINARY ;
ALTER TABLE `CATISSUE_COLL_PROT_REG` ,change `BARCODE` `BARCODE` varchar (255) BINARY ;

ALTER TABLE CATISSUE_CP_REQ_SPECIMEN ADD LABELFORMAT varchar(255) default NULL;

update catissue_query_table_data set TABLE_NAME='CATISSUE_DISTRIBUTION_SPEC_REQ' where table_name='CATISSUE_DISTRIBUTION_SPE_REQ';

delete from catissue_interface_column_data where TABLE_ID=20 AND COLUMN_NAME='SPECIMEN_REQUIREMENT_ID';

INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(340,20,'SPECIMEN_TYPE','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(341,20,'SPECIMEN_CLASS','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(342,20,'TISSUE_SITE','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(343,20,'PATHOLOGY_STATUS','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(344,20,'QUANTITY','double');

DELETE FROM CATISSUE_TABLE_RELATION WHERE RELATIONSHIP_ID=20;

DELETE FROM catissue_related_tables_map WHERE FIRST_TABLE_ID=12 AND SECOND_TABLE_ID=20;

INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,340,'Specimen Type',12);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,341,'Specimen Class',13);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,342,'Tissue Site',14);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,343,'Pathology status',15);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,344,'Quantity',16);


/* for bug 9303 */
update CATISSUE_SPECIMEN_PROTOCOL set enrollment='0' where enrollment is null;


/**Resolved Bug# 7862 **/
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5014,'CPT',NULL,'2003997');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5015,'Paxgene',NULL,'2003997');
