/*Create table and constraints*/
create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER BIGINT not null auto_increment,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER,
	primary key (IDENTIFIER)
)ENGINE = INNODB DEFAULT CHARSET = utf8;


create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER BIGINT not null auto_increment,
	SPECIMEN_ID BIGINT,
	CONTAINER_ID BIGINT,
	primary key (IDENTIFIER),
	index FK_SPECIMEN_POSITION (IDENTIFIER),
	constraint FK_SPECIMEN_POSITION foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_POSITION (IDENTIFIER),
	index FK_SPECIMEN (SPECIMEN_ID),
	constraint FK_SPECIMEN foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER),
	index FK_STORAGE_CONTAINER (CONTAINER_ID),
	constraint FK_STORAGE_CONTAINER foreign key (CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER)
)ENGINE = INNODB DEFAULT CHARSET = utf8;


create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER BIGINT not null auto_increment,
	PARENT_CONTAINER_ID bigint,
	CONTAINER_ID BIGINT,
	primary key (IDENTIFIER),
	index FK_CONTAINER_POSITION (IDENTIFIER), 
	constraint FK_CONTAINER_POSITION foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_POSITION (IDENTIFIER),
	index FK_CONTAINER (CONTAINER_ID),
	constraint FK_CONTAINER foreign key (CONTAINER_ID) references CATISSUE_CONTAINER (IDENTIFIER),
	index FK_OCCUPIED_CONTAINER (PARENT_CONTAINER_ID),
	constraint FK_OCCUPIED_CONTAINER foreign key (PARENT_CONTAINER_ID) references CATISSUE_CONTAINER (IDENTIFIER)
)ENGINE = INNODB DEFAULT CHARSET = utf8;


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all SPECIMEN_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD SPECIMEN_ID BIGINT;
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID BIGINT;
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD IS_SPECIMEN BIGINT;

/**Insert data of specimen*/
insert into CATISSUE_ABSTRACT_POSITION(SPECIMEN_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) select identifier,storage_container_identifier,position_dimension_one,position_dimension_two,1 from catissue_specimen where is_coll_prot_req=0 and activity_status in ('Active','Closed') and storage_container_identifier is not null and POSITION_DIMENSION_ONE is not null and POSITION_DIMENSION_TWO is not null ;
insert into CATISSUE_SPECIMEN_POSITION(IDENTIFIER,SPECIMEN_ID,CONTAINER_ID) select IDENTIFIER,SPECIMEN_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION;


/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP SPECIMEN_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP CONTAINER_ID;


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all CONTAINER_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD PARENT_CONTAINER_ID BIGINT;
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID BIGINT;

/*insert Storage container*/
insert into CATISSUE_ABSTRACT_POSITION(PARENT_CONTAINER_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) select a.parent_container_id,a.identifier,a.position_dimension_one,a.position_dimension_two,0 from catissue_container a join catissue_storage_container b on a.identifier=b.identifier where activity_status in ('Active','Closed') and POSITION_DIMENSION_ONE is not null and POSITION_DIMENSION_TWO is not null and PARENT_CONTAINER_ID is not null;
insert into CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) select IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION where IS_SPECIMEN=0;


/*insert Specimen array*/
insert into CATISSUE_ABSTRACT_POSITION(CONTAINER_ID,PARENT_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) select a.identifier,b.storage_container_id,position_dimension_one,position_dimension_two,2 from catissue_container a, catissue_specimen_array b where a.identifier=b.identifier and a.activity_status in ('Active','Closed')and a.POSITION_DIMENSION_ONE is not null and a.POSITION_DIMENSION_TWO is not null and b.storage_container_id is not null;
insert into CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) select IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION where IS_SPECIMEN=2;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP IS_SPECIMEN;

/*Drop columns from existing table*/
ALTER TABLE CATISSUE_CONTAINER DROP foreign key FK49B8DE5DB097B2E;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP foreign key FKECBF8B3EB3DFB11D;
ALTER TABLE CATISSUE_SPECIMEN DROP foreign key FK1674810432B31EAB;

ALTER TABLE CATISSUE_SPECIMEN DROP POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_SPECIMEN DROP STORAGE_CONTAINER_IDENTIFIER;
ALTER TABLE CATISSUE_CONTAINER DROP POSITION_DIMENSION_ONE;
ALTER TABLE CATISSUE_CONTAINER DROP POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_CONTAINER DROP PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP STORAGE_CONTAINER_ID;

--Insert CSM scripts
INSERT into `CSM_PROTECTION_ELEMENT` select max(PROTECTION_ELEMENT_ID)+1,'AbstractPosition','AbstractPosition Object','edu.wustl.catissuecore.domain.AbstractPosition',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` select max(PROTECTION_ELEMENT_ID)+1,'SpecimenPosition','SpecimenPosition Object','edu.wustl.catissuecore.domain.SpecimenPosition',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;
INSERT into `CSM_PROTECTION_ELEMENT` select max(PROTECTION_ELEMENT_ID)+1,'ContainerPosition','ContainerPosition Object','edu.wustl.catissuecore.domain.ContainerPosition',NULL,NULL,1,'2008-5-28' from CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractPosition'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='SpecimenPosition'),'2008-05-28' from CSM_PG_PE;
INSERT INTO CSM_PG_PE select max(PG_PE_ID)+1,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ContainerPosition'),'2008-05-28' from CSM_PG_PE;

/**Added a workaround so that edit of Container,specimen should work. NEED TO REMOVE */
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_SPECIMEN ADD STORAGE_CONTAINER_IDENTIFIER bigint;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_CONTAINER ADD PARENT_CONTAINER_ID bigint;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY ADD STORAGE_CONTAINER_ID bigint;
