ALTER TABLE CATISSUE_CONTAINER ADD (CONT_FULL bit);
UPDATE CATISSUE_CONTAINER SET CONT_FULL = FULL;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN FULL;

alter table CATISSUE_SPECIMEN_PROTOCOL modify SHORT_TITLE varchar(255) not null unique;

UPDATE CATISSUE_INTERFACE_COLUMN_DATA set COLUMN_NAME = 'CONT_FULL' where IDENTIFIER = 242;