<?xml version="1.0" encoding="UTF-8"?>

<definitions name="PrintWebService" targetNamespace="http://edu.wustl.webservice.catissuecore.print.jboss.org/" xmlns:tns="http://edu.wustl.webservice.catissuecore.print.jboss.org/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types/>
  <message name="PrintService_print">
    <part name="String_1" type="xsd:string"/></message>
  <message name="PrintService_printResponse">
    <part name="result" type="xsd:string"/></message>
  <portType name="PrintService">
    <operation name="print" parameterOrder="String_1">
      <input message="tns:PrintService_print"/>
      <output message="tns:PrintService_printResponse"/></operation></portType>
  <binding name="PrintServiceBinding" type="tns:PrintService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="print">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://edu.wustl.webservice.catissuecore.print.jboss.org/"/></input>
      <output>
        <soap:body use="literal" namespace="http://edu.wustl.webservice.catissuecore.print.jboss.org/"/></output></operation></binding>
  <service name="PrintWebService">
    <port name="PrintServicePort" binding="tns:PrintServiceBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_URL"/></port></service></definitions>
