/*L
 *  Copyright Washington University in St. Louis
 *  Copyright SemanticBits
 *  Copyright Persistent Systems
 *  Copyright Krishagni
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/catissue-core/LICENSE.txt for details.
 */

package gov.nih.nci.caxchange.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface CaXchangeConsumerServiceConstantsBase {
	public static final String SERVICE_NS = "http://caxchange.nci.nih.gov/CaXchangeConsumerService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaXchangeConsumerServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaXchangeConsumerServiceResourceProperties");
	
}
