DELETE FROM DYEXTN_STRING_TYPE_INFO WHERE identifier IN (308,321,315);
INSERT INTO DYEXTN_FILE_TYPE_INFO (Identifier) VALUES(308);
INSERT INTO DYEXTN_FILE_TYPE_INFO (Identifier) VALUES(321);
INSERT INTO DYEXTN_FILE_TYPE_INFO (Identifier) VALUES(315);




