<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="OGSANaming" targetNamespace="http://schemas.ggf.org/naming/2006/03/naming/bindings" xmlns:porttype="http://schemas.ggf.org/naming/2006/03/naming" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://schemas.ggf.org/naming/2006/03/naming" location="resolution_port_type.wsdl"/>
  <wsdl:binding name="NamingSOAPBinding" type="porttype:Naming">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="resolve">
      <soap:operation soapAction="http://schemas.ggf.org/naming/2006/03/naming/Naming/resolveRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UnknownResourceFault">
        <soap:fault name="UnknownResourceFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
