create index INDEX1 ON PATH (FIRST_ENTITY_ID,LAST_ENTITY_ID);
insert into ID_TABLE(NEXT_ASSOCIATION_ID) values(1);

create sequence CATEGORIAL_CLASS_SEQ;
create sequence CATEGORIAL_ATTRIBUTE_SEQ;
create sequence CATEGORY_SEQ; 

create index FK9651EF32D8D56A33 ON CATEGORIAL_CLASS (PARENT_CATEGORIAL_CLASS_ID);
alter table CATEGORIAL_CLASS add constraint FK9651EF32D8D56A33 foreign key (PARENT_CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS (ID); 

create index FK31F77B56E8CBD948 ON CATEGORIAL_ATTRIBUTE (CATEGORIAL_CLASS_ID);
alter table CATEGORIAL_ATTRIBUTE add constraint FK31F77B56E8CBD948 foreign key (CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS (ID); 

create index FK31A8ACFE2D0F63E7 ON CATEGORY (PARENT_CATEGORY_ID);
alter table CATEGORY add constraint FK31A8ACFE2D0F63E7 foreign key (PARENT_CATEGORY_ID) references CATEGORY (ID);

alter table CATEGORY add constraint FK31A8ACFE211D9A6B foreign key (ROOT_CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS (ID);
