DROP SEQUENCE CSM_APPLICATI_APPLICATION__SEQ;
DROP TABLE CSM_APPLICATION CASCADE CONSTRAINTS;

-- CSM_GROUP
DROP SEQUENCE CSM_GROUP_GROUP_ID_SEQ;
DROP TABLE CSM_GROUP CASCADE CONSTRAINTS;

-- CSM_PG_PE
DROP TRIGGER SET_CSM_PG_PE_PG_PE_ID;
DROP SEQUENCE CSM_PG_PE_PG_PE_ID_SEQ;
DROP TRIGGER SET_CSM_PG_PE_UPDATE_DATE;
DROP TABLE CSM_PG_PE CASCADE CONSTRAINTS;

-- CSM_PRIVILEGE
DROP SEQUENCE CSM_PRIVILEGE_PRIVILEGE_ID_SEQ;
DROP TABLE CSM_PRIVILEGE CASCADE CONSTRAINTS;

-- CSM_PROTECTION_ELEMENT
DROP SEQUENCE CSM_PROTECTIO_PROTECTION_E_SEQ;
DROP TABLE CSM_PROTECTION_ELEMENT CASCADE CONSTRAINTS;

-- CSM_PROTECTION_GROUP
DROP SEQUENCE CSM_PROTECTIO_PROTECTION_G_SEQ;
DROP TABLE CSM_PROTECTION_GROUP CASCADE CONSTRAINTS;

-- CSM_ROLE
DROP SEQUENCE CSM_ROLE_ROLE_ID_SEQ;
DROP TABLE CSM_ROLE CASCADE CONSTRAINTS;

-- CSM_ROLE_PRIVILEGE
DROP TRIGGER SET_CSM_ROLE_PRIV_ROLE_PRIVILE;
DROP TRIGGER SET_CSM_ROLE_PRIV_UPDATE_DATE;
DROP SEQUENCE CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ;
DROP TABLE CSM_ROLE_PRIVILEGE CASCADE CONSTRAINTS;

-- CSM_USER 
DROP SEQUENCE CSM_USER_USER_ID_SEQ;
DROP TABLE CSM_USER CASCADE CONSTRAINTS;

-- CSM_USER_GROUP
DROP SEQUENCE CSM_USER_GROU_USER_GROUP_I_SEQ;
DROP TRIGGER SET_CSM_USER_GROU_USER_GROUP_I;
DROP TABLE CSM_USER_GROUP CASCADE CONSTRAINTS;
DROP SEQUENCE CSM_USER_GROU_USER_GROUP_R_SEQ;
DROP TABLE CSM_USER_GROUP_ROLE_PG CASCADE CONSTRAINTS;

DROP TRIGGER SET_CSM_USER_PE_USER_PROTECTIO;
DROP TRIGGER SET_CSM_USER_PE_UPDATE_DATE;
DROP SEQUENCE CSM_USER_PE_USER_PROTECTIO_SEQ;
DROP TABLE CSM_USER_PE CASCADE CONSTRAINTS;

CREATE TABLE CSM_APPLICATION ( 
	APPLICATION_ID NUMBER(38) NOT NULL,
	APPLICATION_NAME VARCHAR2(100) NOT NULL,
	APPLICATION_DESCRIPTION VARCHAR2(200) NOT NULL,
	DECLARATIVE_FLAG NUMBER(1),
	ACTIVE_FLAG NUMBER(1) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_APPLICATI_APPLICATION__SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_GROUP ( 
	GROUP_ID NUMBER(38) NOT NULL,
	GROUP_NAME VARCHAR2(100) NOT NULL,
	GROUP_DESC VARCHAR2(200),
	UPDATE_DATE DATE NOT NULL,
	APPLICATION_ID NUMBER(38) NOT NULL
) 
;

CREATE SEQUENCE CSM_GROUP_GROUP_ID_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_PG_PE ( 
	PG_PE_ID NUMBER(38) NOT NULL,
	PROTECTION_GROUP_ID NUMBER(38) NOT NULL,
	PROTECTION_ELEMENT_ID NUMBER(38) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_PG_PE_PG_PE_ID_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_PRIVILEGE ( 
	PRIVILEGE_ID NUMBER(38) NOT NULL,
	PRIVILEGE_NAME VARCHAR2(100) NOT NULL,
	PRIVILEGE_DESCRIPTION VARCHAR2(200),
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_PRIVILEGE_PRIVILEGE_ID_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_PROTECTION_ELEMENT ( 
	PROTECTION_ELEMENT_ID NUMBER(38) NOT NULL,
	PROTECTION_ELEMENT_NAME VARCHAR2(100) NOT NULL,
	PROTECTION_ELEMENT_DESCRIPTION VARCHAR2(200),
	OBJECT_ID VARCHAR2(100) NOT NULL,
	ATTRIBUTE VARCHAR2(100),
	PROTECTION_ELEMENT_TYPE_ID NUMBER(10),
	APPLICATION_ID NUMBER(38) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_PROTECTIO_PROTECTION_E_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_PROTECTION_GROUP ( 
	PROTECTION_GROUP_ID NUMBER(38) NOT NULL,
	PROTECTION_GROUP_NAME VARCHAR2(100) NOT NULL,
	PROTECTION_GROUP_DESCRIPTION VARCHAR2(200),
	APPLICATION_ID NUMBER(38) NOT NULL,
	LARGE_ELEMENT_COUNT_FLAG NUMBER(1) NOT NULL,
	UPDATE_DATE DATE NOT NULL,
	PARENT_PROTECTION_GROUP_ID NUMBER(38)
) 
;

CREATE SEQUENCE CSM_PROTECTIO_PROTECTION_G_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_ROLE ( 
	ROLE_ID NUMBER(38) NOT NULL,
	ROLE_NAME VARCHAR2(100) NOT NULL,
	ROLE_DESCRIPTION VARCHAR2(200),
	APPLICATION_ID NUMBER(38) NOT NULL,
	ACTIVE_FLAG NUMBER(1) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_ROLE_ROLE_ID_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_ROLE_PRIVILEGE ( 
	ROLE_PRIVILEGE_ID NUMBER(38) NOT NULL,
	ROLE_ID NUMBER(38) NOT NULL,
	PRIVILEGE_ID NUMBER(38) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_USER ( 
	USER_ID NUMBER(38) NOT NULL,
	LOGIN_NAME VARCHAR2(100) NOT NULL,
	FIRST_NAME VARCHAR2(100) NOT NULL,
	LAST_NAME VARCHAR2(100) NOT NULL,
	ORGANIZATION VARCHAR2(100),
	DEPARTMENT VARCHAR2(100),
	TITLE VARCHAR2(100),
	PHONE_NUMBER VARCHAR2(15),
	PASSWORD VARCHAR2(100),
	EMAIL_ID VARCHAR2(100),
	START_DATE DATE,
	END_DATE DATE,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_USER_USER_ID_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_USER_GROUP ( 
	USER_GROUP_ID NUMBER(38) NOT NULL,
	USER_ID NUMBER(38) NOT NULL,
	GROUP_ID NUMBER(38) NOT NULL
) 
;

CREATE SEQUENCE CSM_USER_GROU_USER_GROUP_I_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_USER_GROUP_ROLE_PG ( 
	USER_GROUP_ROLE_PG_ID NUMBER(38) NOT NULL,
	USER_ID NUMBER(38),
	GROUP_ID NUMBER(38),
	ROLE_ID NUMBER(38) NOT NULL,
	PROTECTION_GROUP_ID NUMBER(38) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_USER_GROU_USER_GROUP_R_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

CREATE TABLE CSM_USER_PE ( 
	USER_PROTECTION_ELEMENT_ID NUMBER(38) NOT NULL,
	PROTECTION_ELEMENT_ID NUMBER(38) NOT NULL,
	USER_ID NUMBER(38) NOT NULL,
	UPDATE_DATE DATE NOT NULL
) 
;

CREATE SEQUENCE CSM_USER_PE_USER_PROTECTIO_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;