--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATEGORIAL_CLASS') DROP TABLE CATEGORIAL_CLASS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATEGORIAL_ATTRIBUTE') DROP TABLE CATEGORIAL_ATTRIBUTE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATEGORY') DROP TABLE CATEGORY;

create table CATEGORIAL_CLASS (
   ID bigint not null identity,
   DE_ENTITY_ID bigint,
   PATH_FROM_PARENT_ID bigint,
   PARENT_CATEGORIAL_CLASS_ID bigint
);
alter table CATEGORIAL_CLASS add constraint PK_CATEGORIAL_CLASS_ID primary key (ID);


create table CATEGORIAL_ATTRIBUTE (
   ID bigint not null identity,
   CATEGORIAL_CLASS_ID bigint,
   DE_CATEGORY_ATTRIBUTE_ID bigint,
   DE_SOURCE_CLASS_ATTRIBUTE_ID bigint
);
alter table CATEGORIAL_ATTRIBUTE add constraint PK_CATEGORIAL_ATTRIBUTE_ID primary key (ID);


create table CATEGORY (
   ID bigint not null identity,
   DE_ENTITY_ID bigint,
   PARENT_CATEGORY_ID bigint,
   ROOT_CATEGORIAL_CLASS_ID bigint
);
alter table CATEGORY add constraint PK_CATEGORY_ID primary key (ID);

alter table CATEGORIAL_CLASS add constraint FK_CATEGORIAL_CLS_ID_PARENT foreign key (PARENT_CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS ;
alter table CATEGORIAL_ATTRIBUTE add constraint FK_CATEGO_ATB_CATEGO_CLS_ID foreign key (CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS ;
alter table CATEGORY add constraint FK_CATEGORY_PARENT_CATEG_ID foreign key (PARENT_CATEGORY_ID) references CATEGORY ;
alter table CATEGORY add constraint FK_CATEG_ROOT_CATEG_CLS_ID foreign key (ROOT_CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS ;
