CREATE OR REPLACE PROCEDURE addCSHConstraints 
IS
BEGIN
 
 EXECUTE IMMEDIATE 'ALTER TABLE CATISSUE_SPECIMEN_HIERARCHY ADD CONSTRAINT FK_ANCESTOR_ID_MAP FOREIGN KEY(ANCESTOR_ID) REFERENCES CATISSUE_SPECIMEN(IDENTIFIER)';
 
 EXECUTE IMMEDIATE 'ALTER TABLE CATISSUE_SPECIMEN_HIERARCHY ADD CONSTRAINT FK_DESCENDENT_ID_MAP FOREIGN KEY(DESCENDENT_ID) REFERENCES CATISSUE_SPECIMEN(IDENTIFIER)';

 EXECUTE IMMEDIATE 'ALTER TABLE CATISSUE_SPECIMEN_HIERARCHY ADD CONSTRAINT UK_ANCESTOR_DESCENDENT UNIQUE(ANCESTOR_ID, DESCENDENT_ID)';
 
END;
/


CREATE OR REPLACE TRIGGER TGR_SPECIMEN_REPLICATION AFTER INSERT 
ON CATISSUE_SPECIMEN
FOR EACH ROW
BEGIN

 
 IF (:NEW.PARENT_SPECIMEN_ID IS NOT NULL ) THEN
  INSERT INTO CATISSUE_SPECIMEN_HIERARCHY(ANCESTOR_ID,DESCENDENT_ID) 
    (SELECT CSH.ANCESTOR_ID, :NEW.IDENTIFIER FROM CATISSUE_SPECIMEN_HIERARCHY CSH WHERE CSH.DESCENDENT_ID = :NEW.PARENT_SPECIMEN_ID);
 END IF;
  
 INSERT INTO CATISSUE_SPECIMEN_HIERARCHY(ANCESTOR_ID, DESCENDENT_ID) VALUES (:NEW.IDENTIFIER,:NEW.IDENTIFIER);

END;
/


