
package edu.wustl.webservice.catissuecore.print;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PrintWebService", targetNamespace = "http://print.catissuecore.webservice.wustl.edu/", wsdlLocation = "./WEB-INF/wsdl/PrintWebService.wsdl")
public class PrintWebService
    extends Service
{

    private final static URL PRINTWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WorkSpace/catissuecore_final_print/caTissuePrintWebService/WEB-INF/wsdl/PrintWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PRINTWEBSERVICE_WSDL_LOCATION = url;
    }

    public PrintWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintWebService() {
        super(PRINTWEBSERVICE_WSDL_LOCATION, new QName("http://print.catissuecore.webservice.wustl.edu/", "PrintWebService"));
    }

    /**
     * 
     * @return
     *     returns PrintService
     */
    @WebEndpoint(name = "PrintServicePort")
    public PrintService getPrintServicePort() {
        return (PrintService)super.getPort(new QName("http://print.catissuecore.webservice.wustl.edu/", "PrintServicePort"), PrintService.class);
    }

}
