
package edu.wustl.webservice.catissuecore.print;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PrintService", targetNamespace = "http://print.catissuecore.webservice.wustl.edu/")
public interface PrintService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://print.catissuecore.webservice.wustl.edu/", className = "edu.wustl.webservice.catissuecore.print.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://print.catissuecore.webservice.wustl.edu/", className = "edu.wustl.webservice.catissuecore.print.PrintResponse")
    public String print(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
