LOAD DATA INFILE 'E://GitHub//src/SQL/Permissible_values/CATISSUE_PERMISSIBLE_VALUE.csv' 
BADFILE '/sample.bad'
DISCARDFILE '/sample.dsc'
APPEND 
INTO TABLE CATISSUE_PERMISSIBLE_VALUE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IDENTIFIER NULLIF IDENTIFIER='\\N',CONCEPT_CODE NULLIF CONCEPT_CODE='\\N',DEFINITION NULLIF DEFINITION='\\N',PARENT_IDENTIFIER NULLIF PARENT_IDENTIFIER='\\N',VALUE NULLIF VALUE='\\N',PUBLIC_ID NULLIF PUBLIC_ID='\\N')