<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NotificationConsumerFactory" targetNamespace="http://wsrf.globus.org/core/tests/interop/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:porttype="http://wsrf.globus.org/core/tests/interop" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://wsrf.globus.org/core/tests/interop" location="notification_consumer_factory_port_type.wsdl"/>
  <wsdl:binding name="NotificationConsumerFactorySOAPBinding" type="porttype:NotificationConsumerFactory">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createNotificationConsumer">
      <soap:operation soapAction="http://wsrf.globus.org/core/tests/interop/NotificationConsumerFactory/createNotificationConsumerRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
