//v.3.5 build 120822

/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
dhtmlXGridObject.prototype.setFiltrationLevel=function(d,a,b){this._tr_strfltr=d;this._tr_fltr_c=a;this._tr_fltr_d=b;this.refreshFilters()};
dhtmlXGridObject.prototype.filterTreeBy=function(d,a,b){var c=this._h2;if(typeof this._tr_strfltr=="undefined")this._tr_strfltr=-1;if(this._f_rowsBuffer){if(!b&&(this._h2=this._f_rowsBuffer,this._fake))this._fake._h2=this._h2}else this._f_rowsBuffer=this._h2;var e=!0;this.dma(!0);this._fbf={};if(typeof d=="object")for(var f=0;f<a.length;f++)this._filterTreeA(d[f],a[f]);else this._filterTreeA(d,a);this._fbf=null;this.dma(!1);this._fix_filtered_images(this._h2,c);this._renderSort();this.callEvent("onGridReconstructed",
[])};
dhtmlXGridObject.prototype._filterTreeA=function(d,a){if(a!=""){var b=!0;typeof a=="function"?b=!1:a=(a||"").toString().toLowerCase();var c=function(a,b,e){var g=e.get[a.parent.id];g||(g=c(a.parent,b,e));e=f.get[a.id];e||(e={id:a.id,childs:[],level:a.level,parent:g,index:g.childs.length,image:a.image,state:a.state,buff:a.buff,has_kids:a.has_kids,_xml_await:a._xml_await},g.childs.push(e),f.get[e.id]=e);return e},e=this._fbf,f=new dhtmlxHierarchy,g,i=this._tr_strfltr,k=this,j=function(a){for(var e=0;e<
a.childs.length;e++)k.temp(a.childs[e])};switch(i.toString()){case "-2":g=function(a){if(e[a.id])return!1;j(a);return!0};break;case "-1":g=function(a){return!a.childs.length};break;default:g=function(a){return i==a.level}}this.temp=function(h){if(h.id!=0&&g(h))return(b?this._get_cell_value(h.buff,d).toString().toLowerCase().indexOf(a)==-1:!a(this._get_cell_value(h.buff,d),h.id))?(e[h.id]=!0,this._tr_fltr_c&&c(h.parent,this._h2,f),!1):(c(h,this._h2,f),h.childs&&i!=-2&&this._h2.forEachChild(h.id,function(a){c(a,
this._h2,f)},this),!0);else this._tr_fltr_d&&this._tr_strfltr>h.level&&h.id!=0&&c(h,this._h2,f),j(h)};this.temp(this._h2.get[0]);this._h2=f;if(this._fake)this._fake._h2=this._h2}};
dhtmlXGridObject.prototype._fix_filtered_images=function(d,a){d.forEachChild(0,function(b){if(!b.childs.length&&!b.has_kids){if(b.state!=dhtmlXGridObject._emptyLineImg)b.state=dhtmlXGridObject._emptyLineImg,b.update=!0,this._updateTGRState(b)}else if(b.buff.tagName=="TR"){var c=a.get[b.id];if(c&&c.state!=dhtmlXGridObject._emptyLineImg)b.state=c.state;b.update=!0;this._updateTGRState(b)}},this)};
dhtmlXGridObject.prototype.collectTreeValues=function(d){if(typeof this._tr_strfltr=="undefined")this._tr_strfltr=-1;this.dma(!0);this._build_m_order();var d=this._m_order?this._m_order[d]:d,a={},b=[],c=this._f_rowsBuffer||this._h2;c.forEachChild(0,function(e){if(this._tr_strfltr==-2||this._tr_strfltr==-1&&!e.childs.length||this._tr_strfltr==e.level){var b=this._get_cell_value(e.buff,d);b&&(a[b]=!0)}},this);this.dma(!1);var e=this.combos[d];for(d in a)a[d]===!0&&b.push(e?e.get(d)||d:d);return b.sort()};
dhtmlXGridObject.prototype._in_header_stat_tree_total=function(d,a,b){var c=function(){var e=0;this._h2.forEachChild(0,function(b){var g=parseFloat(this._get_cell_value(b.buff||this.rowsAr[b.id],a));e+=isNaN(g)?0:g},this);return this._maskArr[a]?this._aplNF(e,a):Math.round(e*100)/100};this._stat_in_header(d,c,a,b,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_total_leaf=function(d,a,b){var c=function(){var e=0;this._h2.forEachChild(0,function(b){if(!b.childs.length){var g=parseFloat(this._get_cell_value(b.buff||this.rowsAr[b.id],a));e+=isNaN(g)?0:g}},this);return this._maskArr[a]?this._aplNF(e,a):Math.round(e*100)/100};this._stat_in_header(d,c,a,b,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_multi_total=function(d,a,b){var c=b[1].split(":");b[1]="";var e=function(){var e=0;this._h2.forEachChild(0,function(a){var b=parseFloat(this._get_cell_value(a.buff||this.rowsAr[a.id],c[0]))*parseFloat(this._get_cell_value(a.buff||this.rowsAr[a.id],c[1]));e+=isNaN(b)?0:b},this);return this._maskArr[a]?this._aplNF(e,a):Math.round(e*100)/100};this._stat_in_header(d,e,a,b,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_multi_total_leaf=function(d,a,b){var c=b[1].split(":");b[1]="";var e=function(){var e=0;this._h2.forEachChild(0,function(a){if(!a.childs.length){var b=parseFloat(this._get_cell_value(a.buff||this.rowsAr[a.id],c[0]))*parseFloat(this._get_cell_value(a.buff||this.rowsAr[a.id],c[1]));e+=isNaN(b)?0:b}},this);return this._maskArr[a]?this._aplNF(e,a):Math.round(e*100)/100};this._stat_in_header(d,e,a,b,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_max=function(d,a,b){var c=function(){var e=-999999999;if(this.getRowsNum()==0)return"";this._h2.forEachChild(0,function(b){var c=parseFloat(this._get_cell_value(b.buff||this.rowsAr[b.id],a));isNaN(c)||(e=Math.max(e,c))},this);return this._maskArr[a]?this._aplNF(e,a):e};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_min=function(d,a,b){var c=function(){var e=999999999;if(this.getRowsNum()==0)return"";this._h2.forEachChild(0,function(b){var c=parseFloat(this._get_cell_value(b.buff||this.rowsAr[b.id],a));isNaN(c)||(e=Math.min(e,c))},this);return this._maskArr[a]?this._aplNF(e,a):e};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_average=function(d,a,b){var c=function(){var b=0,c=0;this._h2.forEachChild(0,function(d){var i=parseFloat(this._get_cell_value(d.buff||this.rowsAr[d.id],a));b+=isNaN(i)?0:i;c++},this);return this._maskArr[a]?this._aplNF(b,a):Math.round(b/c*100)/100};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_max_leaf=function(d,a,b){var c=function(){var b=-999999999;if(this.getRowsNum()==0)return"";this._h2.forEachChild(0,function(c){if(!c.childs.length){var d=parseFloat(this._get_cell_value(c.buff||this.rowsAr[c.id],a));isNaN(d)||(b=Math.max(b,d))}},this);return this._maskArr[a]?this._aplNF(b,a):b};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_min_leaf=function(d,a,b){var c=function(){var b=999999999;if(this.getRowsNum()==0)return"";this._h2.forEachChild(0,function(c){if(!c.childs.length){var d=parseFloat(this._get_cell_value(c.buff||this.rowsAr[c.id],a));isNaN(d)||(b=Math.min(b,d))}},this);return this._maskArr[a]?this._aplNF(b,a):b};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_average_leaf=function(d,a,b){var c=function(){var b=0,c=0;this._h2.forEachChild(0,function(d){if(!d.childs.length){var i=parseFloat(this._get_cell_value(d.buff||this.rowsAr[d.id],a));b+=isNaN(i)?0:i;c++}},this);return this._maskArr[a]?this._aplNF(b,a):Math.round(b/c*100)/100};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._in_header_stat_tree_count=function(d,a,b){var c=function(){var a=0;this._h2.forEachChild(0,function(){a++},this);return a};this._stat_in_header(d,c,a,b)};dhtmlXGridObject.prototype._in_header_stat_tree_count_leaf=function(d,a,b){var c=function(){var a=0;this._h2.forEachChild(0,function(b){b.childs.length||a++},this);return a};this._stat_in_header(d,c,a,b)};
dhtmlXGridObject.prototype._stat_in_header=function(d,a,b,c){var e=this,f=function(){this.dma(!0);d.innerHTML=(c[0]?c[0]:"")+a.call(this)+(c[1]?c[1]:"");this.dma(!1);this.callEvent("onStatReady",[])};if(!this._stat_events)this._stat_events=[],this.attachEvent("onClearAll",function(){if(!this.hdr.rows[1]){for(var a=0;a<this._stat_events.length;a++)for(var b=0;b<4;b++)this.detachEvent(this._stat_events[a][b]);this._stat_events=[]}});this._stat_events.push([this.attachEvent("onGridReconstructed",f),
this.attachEvent("onXLE",f),this.attachEvent("onFilterEnd",f),this.attachEvent("onEditCell",function(a,c,d){a==2&&d==b&&f.call(this);return!0})]);d.innerHTML=""};

//v.3.5 build 120822

/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/