/*Vijay Pande: Bug:3834: For Specimen class = 'Molecular' following two permissible values are added*/
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(2651,'Total Nucleic Acid',1,NULL);
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(2652,'Whole Genome Amplified DNA',1,NULL);