/*Create table and constraints*/
create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER number(19,0) NOT NULL,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER,
	primary key (IDENTIFIER)
);

create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER number(19,0) NOT NULL,
	SPECIMEN_ID number(19,0),
	CONTAINER_ID number(19,0),
	primary key (IDENTIFIER),
	CONSTRAINT FK_SPECIMEN_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_SPECIMEN FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN,
	CONSTRAINT FK_STORAGE_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_STORAGE_CONTAINER
);

create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER number(19,0) NOT NULL,
	PARENT_CONTAINER_ID number(19,0),
	CONTAINER_ID number(19,0),
	primary key (IDENTIFIER),
	CONSTRAINT FK_CONTAINER_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_CONTAINER,
	CONSTRAINT FK_OCCUPIED_CONTAINER FOREIGN KEY (PARENT_CONTAINER_ID) REFERENCES CATISSUE_CONTAINER
);

create sequence CATISSUE_ABS_POSITION_SEQ;

INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'AbstractPosition','AbstractPosition Object','edu.wustl.catissuecore.domain.AbstractPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES  (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'SpecimenPosition','SpecimenPosition Object','edu.wustl.catissuecore.domain.SpecimenPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'ContainerPosition','ContainerPosition Object','edu.wustl.catissuecore.domain.ContainerPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractPosition'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='SpecimenPosition'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ContainerPosition'),to_date('2008-05-28','yyyy-mm-dd'));


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all SPECIMEN_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD SPECIMEN_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD IS_SPECIMEN number(19,0);
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER, SPECIMEN_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,IDENTIFIER,STORAGE_CONTAINER_IDENTIFIER,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,1 FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ=0 AND ACTIVITY_STATUS IN ('Active','Closed') AND STORAGE_CONTAINER_IDENTIFIER IS NOT NULL AND POSITION_DIMENSION_ONE IS NOT NULL AND POSITION_DIMENSION_TWO IS NOT NULL ;
INSERT INTO CATISSUE_SPECIMEN_POSITION(IDENTIFIER,SPECIMEN_ID,CONTAINER_ID) SELECT IDENTIFIER,SPECIMEN_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN SPECIMEN_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN CONTAINER_ID;

/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all CONTAINER_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD PARENT_CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID number(19,0);

/*insert Storage container*/
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,A.PARENT_CONTAINER_ID,A.IDENTIFIER,A.POSITION_DIMENSION_ONE,A.POSITION_DIMENSION_TWO,0 FROM CATISSUE_CONTAINER A JOIN CATISSUE_STORAGE_CONTAINER B ON A.IDENTIFIER=B.IDENTIFIER WHERE ACTIVITY_STATUS IN ('Active','Closed') AND POSITION_DIMENSION_ONE IS NOT NULL AND POSITION_DIMENSION_TWO IS NOT NULL AND PARENT_CONTAINER_ID IS NOT NULL;
INSERT INTO CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) SELECT IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION WHERE IS_SPECIMEN = 0;

/*insert Specimen array*/
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER,CONTAINER_ID,PARENT_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,A.IDENTIFIER,B.STORAGE_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,2 FROM CATISSUE_CONTAINER A, CATISSUE_SPECIMEN_ARRAY B WHERE A.IDENTIFIER=B.IDENTIFIER AND A.ACTIVITY_STATUS IN ('Active','Closed')AND A.POSITION_DIMENSION_ONE IS NOT NULL AND A.POSITION_DIMENSION_TWO IS NOT NULL AND B.STORAGE_CONTAINER_ID IS NOT NULL;
INSERT INTO CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) SELECT IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION WHERE IS_SPECIMEN = 2;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN IS_SPECIMEN;

/*Distribution Protocol*/
create table CATISSUE_DISTRIBUTION_SPEC_REQ (
   IDENTIFIER number(19,0) NOT NULL ,
   SPECIMEN_CLASS varchar(255) NOT NULL ,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   QUANTITY double precision,
   DISTRIBUTION_PROTOCOL_ID,
   primary key (IDENTIFIER),
   CONSTRAINT FK_DISTRIBUTION_PROTOCOL FOREIGN KEY (DISTRIBUTION_PROTOCOL_ID) REFERENCES CATISSUE_DISTRIBUTION_PROTOCOL
);

create sequence CATISSUE_DIST_SPECIMEN_REQ_SEQ;

INSERT INTO CATISSUE_DISTRIBUTION_SPEC_REQ (IDENTIFIER, SPECIMEN_CLASS,SPECIMEN_TYPE,TISSUE_SITE,PATHOLOGY_STATUS,QUANTITY,DISTRIBUTION_PROTOCOL_ID) 
select CATISSUE_DIST_SPECIMEN_REQ_SEQ.NEXTVAL, sp.SPECIMEN_CLASS, sp.SPECIMEN_TYPE, sp.TISSUE_SITE, sp.PATHOLOGY_STATUS, q.QUANTITY, dsp.DISTRIBUTION_PROTOCOL_ID from CATISSUE_SPECIMEN_REQUIREMENT sp,
CATISSUE_DISTRIBUTION_SPE_REQ dsp, CATISSUE_QUANTITY q where sp.IDENTIFIER=dsp.SPECIMEN_REQUIREMENT_ID and sp.QUANTITY_ID=q.IDENTIFIER;

ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT ADD INITIAL_QUANTITY double precision;

UPDATE CATISSUE_SPECI_ARRAY_CONTENT sac set INITIAL_QUANTITY=(select QUANTITY from CATISSUE_QUANTITY q where sac.INITIAL_QUANTITY_ID=q.IDENTIFIER);

ALTER TABLE CATISSUE_DISTRIBUTION_SPE_REQ DROP CONSTRAINT FKE34A3688BE10F0CE;
ALTER TABLE CATISSUE_DISTRIBUTION_SPE_REQ DROP CONSTRAINT FKE34A36886B1F36E7;
ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT DROP CONSTRAINT FKBEA9D45892AB74B4;

ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT DROP COLUMN INITIAL_QUANTITY_ID;
DROP TABLE CATISSUE_DISTRIBUTION_SPE_REQ;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'DistributionSpecimenRequirement','DistributionSpecimenRequirement Object','edu.wustl.catissuecore.domain.DistributionSpecimenRequirement',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='DistributionSpecimenRequirement'),to_date('2008-05-28','yyyy-mm-dd'));

/** Specimen Model Related Changes **/

CREATE TABLE CATISSUE_ABSTRACT_SPECIMEN
(                                                                                                                 
      IDENTIFIER NUMBER(19,0) NOT NULL,    
      SPECIMEN_CLASS varchar(50) NOT NULL,         
      SPECIMEN_TYPE varchar(50),                                                                                                                
      LINEAGE varchar(50),                                                                                                              
      PATHOLOGICAL_STATUS varchar(50),                                                                                                  
      PARENT_SPECIMEN_ID number(19,0),                                                                                                    
      SPECIMEN_CHARACTERISTICS_ID number(19,0),                                                                                      
      INITIAL_QUANTITY double precision,                                                                                                        
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK1674810456906G39 FOREIGN KEY (SPECIMEN_CHARACTERISTICS_ID) REFERENCES catissue_specimen_char                 
); 

CREATE TABLE CATISSUE_CP_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,         
     STORAGE_TYPE varchar(255) NOT NULL,      
	 COLLECTION_PROTOCOL_EVENT_ID number(19,0),
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
	 CONSTRAINT FK_PARENT_CP_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_SPECIMEN
 ); 

 CREATE TABLE CATISSUE_MOL_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,   
     CONCENTRATION double precision,
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_MOL_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN                
 );
CREATE TABLE CATISSUE_FLUID_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,       
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_FLUID_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN
);
CREATE TABLE CATISSUE_CELL_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,       
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_CELL_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN                
);
CREATE TABLE CATISSUE_TISSUE_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,       
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_TISSUE_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN               
);

CREATE TABLE CATISSUE_MOLECULAR_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,  
     CONCENTRATION double precision,    
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_MOLECULAR_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN             
   );

CREATE TABLE CATISSUE_FLUID_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL ,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_FLUID_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN                
);
CREATE TABLE CATISSUE_CELL_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL ,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_CELL_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN
);
CREATE TABLE CATISSUE_TISSUE_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL ,       
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_TISSUE_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN
);


INSERT INTO CATISSUE_ABSTRACT_SPECIMEN(IDENTIFIER,SPECIMEN_CLASS,SPECIMEN_TYPE,LINEAGE,PATHOLOGICAL_STATUS,PARENT_SPECIMEN_ID,SPECIMEN_CHARACTERISTICS_ID,INITIAL_QUANTITY) SELECT 
IDENTIFIER,SPECIMEN_CLASS,TYPE,LINEAGE,PATHOLOGICAL_STATUS,PARENT_SPECIMEN_ID,SPECIMEN_CHARACTERISTICS_ID,QUANTITY FROM 
CATISSUE_SPECIMEN;

INSERT INTO CATISSUE_CP_REQ_SPECIMEN(IDENTIFIER,STORAGE_TYPE,COLLECTION_PROTOCOL_EVENT_ID) SELECT 
IDENTIFIER,nvl(POSITION_DIMENSION_ONE,'0'),SPECIMEN_COLLECTION_GROUP_ID FROM  CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1;

UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Virtual' where STORAGE_TYPE='0';
UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Auto'  where STORAGE_TYPE='1';
UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Manual' where STORAGE_TYPE='2';

INSERT INTO CATISSUE_MOL_REQ_SPECIMEN(IDENTIFIER,CONCENTRATION) SELECT IDENTIFIER,CONCENTRATION FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Molecular' AND IS_COLL_PROT_REQ = 1;
INSERT INTO CATISSUE_FLUID_REQ_SPECIMEN(IDENTIFIER) SELECT  IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Fluid' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO CATISSUE_CELL_REQ_SPECIMEN(IDENTIFIER) SELECT  IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Cell' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO CATISSUE_TISSUE_REQ_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Tissue' AND  IS_COLL_PROT_REQ = 1;

INSERT INTO CATISSUE_MOLECULAR_SPECIMEN(IDENTIFIER,CONCENTRATION) SELECT IDENTIFIER,CONCENTRATION FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Molecular' AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO CATISSUE_FLUID_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Fluid'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO CATISSUE_CELL_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Cell'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO CATISSUE_TISSUE_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Tissue'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;

alter table CATISSUE_SPECIMEN_EVENT_PARAM DROP CONSTRAINT FK753F33AD60773DB2;
alter table CATISSUE_SPECIMEN_EVENT_PARAM add constraint FK753F33AD60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_ABSTRACT_SPECIMEN (IDENTIFIER);

ALTER TABLE CATISSUE_SPECIMEN DROP CONSTRAINT FK1674810456906F39;
ALTER TABLE CATISSUE_SPECIMEN DROP CONSTRAINT FK16748104B189E99D; 
DROP INDEX INDX_CATISSUE_SPECIMEN_CLASS;
DROP INDEX INDX_CATISSUE_SPECIMEN_TYPE;
DROP INDEX INDX_CATISSUE_SPECIMEN_PATH;
DROP INDEX INDX_CATISSUE_SPECIMEN_CONC;
DROP INDEX INDX_CATISSUE_SPECIMEN_QTY;
DROP INDEX INDX_CATISSUE_SPECIMEN_AVQTY;

DELETE FROM CATISSUE_EXTERNAL_IDENTIFIER WHERE SPECIMEN_ID IN(SELECT identifier FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1);

UPDATE CATISSUE_SPECIMEN set ACTIVITY_STATUS = 'Disabled' where IDENTIFIER IN
(SELECT SPECIMEN_ID FROM CATISSUE_EXISTING_SP_ORD_ITEM WHERE SPECIMEN_ID IN 
(SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1));

UPDATE CATISSUE_SPECIMEN set ACTIVITY_STATUS = 'Disabled' where IDENTIFIER IN
(Select SPECIMEN_ID from CATISSUE_DERIEVED_SP_ORD_ITEM  WHERE SPECIMEN_ID IN 
(SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1));

DELETE FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1 and ACTIVITY_STATUS = 'ACTIVE';

ALTER TABLE CATISSUE_SPECIMEN ADD (REQ_SPECIMEN_ID number(19,0));

ALTER TABLE CATISSUE_SPECIMEN 
DROP( IS_COLL_PROT_REQ , POSITION_DIMENSION_ONE, POSITION_DIMENSION_TWO , 
SPECIMEN_CLASS , STORAGE_CONTAINER_IDENTIFIER , TYPE, LINEAGE, PATHOLOGICAL_STATUS,
PARENT_SPECIMEN_ID, SPECIMEN_CHARACTERISTICS_ID, QUANTITY , CONCENTRATION);

/*Drop columns from existing table */
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN POSITION_DIMENSION_ONE;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP COLUMN STORAGE_CONTAINER_ID;

alter table CATISSUE_SPECIMEN_COLL_GROUP drop constraint FKDEBAF16753B01F66;

UPDATE CATISSUE_SPECIMEN_COLL_GROUP scg SET Collection_Protocol_Event_Id = 
( SELECT Specimen_Coll_req_Group_Id FROM CATISSUE_COLL_PROT_EVENT scrg WHERE 
  scg.Collection_Protocol_Event_Id = scrg.identifier
);

create table CATISSUE_COLL_PROT_EVENT_TMP (
   IDENTIFIER number(19,0) not null ,
   CLINICAL_STATUS varchar(50),
   COLLECTION_POINT_LABEL varchar(255),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID number(19,0),
   primary key (IDENTIFIER),
   unique (COLLECTION_PROTOCOL_ID,COLLECTION_POINT_LABEL),
   CONSTRAINT FK_COLL_PROT_EVENT FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES catissue_collection_protocol,
   CONSTRAINT FK_PARENT_COLL_PROT_EVENT FOREIGN KEY (IDENTIFIER) REFERENCES catissue_abs_speci_coll_group
);

insert into CATISSUE_COLL_PROT_EVENT_TMP(IDENTIFIER,CLINICAL_STATUS,                                                                                                                 
     COLLECTION_POINT_LABEL,STUDY_CALENDAR_EVENT_POINT,                                                                                                           
    COLLECTION_PROTOCOL_ID)
select SPECIMEN_COLL_REQ_GROUP_ID,CLINICAL_STATUS,                                                                                                                 
     COLLECTION_POINT_LABEL,STUDY_CALENDAR_EVENT_POINT,                                                                                                           
    COLLECTION_PROTOCOL_ID from catissue_coll_prot_event;

drop table catissue_coll_prot_event cascade constraints;

alter table CATISSUE_COLL_PROT_EVENT_TMP
rename to
   CATISSUE_COLL_PROT_EVENT;

Alter table CATISSUE_SPECIMEN_COLL_GROUP add constraint FK_CATISSUE_COLL_PROT_EVENT 
FOREIGN KEY(Collection_Protocol_Event_Id) references CATISSUE_COLL_PROT_EVENT(Identifier);

DROP TABLE CATISSUE_SPECI_COLL_REQ_GROUP;

Delete from CSM_PROTECTION_ELEMENT where protection_element_name like
'edu.wustl.catissuecore.domain.SpecimenCollectionRequirementGroup';

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE
'edu.wustl.catissuecore.domain.SpecimenRequirement'; 

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE
'edu.wustl.catissuecore.domain.MolecularSpecimenRequirement'; 

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE
'edu.wustl.catissuecore.domain.FluidSpecimenRequirement'; 

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE
'edu.wustl.catissuecore.domain.CellSpecimenRequirement'; 

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE
'edu.wustl.catissuecore.domain.TissueSpecimenRequirement'; 

INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
values (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'AbstractSpecimen','AbstractSpecimen Object','edu.wustl.catissuecore.domain.AbstractSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'RequirementSpecimen','RequirementSpecimen Object','edu.wustl.catissuecore.domain.SpecimenRequirement',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
values (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'MolReqSpecimen','MolReqSpecimen Object','edu.wustl.catissuecore.domain.MolecularSpecimenRequirement',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) 
VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'FluidReqSpecimen','FluidReqSpecimen Object','edu.wustl.catissuecore.domain.FluidSpecimenRequirement',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
values (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'CellReqSpecimen','CellReqSpecimen Object','edu.wustl.catissuecore.domain.CellSpecimenRequirement',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'TissueReqSpecimen','TissueReqSpecimen Object','edu.wustl.catissuecore.domain.TissueSpecimenRequirement',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));


INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='RequirementSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='MolReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='FluidReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='CellReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='TissueReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));

CREATE INDEX INDX_CATISSUE_SPECIMEN_CLASS ON CATISSUE_ABSTRACT_SPECIMEN (SPECIMEN_CLASS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_TYPE ON CATISSUE_ABSTRACT_SPECIMEN (SPECIMEN_TYPE);
CREATE INDEX INDX_CATISSUE_SPECIMEN_PATH ON CATISSUE_ABSTRACT_SPECIMEN (PATHOLOGICAL_STATUS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_QTY ON CATISSUE_ABSTRACT_SPECIMEN (INITIAL_QUANTITY);
CREATE INDEX INDX_CATISSUE_SPECIMEN_AVQTY ON CATISSUE_SPECIMEN (AVAILABLE_QUANTITY);
CREATE INDEX INDX_MOL_REQ_SPECIMEN_CONC ON CATISSUE_MOL_REQ_SPECIMEN (CONCENTRATION);
CREATE INDEX INDX_MOLECULAR_SPECIMEN_CONC ON CATISSUE_MOLECULAR_SPECIMEN (CONCENTRATION);

Alter table CATISSUE_CP_REQ_SPECIMEN add CONSTRAINT FK_CP_EVENT_ID FOREIGN KEY (COLLECTION_PROTOCOL_EVENT_ID) REFERENCES catissue_coll_prot_event;
Alter table catissue_specimen add CONSTRAINT FK_REQ_SPECIMEN_ID FOREIGN KEY (REQ_SPECIMEN_ID) REFERENCES CATISSUE_CP_REQ_SPECIMEN(IDENTIFIER);
Alter table catissue_specimen add CONSTRAINT FK_PARENT_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_SPECIMEN(IDENTIFIER);


INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
values(93, 'CATISSUE_ABSTRACT_POSITION', 'Abstract Position', 'AbstractPosition',2,NULL);
INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
values(94, 'CATISSUE_SPECIMEN_POSITION', 'Specimen Position', 'SpecimenPosition',2,1);
INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
values(95, 'CATISSUE_CONTAINER_POSITION', 'Container Position', 'ContainerPosition',2,1);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 96, 'catissue_tissue_specimen', 'Tissue Specimen', 'Tissue Specimen',2,NULL);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 97, 'catissue_cell_specimen', 'Cell Specimen', 'Cell Specimen',2,NULL);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 98, 'catissue_fluid_specimen', 'Fluid Specimen', 'Fluid Specimen',2,NULL);

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID,FOR_SQI)
VALUES ( 99, 'catissue_molecular_specimen', 'Molecular Specimen', 'Molecular Specimen',2,NULL);

/*Metadata updation of Simple Query due to model changes*/

UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET TABLE_ID = 92 WHERE IDENTIFIER = 330; 
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER = 331; 

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (331,94,'IDENTIFIER','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (332,94,'SPECIMEN_ID','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (333,94,'CONTAINER_ID','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (334,95,'IDENTIFIER','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (335,95,'CONTAINER_ID','bigint');
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
values (336,93,'IDENTIFIER','bigint');

DELETE from CATISSUE_INTERFACE_COLUMN_DATA where IDENTIFIER = 194;
DELETE from CATISSUE_INTERFACE_COLUMN_DATA where IDENTIFIER = 195;

UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET TABLE_ID = 93 WHERE IDENTIFIER IN (249,250);
UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET table_id = 94 WHERE IDENTIFIER IN (200);
UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET table_id = 95 WHERE IDENTIFIER IN (247);

INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(138,94,93,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(139,95,93,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(140,33,94,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(141,72,95,70);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(142,21,95,70);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(143,94,94,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(144,95,95,NULL);
INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH) 
values(145,21,94,NULL);

INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 93 , 94 , 'IDENTIFIER','IDENTIFIER');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 93 , 95 , 'IDENTIFIER','IDENTIFIER');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 33 , 94 , 'IDENTIFIER','SPECIMEN_ID');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 72 , 95 , 'IDENTIFIER','CONTAINER_ID');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 21 , 94 , 'IDENTIFIER','CONTAINER_ID');
INSERT INTO CATISSUE_RELATED_TABLES_MAP values ( 21 , 95 , 'IDENTIFIER','CONTAINER_ID');

DELETE FROM CATISSUE_RELATED_TABLES_MAP where FIRST_TABLE_ID = 21 AND SECOND_TABLE_ID = 33;

DELETE FROM CATISSUE_SEARCH_DISPLAY_DATA where COL_ID in (194,195);
DELETE FROM CATISSUE_SEARCH_DISPLAY_DATA where COL_ID in (249,250);

INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(138, 249, 'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(138, 250, 'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(139, 249, 'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(139, 250, 'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(34,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(34,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(140,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(140,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(141,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(141,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(142,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(142,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(110,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(110,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(114,249,'Position Dimension One',1,1);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(114,250,'Position Dimension Two',1,2);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(144,247,'Parent Container Id',1,3);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
values(143,333,'Parent Container Id',1,3);


create sequence CATISSUE_RACE_SEQ start with 1 increment by 1;
alter table CATISSUE_RACE add  IDENTIFIER number(19,0);
update  CATISSUE_RACE set IDENTIFIER=CATISSUE_RACE_SEQ.nextval;
alter table CATISSUE_RACE add primary key (IDENTIFIER);

/*Metadata for Specimen due to model changes*/

INSERT INTO CATISSUE_QUERY_TABLE_DATA(TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI)
VALUES(100,'CATISSUE_ABSTRACT_SPECIMEN','Abstract Specimen','AbstractSpecimen',2,NULL);

INSERT INTO CATISSUE_RELATED_TABLES_MAP values(100,33,'IDENTIFIER','IDENTIFIER');

UPDATE CATISSUE_INTERFACE_COLUMN_DATA set TABLE_ID = 100 where IDENTIFIER in (202,199,322,192,102,208,103);

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
VALUES(337,100,'IDENTIFIER','bigint');

INSERT INTO CATISSUE_TABLE_RELATION (RELATIONSHIP_ID, PARENT_TABLE_ID, CHILD_TABLE_ID, TABLES_IN_PATH)
VALUES(146,33,100,NULL);

UPDATE CATISSUE_SEARCH_DISPLAY_DATA set RELATIONSHIP_ID = 146 where RELATIONSHIP_ID = 34 AND COL_ID in (192,208,199,102,103,322);

UPDATE CATISSUE_INTERFACE_COLUMN_DATA set COLUMN_NAME = 'SPECIMEN_TYPE' where IDENTIFIER = 192;
UPDATE CATISSUE_INTERFACE_COLUMN_DATA set COLUMN_NAME = 'INITIAL_QUANTITY' where IDENTIFIER = 103;

DELETE from CATISSUE_INTERFACE_COLUMN_DATA where IDENTIFIER = 105;
DELETE from CATISSUE_SEARCH_DISPLAY_DATA where COL_ID = 105;

UPDATE CATISSUE_RELATED_TABLES_MAP set SECOND_TABLE_ID = 100 where FIRST_TABLE_ID = 34 and SECOND_TABLE_ID = 33;

UPDATE CATISSUE_RELATED_TABLES_MAP set SECOND_TABLE_ID = 100 where FIRST_TABLE_ID = 33 and SECOND_TABLE_ID = 33;
UPDATE CATISSUE_RELATED_TABLES_MAP set FIRST_TABLE_ID = 100 where FIRST_TABLE_ID = 33 and SECOND_TABLE_ID = 100;

/*Removing Quantity table and all data associate with it*/

DELETE from CATISSUE_QUERY_TABLE_DATA where TABLE_ID = 74;

DELETE from CATISSUE_RELATED_TABLES_MAP where FIRST_TABLE_ID = 12 and SECOND_TABLE_ID = 74;

DELETE from CATISSUE_INTERFACE_COLUMN_DATA where TABLE_ID = 74;

DELETE from CATISSUE_TABLE_RELATION where RELATIONSHIP_ID in (119,120);

DELETE from CATISSUE_SEARCH_DISPLAY_DATA where RELATIONSHIP_ID = 120;

ALTER TABLE CATISSUE_SPECIMEN_REQUIREMENT DROP CONSTRAINT FK39AFE96861A1C94F;
DROP table CATISSUE_SPECIMEN_REQUIREMENT;
DROP table CATISSUE_QUANTITY;

/** MSR changes : Start **/

DELETE FROM CSM_PROTECTION_ELEMENT WHERE OBJECT_ID LIKE '%ACTION%';

INSERT INTO CSM_PRIVILEGE VALUES(13,'USER_PROVISIONING','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR USER CREATION AND ASSIGNING PRIVILEGES TO THAT USER',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(14,'REPOSITORY_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT SITES',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(15,'STORAGE_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT STORAGE TYPES AND CONTAINERS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(16,'PROTOCOL_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT COLLECTION AS WELL AS DISTRIBUTION PROTOCOLS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(17,'DEFINE_ANNOTATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT ANNOTATIONS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(18,'REGISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR REGISTERING PARTICIPANT AND CONSENTS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(20,'SPECIMEN_ACCESSION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT SPECIMEN,SPECIMEN COLLECTION GROUP AND CONSENTS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(21,'DISTRIBUTION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR DISTRIBUTION',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(22,'QUERY','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR QUERY',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(23,'PHI_ACCESS','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR VIEWING PHI DATA',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(24,'PARTICIPANT_SCG_ANNOTATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT ANNOTATION TO PARTICIPANT OR SCG',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(25,'SPECIMEN_ANNOTATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR FOR ADD EDIT SPECIMEN ANNOTATION',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(26,'SPECIMEN_PROCESSING','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT ALIQUOT, DERIVATIVE, EVENTS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(27,'SPECIMEN_STORAGE','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT STORAGE AND TRANSFER EVENTS',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(28,'GENERAL_SITE_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT SITES',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(29,'GENERAL_ADMINISTRATION','THIS PRIVILEGE GRANTS PERMISSION TO A USER FOR ADD EDIT DEPARTMENT,INSTITUTION,CANCER RESEARCH GROUP',TO_DATE('2008-06-19','YYYY-MM-DD'));
INSERT INTO CSM_PRIVILEGE VALUES(30,'SHIPMENT_PROCESSING','THIS PRIVILEGE GRANTS PERMISSION TO A USER TO PROCESS SHIPMENTS',TO_DATE('2008-08-20','YYYY-MM-DD'));

INSERT INTO CSM_ROLE VALUES(13,'SUPERADMINISTRATOR','SUPER ADMINISTRATOR ROLE',1,0,TO_DATE('2008-06-19','YYYY-MM-DD'));

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,13,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,17,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,14,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,15,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,16,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,18,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,20,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,21,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,22,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,23,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,24,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,25,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,26,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,27,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,28,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,13,29,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,13,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,14,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,15,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,16,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,18,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,20,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,21,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,22,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,23,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,24,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,25,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,26,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,27,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,28,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,18,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,20,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,21,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,22,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,23,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,24,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,25,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,26,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,27,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,21,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,22,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,25,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,26,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,3,27,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,7,22,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

CREATE TABLE CATISSUE_SITE_USERS (
   SITE_ID NUMBER(19,0) ,
   USER_ID NUMBER(19,0) ,
   PRIMARY KEY (SITE_ID, USER_ID)
);

CREATE TABLE CATISSUE_SITE_CP(
   SITE_ID NUMBER(19,0) ,
   COLLECTION_PROTOCOL_ID NUMBER(19,0) ,
   PRIMARY KEY (SITE_ID,COLLECTION_PROTOCOL_ID)
 );

CREATE TABLE CATISSUE_USER_CP(
  USER_ID NUMBER(19,0) ,
  COLLECTION_PROTOCOL_ID NUMBER(19,0) ,
  PRIMARY KEY (USER_ID,COLLECTION_PROTOCOL_ID)
 );

ALTER TABLE CATISSUE_SITE_USERS ADD CONSTRAINT FK1 FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_USERS ADD CONSTRAINT FK2 FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);

ALTER TABLE CATISSUE_SITE_CP ADD CONSTRAINT FK3 FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_CP ADD CONSTRAINT FK4 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

ALTER TABLE CATISSUE_USER_CP ADD CONSTRAINT FK5 FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_USER_CP ADD CONSTRAINT FK6 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'ADMIN_PROTECTION_ELEMENT','ADMIN_PROTECTION_ELEMENT Object','ADMIN_PROTECTION_ELEMENT',NULL,NULL,1,to_date('2008-07-22','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ADMIN_PROTECTION_ELEMENT'),to_date('2008-07-22','yyyy-mm-dd'));
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,29,TO_DATE('2008-07-22','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,5,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,6,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,7,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,4,23,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,5,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,6,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,7,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,11,23,TO_DATE('2008-06-19','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,1,30,TO_DATE('2008-08-20','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(ROLE_PRIVILEGE_ID)+1,2,30,TO_DATE('2008-08-20','YYYY-MM-DD') FROM CSM_ROLE_PRIVILEGE;

/** MSR changes : End **/

INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5013,'Distributed And Close',NULL,'4285');
/** Barcode related changes  start **/
ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP ADD BARCODE varchar(255) unique;
ALTER TABLE CATISSUE_COLL_PROT_REG ADD BARCODE varchar(255) unique;

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
VALUES (338,35,'BARCODE','varchar');
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
VALUES(30,338,'Barcode',0,2);

INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA(IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE )
VALUES (339,27,'BARCODE','varchar');
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER)
VALUES(29,339,'Barcode',0,8);
/** Barcode related changes  end **/

/** Encounter Timestamp **/
ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP ADD ENCOUNTER_TIMESTAMP date;

ALTER TABLE CATISSUE_CP_REQ_SPECIMEN ADD LABELFORMAT varchar(255) default NULL;

update catissue_query_table_data set TABLE_NAME='CATISSUE_DISTRIBUTION_SPEC_REQ' where table_name='CATISSUE_DISTRIBUTION_SPE_REQ';

delete from catissue_interface_column_data where TABLE_ID=20 AND COLUMN_NAME='SPECIMEN_REQUIREMENT_ID';

INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(340,20,'SPECIMEN_TYPE','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(341,20,'SPECIMEN_CLASS','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(342,20,'TISSUE_SITE','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(343,20,'PATHOLOGY_STATUS','varchar');
INSERT INTO catissue_interface_column_data( IDENTIFIER, TABLE_ID, COLUMN_NAME , ATTRIBUTE_TYPE ) VALUES(344,20,'QUANTITY','double');

DELETE FROM CATISSUE_TABLE_RELATION WHERE RELATIONSHIP_ID=20;

DELETE FROM catissue_related_tables_map WHERE FIRST_TABLE_ID=12 AND SECOND_TABLE_ID=20;

INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,340,'Specimen Type',12);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,341,'Specimen Class',13);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,342,'Tissue Site',14);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,343,'Pathology status',15);
INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA(RELATIONSHIP_ID, COL_ID, DISPLAY_NAME,ATTRIBUTE_ORDER) VALUES(19,344,'Quantity',16);


/* for bug : 9303*/
UPDATE CATISSUE_SPECIMEN_PROTOCOL SET ENROLLMENT = '0' where ENROLLMENT is null;

/**Resolved Bug# 7862 **/
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5014,'CPT',NULL,'2003997');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5015,'Paxgene',NULL,'2003997');

/* to remove unnecessary protection elements */
delete  
FROM csm_protection_element
WHERE regexp_like(object_id,   '_[[:digit:]]')
   AND NOT regexp_like(object_id,   'Site_[[:digit:]]')
   AND NOT regexp_like(object_id,   'CollectionProtocol_[[:digit:]]')
   AND NOT regexp_like(object_id,   'User_[[:digit:]]')
   AND NOT regexp_like(object_id,   'StorageContainer_[[:digit:]]');


/** To resolve bug #9654 **/
UPDATE CATISSUE_TABLE_RELATION SET CHILD_TABLE_ID=100 WHERE RELATIONSHIP_ID=52;
UPDATE CATISSUE_SEARCH_DISPLAY_DATA SET COL_ID=337 WHERE RELATIONSHIP_ID=52 AND COL_ID=191;