/*Create table and constraints*/
create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER number(19,0) NOT NULL,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER,
	primary key (IDENTIFIER)
);

create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER number(19,0) NOT NULL,
	SPECIMEN_ID number(19,0),
	CONTAINER_ID number(19,0),
	primary key (IDENTIFIER),
	CONSTRAINT FK_SPECIMEN_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_SPECIMEN FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN,
	CONSTRAINT FK_STORAGE_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_STORAGE_CONTAINER
);

create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER number(19,0) NOT NULL,
	PARENT_CONTAINER_ID number(19,0),
	CONTAINER_ID number(19,0),
	primary key (IDENTIFIER),
	CONSTRAINT FK_CONTAINER_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_CONTAINER,
	CONSTRAINT FK_OCCUPIED_CONTAINER FOREIGN KEY (PARENT_CONTAINER_ID) REFERENCES CATISSUE_CONTAINER
);

create sequence CATISSUE_ABS_POSITION_SEQ;

INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'AbstractPosition','AbstractPosition Object','edu.wustl.catissuecore.domain.AbstractPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES  (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'SpecimenPosition','SpecimenPosition Object','edu.wustl.catissuecore.domain.SpecimenPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'ContainerPosition','ContainerPosition Object','edu.wustl.catissuecore.domain.ContainerPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractPosition'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='SpecimenPosition'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ContainerPosition'),to_date('2008-05-28','yyyy-mm-dd'));


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all SPECIMEN_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD SPECIMEN_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD IS_SPECIMEN number(19,0);
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER, SPECIMEN_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,IDENTIFIER,STORAGE_CONTAINER_IDENTIFIER,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,1 FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ=0 AND ACTIVITY_STATUS IN ('Active','Closed') AND STORAGE_CONTAINER_IDENTIFIER IS NOT NULL AND POSITION_DIMENSION_ONE IS NOT NULL AND POSITION_DIMENSION_TWO IS NOT NULL ;
INSERT INTO CATISSUE_SPECIMEN_POSITION(IDENTIFIER,SPECIMEN_ID,CONTAINER_ID) SELECT IDENTIFIER,SPECIMEN_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN SPECIMEN_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN CONTAINER_ID;

/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all CONTAINER_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD PARENT_CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID number(19,0);

/*insert Storage container*/
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,A.PARENT_CONTAINER_ID,A.IDENTIFIER,A.POSITION_DIMENSION_ONE,A.POSITION_DIMENSION_TWO,0 FROM CATISSUE_CONTAINER A JOIN CATISSUE_STORAGE_CONTAINER B ON A.IDENTIFIER=B.IDENTIFIER WHERE ACTIVITY_STATUS IN ('Active','Closed') AND POSITION_DIMENSION_ONE IS NOT NULL AND POSITION_DIMENSION_TWO IS NOT NULL AND PARENT_CONTAINER_ID IS NOT NULL;
INSERT INTO CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) SELECT IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION WHERE IS_SPECIMEN = 0;

/*insert Specimen array*/
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER,CONTAINER_ID,PARENT_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,A.IDENTIFIER,B.STORAGE_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,2 FROM CATISSUE_CONTAINER A, CATISSUE_SPECIMEN_ARRAY B WHERE A.IDENTIFIER=B.IDENTIFIER AND A.ACTIVITY_STATUS IN ('Active','Closed')AND A.POSITION_DIMENSION_ONE IS NOT NULL AND A.POSITION_DIMENSION_TWO IS NOT NULL AND B.STORAGE_CONTAINER_ID IS NOT NULL;
INSERT INTO CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) SELECT IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION WHERE IS_SPECIMEN = 2;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN IS_SPECIMEN;

/*Drop columns from existing table */
ALTER TABLE CATISSUE_SPECIMEN DROP COLUMN POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_SPECIMEN DROP COLUMN STORAGE_CONTAINER_IDENTIFIER;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN POSITION_DIMENSION_ONE;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP COLUMN STORAGE_CONTAINER_ID;

/**Added a workaround so that edit of Container,specimen should work. NEED TO REMOVE **/
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_SPECIMEN ADD STORAGE_CONTAINER_IDENTIFIER number(19,0);
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_CONTAINER ADD PARENT_CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_SPECIMEN_ARRAY ADD STORAGE_CONTAINER_ID number(19,0);