/* Adding WUSTLKey column in CATISSUE_USER table */
ALTER TABLE CATISSUE_USER ADD WUSTLKEY varchar2(100) UNIQUE;

/**  Bug 13225 -  Clinical Diagnosis subset at CP definition level 
 */
create table CATISSUE_CLINICAL_DIAGNOSIS (
   IDENTIFIER number(19,0) not null ,
   CLINICAL_DIAGNOSIS varchar(255),
   COLLECTION_PROTOCOL_ID number(19,0),
   primary key (IDENTIFIER),
   CONSTRAINT FK_CD_COLPROT FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL
);
create sequence CATISSUE_CLINICAL_DIAG_SEQ;

/*Bulk Operations from UI*/
CREATE SEQUENCE CATISSUE_BULK_OPERATION_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
create table catissue_bulk_operation 
(
	IDENTIFIER number(19,0) not null,
	OPERATION VARCHAR(255) not null unique,
	CSV_TEMPLATE VARCHAR(500) not null,
	XML_TEMPALTE VARCHAR(1000) not null,
	DROPDOWN_NAME VARCHAR(100) not null unique,
	CONSTRAINT CATISSUE_BULK_OPERATION_SEQ PRIMARY KEY (IDENTIFIER)
);
commit;