/*Create table and constraints*/
create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER number(19,0) NOT NULL,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER,
	primary key (IDENTIFIER)
);

create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER number(19,0) NOT NULL,
	SPECIMEN_ID number(19,0),
	CONTAINER_ID number(19,0),
	primary key (IDENTIFIER),
	CONSTRAINT FK_SPECIMEN_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_SPECIMEN FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN,
	CONSTRAINT FK_STORAGE_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_STORAGE_CONTAINER
);

create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER number(19,0) NOT NULL,
	PARENT_CONTAINER_ID number(19,0),
	CONTAINER_ID number(19,0),
	primary key (IDENTIFIER),
	CONSTRAINT FK_CONTAINER_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_CONTAINER,
	CONSTRAINT FK_OCCUPIED_CONTAINER FOREIGN KEY (PARENT_CONTAINER_ID) REFERENCES CATISSUE_CONTAINER
);

create sequence CATISSUE_ABS_POSITION_SEQ;

INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'AbstractPosition','AbstractPosition Object','edu.wustl.catissuecore.domain.AbstractPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES  (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'SpecimenPosition','SpecimenPosition Object','edu.wustl.catissuecore.domain.SpecimenPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'ContainerPosition','ContainerPosition Object','edu.wustl.catissuecore.domain.ContainerPosition',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractPosition'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='SpecimenPosition'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='ContainerPosition'),to_date('2008-05-28','yyyy-mm-dd'));


/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all SPECIMEN_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD SPECIMEN_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD IS_SPECIMEN number(19,0);
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER, SPECIMEN_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,IDENTIFIER,STORAGE_CONTAINER_IDENTIFIER,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,1 FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ=0 AND ACTIVITY_STATUS IN ('Active','Closed') AND STORAGE_CONTAINER_IDENTIFIER IS NOT NULL AND POSITION_DIMENSION_ONE IS NOT NULL AND POSITION_DIMENSION_TWO IS NOT NULL ;
INSERT INTO CATISSUE_SPECIMEN_POSITION(IDENTIFIER,SPECIMEN_ID,CONTAINER_ID) SELECT IDENTIFIER,SPECIMEN_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN SPECIMEN_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN CONTAINER_ID;

/*Temperory modify CATISSUE_ABSTRACT_POSITION to capture all CONTAINER_POSITION DATA*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD PARENT_CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_ABSTRACT_POSITION ADD CONTAINER_ID number(19,0);

/*insert Storage container*/
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,A.PARENT_CONTAINER_ID,A.IDENTIFIER,A.POSITION_DIMENSION_ONE,A.POSITION_DIMENSION_TWO,0 FROM CATISSUE_CONTAINER A JOIN CATISSUE_STORAGE_CONTAINER B ON A.IDENTIFIER=B.IDENTIFIER WHERE ACTIVITY_STATUS IN ('Active','Closed') AND POSITION_DIMENSION_ONE IS NOT NULL AND POSITION_DIMENSION_TWO IS NOT NULL AND PARENT_CONTAINER_ID IS NOT NULL;
INSERT INTO CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) SELECT IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION WHERE IS_SPECIMEN = 0;

/*insert Specimen array*/
INSERT INTO CATISSUE_ABSTRACT_POSITION(IDENTIFIER,CONTAINER_ID,PARENT_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,IS_SPECIMEN) SELECT CATISSUE_ABS_POSITION_SEQ.NEXTVAL,A.IDENTIFIER,B.STORAGE_CONTAINER_ID,POSITION_DIMENSION_ONE,POSITION_DIMENSION_TWO,2 FROM CATISSUE_CONTAINER A, CATISSUE_SPECIMEN_ARRAY B WHERE A.IDENTIFIER=B.IDENTIFIER AND A.ACTIVITY_STATUS IN ('Active','Closed')AND A.POSITION_DIMENSION_ONE IS NOT NULL AND A.POSITION_DIMENSION_TWO IS NOT NULL AND B.STORAGE_CONTAINER_ID IS NOT NULL;
INSERT INTO CATISSUE_CONTAINER_POSITION(IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID) SELECT IDENTIFIER,PARENT_CONTAINER_ID,CONTAINER_ID FROM CATISSUE_ABSTRACT_POSITION WHERE IS_SPECIMEN = 2;

/* drop Temperory columns from CATISSUE_ABSTRACT_POSITION*/
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN CONTAINER_ID;
ALTER TABLE CATISSUE_ABSTRACT_POSITION DROP COLUMN IS_SPECIMEN;

/*Drop columns from existing table */
ALTER TABLE CATISSUE_SPECIMEN DROP COLUMN POSITION_DIMENSION_ONE;
ALTER TABLE CATISSUE_SPECIMEN DROP COLUMN POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_SPECIMEN DROP COLUMN STORAGE_CONTAINER_IDENTIFIER;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN POSITION_DIMENSION_ONE;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN POSITION_DIMENSION_TWO;
ALTER TABLE CATISSUE_CONTAINER DROP COLUMN PARENT_CONTAINER_ID;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY DROP COLUMN STORAGE_CONTAINER_ID;

/**Added a workaround so that edit of Container,specimen should work. NEED TO REMOVE **/
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_SPECIMEN ADD STORAGE_CONTAINER_IDENTIFIER number(19,0);
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_CONTAINER ADD PARENT_CONTAINER_ID number(19,0);
ALTER TABLE CATISSUE_SPECIMEN_ARRAY ADD STORAGE_CONTAINER_ID number(19,0);


/** Specimen Model Related Changes **/

CREATE TABLE CATISSUE_ABSTRACT_SPECIMEN
(                                                                                                                 
      IDENTIFIER NUMBER(19,0) NOT NULL,    
      SPECIMEN_CLASS varchar(50) NOT NULL,         
      SPECIMEN_TYPE varchar(50),                                                                                                                
      LINEAGE varchar(50),                                                                                                              
      PATHOLOGICAL_STATUS varchar(50),                                                                                                  
      PARENT_SPECIMEN_ID number(19,0),                                                                                                    
      SPECIMEN_CHARACTERISTICS_ID number(19,0),                                                                                      
      INITIAL_QUANTITY double precision,                                                                                                        
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK1674810456906G39 FOREIGN KEY (SPECIMEN_CHARACTERISTICS_ID) REFERENCES catissue_specimen_char                 
); 

CREATE TABLE CATISSUE_CP_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,         
     STORAGE_TYPE varchar(255) NOT NULL,      
	 COLLECTION_PROTOCOL_EVENT_ID number(19,0),
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
	 CONSTRAINT FK_PARENT_CP_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_SPECIMEN
 ); 

 CREATE TABLE CATISSUE_MOL_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,   
     CONCENTRATION double precision,
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_MOL_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN                
 );
CREATE TABLE CATISSUE_FLUID_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,       
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_FLUID_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN
);
CREATE TABLE CATISSUE_CELL_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_CELL_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN                
);
CREATE TABLE CATISSUE_TISSUE_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_TISSUE_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN               
);

CREATE TABLE CATISSUE_MOLECULAR_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL,  
     CONCENTRATION double precision,    
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_MOLECULAR_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN             
   );

CREATE TABLE CATISSUE_FLUID_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL ,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_FLUID_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN                
);
CREATE TABLE CATISSUE_CELL_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL ,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_CELL_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN
);
CREATE TABLE CATISSUE_TISSUE_SPECIMEN
(                                                                                                                 
     IDENTIFIER NUMBER(19,0) NOT NULL ,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_TISSUE_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN
);


INSERT INTO CATISSUE_ABSTRACT_SPECIMEN(IDENTIFIER,SPECIMEN_CLASS,SPECIMEN_TYPE,LINEAGE,PATHOLOGICAL_STATUS,PARENT_SPECIMEN_ID,SPECIMEN_CHARACTERISTICS_ID,INITIAL_QUANTITY) SELECT 
IDENTIFIER,SPECIMEN_CLASS,TYPE,LINEAGE,PATHOLOGICAL_STATUS,PARENT_SPECIMEN_ID,SPECIMEN_CHARACTERISTICS_ID,QUANTITY FROM 
CATISSUE_SPECIMEN;

INSERT INTO CATISSUE_CP_REQ_SPECIMEN(IDENTIFIER,STORAGE_TYPE,COLLECTION_PROTOCOL_EVENT_ID) SELECT 
IDENTIFIER,nvl(POSITION_DIMENSION_ONE,'0'),SPECIMEN_COLLECTION_GROUP_ID FROM  CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1;

UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Virtual' where STORAGE_TYPE='0';
UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Auto'  where STORAGE_TYPE='1';
UPDATE CATISSUE_CP_REQ_SPECIMEN SET STORAGE_TYPE = 'Manual' where STORAGE_TYPE='2';

INSERT INTO CATISSUE_MOL_REQ_SPECIMEN(IDENTIFIER,CONCENTRATION) SELECT IDENTIFIER,CONCENTRATION FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Molecular' AND IS_COLL_PROT_REQ = 1;
INSERT INTO CATISSUE_FLUID_REQ_SPECIMEN(IDENTIFIER) SELECT  IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Fluid' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO CATISSUE_CELL_REQ_SPECIMEN(IDENTIFIER) SELECT  IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Cell' AND  IS_COLL_PROT_REQ = 1;
INSERT INTO CATISSUE_TISSUE_REQ_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Tissue' AND  IS_COLL_PROT_REQ = 1;

INSERT INTO CATISSUE_MOLECULAR_SPECIMEN(IDENTIFIER,CONCENTRATION) SELECT IDENTIFIER,CONCENTRATION FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Molecular' AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO CATISSUE_FLUID_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Fluid'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO CATISSUE_CELL_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Cell'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;
INSERT INTO CATISSUE_TISSUE_SPECIMEN(IDENTIFIER) SELECT IDENTIFIER FROM CATISSUE_SPECIMEN WHERE SPECIMEN_CLASS='Tissue'  AND  (IS_COLL_PROT_REQ IS NULL OR IS_COLL_PROT_REQ =0) ;

alter table CATISSUE_SPECIMEN_EVENT_PARAM DROP CONSTRAINT FK753F33AD60773DB2;
alter table CATISSUE_SPECIMEN_EVENT_PARAM add constraint FK753F33AD60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_ABSTRACT_SPECIMEN (IDENTIFIER);

ALTER TABLE CATISSUE_SPECIMEN DROP CONSTRAINT FK1674810456906F39;
ALTER TABLE CATISSUE_SPECIMEN DROP CONSTRAINT FK16748104B189E99D; 
DROP INDEX INDX_CATISSUE_SPECIMEN_CLASS;
DROP INDEX INDX_CATISSUE_SPECIMEN_TYPE;
DROP INDEX INDX_CATISSUE_SPECIMEN_PATH;
DROP INDEX INDX_CATISSUE_SPECIMEN_CONC;
DROP INDEX INDX_CATISSUE_SPECIMEN_QTY;
DROP INDEX INDX_CATISSUE_SPECIMEN_AVQTY;

DELETE FROM  CATISSUE_EXTERNAL_IDENTIFIER WHERE SPECIMEN_ID IN(SELECT identifier FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1);
DELETE FROM CATISSUE_SPECIMEN WHERE IS_COLL_PROT_REQ = 1;


ALTER TABLE CATISSUE_SPECIMEN ADD (REQ_SPECIMEN_ID number(19,0));

ALTER TABLE CATISSUE_SPECIMEN 
DROP( IS_COLL_PROT_REQ , POSITION_DIMENSION_ONE, POSITION_DIMENSION_TWO , 
SPECIMEN_CLASS , STORAGE_CONTAINER_IDENTIFIER , TYPE, LINEAGE, PATHOLOGICAL_STATUS,
PARENT_SPECIMEN_ID, SPECIMEN_CHARACTERISTICS_ID, QUANTITY , CONCENTRATION);

alter table CATISSUE_SPECIMEN_COLL_GROUP drop constraint FK_CATISSUE_COLL_PROT_EVENT;

UPDATE CATISSUE_SPECIMEN_COLL_GROUP scg SET Collection_Protocol_Event_Id = 
( SELECT Specimen_Coll_req_Group_Id FROM CATISSUE_COLL_PROT_EVENT scrg WHERE 
  scg.Collection_Protocol_Event_Id = scrg.identifier
);

create table CATISSUE_COLL_PROT_EVENT_TMP (
   IDENTIFIER number(19,0) not null ,
   CLINICAL_STATUS varchar(50),
   COLLECTION_POINT_LABEL varchar(255),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID number(19,0),
   primary key (IDENTIFIER),
   unique (COLLECTION_PROTOCOL_ID,COLLECTION_POINT_LABEL),
   CONSTRAINT FK_COLL_PROT_EVENT FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES catissue_collection_protocol,
   CONSTRAINT FK_PARENT_COLL_PROT_EVENT FOREIGN KEY (IDENTIFIER) REFERENCES catissue_abs_speci_coll_group
);

insert into CATISSUE_COLL_PROT_EVENT_TMP(IDENTIFIER,CLINICAL_STATUS,                                                                                                                 
     COLLECTION_POINT_LABEL,STUDY_CALENDAR_EVENT_POINT,                                                                                                           
    COLLECTION_PROTOCOL_ID)
select SPECIMEN_COLL_REQ_GROUP_ID,CLINICAL_STATUS,                                                                                                                 
     COLLECTION_POINT_LABEL,STUDY_CALENDAR_EVENT_POINT,                                                                                                           
    COLLECTION_PROTOCOL_ID from catissue_coll_prot_event;

drop table catissue_coll_prot_event cascade constraints;

alter table CATISSUE_COLL_PROT_EVENT_TMP
rename to
   CATISSUE_COLL_PROT_EVENT;

Alter table CATISSUE_SPECIMEN_COLL_GROUP add constraint FK_CATISSUE_COLL_PROT_EVENT 
FOREIGN KEY(Collection_Protocol_Event_Id) references CATISSUE_COLL_PROT_EVENT(Identifier);

DROP TABLE CATISSUE_SPECI_COLL_REQ_GROUP;
ALTER TABLE CATISSUE_ABS_SPECI_COLL_GROUP  ADD( NAME  varchar(255) DEFAULT NULL);
ALTER TABLE CATISSUE_ABS_SPECI_COLL_GROUP  ADD Constraint name_unique UNIQUE (NAME);

Update CATISSUE_ABS_SPECI_COLL_GROUP ascg 
Set NAME =(
Select name from CATISSUE_SPECIMEN_COLL_GROUP scg
where ascg.identifier = scg.identifier );

ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP DROP COLUMN NAME;


Delete from CSM_PROTECTION_ELEMENT where protection_element_name like
'edu.wustl.catissuecore.domain.SpecimenCollectionRequirementGroup';

create sequence CATISSUE_ABSTRACT_SPECIMEN_SEQ;
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
values (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'AbstractSpecimen','AbstractSpecimen Object','edu.wustl.catissuecore.domain.AbstractSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'RequirementSpecimen','RequirementSpecimen Object','edu.wustl.catissuecore.domain.RequirementSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
values (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'MolReqSpecimen','MolReqSpecimen Object','edu.wustl.catissuecore.domain.MolecularRequirementSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) 
VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'FluidReqSpecimen','FluidReqSpecimen Object','edu.wustl.catissuecore.domain.FluidRequirementSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
values (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'CellReqSpecimen','CellReqSpecimen Object','edu.wustl.catissuecore.domain.CellRequirementSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));
INSERT into CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
VALUES (CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'TissueReqSpecimen','TissueReqSpecimen Object','edu.wustl.catissuecore.domain.TissueRequirementSpecimen',NULL,NULL,1,to_date('2008-05-28','yyyy-mm-dd'));


INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='AbstractSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='RequirementSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='MolReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='FluidReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='CellReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));
INSERT INTO CSM_PG_PE VALUES (CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(select PROTECTION_ELEMENT_ID from csm_protection_element where PROTECTION_ELEMENT_NAME='TissueReqSpecimen'),to_date('2008-05-28','yyyy-mm-dd'));

CREATE INDEX INDX_CATISSUE_SPECIMEN_CLASS ON CATISSUE_ABSTRACT_SPECIMEN (SPECIMEN_CLASS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_TYPE ON CATISSUE_ABSTRACT_SPECIMEN (SPECIMEN_TYPE);
CREATE INDEX INDX_CATISSUE_SPECIMEN_PATH ON CATISSUE_ABSTRACT_SPECIMEN (PATHOLOGICAL_STATUS);
CREATE INDEX INDX_CATISSUE_SPECIMEN_QTY ON CATISSUE_ABSTRACT_SPECIMEN (INITIAL_QUANTITY);
CREATE INDEX INDX_CATISSUE_SPECIMEN_AVQTY ON CATISSUE_SPECIMEN (AVAILABLE_QUANTITY);
CREATE INDEX INDX_MOL_REQ_SPECIMEN_CONC ON CATISSUE_MOL_REQ_SPECIMEN (CONCENTRATION);
CREATE INDEX INDX_MOLECULAR_SPECIMEN_CONC ON CATISSUE_MOLECULAR_SPECIMEN (CONCENTRATION);

Alter table CATISSUE_CP_REQ_SPECIMEN add CONSTRAINT FK_CP_EVENT_ID FOREIGN KEY (COLLECTION_PROTOCOL_EVENT_ID) REFERENCES catissue_coll_prot_event;
Alter table catissue_specimen add CONSTRAINT FK_REQ_SPECIMEN_ID FOREIGN KEY (REQ_SPECIMEN_ID) REFERENCES CATISSUE_CP_REQ_SPECIMEN(IDENTIFIER);
Alter table catissue_specimen add CONSTRAINT FK_PARENT_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_SPECIMEN(IDENTIFIER);