alter table CATISSUE_SPECIMEN_PROTOCOL add (GENERATE_LABEL number(1,0) default 0);
alter table CATISSUE_SPECIMEN_PROTOCOL add (LABEL_FORMAT varchar(255) default null);
alter table CATISSUE_CP_REQ_SPECIMEN add (GENERATE_LABEL number(1,0) default 0);

CREATE INDEX INDX_COLL_PROT_ID ON CATISSUE_COLL_PROT_REG (COLLECTION_PROTOCOL_ID);

CREATE TABLE KEY_SEQ_GENERATOR
   (	IDENTIFIER NUMBER(19,0) NOT NULL ENABLE,
	KEY_VALUE VARCHAR2(50 BYTE) NOT NULL ENABLE,
	KEY_SEQUENCE_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
	KEY_TYPE VARCHAR2(255 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY (IDENTIFIER)
	 );
create sequence KEY_GENERATOR_SEQ;
CREATE INDEX KEY_SEQ_GENERATOR_INDEX ON KEY_SEQ_GENERATOR (KEY_VALUE);
CREATE INDEX KEY_GENERATOR_KEY_TYPE_INDEX ON KEY_SEQ_GENERATOR (KEY_TYPE);