-- Ordering system  related alter table script*/

create sequence CATISSUE_ORDER_SEQ;
create sequence CATISSUE_ORDER_ITEM_SEQ;

create table CATISSUE_PATH_CASE_ORDER_ITEM (
   IDENTIFIER number(19,0) not null,
   PATHOLOGICAL_STATUS varchar(255),
   TISSUE_SITE varchar(255),
   SPECIMEN_COLL_GROUP_ID number(19,0),
   primary key (IDENTIFIER)
);

create table CATISSUE_DERIEVED_SP_ORD_ITEM (
   IDENTIFIER number(19,0) not null,
   SPECIMEN_ID number(19,0),
   primary key (IDENTIFIER)
);


create table CATISSUE_NEW_SPEC_ORD_ITEM (
   IDENTIFIER number(19,0) not null,
   SPECIMEN_CLASS varchar(255),
   SPECIMEN_TYPE varchar(255),
   primary key (IDENTIFIER)
);

create table CATISSUE_EXISTING_SP_ORD_ITEM (
   IDENTIFIER number(19,0) not null,
   SPECIMEN_ID number(19,0),
   primary key (IDENTIFIER)
);

create table CATISSUE_SPECIMEN_ORDER_ITEM (
   IDENTIFIER number(19,0) not null,
   ARRAY_ORDER_ITEM_ID number(19,0),
   primary key (IDENTIFIER)
);

create table CATISSUE_EXIST_SP_AR_ORD_ITEM (
   IDENTIFIER number(19,0) not null,
   SPECIMEN_ARRAY_ID number(19,0),
   primary key (IDENTIFIER)
);

create table CATISSUE_NEW_SP_AR_ORDER_ITEM (
   IDENTIFIER number(19,0) not null,
   ARRAY_TYPE_ID number(19,0),
   NAME varchar(255),
   SPECIMEN_ARRAY_ID number(19,0),
   primary key (IDENTIFIER)
);

create table CATISSUE_SP_ARRAY_ORDER_ITEM (
   IDENTIFIER number(19,0) not null,
   primary key (IDENTIFIER)
);

create table CATISSUE_ORDER_ITEM (
   IDENTIFIER number(19,0) not null,
   DESCRIPTION varchar2(500),
   DISTRIBUTED_ITEM_ID number(19,0),
   STATUS varchar(50),
   REQUESTED_QUANTITY double precision,
   ORDER_ID number(19,0),
   primary key (IDENTIFIER)
);

create table CATISSUE_ORDER (
   IDENTIFIER number(19,0) not null,
   COMMENTS varchar2(500),
   DISTRIBUTION_PROTOCOL_ID number(19,0),
   NAME varchar2(500),
   REQUESTED_DATE date,
   STATUS varchar(50),
   primary key (IDENTIFIER)
);


/* extra for catissue_distribution */
 alter table catissue_distribution add ORDER_ID number(19,0);
 alter table catissue_distributed_item add  SPECIMEN_ARRAY_ID number(19,0);    
/* extra finished */

alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint FKBD5029D5F69249F7 foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint FKBD5029D5BC7298A9 foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);

alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint FK3742152BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);
alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint FK3742152B60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

alter table CATISSUE_NEW_SPEC_ORD_ITEM add constraint FK_NW_SPEC_ODR_ITM foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint FKF8B855EEBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint FKF8B855EE60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint FK48C3B39FBC7298A9 foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint FK48C3B39F83505A30 foreign key (ARRAY_ORDER_ITEM_ID) references CATISSUE_NEW_SP_AR_ORDER_ITEM (IDENTIFIER);


alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint FKE3823170BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint FKE3823170C4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FKC5C92CCBCE5FBC3A foreign key (ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FKC5C92CCBBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FKC5C92CCBC4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

alter table CATISSUE_SP_ARRAY_ORDER_ITEM add constraint FK_SP_ARAY_ODR_ITM foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_ORDER_ITEM add constraint FKB501E88060975C0B foreign key (DISTRIBUTED_ITEM_ID) references CATISSUE_DISTRIBUTED_ITEM (IDENTIFIER);
alter table CATISSUE_ORDER_ITEM add constraint FKB501E880783867CC foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_ORDER add constraint FK543F22B26B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);

alter table CATISSUE_DISTRIBUTION add constraint FK54276680783867CC foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add constraint FKA7C3ED4BC4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY;


-- csm_inserData_Oracle.sql */
-------Ordering System------*/
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Order','Order Object','edu.wustl.catissuecore.domain.OrderDetails',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'OrderItem','OrderItem Object','edu.wustl.catissuecore.domain.OrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Derived Specimen Order Item','Derived Specimen Order Item Object','edu.wustl.catissuecore.domain.DerivedSpecimenOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Existing Specimen Array Order Item','Existing Specimen Array Order Item Object','edu.wustl.catissuecore.domain.ExistingSpecimenArrayOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Existing Specimen Order Item','Existing Specimen Order Item Object','edu.wustl.catissuecore.domain.ExistingSpecimenOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'New Specimen Array Order Item','New Specimen Array Order Item Object','edu.wustl.catissuecore.domain.NewSpecimenArrayOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'New Specimen Order Item','New Specimen Order Item Object','edu.wustl.catissuecore.domain.NewSpecimenOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Pathological Case Order Item','Pathological Case Order Item Object','edu.wustl.catissuecore.domain.PathologicalCaseOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Specimen Array Order Item','Specimen Array Order Item Object','edu.wustl.catissuecore.domain.SpecimenArrayOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Specimen Order Item','Specimen Order Item Object','edu.wustl.catissuecore.domain.SpecimenOrderItem',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;


INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'edu.wustl.catissuecore.action.RequestListAction','edu.wustl.catissuecore.action.RequestListAction','edu.wustl.catissuecore.action.RequestListAction',NULL,NULL,1,TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.RequestListAction'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.RequestListAction'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.RequestListAction'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;

-- giving create priviledge to scientist for order -start*/
INSERT INTO CSM_ROLE SELECT MAX(ROLE_ID)+1,'CREATE_ONLY','Create only role',1,0,TO_DATE('0001-01-01','yyyy-mm-dd') FROM CSM_ROLE;
INSERT INTO CSM_ROLE_PRIVILEGE SELECT MAX(a.ROLE_PRIVILEGE_ID)+1,MAX(b.ROLE_ID) ,1,TO_DATE('0001-01-01','yyyy-mm-dd') FROM CSM_ROLE_PRIVILEGE a,CSM_ROLE b;
INSERT INTO CSM_PROTECTION_GROUP SELECT MAX(PROTECTION_GROUP_ID)+1,'SCIENTIST_PROTECTION_GROUP',NULL,1,0,TO_DATE('0001-01-01','yyyy-mm-dd'),NULL FROM CSM_PROTECTION_GROUP;
alter sequence CSM_PROTECTIO_PROTECTION_G_SEQ increment by 2;
select  CSM_PROTECTIO_PROTECTION_G_SEQ.nextval from dual;
alter sequence CSM_PROTECTIO_PROTECTION_G_SEQ increment by 1;

INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Order'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='OrderItem'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,(SELECT MAX(PROTECTION_GROUP_ID) FROM CSM_PROTECTION_GROUP),(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;

INSERT INTO CSM_USER_GROUP_ROLE_PG SELECT MAX(USER_GROUP_ROLE_PG_ID)+1 ,NULL,4,MAX(c.ROLE_ID),MAX(b.protection_group_id),TO_DATE('0001-01-01','yyyy-mm-dd') FROM CSM_USER_GROUP_ROLE_PG a,CSM_PROTECTION_GROUP b ,CSM_ROLE c;
select CSM_USER_GROU_USER_GROUP_R_SEQ.NEXTVAL from dual;
-- giving create priviledge to scientist for order -finish*/


	---------Ordering System---------*/	
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Order'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Order'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Order'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='OrderItem'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='OrderItem'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='OrderItem'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Derived Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Existing Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='New Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Pathological Case Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Array Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Specimen Order Item'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;


-- cde_dummydata_common.sql */


--******Ordering System******/
INSERT INTO CATISSUE_CDE VALUES ( '4284','Request Status','Statuses for the ordered requests',1.0,NULL);
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5000,'All',NULL,'4284');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5001,'New',NULL,'4284');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5002,'Pending',NULL,'4284');

INSERT INTO CATISSUE_CDE VALUES ( '4285','Requested Items Status','Statuses for the individual elements in the ordered request',1.0,NULL);
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5005,'New',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5006,'Pending - Protocol Review',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5007,'Pending - For Distribution',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5012,'Distributed',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5008,'Pending - Specimen Preparation',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5009,'Rejected - Inappropriate Request',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5010,'Rejected - Specimen Unavailable',NULL,'4285');
INSERT INTO CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER, VALUE, PARENT_IDENTIFIER, PUBLIC_ID) VALUES(5011,'Rejected - Unable to Create',NULL,'4285');


-- initDB_inser_Common.sql */
--Ordering System*/
INSERT INTO CATISSUE_QUERY_TABLE_DATA  SELECT MAX(TABLE_ID)+1, 'CATISSUE_ORDER', 'Order', 'OrderDetails', 2,NULL FROM CATISSUE_QUERY_TABLE_DATA ;
-- order system finish */


-- ordering changes finish */


----------Consent Tracking-------*/
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Consent Tier','ConsentTier Object','edu.wustl.catissuecore.domain.ConsentTier',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Consent Tier Response','Consent Tier Response Object','edu.wustl.catissuecore.domain.ConsentTierResponse',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Consent Tier Status','Consent Tier Status Object','edu.wustl.catissuecore.domain.ConsentTierStatus',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
	
----------Consent Tracking-------*/
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;

--Consent Tracking related drop, create and add foreign key scripts.*/
--drop table CATISSUE_CONSENT_TIER_RESPONSE;
--drop table CATISSUE_CONSENT_TIER_STATUS;
--drop table CATISSUE_CONSENT_TIER;

CREATE TABLE CATISSUE_CONSENT_TIER_RESPONSE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   RESPONSE VARCHAR(255),
   CONSENT_TIER_ID NUMBER(19,0),
   COLL_PROT_REG_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_CONSENT_TIER_STATUS (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONSENT_TIER_ID NUMBER(19,0),
   STATUS VARCHAR(255),
   SPECIMEN_ID NUMBER(19,0),
   SPECIMEN_COLL_GROUP_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_CONSENT_TIER (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   STATEMENT VARCHAR2(500),
   COLL_PROTOCOL_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);

ALTER TABLE CATISSUE_CONSENT_TIER_RESPONSE  ADD constraint FKFB1995FD4AD77FCB foreign key (COLL_PROT_REG_ID) references CATISSUE_COLL_PROT_REG (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_RESPONSE  ADD constraint FKFB1995FD17B9953 foreign key (CONSENT_TIER_ID) references CATISSUE_CONSENT_TIER (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS  ADD constraint FKF74E94AEF69249F7 foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS  ADD constraint FKF74E94AE60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS  ADD constraint FKF74E94AE17B9953 foreign key (CONSENT_TIER_ID) references CATISSUE_CONSENT_TIER (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER  ADD constraint FK51725303E36A4B4F foreign key (COLL_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

CREATE sequence CATISSUE_CONSENT_TIER_RES_SEQ;
CREATE sequence CATISSUE_CONSENT_TIER_STAT_SEQ;
CREATE sequence CATISSUE_CONSENT_TIER_SEQ;


------caTissue tables changed for and consent tracking----- */
--alter table CATISSUE_COLL_PROT_REG drop constraint FK5EB25F13A0FF79D4;
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL ADD  UNSIGNED_CONSENT_DOC_URL VARCHAR2(500);
ALTER TABLE CATISSUE_COLL_PROT_REG ADD  (CONSENT_SIGN_DATE DATE,CONSENT_DOC_URL VARCHAR2(500),CONSENT_WITNESS NUMBER(19,0));
ALTER TABLE CATISSUE_COLL_PROT_REG ADD constraint FK5EB25F13A0FF79D4 foreign key (CONSENT_WITNESS) references CATISSUE_USER (IDENTIFIER);


-- ------------------------New Table entry For ConsentWithdrawal ---------- Mandar : 18-Jan-07 -------------start */
INSERT INTO CATISSUE_QUERY_TABLE_DATA  SELECT MAX(TABLE_ID)+1, 'CATISSUE_RETURN_EVENT_PARAM', 'Return Event Parameters', 'ReturnEventParameters',2,2 FROM CATISSUE_QUERY_TABLE_DATA;
INSERT INTO CATISSUE_INTERFACE_COLUMN_DATA SELECT MAX(IDENTIFIER)+1, MAX(b.table_id), 'IDENTIFIER', 'bigint' FROM CATISSUE_INTERFACE_COLUMN_DATA a,CATISSUE_QUERY_TABLE_DATA b;

CREATE TABLE CATISSUE_RETURN_EVENT_PARAM (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   primary key (IDENTIFIER)
);

ALTER TABLE CATISSUE_RETURN_EVENT_PARAM ADD constraint FKD8890A48BC7298A91 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM (IDENTIFIER);

INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'ReturnEventParameters','ReturnEventParameters Class','edu.wustl.catissuecore.domain.ReturnEventParameters',NULL,NULL,1,TO_DATE('2007-01-18','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='ReturnEventParameters'),TO_DATE('2006-01-18','yyyy-mm-dd') FROM dual;

-- ------------------------New Table entry For ConsentWithdrawal ---------- Mandar : 18-Jan-07 -------------end	 */

--------------------------New Column Entry For ConsentWaived ---------- Mandar : 25-Jan-07 -------------start */
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL ADD CONSENTS_WAIVED NUMBER(1,0);
UPDATE CATISSUE_COLLECTION_PROTOCOL SET CONSENTS_WAIVED=0 WHERE CONSENTS_WAIVED IS NULL;
--------------------------New Column Entry For ConsentWaived ---------- Mandar : 25-Jan-07 -------------end */

--***Participant add column- start**********/
ALTER TABLE CATISSUE_PARTICIPANT ADD  MARITAL_STATUS VARCHAR2(50);
--***Participant add column- end**********/

--***caTIES Realated Tables - start**********/

--drop table CATISSUE_REPORT_TEXTCONTENT cascade constraints;
--drop table CATISSUE_IDENTIFIED_REPORT cascade constraints;
--drop table CATISSUE_CONCEPT_REFERENT cascade constraints;
--drop table CATISSUE_REPORT_CONTENT cascade constraints;
--drop table CATISSUE_REVIEW_PARAMS cascade constraints;
--drop table CATISSUE_REPORT_BICONTENT cascade constraints;
--drop table CATISSUE_REPORT_SECTION cascade constraints;
--drop table CATISSUE_DEIDENTIFIED_REPORT cascade constraints;
--drop table CATISSUE_QUARANTINE_PARAMS cascade constraints;
--drop table CATISSUE_PATHOLOGY_REPORT cascade constraints;
--drop table CATISSUE_REPORT_XMLCONTENT cascade constraints;
--drop table CATISSUE_REPORT_QUEUE cascade constraints;
--drop table CATISSUE_REPORT_PARTICIP_REL cascade constraints;
--drop table CATISSUE_CONCEPT cascade constraints;
--drop table CATISSUE_SEMANTIC_TYPE cascade constraints;
--drop table CATISSUE_CONCEPT_CLASSIFICATN cascade constraints;

-- drop sequence CATISSUE_CONCEPT_REFERENT_SEQ;
--drop sequence CATISSUE_PATHOLOGY_REPORT_SEQ;
--drop sequence CATISSUE_QUARANTINE_PARAMS_SEQ;
--drop sequence CATISSUE_REPORT_SECTION_SEQ;
--drop sequence CATISSUE_REVIEW_PARAMS_SEQ;
--drop sequence CATISSUE_REPORT_CONTENT_SEQ;
--drop sequence CATISSUE_REPORT_QUEUE_SEQ;
--drop sequence CATISSUE_SEMANTIC_TYPE_SEQ;
--drop sequence CATISSUE_CONCEPT_SEQ;
--drop sequence CATISSUE_CONCEPT_CLASSFCTN_SEQ;

CREATE TABLE CATISSUE_REPORT_TEXTCONTENT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   REPORT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_IDENTIFIED_REPORT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DEID_REPORT NUMBER(19,0),
   SCG_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_CONCEPT_REFERENT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONCEPT_ID NUMBER(19,0),
   CONCEPT_CLASSIFICATION_ID NUMBER(19,0),
   DEIDENTIFIED_REPORT_ID NUMBER(19,0),
   END_OFFSET NUMBER(19,0),
   IS_MODIFIER NUMBER(1,0),
   IS_NEGATED NUMBER(1,0),
   START_OFFSET NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_CONTENT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   REPORT_DATA clob,
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REVIEW_PARAMS (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   REVIEWER_ROLE VARCHAR(100),
   REPORT_ID NUMBER(19,0),
   EVENT_TIMESTAMP timestamp,
   USER_ID NUMBER(19,0),
   COMMENTS VARCHAR2(4000),
   STATUS VARCHAR(100),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_BICONTENT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   REPORT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_SECTION (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DOCUMENT_FRAGMENT VARCHAR2(4000),
   END_OFFSET INTEGER,
   NAME VARCHAR(100),
   START_OFFSET INTEGER,
   TEXT_CONTENT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_DEIDENTIFIED_REPORT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   STATUS VARCHAR(100),
   SCG_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_QUARANTINE_PARAMS (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   DEID_REPORT_ID NUMBER(19,0),
   IS_QUARANTINED NUMBER(1),
   EVENT_TIMESTAMP timestamp,
   USER_ID NUMBER(19,0),
   COMMENTS VARCHAR2(4000),
   STATUS VARCHAR(100),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_PATHOLOGY_REPORT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   ACTIVITY_STATUS VARCHAR(100),
   REVIEW_FLAG NUMBER(1),
   SOURCE_ID NUMBER(19,0),
   REPORT_STATUS VARCHAR(100),
   COLLECTION_DATE_TIME timestamp,
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_XMLCONTENT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   REPORT_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_QUEUE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   STATUS VARCHAR(50),
   SURGICAL_PATHOLOGY_NUMBER VARCHAR(50),
   PARTICIPANT_NAME VARCHAR(255),
   SITE_NAME VARCHAR(255),
   REPORT_LOADED_DATE DATE,
   REPORT_TEXT clob,
   SPECIMEN_COLL_GRP_ID NUMBER(19,0),
   REPORT_COLLECTION_DATE DATE,
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_REPORT_PARTICIP_REL(
   PARTICIPANT_ID NUMBER(19,0),
   REPORT_ID NUMBER(19,0)
);
CREATE TABLE CATISSUE_CONCEPT (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   CONCEPT_UNIQUE_ID VARCHAR(30),
   NAME VARCHAR2(500),
   SEMANTIC_TYPE_ID NUMBER(19,0),
   primary key (IDENTIFIER)
);

CREATE TABLE CATISSUE_SEMANTIC_TYPE (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   LABEL VARCHAR2(500),
   primary key (IDENTIFIER)
);

CREATE TABLE CATISSUE_CONCEPT_CLASSIFICATN (
   IDENTIFIER NUMBER(19,0) NOT NULL,
   NAME VARCHAR2(500),
   primary key (IDENTIFIER)
);


ALTER TABLE CATISSUE_REPORT_TEXTCONTENT ADD constraint FKD74882FD91092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_TEXTCONTENT ADD constraint FKD74882FDBC7298A9 foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD constraint FK6A2246DCBC7298A9 foreign key (IDENTIFIER) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD constraint FK6A2246DC752DD177 foreign key (DEID_REPORT) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD constraint FK6A2246DC91741663 foreign key (SCG_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD constraint FK799CCA7E9F96B363 foreign key (DEIDENTIFIED_REPORT_ID) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REVIEW_PARAMS ADD constraint FK5311FFF62206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_REVIEW_PARAMS ADD constraint FK5311FFF691092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_BICONTENT ADD constraint FK8A9A4EE391092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_BICONTENT ADD constraint FK8A9A4EE3BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT ADD constraint FKCDD0DF7BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT ADD constraint FKCDD0DF7B91741663 foreign key (SCG_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_QUARANTINE_PARAMS ADD constraint FK3C12AE3B2206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_QUARANTINE_PARAMS ADD constraint FK3C12AE3B3EEC14E3 foreign key (DEID_REPORT_ID) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_PATHOLOGY_REPORT ADD constraint FK904EC9F040DCD7BF foreign key (SOURCE_ID) references CATISSUE_SITE (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_XMLCONTENT ADD constraint FK4597C9F1BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_XMLCONTENT ADD constraint FK4597C9F191092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
ALTER TABLE CATISSUE_REPORT_QUEUE ADD constraint FK214246228CA560D1 foreign key (SPECIMEN_COLL_GRP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT ADD constraint FKC1A3C8CC7F0C2C7 foreign key (SEMANTIC_TYPE_ID) references CATISSUE_SEMANTIC_TYPE (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD constraint FK799CCA7EA9816272 foreign key (CONCEPT_ID) references CATISSUE_CONCEPT (IDENTIFIER);
ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD constraint FK799CCA7E72C371DD foreign key (CONCEPT_CLASSIFICATION_ID) references CATISSUE_CONCEPT_CLASSIFICATN (IDENTIFIER);

CREATE sequence CATISSUE_CONCEPT_REFERENT_SEQ;
CREATE sequence CATISSUE_PATHOLOGY_REPORT_SEQ;
CREATE sequence CATISSUE_QUARANTINE_PARAMS_SEQ;
CREATE sequence CATISSUE_REPORT_SECTION_SEQ;
CREATE sequence CATISSUE_REVIEW_PARAMS_SEQ;
CREATE sequence CATISSUE_REPORT_CONTENT_SEQ;
CREATE sequence CATISSUE_REPORT_QUEUE_SEQ;
CREATE sequence CATISSUE_SEMANTIC_TYPE_SEQ;
CREATE sequence CATISSUE_CONCEPT_SEQ;
CREATE sequence CATISSUE_CONCEPT_CLASSFCTN_SEQ;

INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL ,'IdentifiedSurgicalPathologyReport','IdentifiedSurgicalPathologyReport Object','edu.wustl.catissuecore.domain.pathology.IdentifiedSurgicalPathologyReport',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL ,'DeidentifiedSurgicalPathologyReport','DeidentifiedSurgicalPathologyReport Object','edu.wustl.catissuecore.domain.pathology.DeidentifiedSurgicalPathologyReport',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL ,'ReportLoaderQueue','ReportLoaderQueue Object','edu.wustl.catissuecore.domain.pathology.ReportLoaderQueue',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL ,'Review Comments','PathologyReportReviewParameter Object','edu.wustl.catissuecore.domain.pathology.PathologyReportReviewParameter',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL ,'Quarantine Comments','QuarantineEventParameter Object','edu.wustl.catissuecore.domain.pathology.QuarantineEventParameter',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;

-- reseting sequence for CSM_PROTECTION_ELEMENT table to correct position
--select CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL from dual;
--select CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL from dual;
--select CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL from dual;
--select CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL from dual;
--select CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL from dual;

INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='IdentifiedSurgicalPathologyReport'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='IdentifiedSurgicalPathologyReport'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='IdentifiedSurgicalPathologyReport'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='DeidentifiedSurgicalPathologyReport'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='DeidentifiedSurgicalPathologyReport'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='DeidentifiedSurgicalPathologyReport'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='ReportLoaderQueue'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='ReportLoaderQueue'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='ReportLoaderQueue'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Review Comments'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Review Comments'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Review Comments'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Quarantine Comments'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Quarantine Comments'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Quarantine Comments'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;

DELETE FROM CATISSUE_QUERY_TABLE_DATA WHERE TABLE_ID=26;
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER=44;
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER=45;
DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA WHERE IDENTIFIER=46;
DELETE FROM CATISSUE_TABLE_RELATION WHERE RELATIONSHIP_ID=47;
DELETE FROM CATISSUE_RELATED_TABLES_MAP WHERE FIRST_TABLE_ID=26 AND SECOND_TABLE_ID=35;
UPDATE CATISSUE_INTERFACE_COLUMN_DATA SET COLUMN_NAME='SURGICAL_PATHOLOGY_NUMBER' WHERE IDENTIFIER=215;

INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'edu.wustl.catissuecore.action.ConflictViewAction','edu.wustl.catissuecore.action.ConflictViewAction','edu.wustl.catissuecore.action.ConflictViewAction',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,1,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.ConflictViewAction'),TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;


INSERT INTO CATISSUE_QUERY_TABLE_DATA  SELECT MAX(TABLE_ID)+1, 'CATISSUE_REVIEW_PARAMS', 'Pathology Report Review Parameter', 'PathologyReportReviewParameter', 2,NULL FROM CATISSUE_QUERY_TABLE_DATA ;
INSERT INTO CATISSUE_QUERY_TABLE_DATA  SELECT MAX(TABLE_ID)+1, 'CATISSUE_QUARANTINE_PARAMS', 'Quarantine Event Parameter', 'QuarantineEventParameter', 2,NULL FROM CATISSUE_QUERY_TABLE_DATA ;

-- caTIES Realated Tables - end */

/* Local Extension  */
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'Local Extensions','Local Extensions class','edu.common.dynamicextensions.domain.integration.EntityMap',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction','edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction','edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction',NULL,NULL,1,TO_DATE('2006-11-27','yyyy-mm-dd') FROM dual;

/* Local Extension  */
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,17,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE OBJECT_ID='edu.common.dynamicextensions.domain.integration.EntityMap'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,17,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE OBJECT_ID='edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction'),TO_DATE('2007-01-04','yyyy-mm-dd') FROM dual;


/*  changes for making Action a secureAction  :kalpana */
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction','edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction','edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction',NULL,NULL,1,TO_DATE('2007-12-25','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction','edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction','edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction',NULL,NULL,1,TO_DATE('2007-12-25','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PROTECTION_ELEMENT SELECT CSM_PROTECTIO_PROTECTION_E_SEQ.NEXTVAL,'edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction','edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction','edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction',NULL,NULL,1,TO_DATE('2007-12-25','yyyy-mm-dd') FROM dual;


INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,19,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE OBJECT_ID='edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction'),TO_DATE('2007-12-25','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,19,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE OBJECT_ID='edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction'),TO_DATE('2007-12-25','yyyy-mm-dd') FROM dual;
INSERT INTO CSM_PG_PE SELECT CSM_PG_PE_PG_PE_ID_SEQ.NEXTVAL,19,(SELECT PROTECTION_ELEMENT_ID FROM csm_protection_element WHERE OBJECT_ID='edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction'),TO_DATE('2007-12-25','yyyy-mm-dd') FROM dual;


/* kalpana  end */

/* Supriya :Changes to run Query on SCG in simple search Added metadata related to Abstract SCG.*/

INSERT INTO CATISSUE_QUERY_TABLE_DATA values (92, 'CATISSUE_ABS_SPECI_COLL_GROUP', 'Abstract Specimen Coll Group', 'AbstractScg',2,NULL) ;


UPDATE catissue_interface_column_data SET table_id = 92 WHERE identifier IN (210,211,212,213);


INSERT INTO catissue_interface_column_data (IDENTIFIER,TABLE_ID,COLUMN_NAME,ATTRIBUTE_TYPE) VALUES (331,92,'IDENTIFIER','bigint');


INSERT INTO catissue_table_relation values(131,35,92,NULL);


INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER) VALUES (131, 210, 'Clinical Diagnosis',1,7);

INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER) VALUES (131, 211, 'Clinical Status',1,8);


UPDATE CATISSUE_RELATED_TABLES_MAP SET second_table_id = 92 WHERE second_table_id = 35 AND first_table_id=3;


INSERT INTO CATISSUE_RELATED_TABLES_MAP VALUES ( 92 , 35 , 'IDENTIFIER','IDENTIFIER');


 

/*Supriya end*/


/* TODO Added in next script CSMUpgrade_3_to_3.2 */

commit;