alter table DYEXTN_COLUMN_PROPERTIES add CNSTR_KEY_PROP_ID number(19,0);

alter table DYEXTN_CONSTRAINTKEY_PROP add constraint FK80C9511D6B558E0E foreign key (SRC_CONSTRAINT_KEY_ID) references DYEXTN_CONSTRAINT_PROPERTIES;

alter table DYEXTN_CONSTRAINTKEY_PROP add constraint FK80C9511D2C4ACB4B foreign key (TGT_CONSTRAINT_KEY_ID) references DYEXTN_CONSTRAINT_PROPERTIES;

alter table DYEXTN_CONSTRAINTKEY_PROP add constraint FK80C9511DF3077C33 foreign key (PRIMARY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;

alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3F4953F037 foreign key (CNSTR_KEY_PROP_ID) references DYEXTN_CONSTRAINTKEY_PROP;

alter table DYEXTN_CONSTRAINT_PROPERTIES add CONSTRAINT_NAME varchar2(255);

alter table DYEXTN_CONSTRAINT_PROPERTIES add ABSTRACT_ENTITY_ID number(19,0);

alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD81DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY;

alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL add constraint FKD2168AAA4AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY;

alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL add constraint FKD2168AAA4DC2CD16 foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;