<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Portions of this file Copyright 1999-2005 University of Chicago
  Portions of this file Copyright 1999-2005 The University of Southern California.
  
  This file or a portion of this file is licensed under the
  terms of the Globus Toolkit Public License, found at
  http://www.globus.org/toolkit/download/license.html.
  If you redistribute this file, with or without
  modifications, you must include this notice in the file.
-->
<definitions name="ResourceMappingInvalidation"
    targetNamespace="http://wsrf.globus.org/tests/invalidate"
    xmlns:tns="http://wsrf.globus.org/tests/invalidate"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:gtwsdl="http://www.globus.org/namespaces/2004/01/GTWSDLExtensions"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <types>
        <xsd:schema targetNamespace="http://wsrf.globus.org/tests/invalidate"
            xmlns:tns="http://wsrf.globus.org/tests/invalidate"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

            <xsd:element name="InvalidateRequest">
                <xsd:complexType/>
            </xsd:element>

            <xsd:element name="InvalidateResponse">
                <xsd:complexType/>
            </xsd:element>

        </xsd:schema>
    </types>

    <message name="InvalidateRequest">
        <part name="request" element="tns:InvalidateRequest"/>
    </message>

    <message name="InvalidateResponse">
        <part name="response" element="tns:InvalidateResponse"/>
    </message>

    <portType name="Invalidate">
        <wsdl:operation name="invalidate">
            <wsdl:input  message="tns:InvalidateRequest"/>
            <wsdl:output message="tns:InvalidateResponse"/>
        </wsdl:operation>
    </portType>

</definitions>
