//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:02:46 PM IST 
//


package edu.wustl.catissuecore.jaxb.domain;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CollectionProtocolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollectionProtocolType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrincipalInvestigator" type="{}PrincipalInvestigatorType"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "CollectionProtocolType", propOrder = {
    "principalInvestigator",
    "title"
})
public class CollectionProtocolType {

    @XmlElement(name = "PrincipalInvestigator")
    protected PrincipalInvestigatorType principalInvestigator;
    @XmlElement(name = "Title")
    protected String title;

    /**
     * Gets the value of the principalInvestigator property.
     * 
     * @return
     *     possible object is
     *     {@link PrincipalInvestigatorType }
     *     
     */
    public PrincipalInvestigatorType getPrincipalInvestigator() {
        return principalInvestigator;
    }

    /**
     * Sets the value of the principalInvestigator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrincipalInvestigatorType }
     *     
     */
    public void setPrincipalInvestigator(PrincipalInvestigatorType value) {
        this.principalInvestigator = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
