//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.04.19 at 07:06:49 PM IST
//


package edu.wustl.catissuecore.jaxb.domain;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.transform.Source;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;

import org.xml.sax.SAXException;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Specimen }
     *
     */
    public Specimen createSpecimen() {
        return new Specimen();
    }

    public Object unMarshelExportDataXml(String packageName,String fileName,String schemaFile) throws JAXBException, FileNotFoundException, SAXException
    {
    	JAXBContext context =JAXBContext.newInstance(packageName) ;
        Unmarshaller unmarshaller =context.createUnmarshaller() ;
        Source schemaSource = new StreamSource(this.getClass().getClassLoader().getResourceAsStream(schemaFile));
        Schema mySchema = SchemaFactory.newInstance("http://www.w3.org/2001/XMLSchema").newSchema(schemaSource);
        unmarshaller.setSchema(mySchema);
        return unmarshaller.unmarshal(new FileInputStream(fileName)) ;
    }

    public void marshelExportDataXml(String packageName,String fileName,Object obj) throws JAXBException, FileNotFoundException, SAXException
    {
    	JAXBContext context =JAXBContext.newInstance(packageName) ;
        Marshaller marshaller =context.createMarshaller();
        marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT,Boolean.TRUE);
        marshaller.marshal(obj, new FileOutputStream(fileName)) ;
    }

  }
