//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:02:46 PM IST 
//


package edu.wustl.catissuecore.jaxb.domain;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecimenPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StorageContainer" type="{}StorageContainerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "SpecimenPositionType", propOrder = {
    "storageContainer"
})
public class SpecimenPositionType {

    @XmlElement(name = "StorageContainer")
    protected StorageContainerType storageContainer;

    /**
     * Gets the value of the storageContainer property.
     * 
     * @return
     *     possible object is
     *     {@link StorageContainerType }
     *     
     */
    public StorageContainerType getStorageContainer() {
        return storageContainer;
    }

    /**
     * Sets the value of the storageContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageContainerType }
     *     
     */
    public void setStorageContainer(StorageContainerType value) {
        this.storageContainer = value;
    }

}
