//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:02:46 PM IST 
//


package edu.wustl.catissuecore.jaxb.domain;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecimenCharacteristicsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenCharacteristicsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TissueSite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "SpecimenCharacteristicsType", propOrder = {
    "tissueSite"
})
public class SpecimenCharacteristicsType {

    @XmlElement(name = "TissueSite")
    protected String tissueSite;

    /**
     * Gets the value of the tissueSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTissueSite() {
        return tissueSite;
    }

    /**
     * Sets the value of the tissueSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTissueSite(String value) {
        this.tissueSite = value;
    }

}
