//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:02:46 PM IST 
//


package edu.wustl.catissuecore.jaxb.domain;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecimenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PathologicalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="IsAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SpecimenCharacteristics" type="{}SpecimenCharacteristicsType"/>
 *         &lt;element name="SpecimenPosition" type="{}SpecimenPositionType"/>
 *         &lt;element name="SpecimenEvents" type="{}SpecimenEventsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "SpecimenType", propOrder = {
    "id",
    "clazz",
    "type",
    "pathologicalStatus",
    "quantity",
    "isAvailable",
    "specimenCharacteristics",
    "specimenPosition",
    "specimenEvents"
})
public class SpecimenType {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Class")
    protected String clazz;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "PathologicalStatus")
    protected String pathologicalStatus;
    @XmlElement(name = "Quantity")
    protected double quantity;
    @XmlElement(name = "IsAvailable")
    protected boolean isAvailable;
    @XmlElement(name = "SpecimenCharacteristics")
    protected SpecimenCharacteristicsType specimenCharacteristics;
    @XmlElement(name = "SpecimenPosition")
    protected SpecimenPositionType specimenPosition;
    @XmlElement(name = "SpecimenEvents")
    protected SpecimenEventsType specimenEvents;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the pathologicalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathologicalStatus() {
        return pathologicalStatus;
    }

    /**
     * Sets the value of the pathologicalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathologicalStatus(String value) {
        this.pathologicalStatus = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public double getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(double value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the isAvailable property.
     * 
     */
    public boolean isIsAvailable() {
        return isAvailable;
    }

    /**
     * Sets the value of the isAvailable property.
     * 
     */
    public void setIsAvailable(boolean value) {
        this.isAvailable = value;
    }

    /**
     * Gets the value of the specimenCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenCharacteristicsType }
     *     
     */
    public SpecimenCharacteristicsType getSpecimenCharacteristics() {
        return specimenCharacteristics;
    }

    /**
     * Sets the value of the specimenCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenCharacteristicsType }
     *     
     */
    public void setSpecimenCharacteristics(SpecimenCharacteristicsType value) {
        this.specimenCharacteristics = value;
    }

    /**
     * Gets the value of the specimenPosition property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenPositionType }
     *     
     */
    public SpecimenPositionType getSpecimenPosition() {
        return specimenPosition;
    }

    /**
     * Sets the value of the specimenPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenPositionType }
     *     
     */
    public void setSpecimenPosition(SpecimenPositionType value) {
        this.specimenPosition = value;
    }

    /**
     * Gets the value of the specimenEvents property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenEventsType }
     *     
     */
    public SpecimenEventsType getSpecimenEvents() {
        return specimenEvents;
    }

    /**
     * Sets the value of the specimenEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenEventsType }
     *     
     */
    public void setSpecimenEvents(SpecimenEventsType value) {
        this.specimenEvents = value;
    }

}
