--SET IMPLICIT_TRANSACTIONS ON

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PERMISSIBLE_VALUE') DROP TABLE CATISSUE_PERMISSIBLE_VALUE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CDE') DROP TABLE CATISSUE_CDE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_COORDINATORS') DROP TABLE CATISSUE_COLL_COORDINATORS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CANCER_RESEARCH_GROUP') DROP TABLE CATISSUE_CANCER_RESEARCH_GROUP;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLLECTION_PROTOCOL') DROP TABLE CATISSUE_COLLECTION_PROTOCOL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EVENT_PARAM') DROP TABLE CATISSUE_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_TRANSFER_EVENT_PARAM') DROP TABLE CATISSUE_TRANSFER_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STOR_CONT_SPEC_CLASS') DROP TABLE CATISSUE_STOR_CONT_SPEC_CLASS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_EVENT_PARAM') DROP TABLE CATISSUE_COLL_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PASSWORD') DROP TABLE CATISSUE_PASSWORD;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_BIOHZ_REL') DROP TABLE CATISSUE_SPECIMEN_BIOHZ_REL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_MOL_SPE_REVIEW_PARAM') DROP TABLE CATISSUE_MOL_SPE_REVIEW_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STOR_TYPE_HOLDS_TYPE') DROP TABLE CATISSUE_STOR_TYPE_HOLDS_TYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STORAGE_TYPE') DROP TABLE CATISSUE_STORAGE_TYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONTAINER') DROP TABLE CATISSUE_CONTAINER;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTION_SPEC_REQ') DROP TABLE CATISSUE_DISTRIBUTION_SPEC_REQ;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SITE') DROP TABLE CATISSUE_SITE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EMBEDDED_EVENT_PARAM') DROP TABLE CATISSUE_EMBEDDED_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_IN_OUT_EVENT_PARAM') DROP TABLE CATISSUE_IN_OUT_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_DISTRIBUTION_REL') DROP TABLE CATISSUE_COLL_DISTRIBUTION_REL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISPOSAL_EVENT_PARAM') DROP TABLE CATISSUE_DISPOSAL_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_REQUIREMENT') DROP TABLE CATISSUE_SPECIMEN_REQUIREMENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_INSTITUTION') DROP TABLE CATISSUE_INSTITUTION;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ST_CONT_ST_TYPE_REL') DROP TABLE CATISSUE_ST_CONT_ST_TYPE_REL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_PROTOCOL') DROP TABLE CATISSUE_SPECIMEN_PROTOCOL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_FLUID_SPE_EVENT_PARAM') DROP TABLE CATISSUE_FLUID_SPE_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_BIOHAZARD') DROP TABLE CATISSUE_BIOHAZARD;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_QUANTITY') DROP TABLE CATISSUE_QUANTITY;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPUN_EVENT_PARAMETERS') DROP TABLE CATISSUE_SPUN_EVENT_PARAMETERS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_RECEIVED_EVENT_PARAM') DROP TABLE CATISSUE_RECEIVED_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_RACE') DROP TABLE CATISSUE_RACE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECI_ARRAY_CONTENT') DROP TABLE CATISSUE_SPECI_ARRAY_CONTENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ADDRESS') DROP TABLE CATISSUE_ADDRESS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORTED_PROBLEM') DROP TABLE CATISSUE_REPORTED_PROBLEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_ARRAY') DROP TABLE CATISSUE_SPECIMEN_ARRAY;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_ARRAY_TYPE') DROP TABLE CATISSUE_SPECIMEN_ARRAY_TYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTED_ITEM') DROP TABLE CATISSUE_DISTRIBUTED_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PARTICIPANT') DROP TABLE CATISSUE_PARTICIPANT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_CHAR') DROP TABLE CATISSUE_SPECIMEN_CHAR;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_EVENT_PARAM') DROP TABLE CATISSUE_SPECIMEN_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STOR_TYPE_SPEC_CLASS') DROP TABLE CATISSUE_STOR_TYPE_SPEC_CLASS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_PROT_EVENT') DROP TABLE CATISSUE_COLL_PROT_EVENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONTAINER_TYPE') DROP TABLE CATISSUE_CONTAINER_TYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CAPACITY') DROP TABLE CATISSUE_CAPACITY;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PART_MEDICAL_ID') DROP TABLE CATISSUE_PART_MEDICAL_ID;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STORAGE_CONTAINER') DROP TABLE CATISSUE_STORAGE_CONTAINER;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CELL_SPE_REVIEW_PARAM') DROP TABLE CATISSUE_CELL_SPE_REVIEW_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTION') DROP TABLE CATISSUE_DISTRIBUTION;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PROCEDURE_EVENT_PARAM') DROP TABLE CATISSUE_PROCEDURE_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTION_PROTOCOL') DROP TABLE CATISSUE_DISTRIBUTION_PROTOCOL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EXTERNAL_IDENT--IFIER') DROP TABLE CATISSUE_EXTERNAL_IDENT--IFIER;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DEPARTMENT') DROP TABLE CATISSUE_DEPARTMENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_FIXED_EVENT_PARAM') DROP TABLE CATISSUE_FIXED_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_THAW_EVENT_PARAMETERS') DROP TABLE CATISSUE_THAW_EVENT_PARAMETERS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_PROT_REG') DROP TABLE CATISSUE_COLL_PROT_REG;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_FROZEN_EVENT_PARAM') DROP TABLE CATISSUE_FROZEN_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_USER') DROP TABLE CATISSUE_USER;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_TIS_SPE_EVENT_PARAM') DROP TABLE CATISSUE_TIS_SPE_EVENT_PARAM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ST_CONT_COLL_PROT_REL') DROP TABLE CATISSUE_ST_CONT_COLL_PROT_REL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STORTY_HOLDS_SPARRTY') DROP TABLE CATISSUE_STORTY_HOLDS_SPARRTY;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONT_HOLDS_SPARRTYPE') DROP TABLE CATISSUE_CONT_HOLDS_SPARRTYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ABS_SPECI_COLL_GROUP') DROP TABLE CATISSUE_ABS_SPECI_COLL_GROUP;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECI_COLL_REQ_GROUP') DROP TABLE CATISSUE_SPECI_COLL_REQ_GROUP;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_COLL_GROUP') DROP TABLE CATISSUE_SPECIMEN_COLL_GROUP;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_TYPE') DROP TABLE CATISSUE_SPECIMEN_TYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT_QUERY_LOG') DROP TABLE CATISSUE_AUDIT_EVENT_QUERY_LOG;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT') DROP TABLE CATISSUE_AUDIT_EVENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT_LOG') DROP TABLE CATISSUE_AUDIT_EVENT_LOG;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT_DETAILS') DROP TABLE CATISSUE_AUDIT_EVENT_DETAILS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_LABEL_COUNT') DROP TABLE CATISSUE_SPECIMEN_LABEL_COUNT;

--caTies
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_TEXTCONTENT') DROP TABLE CATISSUE_REPORT_TEXTCONTENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_IDENT--IFIED_REPORT') DROP TABLE CATISSUE_IDENT--IFIED_REPORT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONCEPT_REFERENT') DROP TABLE CATISSUE_CONCEPT_REFERENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_CONTENT') DROP TABLE CATISSUE_REPORT_CONTENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REVIEW_PARAMS') DROP TABLE CATISSUE_REVIEW_PARAMS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_BICONTENT') DROP TABLE CATISSUE_REPORT_BICONTENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_SECTION') DROP TABLE CATISSUE_REPORT_SECTION;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DEIDENT--IFIED_REPORT') DROP TABLE CATISSUE_DEIDENT--IFIED_REPORT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_QUARANTINE_PARAMS') DROP TABLE CATISSUE_QUARANTINE_PARAMS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PATHOLOGY_REPORT') DROP TABLE CATISSUE_PATHOLOGY_REPORT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_XMLCONTENT') DROP TABLE CATISSUE_REPORT_XMLCONTENT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_QUEUE') DROP TABLE CATISSUE_REPORT_QUEUE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_PARTICIP_REL') DROP TABLE CATISSUE_REPORT_PARTICIP_REL;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONCEPT') DROP TABLE CATISSUE_CONCEPT;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SEMANTIC_TYPE') DROP TABLE CATISSUE_SEMANTIC_TYPE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONCEPT_CLASS--IFICATN') DROP TABLE CATISSUE_CONCEPT_CLASS--IFICATN;

------ Consent Tracking related drop, create and add foreign key scripts.
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONSENT_TIER_RESPONSE') DROP TABLE CATISSUE_CONSENT_TIER_RESPONSE;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONSENT_TIER_STATUS') DROP TABLE CATISSUE_CONSENT_TIER_STATUS;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONSENT_TIER') DROP TABLE CATISSUE_CONSENT_TIER;

-- Specimen Order
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PATH_CASE_ORDER_ITEM') DROP TABLE CATISSUE_PATH_CASE_ORDER_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DERIEVED_SP_ORD_ITEM') DROP TABLE CATISSUE_DERIEVED_SP_ORD_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_NEW_SPEC_ORD_ITEM') DROP TABLE CATISSUE_NEW_SPEC_ORD_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EXISTING_SP_ORD_ITEM') DROP TABLE CATISSUE_EXISTING_SP_ORD_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_ORDER_ITEM') DROP TABLE CATISSUE_SPECIMEN_ORDER_ITEM;

-- Specimen Array Order
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_NEW_SP_AR_ORDER_ITEM') DROP TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EXIST_SP_AR_ORD_ITEM') DROP TABLE CATISSUE_EXIST_SP_AR_ORD_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SP_ARRAY_ORDER_ITEM') DROP TABLE CATISSUE_SP_ARRAY_ORDER_ITEM;

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ORDER_ITEM') DROP TABLE CATISSUE_ORDER_ITEM;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ORDER') DROP TABLE CATISSUE_ORDER;

--Specimen Model change
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ABSTRACT_SPECIMEN') DROP TABLE CATISSUE_ABSTRACT_SPECIMEN;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN') DROP TABLE CATISSUE_SPECIMEN;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CP_REQ_SPECIMEN') DROP TABLE CATISSUE_CP_REQ_SPECIMEN;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_fluid_req_specimen') DROP TABLE catissue_fluid_req_specimen;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_fluid_specimen') DROP TABLE catissue_fluid_specimen;

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_cell_specimen') DROP TABLE catissue_cell_specimen;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_cell_req_specimen') DROP TABLE catissue_cell_req_specimen;

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_tissue_specimen') DROP TABLE catissue_tissue_specimen;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_tissue_req_specimen') DROP TABLE catissue_tissue_req_specimen;

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_mol_req_specimen') DROP TABLE catissue_mol_req_specimen;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_molecular_specimen') DROP TABLE catissue_molecular_specimen;
--SET IMPLICIT_TRANSACTIONS OFF 

create table CATISSUE_PERMISSIBLE_VALUE (
   IDENTIFIER bigint not null identity,
   CONCEPT_CODE varchar(40),
   DEFINITION varchar(500),
   PARENT_IDENTIFIER bigint,
   VALUE varchar(225),
   PUBLIC_ID varchar(30)
);

create table CATISSUE_CDE (
   PUBLIC_ID varchar(30) not null,
   LONG_NAME varchar(200),
   DEFINITION varchar(500),
   VERSION varchar(50),
   LAST_UPDATED smalldatetime
);

create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER bigint not null identity,
   IP_ADDRESS varchar(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(500)
);

create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER bigint not null identity,
   OBJECT_IDENTIFIER bigint,
   OBJECT_NAME varchar(50),
   EVENT_TYPE varchar(50),
   AUDIT_EVENT_ID bigint
);

create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER bigint not null identity,
   ELEMENT_NAME varchar(150),
   PREVIOUS_VALUE varchar(150),
   CURRENT_VALUE varchar(500),
   AUDIT_EVENT_LOG_ID bigint
);

create table CATISSUE_COLL_COORDINATORS (
   COLLECTION_PROTOCOL_ID numeric(20) not null,
   USER_ID bigint not null
);

create table CATISSUE_CANCER_RESEARCH_GROUP (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique
);

create table CATISSUE_COLLECTION_PROTOCOL (
   IDENTIFIER numeric(20) not null,
   ALIQUOT_IN_SAME_CONTAINER numeric(1,0),
   UNSIGNED_CONSENT_DOC_URL varchar(500),
   CONSENTS_WAIVED numeric(1,0),
   CP_TYPE varchar(50) default NULL,
   PARENT_CP_ID numeric(20) default NULL,
   SEQUENCE_NUMBER integer,	
   STUDY_CALENDAR_EVENT_POINT DOUBLE PRECISION default NULL
);

create table CATISSUE_EVENT_PARAM (
   IDENTIFIER bigint not null
);

create table CATISSUE_TRANSFER_EVENT_PARAM (
   IDENTIFIER bigint not null,
   FROM_POSITION_DIMENSION_ONE integer,
   FROM_POSITION_DIMENSION_TWO integer,
   TO_POSITION_DIMENSION_ONE integer,
   TO_POSITION_DIMENSION_TWO integer,
   TO_STORAGE_CONTAINER_ID bigint,
   FROM_STORAGE_CONTAINER_ID bigint
);

create table CATISSUE_STOR_CONT_SPEC_CLASS (
   STORAGE_CONTAINER_ID bigint not null,
   SPECIMEN_CLASS varchar(50)
);

create table CATISSUE_COLL_EVENT_PARAM (
   IDENTIFIER bigint not null,
   COLLECTION_PROCEDURE varchar(50),
   CONTAINER varchar(50)
);

create table CATISSUE_PASSWORD (
   IDENTIFIER bigint not null identity,
   PASSWORD varchar(255),
   UPDATE_DATE smalldatetime,
   USER_ID bigint
);

create table CATISSUE_SPECIMEN_BIOHZ_REL (
   BIOHAZARD_ID bigint not null,
   SPECIMEN_ID numeric(20) not null
);

create table CATISSUE_MOL_SPE_REVIEW_PARAM (
   IDENTIFIER bigint not null,
   GEL_IMAGE_URL varchar(255),
   QUALITY_INDEX varchar(50),
   LANE_NUMBER varchar(50),
   GEL_NUMBER integer,
   ABSORBANCE_AT_260 double precision,
   ABSORBANCE_AT_280 double precision,
   RATIO_28S_TO_18S double precision
);

create table CATISSUE_STORAGE_TYPE (
   IDENTIFIER bigint not null,
   DEFAULT_TEMPERATURE DOUBLE PRECISION
);

create table CATISSUE_CONTAINER (
   IDENTIFIER bigint not null identity,
   ACTIVITY_STATUS varchar(50),
   BARCODE varchar(255),
   CAPACITY_ID bigint,
   COMMENTS varchar(500),
   CONT_FULL numeric(1,0),
   NAME varchar(255) unique not null
);

create table CATISSUE_SITE (
   IDENTIFIER numeric(20) not null identity,
   NAME varchar(255) not null unique,
   TYPE varchar(50),
   EMAIL_ADDRESS varchar(255),
   USER_ID bigint,
   ACTIVITY_STATUS varchar(50),
   ADDRESS_ID bigint
);

create table CATISSUE_EMBEDDED_EVENT_PARAM (
   IDENTIFIER bigint not null,
   EMBEDDING_MEDIUM varchar(50)
);

create table CATISSUE_IN_OUT_EVENT_PARAM (
   IDENTIFIER bigint not null,
   STORAGE_STATUS varchar(100) not null
);

create table CATISSUE_COLL_DISTRIBUTION_REL (
   COLLECTION_PROTOCOL_ID numeric(20) not null,
   DISTRIBUTION_PROTOCOL_ID numeric(20) not null
);

create table CATISSUE_DISPOSAL_EVENT_PARAM (
   IDENTIFIER bigint not null,
   REASON varchar(255)
);

create table CATISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null identity,
   SPECIMEN_CLASS varchar(255) not null,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   QUANTITY_ID bigint
);

create table CATISSUE_INSTITUTION (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique
);

create table CATISSUE_ST_CONT_ST_TYPE_REL (
   STORAGE_CONTAINER_ID bigint not null,
   STORAGE_TYPE_ID bigint not null
);

create table CATISSUE_STOR_TYPE_HOLDS_TYPE (
   STORAGE_TYPE_ID bigint not null,
   HOLDS_STORAGE_TYPE_ID bigint not null
);

create table CATISSUE_STORTY_HOLDS_SPARRTY (
   STORAGE_TYPE_ID bigint not null,
   SPECIMEN_ARRAY_TYPE_ID bigint not null
);

create table CATISSUE_CONT_HOLDS_SPARRTYPE (
   STORAGE_CONTAINER_ID bigint not null,
   SPECIMEN_ARRAY_TYPE_ID bigint not null
);

create table CATISSUE_SPECIMEN_PROTOCOL (
   IDENTIFIER numeric(20) not null identity,
   PRINCIPAL_INVESTIGATOR_ID bigint,
   TITLE varchar(255) not null unique,
   SHORT_TITLE varchar(255),
   IRB_IDENTIFIER varchar(255),
   START_DATE smalldatetime,
   END_DATE smalldatetime,
   ENROLLMENT integer,
   DESCRIPTION_URL varchar(255),
   ACTIVITY_STATUS varchar(50)
);

create table CATISSUE_FLUID_SPE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   CELL_COUNT double precision
);

create table CATISSUE_BIOHAZARD (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique,
   COMMENTS varchar(500),
   TYPE varchar(50)
);

create table CATISSUE_QUANTITY (
   IDENTIFIER bigint not null identity,
   QUANTITY double precision
);

create table CATISSUE_SPUN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   GFORCE double precision,
   DURATION_IN_MINUTES integer
);

create table CATISSUE_RECEIVED_EVENT_PARAM (
   IDENTIFIER bigint not null,
   RECEIVED_QUALITY varchar(255)
);

create table CATISSUE_RACE (
   IDENTIFIER bigint not null identity,
   PARTICIPANT_ID bigint not null,
   RACE_NAME varchar(50)
);

create table CATISSUE_SPECI_ARRAY_CONTENT (
   IDENTIFIER bigint not null identity,
   CONC_IN_MICROGM_PER_MICROLTR double precision,
   INITIAL_QUANTITY double precision,
   POSITION_DIMENSION_ONE integer,
   POSITION_DIMENSION_TWO integer,
   SPECIMEN_ID numeric(20),
   SPECIMEN_ARRAY_ID bigint
);

create table CATISSUE_ADDRESS (
   IDENTIFIER bigint not null identity,
   STREET varchar(255),
   CITY varchar(50),
   STATE varchar(50),
   COUNTRY varchar(50),
   ZIPCODE varchar(30),
   PHONE_NUMBER varchar(50),
   FAX_NUMBER varchar(50)
);

create table CATISSUE_REPORTED_PROBLEM (
   IDENTIFIER bigint not null identity,
   AFFILIATION varchar(255) not null,
   NAME_OF_REPORTER varchar(255) not null,
   REPORTERS_EMAIL_ID varchar(255) not null,
   MESSAGE_BODY varchar(500) not null,
   SUBJECT varchar(255),
   REPORTED_DATE smalldatetime,
   ACTIVITY_STATUS varchar(100),
   COMMENTS varchar(500)
);

create table CATISSUE_SPECIMEN_ARRAY (
   IDENTIFIER bigint not null,
   CREATED_BY_ID bigint,
   SPECIMEN_ARRAY_TYPE_ID bigint,
   DISTRIBUTION_ID bigint,
   AVAILABLE numeric(1,0)
);

create table CATISSUE_SPECIMEN_ARRAY_TYPE (
   IDENTIFIER bigint not null,
   SPECIMEN_CLASS varchar(50)
);

create table CATISSUE_DISTRIBUTED_ITEM (
   IDENTIFIER bigint not null identity,
   QUANTITY double precision,
   SPECIMEN_ID numeric(20),
   DISTRIBUTION_ID bigint
);

create table CATISSUE_PARTICIPANT (
   IDENTIFIER bigint not null identity,
   LAST_NAME varchar(255),
   FIRST_NAME varchar(255),
   MIDDLE_NAME varchar(255),
   BIRTH_DATE smalldatetime,
   GENDER varchar(20),
   GENOTYPE varchar(50),
   ETHNICITY varchar(50),
   SOCIAL_SECURITY_NUMBER varchar(50),
   ACTIVITY_STATUS varchar(50),
   DEATH_DATE smalldatetime,
   VITAL_STATUS varchar(50)
);

create table CATISSUE_SPECIMEN_CHAR (
   IDENTIFIER numeric(20) not null identity,
   TISSUE_SITE varchar(150),
   TISSUE_SIDE varchar(50)
);

/*Ashish Gupta Bug id 2741---Added Association between SCG and Events*/
create table CATISSUE_SPECIMEN_EVENT_PARAM (
   IDENTIFIER bigint not null identity,
   SPECIMEN_COLL_GRP_ID numeric(20),
   SPECIMEN_ID numeric(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(500)
);

create table CATISSUE_STOR_TYPE_SPEC_CLASS (
   STORAGE_TYPE_ID bigint not null,
   SPECIMEN_CLASS varchar(50)
);

create table CATISSUE_COLL_PROT_REG (
   IDENTIFIER numeric(20) not null identity,
   PROTOCOL_PARTICIPANT_ID varchar(255),
   REGISTRATION_DATE smalldatetime,
   PARTICIPANT_ID bigint,
   COLLECTION_PROTOCOL_ID numeric(20),
   ACTIVITY_STATUS varchar(50),
   CONSENT_SIGN_DATE datetime,
   CONSENT_DOC_URL varchar(500),
   CONSENT_WITNESS bigint,
   BARCODE varchar(255),
   DATE_OFFSET integer
);

create table CATISSUE_ABS_SPECI_COLL_GROUP (
   IDENTIFIER numeric(20) not null identity,
   CLINICAL_DIAGNOSIS varchar(150),
   CLINICAL_STATUS varchar(50),
   ACTIVITY_STATUS varchar(50),
   SITE_ID numeric(20)
);

create table CATISSUE_COLL_PROT_EVENT (
   IDENTIFIER numeric(20) not null,
   CLINICAL_STATUS varchar(50),
   COLLECTION_POINT_LABEL varchar(255),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID numeric(20),
   LABELFORMAT varchar(255) default NULL
);

create table CATISSUE_SPECIMEN_COLL_GROUP (
   IDENTIFIER numeric(20) not null,
   NAME varchar(255), 
   BARCODE varchar(255), 
   COMMENTS varchar(2000),
   ENCOUNTER_TIMESTAMP datetime,
   COLLECTION_PROTOCOL_REG_ID numeric(20),
   SURGICAL_PATHOLOGY_NUMBER varchar(50),
   COLLECTION_PROTOCOL_EVENT_ID numeric(20),
   COLLECTION_STATUS varchar(50),
   DATE_OFFSET integer
);

create table CATISSUE_CONTAINER_TYPE (
   IDENTIFIER bigint not null identity,
   CAPACITY_ID bigint,
   NAME varchar(255),
   ONE_DIMENSION_LABEL varchar(255),
   TWO_DIMENSION_LABEL varchar(255),
   COMMENTS varchar(500),
   ACTIVITY_STATUS VARCHAR(50)
);

create table CATISSUE_CAPACITY (
   IDENTIFIER bigint not null identity,
   ONE_DIMENSION_CAPACITY integer,
   TWO_DIMENSION_CAPACITY integer
);

create table CATISSUE_PART_MEDICAL_ID (
   IDENTIFIER bigint not null identity,
   MEDICAL_RECORD_NUMBER varchar(255),
   SITE_ID numeric(20),
   PARTICIPANT_ID bigint
);

create table CATISSUE_STORAGE_CONTAINER (
   IDENTIFIER bigint not null,
   SITE_ID numeric(20),
   TEMPERATURE double precision,
   STORAGE_TYPE_ID bigint
);

create table CATISSUE_CELL_SPE_REVIEW_PARAM (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PER double precision,
   VIABLE_CELL_PERCENTAGE double precision
);

create table CATISSUE_DISTRIBUTION (
   IDENTIFIER bigint not null identity,
   TO_SITE_ID numeric(20),
   DISTRIBUTION_PROTOCOL_ID numeric(20),
   ACTIVITY_STATUS varchar(50),
   SPECIMEN_ID numeric(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(500)
);

create table CATISSUE_PROCEDURE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   URL varchar(255) not null,
   NAME varchar(255) not null
);

create table CATISSUE_DISTRIBUTION_PROTOCOL (
   IDENTIFIER numeric(20) not null
);

create table CATISSUE_DISTRIBUTION_SPEC_REQ (
   IDENTIFIER bigint not null identity,
   SPECIMEN_CLASS varchar(255) not null,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   QUANTITY double precision,
   DISTRIBUTION_PROTOCOL_ID numeric(20)
);

create table CATISSUE_EXTERNAL_IDENTIFIER (
   IDENTIFIER bigint not null identity,
   NAME varchar(255),
   VALUE varchar(255),
   SPECIMEN_ID numeric(20)
);

create table CATISSUE_DEPARTMENT (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique
);

create table CATISSUE_FIXED_EVENT_PARAM (
   IDENTIFIER bigint not null,
   FIXATION_TYPE varchar(50) not null,
   DURATION_IN_MINUTES integer
);

create table CATISSUE_THAW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null
);

create table CATISSUE_FROZEN_EVENT_PARAM (
   IDENTIFIER bigint not null,
   METHOD varchar(50)
);

-- Specimen Model Change

CREATE TABLE CATISSUE_ABSTRACT_SPECIMEN
(                                                                                                                 
      IDENTIFIER numeric(20) NOT NULL identity,    
      SPECIMEN_CLASS varchar(50) NOT NULL,         
      SPECIMEN_TYPE varchar(50),                                                                                                                
      LINEAGE varchar(50),                                                                                                              
      PATHOLOGICAL_STATUS varchar(50),                                                                                                  
      PARENT_SPECIMEN_ID numeric(20),                                                                                                    
      SPECIMEN_CHARACTERISTICS_ID numeric(20),                                                                                      
      INITIAL_QUANTITY double precision
); 

CREATE TABLE CATISSUE_CP_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL,         
     STORAGE_TYPE varchar(255) NOT NULL,      
     COLLECTION_PROTOCOL_EVENT_ID numeric(20),
     LABELFORMAT varchar(255) default NULL                                                                                                      
 );
 
CREATE TABLE CATISSUE_MOL_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL,   
     CONCENTRATION double precision                                                                                                            
);

CREATE TABLE CATISSUE_FLUID_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL                                                                                                  
);

CREATE TABLE CATISSUE_CELL_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL                                                                                                                  
);

CREATE TABLE CATISSUE_TISSUE_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL                                                                                                     
);

CREATE TABLE CATISSUE_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL,
     LABEL varchar(255),                                                                                                               
     AVAILABLE numeric(1,0),                                                                                                         
     BARCODE varchar(255),
     COMMENTS varchar(500),
     ACTIVITY_STATUS varchar(50),                                                                                              
     SPECIMEN_COLLECTION_GROUP_ID numeric(20),     
     REQ_SPECIMEN_ID numeric(20),     
     AVAILABLE_QUANTITY double precision,                                                                                                        
     CREATED_ON_DATE smalldatetime ,                                                                                                             
     COLLECTION_STATUS varchar(50)                                                                                                                
); 

CREATE TABLE CATISSUE_MOLECULAR_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL,  
     CONCENTRATION double precision                                                                                                                   
);

CREATE TABLE CATISSUE_FLUID_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL                                                                                                     
);

CREATE TABLE CATISSUE_CELL_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL                                                                                                          
);

CREATE TABLE CATISSUE_TISSUE_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL                                                                                                        
);

create table CATISSUE_USER (
   IDENTIFIER bigint not null identity,
   EMAIL_ADDRESS varchar(255),
   FIRST_NAME varchar(255),
   LAST_NAME varchar(255),
   LOGIN_NAME varchar(255) not null unique,
   START_DATE smalldatetime,
   ACTIVITY_STATUS varchar(50),
   DEPARTMENT_ID bigint,
   CANCER_RESEARCH_GROUP_ID bigint,
   INSTITUTION_ID bigint,
   ADDRESS_ID bigint,
   CSM_USER_ID bigint,
   STATUS_COMMENT varchar(500),
   FIRST_TIME_LOGIN numeric(1,0) default 1
);

create table CATISSUE_TIS_SPE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PER double precision,
   NECROSIS_PERCENTAGE double precision,
   LYMPHOCYTIC_PERCENTAGE double precision,
   TOTAL_CELLULARITY_PERCENTAGE double precision,
   HISTOLOGICAL_QUALITY varchar(50)
);

create table CATISSUE_ST_CONT_COLL_PROT_REL (
   STORAGE_CONTAINER_ID bigint not null,
   COLLECTION_PROTOCOL_ID numeric(20) not null
);

create table CATISSUE_SPECIMEN_TYPE (
   SPECIMEN_ARRAY_TYPE_ID bigint not null,
   SPECIMEN_TYPE varchar(50)
);

create table CATISSUE_AUDIT_EVENT_QUERY_LOG (
   IDENTIFIER bigint not null identity,
   QUERY_DETAILS varchar(max),  
   AUDIT_EVENT_ID bigint
);

alter table CATISSUE_PERMISSIBLE_VALUE add constraint PK_CATISSUE_PER_VAL_ID primary key (IDENTIFIER);
alter table CATISSUE_CDE add constraint PK_CATISSUE_CDE_PUBLIC_ID primary key (PUBLIC_ID);
alter table CATISSUE_AUDIT_EVENT add constraint PK_CATISSUE_AUDIT_EVENT_ID primary key (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_LOG add constraint PK_CATISSUE_AUDIT_EVE_LOG_ID primary key (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_DETAILS add constraint PK_CATISSUE_AUDIT_EVE_DET_ID primary key (IDENTIFIER);
alter table CATISSUE_COLL_COORDINATORS add constraint PK_CAT_COL_COOR_COL_PROUSERID primary key (COLLECTION_PROTOCOL_ID, USER_ID);
alter table CATISSUE_CANCER_RESEARCH_GROUP add constraint PK_CATISSUE_CAN_RESE_GR_ID primary key (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL add constraint PK_CATISSUE_COLL_PROTO_ID primary key (IDENTIFIER);
alter table CATISSUE_EVENT_PARAM add constraint PK_CATISSUE_EVENT_PARAM_ID primary key (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAM add constraint PK_CATISSUE_TRANS_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_COLL_EVENT_PARAM add constraint PK_CATISSUE_COLL_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_PASSWORD add constraint PK_CATISSUE_PASSWORD_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_BIOHZ_REL add constraint PK_CATISSUE_SPECI_BIO_REL_ID primary key (SPECIMEN_ID, BIOHAZARD_ID);
alter table CATISSUE_MOL_SPE_REVIEW_PARAM add constraint PK_CATISUE_MOL_SPE_REV_PARId primary key (IDENTIFIER);
alter table CATISSUE_STORAGE_TYPE add constraint PK_CATISSUE_STORAGE_TYPE_ID primary key (IDENTIFIER);
alter table CATISSUE_CONTAINER add constraint PK_CATISSUE_CONTAINER_ID primary key (IDENTIFIER);
alter table CATISSUE_SITE add constraint PK_CATISSUE_SITE_ID primary key (IDENTIFIER);
alter table CATISSUE_EMBEDDED_EVENT_PARAM add constraint PK_CATISSUE_EMBED_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_IN_OUT_EVENT_PARAM add constraint PK_CATISSUE_InOut_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_COLL_DISTRIBUTION_REL add constraint PK_CAT_COLL_DIST_PROTO_ID_REL primary key (COLLECTION_PROTOCOL_ID, DISTRIBUTION_PROTOCOL_ID);
alter table CATISSUE_DISPOSAL_EVENT_PARAM add constraint PK_CATISSUE_DISPO_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_REQUIREMENT add constraint PK_CATISSUE_SPECIMEN_REQ_ID primary key (IDENTIFIER);
alter table CATISSUE_INSTITUTION add constraint PK_CATISSUE_INSTITUTION_ID primary key (IDENTIFIER);
alter table CATISSUE_ST_CONT_ST_TYPE_REL add constraint PK_CAT_STG_CONT_TYP_ID_REL primary key (STORAGE_CONTAINER_ID, STORAGE_TYPE_ID);
alter table CATISSUE_STOR_TYPE_HOLDS_TYPE add constraint PK_CAT_HOLDS_STOAGE_TYPE_ID primary key (STORAGE_TYPE_ID, HOLDS_STORAGE_TYPE_ID);
alter table CATISSUE_STORTY_HOLDS_SPARRTY add constraint PK_CAT_SPARTY_STO_SPEC_TYP_ID primary key (STORAGE_TYPE_ID, SPECIMEN_ARRAY_TYPE_ID);
alter table CATISSUE_CONT_HOLDS_SPARRTYPE add constraint PK_CAT_CON_HO_SPAR_ST_SPE_ID primary key (STORAGE_CONTAINER_ID, SPECIMEN_ARRAY_TYPE_ID);
alter table CATISSUE_SPECIMEN_PROTOCOL add constraint PK_CATISSUE_SPECI_PROTO_ID primary key (IDENTIFIER);
alter table CATISSUE_FLUID_SPE_EVENT_PARAM add constraint PK_CAT_FLU_SPE_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_BIOHAZARD add constraint PK_CATISSUE_BIOHAZARD_ID primary key (IDENTIFIER);
alter table CATISSUE_QUANTITY add constraint PK_CATISSUE_QUANTITY_ID primary key (IDENTIFIER);
alter table CATISSUE_SPUN_EVENT_PARAMETERS add constraint PK_CATISUE_SPUN_EVE_PARAM_ID primary key (IDENTIFIER);
alter table CATISSUE_RECEIVED_EVENT_PARAM add constraint PK_CATISUE_RECE_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_RACE add constraint PK_CATISSUE_RACE_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECI_ARRAY_CONTENT add constraint PK_CATISUE_SPECI_ARR_CONT_ID primary key (IDENTIFIER);
alter table CATISSUE_ADDRESS add constraint PK_CATISSUE_ADDRESS_ID primary key (IDENTIFIER);
alter table CATISSUE_REPORTED_PROBLEM add constraint PK_CATISSUE_REPORTED_PROB_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ARRAY add constraint PK_CATISSUE_SPECI_ARRAY_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ARRAY_TYPE add constraint PK_CATISUE_SPECI_ARR_TYPE_ID primary key (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add constraint PK_CATISSUE_DIST_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_PARTICIPANT add constraint PK_CATISSUE_PARTICIPANT_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_CHAR add constraint PK_CATISSUE_SPECIMEN_CHAR_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_EVENT_PARAM add constraint PK_CATISSUE_SPECI_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_COLL_PROT_REG add constraint PK_CATISSUE_COLL_PROT_REG_ID primary key (IDENTIFIER);
alter table CATISSUE_ABS_SPECI_COLL_GROUP add constraint PK_CAT_ABS_SPECI_COLL_GR_ID primary key (IDENTIFIER);
alter table CATISSUE_COLL_PROT_EVENT add constraint PK_CATISSUE_COLL_PROT_EVE_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLL_GROUP add constraint PK_CATISSUE_SPECI_COLL_GR_ID primary key (IDENTIFIER);
alter table CATISSUE_CONTAINER_TYPE add constraint PK_CATISSUE_CONTAINER_TY_ID primary key (IDENTIFIER);
alter table CATISSUE_CAPACITY add constraint PK_CATISSUE_CAPACITY_ID primary key (IDENTIFIER);
alter table CATISSUE_PART_MEDICAL_ID add constraint PK_CAT_PART_MEDICAL_ID_ID primary key (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add constraint PK_CATISSUE_STORAGE_CONT_ID primary key (IDENTIFIER);
alter table CATISSUE_CELL_SPE_REVIEW_PARAM add constraint PK_CATI_CELL_SPE_REV_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add constraint PK_CATISSUE_DISTRIBUTION_ID primary key (IDENTIFIER);
alter table CATISSUE_PROCEDURE_EVENT_PARAM add constraint PK_CATISSUE_PROCE_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_PROTOCOL add constraint PK_CATISSUE_DISTRI_PROTO_ID primary key (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_SPEC_REQ add constraint PK_CATI_DISTRI_SPEC_REQ_ID primary key (IDENTIFIER);
alter table CATISSUE_EXTERNAL_IDENTIFIER add constraint PK_CATISSUE_EXTERNAL_IDEN_ID primary key (IDENTIFIER);
alter table CATISSUE_DEPARTMENT add constraint PK_CATISSUE_DEPARTMENT_ID primary key (IDENTIFIER);
alter table CATISSUE_FIXED_EVENT_PARAM add constraint PK_CATISSUE_FIXED_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_THAW_EVENT_PARAMETERS add constraint PK_CATISUE_THAW_EVE_PARAM_ID primary key (IDENTIFIER);
alter table CATISSUE_FROZEN_EVENT_PARAM add constraint PK_CATISUE_FROZEN_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_ABSTRACT_SPECIMEN add constraint PK_CATISUE_ABSTRACT_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_CP_REQ_SPECIMEN add constraint PK_CATISSUE_CP_REQ_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_MOL_REQ_SPECIMEN add constraint PK_CATISSUE_MOL_REQ_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_FLUID_REQ_SPECIMEN add constraint PK_CATISSUE_FLU_REQ_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_CELL_REQ_SPECIMEN add constraint PK_CATISUE_CELL_REQ_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_TISSUE_REQ_SPECIMEN add constraint PK_CATISSUE_TIS_REQ_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN add constraint PK_CATISSUE_SPECIMEN_ID primary key (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN add constraint PK_CATISSUE_MOLECU_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN add constraint PK_CATISSUE_FLUID_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN add constraint PK_CATISSUE_CELL_SPECIMEN_ID primary key (IDENTIFIER);
alter table CATISSUE_TISSUE_SPECIMEN add constraint PK_CATISSUE_TISSUE_SPECI_ID primary key (IDENTIFIER);
alter table CATISSUE_USER add constraint PK_CATISSUE_USER_ID primary key (IDENTIFIER);
alter table CATISSUE_TIS_SPE_EVENT_PARAM add constraint PK_CATI_TIS_SPE_EVE_PAR_ID primary key (IDENTIFIER);
alter table CATISSUE_ST_CONT_COLL_PROT_REL add constraint PK_CAT_ST_CON_COL_PRO_REL_ID primary key (STORAGE_CONTAINER_ID, COLLECTION_PROTOCOL_ID);
alter table CATISSUE_AUDIT_EVENT_QUERY_LOG add constraint PK_CAT_AUDIT_EVE_QUE_LOG_ID primary key (IDENTIFIER);

alter table CATISSUE_COLL_PROT_EVENT add constraint FK_CAT_COL_PRO_EVE_COLL_PRO_ID foreign key (COLLECTION_PROTOCOL_ID) references catissue_collection_protocol ;
alter table CATISSUE_COLL_PROT_EVENT add constraint FK_CAT_COLL_PROT_EVENT_ID foreign key (IDENTIFIER) references catissue_abs_speci_coll_group ;
alter table CATISSUE_SPECIMEN_COLL_GROUP add constraint FK_CAT_SPEC_COL_GR_Pro_reg_Id foreign key (Collection_Protocol_reg_Id) references CATISSUE_COLL_PROT_REG( IdentIfier ) ;
alter table CATISSUE_SPECIMEN_COLL_GROUP add constraint FK_CAT_spec_coll_Gr_Id foreign key (IdentIfier) references CATISSUE_ABS_SPECI_COLL_GROUP( IdentIfier ) ;
alter table CATISSUE_DISTRIBUTION_SPEC_REQ add constraint FK_CAT_DIST_SPEC_REQ_PROT_ID foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL;
alter table CATISSUE_ABSTRACT_SPECIMEN add constraint FK_CATISSUE_ABST_SPE_CHAR_ID foreign key (SPECIMEN_CHARACTERISTICS_ID) references catissue_specimen_char;
alter table CATISSUE_CP_REQ_SPECIMEN add constraint FK_CAT_CP_REQ_SPEC_CP_EVE_ID foreign key (COLLECTION_PROTOCOL_EVENT_ID) references catissue_coll_prot_event;
alter table CATISSUE_CP_REQ_SPECIMEN add constraint FK_CATISSUE_CP_REQ_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_SPECIMEN;
alter table CATISSUE_MOL_REQ_SPECIMEN add constraint FK_CATISSUE_MOL_REQ_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_CP_REQ_SPECIMEN;
alter table CATISSUE_FLUID_REQ_SPECIMEN add constraint FK_CATISSUE_FLU_REQ_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_CP_REQ_SPECIMEN;
alter table CATISSUE_MOLECULAR_SPECIMEN add constraint FK_CATISSUE_MOLECUL_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN;
alter table CATISSUE_CELL_REQ_SPECIMEN add constraint FK_CATISSUE_CELL_REQ_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_CP_REQ_SPECIMEN;
alter table CATISSUE_TISSUE_REQ_SPECIMEN add constraint FK_CATI_TISSUE_REQ_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_CP_REQ_SPECIMEN;
alter table CATISSUE_SPECIMEN add constraint FK_CATISSUE_SPECI_COLL_GR_ID foreign key (SPECIMEN_COLLECTION_GROUP_ID) references catissue_specimen_coll_group;
alter table CATISSUE_SPECIMEN add constraint FK_CATISUE_SPECI_REQ_SPECI_ID foreign key (REQ_SPECIMEN_ID) references CATISSUE_CP_REQ_SPECIMEN;
alter table CATISSUE_SPECIMEN add constraint FK_CATISSUE_SPECIMEN_ID foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_SPECIMEN;
alter table CATISSUE_FLUID_SPECIMEN add constraint FK_CATISSUE_FLUID_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN;
alter table CATISSUE_CELL_SPECIMEN add constraint FK_CATISSUE_CELL_SPECIMEN_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN;
alter table CATISSUE_TISSUE_SPECIMEN add constraint FK_CATISSUE_TISSUE_SPECI_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN;
alter table CATISSUE_AUDIT_EVENT_QUERY_LOG add constraint FK_CAT_AUDIT_EVENT_QUEUE_ID foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT ;
alter table CATISSUE_COLL_COORDINATORS add constraint FK_CATISSUE_COLL_COORD_PRO_ID foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL ;
alter table CATISSUE_COLL_COORDINATORS  add constraint FK_CATISUE_COLL_COORD_USER_ID foreign key (USER_ID) references CATISSUE_USER ;
alter table CATISSUE_COLLECTION_PROTOCOL  add constraint FK_CATISSUE_COLLEC_PROT_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL  ;
alter table CATISSUE_COLLECTION_PROTOCOL  add constraint FK_CATI_COLL_PROT_PAR_CP_ID foreign key (PARENT_CP_ID) references CATISSUE_COLLECTION_PROTOCOL;
alter table CATISSUE_EVENT_PARAM  add constraint FK_CATISSUE_EVENT_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_TRANSFER_EVENT_PARAM  add constraint FK_CtTra_EVE_PAR_ToSTG_CNT_ID foreign key (TO_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_TRANSFER_EVENT_PARAM  add constraint FK_CtTra_EVE_PAR_FmSTG_CNT_ID foreign key (FROM_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_TRANSFER_EVENT_PARAM  add constraint FK_CATISSUE_TRANS_EVE_PAR_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_STOR_CONT_SPEC_CLASS  add constraint FK_CAT_STG_CNT_SPEC_CLS_ST_ID foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_COLL_EVENT_PARAM  add constraint FK_CATISSUE_COLL_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_PASSWORD  add constraint FK_CATISSUE_PASSWORD_USER_ID foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_SPECIMEN_BIOHZ_REL  add constraint FK_CATISSUE_SPEC_BIOHZ_REL_ID foreign key (BIOHAZARD_ID) references CATISSUE_BIOHAZARD  ;
alter table CATISSUE_SPECIMEN_BIOHZ_REL  add constraint FK_CATISSUE_SPEC_ID_BIOHZ_REL foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_MOL_SPE_REVIEW_PARAM  add constraint FK_CATISUE_MOL_SPE_REV_PAR_ID foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_STORAGE_TYPE  add constraint FK_CATISSUE_STORAGE_TYPE_ID foreign key (IDENTIFIER) references CATISSUE_CONTAINER_TYPE  ;
alter table CATISSUE_CONTAINER  add constraint FK_CATISSUE_CONT_CAPACITY_ID foreign key (CAPACITY_ID) references CATISSUE_CAPACITY  ;
alter table CATISSUE_SITE  add constraint FK_CATISSUE_SITE_ADDRESS_ID foreign key (ADDRESS_ID) references CATISSUE_ADDRESS  ;
alter table CATISSUE_SITE  add constraint FK_CATISSUE_SITE_USER_ID foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_EMBEDDED_EVENT_PARAM  add constraint FK_CATISSUE_EMBED_EVE_PAR_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_IN_OUT_EVENT_PARAM  add constraint FK_CATISSUE_IN_OUT_EVE_PAR_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_COLL_DISTRIBUTION_REL  add constraint FK_CAT_COLL_DISTRI_REL_PRO_ID foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL  ;
alter table CATISSUE_COLL_DISTRIBUTION_REL  add constraint FK_CAT_COLL_DIST_REL_PRO_ID foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL  ;
alter table CATISSUE_DISPOSAL_EVENT_PARAM  add constraint FK_CATISSUE_DISPO_EVE_PAR_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_ST_CONT_ST_TYPE_REL  add constraint FK_CAT_ST_CONT_TYPE_REL_ST_ID foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_ST_CONT_ST_TYPE_REL  add constraint FK_CAT_ST_CONT_TYPE_REL_ID foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_STOR_TYPE_HOLDS_TYPE  add constraint FK_CAT_STOR_TYPE_HOLD_TYPE_ID foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_STOR_TYPE_HOLDS_TYPE  add constraint FK_CATISSUE_STOR_TYPE_HOLD_ID foreign key (HOLDS_STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_STORTY_HOLDS_SPARRTY  add constraint FK_CAT_STO_HOLD_SPAR_TYPE_ID foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_STORTY_HOLDS_SPARRTY  add constraint FK_CAT_STOR_HOLD_ARR_TYPE_ID foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_CONT_HOLDS_SPARRTYPE  add constraint FK_CAT_CONT_HOLDS_ARR_TYPE_ID foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_CONT_HOLDS_SPARRTYPE  add constraint FK_CATISSUE_CONT_HOLD_CONT_ID foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_SPECIMEN_PROTOCOL add constraint FK_CtSPEC_PROT_PRINC_INVST_ID foreign key (PRINCIPAL_INVESTIGATOR_ID) references CATISSUE_USER  ;
alter table CATISSUE_FLUID_SPE_EVENT_PARAM  add constraint FK_CAT_FLUID_SPE_EVE_PAR_ID foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_SPUN_EVENT_PARAMETERS  add constraint FK_CATISSUE_SPUN_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_RECEIVED_EVENT_PARAM  add constraint FK_CATISSUE_RECE_EVE_PAR_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_RACE  add constraint FK_CATISSUE_RACE_PARTICI_ID foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT  ;

/*alter table CATISSUE_COLL_SPECIMEN_REQ  add constraint FK_ foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT  ;*/
/*alter table CATISSUE_COLL_SPECIMEN_REQ  add constraint FK_ foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLL_PROT_EVENT  ;*/

alter table CATISSUE_SPECI_ARRAY_CONTENT  add constraint FK_CATISSUE_SPECI_ARRAY_ID foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY  ;
alter table CATISSUE_SPECI_ARRAY_CONTENT  add constraint FK_CAT_SPECI_ARR_CONT_SPEC_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FK_CAT_SPEC_ARRAY_CREA_BY_ID foreign key (CREATED_BY_ID) references CATISSUE_USER  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FK_CAT_SPECI_ARR_DISTRI_ID foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FK_CATISSUE_SPECIMEN_ARRAY_ID foreign key (IDENTIFIER) references CATISSUE_CONTAINER  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FK_CATISSUE_SPECI_ARR_TYPE_ID foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_SPECIMEN_ARRAY_TYPE  add constraint FK_CAT_SPEC_ARY_TYP_IDENTIFIR foreign key (IDENTIFIER) references CATISSUE_CONTAINER_TYPE  ;
alter table CATISSUE_DISTRIBUTED_ITEM  add constraint FK_CAT_DISTRI_ITEM_SPECI_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_DISTRIBUTED_ITEM  add constraint FK_CATISSUE_DISTRIBUTED_ID foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION  ;
alter table CATISSUE_SPECIMEN_EVENT_PARAM  add constraint FK_CAT_SPECI_EVE_COLL_GR_ID foreign key (SPECIMEN_COLL_GRP_ID) references CATISSUE_SPECIMEN_COLL_GROUP;
alter table CATISSUE_SPECIMEN_EVENT_PARAM  add constraint FK_CAT_SPEC_EVENT_PAR_SPEC_ID foreign key (SPECIMEN_ID) references CATISSUE_ABSTRACT_SPECIMEN;
alter table CATISSUE_SPECIMEN_EVENT_PARAM  add constraint FK_CAT_SPECI_EVE_PAR_USER_ID foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_STOR_TYPE_SPEC_CLASS  add constraint FK_CATISSUE_STOR_TYPE_ID foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_CONTAINER_TYPE  add constraint FK_CATISSUE_CONT_TYPE_CAPA_ID foreign key (CAPACITY_ID) references CATISSUE_CAPACITY  ;
alter table CATISSUE_PART_MEDICAL_ID  add constraint FK_CAT_PART_MEDI_ID_SITE_ID foreign key (SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_PART_MEDICAL_ID  add constraint FK_CAT_PART_MEDI_ID_PARTI_ID foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT  ;
alter table CATISSUE_STORAGE_CONTAINER  add constraint FK_CATISSUE_STORAGE_CONT_ID foreign key (IDENTIFIER) references CATISSUE_CONTAINER  ;
alter table CATISSUE_STORAGE_CONTAINER  add constraint FK_CATISSUE_STOR_CONT_SITE_ID foreign key (SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_STORAGE_CONTAINER  add constraint FK_CAT_STO_CONT_STO_TYPE_ID foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_CELL_SPE_REVIEW_PARAM  add constraint FK_CAT_CELL_SPE_REV_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK_CATISSUE_DISTRI_USER_ID foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK_CATISSUE_DISTRI_PROT_ID foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK_CATISSUE_DISTRI_TO_SITE_ID foreign key (TO_SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK_CATISSUE_DISTRIBU_SPECI_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_PROCEDURE_EVENT_PARAM  add constraint FK_CATISUE_PROCE_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_DISTRIBUTION_PROTOCOL  add constraint FK_CATISSUE_DISTRIBU_PROTO_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL  ;
alter table CATISSUE_EXTERNAL_IDENTIFIER  add constraint FK_CATISSUE_EXT_ID_SPECI_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_FIXED_EVENT_PARAM  add constraint FK_CATISUE_FIXED_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_THAW_EVENT_PARAMETERS  add constraint FK_CATISSUE_THAW_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_COLL_PROT_REG  add constraint FK_CAT_COLL_PROT_REG_PARTI_ID foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT  ;
alter table CATISSUE_COLL_PROT_REG add constraint FK_CAT_COLL_PROT_REG_CON_WITS foreign key (CONSENT_WITNESS) references CATISSUE_USER;
alter table CATISSUE_COLL_PROT_REG  add constraint FK_CAT_COLL_PROT_REG_CO_PR_ID foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL  ;
alter table CATISSUE_FROZEN_EVENT_PARAM  add constraint FK_CAT_FROZEN_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_USER  add constraint FK_CATISSUE_USER_INST_ID foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION  ;
alter table CATISSUE_USER  add constraint FK_CAT_USER_CANC_RESER_GR_ID foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP  ;
alter table CATISSUE_USER  add constraint FK_CATISSUE_USER_ADDRESS_ID foreign key (ADDRESS_ID) references CATISSUE_ADDRESS  ;
alter table CATISSUE_USER  add constraint FK_CATISSUE_USER_DEPT_ID foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT  ;
alter table CATISSUE_TIS_SPE_EVENT_PARAM  add constraint FK_CAT_TIS_SPE_EVE_PARAM_ID foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_ST_CONT_COLL_PROT_REL  add constraint FK_CAT_ST_CONT_ID_COLL_PR_REL foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_ST_CONT_COLL_PROT_REL  add constraint FK_CAT_ST_CON_COL_PROT_ID_REL foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL  ;
alter table CATISSUE_ABS_SPECI_COLL_GROUP add constraint FK_CAT_ABS_SPE_COL_GR_SITE_ID foreign key (SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_SPECIMEN_COLL_GROUP  add constraint FK_CAT_SPEC_COL_GR_PRT_EVE_ID foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLL_PROT_EVENT  ;
alter table CATISSUE_SPECIMEN_TYPE  add constraint FK_CAT_SPE_TYPE_ARRAY_TYPE_ID foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_PERMISSIBLE_VALUE  add constraint FK_CAT_PERMI_VALUE_PARENT_ID foreign key (PARENT_IDENTIFIER) references CATISSUE_PERMISSIBLE_VALUE  ;
alter table CATISSUE_PERMISSIBLE_VALUE  add constraint FK_CAT_PERMIS_VALUE_PUBLIC_ID foreign key (PUBLIC_ID) references CATISSUE_CDE ;
alter table CATISSUE_AUDIT_EVENT  add constraint FK_CATISSUE_AUDIT_EVE_USER_ID foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_AUDIT_EVENT_LOG  add constraint FK_CAT_AUDIT_EVE_LOG_AUDIT_ID foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT  ;
alter table CATISSUE_AUDIT_EVENT_DETAILS  add constraint FK_CAT_AUDIT_EVE_LOG_ID foreign key (AUDIT_EVENT_LOG_ID) references CATISSUE_AUDIT_EVENT_LOG  ;

/* Consent Tracking related drop, create and add foreign key scripts. */
create table CATISSUE_CONSENT_TIER_RESPONSE (
   IDENTIFIER bigint not null identity,
   RESPONSE varchar(255),
   CONSENT_TIER_ID bigint,
   COLL_PROT_REG_ID numeric(20)
);

create table CATISSUE_CONSENT_TIER_STATUS (
   IDENTIFIER bigint not null identity,
   CONSENT_TIER_ID bigint,
   STATUS varchar(255),
   SPECIMEN_ID numeric(20),
   SPECIMEN_COLL_GROUP_ID numeric(20)
);

create table CATISSUE_CONSENT_TIER (
   IDENTIFIER bigint not null identity,
   STATEMENT varchar(500),
   COLL_PROTOCOL_ID numeric(20)
);

alter table CATISSUE_CONSENT_TIER_RESPONSE add constraint PK_CAT_CONSENT_TIER_RESP_ID primary key (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS add constraint PK_CAT_CONSENT_TIER_STAT_ID primary key (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER add constraint PK_CATISSUE_CONSENT_TIER_ID primary key (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_RESPONSE  add constraint FK_CAT_CONSENT_TIER_RESP_ID foreign key (COLL_PROT_REG_ID) references CATISSUE_COLL_PROT_REG (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_RESPONSE  add constraint FK_CATISSUE_CONSENT_TIER_ID foreign key (CONSENT_TIER_ID) references CATISSUE_CONSENT_TIER (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS  add constraint FK_CAT_CONSENT_TIER_GR_ID foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS  add constraint FK_CAT_CON_TIER_STAT_SPEC_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS  add constraint FK_CAT_CON_TIER_ID_STATUS foreign key (CONSENT_TIER_ID) references CATISSUE_CONSENT_TIER (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER  add constraint FK_CAT_CON_TIER_COLL_PROT_ID foreign key (COLL_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

/* Specimen Order */
create table CATISSUE_PATH_CASE_ORDER_ITEM (
   IDENTIFIER bigint not null,
   PATHOLOGICAL_STATUS varchar(255),
   TISSUE_SITE varchar(255),
   SPECIMEN_COLL_GROUP_ID numeric(20)
);

create table CATISSUE_DERIEVED_SP_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ID numeric(20)
);

create table CATISSUE_NEW_SPEC_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_CLASS varchar(255),
   SPECIMEN_TYPE varchar(255)
);

create table CATISSUE_EXISTING_SP_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ID numeric(20)
);

create table CATISSUE_SPECIMEN_ORDER_ITEM (
   IDENTIFIER bigint not null,
   ARRAY_ORDER_ITEM_ID bigint
);

/* Specimen Array Order */

create table CATISSUE_EXIST_SP_AR_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ARRAY_ID bigint
);

create table CATISSUE_NEW_SP_AR_ORDER_ITEM (
   IDENTIFIER bigint not null,
   ARRAY_TYPE_ID bigint,
   NAME varchar(255),
   SPECIMEN_ARRAY_ID bigint
);

create table CATISSUE_SP_ARRAY_ORDER_ITEM (
   IDENTIFIER bigint not null
);

create table CATISSUE_ORDER_ITEM (
   IDENTIFIER bigint not null identity,
   DESCRIPTION varchar(500),
   DISTRIBUTED_ITEM_ID bigint,
   STATUS varchar(50),
   REQUESTED_QUANTITY double precision,
   ORDER_ID bigint
);

create table CATISSUE_ORDER (
   IDENTIFIER bigint not null identity,
   COMMENTS varchar(500),
   DISTRIBUTION_PROTOCOL_ID numeric(20),
   NAME varchar(500),
   REQUESTED_DATE datetime,
   STATUS varchar(50)
);

alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint PK_CAT_PATH_CASE_OR_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint PK_CAT_DER_SP_ORD_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_NEW_SPEC_ORD_ITEM add constraint PK_CAT_NEW_SPEC_ORD_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint PK_CAT_EXIST_SP_ORD_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint PK_CAT_SPECIMEN_ORDER_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint PK_CAT_EXIST_SP_AR_ORD_ITM_ID primary key (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint PK_CAT_NEW_SP_AR_OR_ITM_ID primary key (IDENTIFIER);
alter table CATISSUE_SP_ARRAY_ORDER_ITEM add constraint PK_CAT_SP_ARRAY_OR_ITM_ID primary key (IDENTIFIER);
alter table CATISSUE_ORDER_ITEM add constraint PK_CATISSUE_ORDER_ITEM_ID primary key (IDENTIFIER);
alter table CATISSUE_ORDER add constraint PK_CATISSUE_ORDER_ID primary key (IDENTIFIER);

/* extra for catissue_distribution */
 alter table catissue_distribution add ORDER_ID bigint;
 alter table catissue_distributed_item add  SPECIMEN_ARRAY_ID bigint;    
/* extra finished */

alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint FK_CAT_PTH_CSE_ITM_SPEC_GR_ID foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint FK_CAT_PATH_CASE_ORDER_ITM_ID foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);
alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint FK_CAT_DERIVED_SP_ORD_ITM_ID foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);
alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint FK_CAT_DER_SP_ORD_ITM_SPEC_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_NEW_SPEC_ORD_ITEM add constraint FK_CAT_NEW_SPEC_ORD_ITM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint FK_CAT_EXIST_SP_ORD_ITM_ID foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint FK_CAT_EXT_SP_ORD_ITM_SPEC_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint FK_CAT_SPECIMEN_ORDER_ITM_ID foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint FK_CAT_SPEC_ORD_ITM_IDARR_ORD foreign key (ARRAY_ORDER_ITEM_ID) references CATISSUE_NEW_SP_AR_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint FK_CAT_EXIST_SP_AR_ORD_ITM_ID foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint FK_CAT_EXIST_SP_AR_ID_ORD_ITM foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FK_CT_NW_SP_AR_TYP_ID_ORD_ITM foreign key (ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FK_CAT_NEW_SP_AR_ORDER_ITM_ID foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FK_CAT_NEW_SP_AR_ID_ORDER_ITM foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);
alter table CATISSUE_SP_ARRAY_ORDER_ITEM add constraint FK_CAT_SP_ARRAY_ORD_ITM_ID foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_ORDER_ITEM add constraint FK_CAT_ORDER_ITEM_DIST_ITM_ID foreign key (DISTRIBUTED_ITEM_ID) references CATISSUE_DISTRIBUTED_ITEM (IDENTIFIER);
alter table CATISSUE_ORDER_ITEM add constraint FK_CATISSUE_ORD_ITEM_ORD_ID foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_ORDER add constraint FK_CAT_ORD_DISTR_PROT_ID foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add constraint FK_CAT_DISTRIBUTION_ORD_ID foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add constraint FK_CAT_DIST_ITM_SPEC_ARY_ID foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY;

create table CATISSUE_SPECIMEN_LABEL_COUNT (
   LABEL_COUNT bigint not null
);

INSERT INTO CATISSUE_SPECIMEN_LABEL_COUNT (LABEL_COUNT) VALUES ('0');

/****caTIES Realated Tables - start**********/

create table CATISSUE_REPORT_TEXTCONTENT (
   IDENTIFIER bigint not null,
   REPORT_ID bigint
);

create table CATISSUE_IDENTIFIED_REPORT (
   IDENTIFIER bigint not null,
   DEID_REPORT bigint,
   SCG_ID numeric(20)
);

create table CATISSUE_CONCEPT_REFERENT (
   IDENTIFIER bigint not null identity,
   CONCEPT_ID bigint,
   CONCEPT_CLASSIFICATION_ID bigint,
   DEIDENTIFIED_REPORT_ID bigint,
   END_OFFSET bigint,
   IS_MODIFIER numeric(1,0),
   IS_NEGATED numeric(1,0),
   START_OFFSET bigint
);

create table CATISSUE_REPORT_CONTENT (
   IDENTIFIER bigint not null identity,
   REPORT_DATA varchar(max)
);

create table CATISSUE_REVIEW_PARAMS (
   IDENTIFIER bigint not null identity,
   REVIEWER_ROLE varchar(100),
   REPORT_ID bigint,
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(4000),
   STATUS varchar(100)
);

create table CATISSUE_REPORT_BICONTENT (
   IDENTIFIER bigint not null,
   REPORT_ID bigint
);

create table CATISSUE_REPORT_SECTION (
   IDENTIFIER bigint not null identity,
   DOCUMENT_FRAGMENT varchar(4000),
   END_OFFSET integer,
   NAME varchar(100),
   START_OFFSET integer,
   TEXT_CONTENT_ID bigint
);

create table CATISSUE_DEIDENTIFIED_REPORT (
   IDENTIFIER bigint not null,
   STATUS varchar(100),
   SCG_ID numeric(20)
);

create table CATISSUE_QUARANTINE_PARAMS (
   IDENTIFIER bigint not null identity,
   DEID_REPORT_ID bigint,
   IS_QUARANTINED numeric(1),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(4000),
   STATUS varchar(100)
);


create table CATISSUE_PATHOLOGY_REPORT (
   IDENTIFIER bigint not null identity,
   ACTIVITY_STATUS varchar(100),
   REVIEW_FLAG numeric(1),
   SOURCE_ID numeric(20),
   REPORT_STATUS varchar(100),
   COLLECTION_DATE_TIME smalldatetime
);

create table CATISSUE_REPORT_XMLCONTENT (
   IDENTIFIER bigint not null,
   REPORT_ID bigint
);

create table CATISSUE_REPORT_QUEUE (
   IDENTIFIER bigint not null identity,
   STATUS varchar(50),
   SURGICAL_PATHOLOGY_NUMBER varchar(50),
   PARTICIPANT_NAME varchar(255),
   SITE_NAME varchar(255),
   REPORT_LOADED_DATE smalldatetime,
   REPORT_TEXT varchar(max),
   SPECIMEN_COLL_GRP_ID numeric(20),
   REPORT_COLLECTION_DATE smalldatetime
);

create table CATISSUE_REPORT_PARTICIP_REL(
   PARTICIPANT_ID bigint,
   REPORT_ID bigint
);
create table CATISSUE_CONCEPT (
   IDENTIFIER bigint not null identity,
   CONCEPT_UNIQUE_ID varchar(30),
   NAME varchar(500),
   SEMANTIC_TYPE_ID bigint
);


create table CATISSUE_SEMANTIC_TYPE (
   IDENTIFIER bigint not null identity,
   LABEL varchar(500)
);

create table CATISSUE_CONCEPT_CLASSIFICATN (
   IDENTIFIER bigint not null identity,
   NAME varchar(500)
);

alter table CATISSUE_SPECIMEN_LABEL_COUNT add constraint PK_CAT_SPEC_LBL_CNT_LBL_CNT primary key (LABEL_COUNT);
alter table CATISSUE_REPORT_TEXTCONTENT add constraint PK_CATISSUE_REPORT_TXTCONT_ID primary key (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint PK_CATISSUE_IDENTIFIED_RPT_ID primary key (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint PK_CATISSUE_CO_REFERENT_ID primary key (IDENTIFIER);
alter table CATISSUE_REPORT_CONTENT add constraint PK_CATISSUE_REPORT_CONTENT_ID primary key (IDENTIFIER);
alter table CATISSUE_REVIEW_PARAMS add constraint PK_CATISSUE_REVIEW_PARAMS_ID primary key (IDENTIFIER);
alter table CATISSUE_REPORT_BICONTENT add constraint PK_CATISSUE_RPT_BICONTENT_ID primary key (IDENTIFIER);
alter table CATISSUE_REPORT_SECTION add constraint PK_CATISSUE_RPT_SECTION_ID primary key (IDENTIFIER);
alter table CATISSUE_DEIDENTIFIED_REPORT add constraint PK_CAT_DEIDENTIFIED_RPT_ID primary key (IDENTIFIER);
alter table CATISSUE_QUARANTINE_PARAMS add constraint PK_CAT_QUARANTINE_PARM_ID primary key (IDENTIFIER);
alter table CATISSUE_PATHOLOGY_REPORT add constraint PK_CATISSUE_PATHOLOGY_RPT_ID primary key (IDENTIFIER);
alter table CATISSUE_REPORT_XMLCONTENT add constraint PK_CATISSUE_RPT_XMLCONT_ID primary key (IDENTIFIER);
alter table CATISSUE_REPORT_QUEUE add constraint PK_CATISSUE_REPORT_QUEUE_ID primary key (IDENTIFIER);
alter table CATISSUE_CONCEPT add constraint PK_CATISSUE_CONCEPT_ID primary key (IDENTIFIER);
alter table CATISSUE_SEMANTIC_TYPE add constraint PK_CATISSUE_SEMANTIC_TYPE_ID primary key (IDENTIFIER);
alter table CATISSUE_CONCEPT_CLASSIFICATN add constraint PK_CAT_CONPT_CLASSIFICATN_ID primary key (IDENTIFIER);

alter table CATISSUE_REPORT_TEXTCONTENT add constraint FK_CAT_RPT_TXTCONT_RPT_ID foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_TEXTCONTENT add constraint FK_CATISSUE_REPORT_TXTCONT_ID foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint FK_CATISSUE_IDENTIFIED_RPT_ID foreign key (IDENTIFIER) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint FK_CATISSUE_ID_RPT_DEID_RPT foreign key (DEID_REPORT) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint FK_CATISSUE_ID_RPT_SCG_ID foreign key (SCG_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint FK_CAT_CON_REFE_DEID_RPT_ID foreign key (DEIDENTIFIED_REPORT_ID) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
alter table CATISSUE_REVIEW_PARAMS add constraint FK_CAT_REVIEW_PARAMS_USER_ID foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_REVIEW_PARAMS add constraint FK_CAT_REVIEW_PARAM_RPT_ID foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_BICONTENT add constraint FK_CAT_RPT_BICONTENT_RPT_ID foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_BICONTENT add constraint FK_CATISSUE_RPT_BICONTENT_ID foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
alter table CATISSUE_DEIDENTIFIED_REPORT add constraint FK_CAT_DEIDENTIFIED_RPT_ID foreign key (IDENTIFIER) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_DEIDENTIFIED_REPORT add constraint FK_CAT_DEIDENTIFID_RPT_SCG_ID foreign key (SCG_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_QUARANTINE_PARAMS add constraint FK_CAT_QUARANTINE_PRM_USR_ID foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_QUARANTINE_PARAMS add constraint FK_CAT_QUARAN_PRM_DEID_RPT_ID foreign key (DEID_REPORT_ID) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
alter table CATISSUE_PATHOLOGY_REPORT add constraint FK_CAT_PATHOLOGY_RPT_SRC_ID foreign key (SOURCE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_REPORT_XMLCONTENT add constraint FK_CATISSUE_REPORT_XMLCONT_ID foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
alter table CATISSUE_REPORT_XMLCONTENT add constraint FK_CAT_RPT_XMLCONT_RPT_ID foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_QUEUE add constraint FK_CAT_RPT_Q_SPEC_COLL_GRP_ID foreign key (SPECIMEN_COLL_GRP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_CONCEPT add constraint FK_CAT_CONC_SEMANTIC_TYP_ID foreign key (SEMANTIC_TYPE_ID) references CATISSUE_SEMANTIC_TYPE (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint FK_CAT_CPT_REFERENT_CPT_ID foreign key (CONCEPT_ID) references CATISSUE_CONCEPT (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint FK_CAT_CPT_REFE_CPT_CLASS_ID foreign key (CONCEPT_CLASSIFICATION_ID) references CATISSUE_CONCEPT_CLASSIFICATN (IDENTIFIER);

/****caTIES Realated Tables - end**********/
alter table catissue_consent_tier_status drop CONSTRAINT  FK_CAT_CONSENT_TIER_GR_ID;
alter table catissue_consent_tier_status add CONSTRAINT FK_CAT_CONSENT_TIER_GR_ID FOREIGN KEY (SPECIMEN_COLL_GROUP_ID) REFERENCES catissue_specimen_coll_group (IDENTIFIER);
alter table catissue_specimen_event_param drop CONSTRAINT FK_CAT_SPECI_EVE_COLL_GR_ID;
alter table catissue_specimen_event_param add CONSTRAINT FK_CAT_SPECI_EVE_COLL_GR_ID FOREIGN KEY (SPECIMEN_COLL_GRP_ID) REFERENCES catissue_specimen_coll_group (IDENTIFIER);  
alter table catissue_identified_report drop CONSTRAINT FK_CATISSUE_ID_RPT_SCG_ID;
alter table catissue_identified_report add CONSTRAINT FK_CATISSUE_ID_RPT_SCG_ID FOREIGN KEY (SCG_ID) REFERENCES catissue_specimen_coll_group (IDENTIFIER);  
alter table catissue_deidentified_report drop CONSTRAINT FK_CAT_DEIDENTIFID_RPT_SCG_ID;
alter table catissue_deidentified_report add CONSTRAINT FK_CAT_DEIDENTIFID_RPT_SCG_ID FOREIGN KEY (SCG_ID) REFERENCES catissue_specimen_coll_group (IDENTIFIER); 

/* Suite 1.1 model changes */
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ABSTRACT_POSITION') DROP TABLE CATISSUE_ABSTRACT_POSITION;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_POSITION') DROP TABLE CATISSUE_SPECIMEN_POSITION;
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONTAINER_POSITION') DROP TABLE CATISSUE_CONTAINER_POSITION;


create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER bigint NOT NULL identity,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER
);

create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER bigint NOT NULL,
	SPECIMEN_ID numeric(20),
	CONTAINER_ID bigint
);

create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER bigint NOT NULL,
	PARENT_CONTAINER_ID bigint,
	CONTAINER_ID bigint
);

alter table CATISSUE_ABSTRACT_POSITION add constraint PK_CATISSUE_ABSTRACT_POS_ID primary key (IDENTIFIER);
alter table CATISSUE_SPECIMEN_POSITION add constraint PK_CATISSUE_SPECIMEN_POS_ID primary key (IDENTIFIER);
alter table CATISSUE_CONTAINER_POSITION add constraint PK_CATISSUE_CONTAINER_POS_ID primary key (IDENTIFIER);

/* For specimen Model change*/

/** MSR changes : Start **/

CREATE TABLE CATISSUE_SITE_USERS (
   SITE_ID numeric(20) ,
   USER_ID bigint,
   primary key(SITE_ID, USER_ID)
);

CREATE TABLE CATISSUE_SITE_CP(
   SITE_ID numeric(20) ,
   COLLECTION_PROTOCOL_ID numeric(20),
PRIMARY KEY (SITE_ID,COLLECTION_PROTOCOL_ID) 
 );
 
CREATE TABLE CATISSUE_USER_CP(
  USER_ID bigint ,
  COLLECTION_PROTOCOL_ID numeric(20),
PRIMARY KEY (USER_ID,COLLECTION_PROTOCOL_ID) 
 );

alter table CATISSUE_SPECIMEN_POSITION add constraint FK_CATISSUE_SPECIMEN_POS_ID foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_POSITION;
alter table CATISSUE_SPECIMEN_POSITION add constraint FK_CATISSUE_SPEC_POS_SPEC_ID foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN;
alter table CATISSUE_SPECIMEN_POSITION add constraint FK_CATISSUE_SPEC_POS_CONT_ID foreign key (CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER;
alter table CATISSUE_CONTAINER_POSITION add constraint FK_CATISSUE_CONTAINER_POS_ID foreign key (IDENTIFIER) references CATISSUE_ABSTRACT_POSITION;
alter table CATISSUE_CONTAINER_POSITION add constraint FK_CATISSUE_CONT_POS_CONT_ID foreign key (CONTAINER_ID) references CATISSUE_CONTAINER;
alter table CATISSUE_CONTAINER_POSITION add constraint FK_CAT_CONT_POS_PARNT_CONT_ID foreign key (PARENT_CONTAINER_ID) references CATISSUE_CONTAINER;

/**Added a workaround so that edit of Container,specimen should work. NEED TO REMOVE **/
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_SPECIMEN ADD STORAGE_CONTAINER_IDENTIFIER bigint;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_CONTAINER ADD PARENT_CONTAINER_ID bigint;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY ADD STORAGE_CONTAINER_ID bigint;

ALTER TABLE CATISSUE_SITE_USERS ADD CONSTRAINT FK_CATISSUE_SITE_USRS_USR_ID FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_USERS ADD CONSTRAINT FK_CATISSUE_SITE_USRS_SITE_ID FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);

ALTER TABLE CATISSUE_SITE_CP ADD CONSTRAINT FK_CATISSUE_SITE_CP_SITE_ID FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_CP ADD CONSTRAINT FK_CAT_SITE_CP_COL_PROT_ID FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

ALTER TABLE CATISSUE_USER_CP ADD CONSTRAINT FK_CATISSUE_USER_CP_USER_ID FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_USER_CP ADD CONSTRAINT FK_CAT_USR_CP_COL_PROT_ID FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

/** MSR changes : End **/