
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PERMISSIBLE_VALUE') DROP TABLE CATISSUE_PERMISSIBLE_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CDE') DROP TABLE CATISSUE_CDE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_COORDINATORS') DROP TABLE CATISSUE_COLL_COORDINATORS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CANCER_RESEARCH_GROUP') DROP TABLE CATISSUE_CANCER_RESEARCH_GROUP;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLLECTION_PROTOCOL') DROP TABLE CATISSUE_COLLECTION_PROTOCOL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EVENT_PARAM') DROP TABLE CATISSUE_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_TRANSFER_EVENT_PARAM') DROP TABLE CATISSUE_TRANSFER_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STOR_CONT_SPEC_CLASS') DROP TABLE CATISSUE_STOR_CONT_SPEC_CLASS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_EVENT_PARAM') DROP TABLE CATISSUE_COLL_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PASSWORD') DROP TABLE CATISSUE_PASSWORD;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_BIOHZ_REL') DROP TABLE CATISSUE_SPECIMEN_BIOHZ_REL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_MOL_SPE_REVIEW_PARAM') DROP TABLE CATISSUE_MOL_SPE_REVIEW_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STOR_TYPE_HOLDS_TYPE') DROP TABLE CATISSUE_STOR_TYPE_HOLDS_TYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STORAGE_TYPE') DROP TABLE CATISSUE_STORAGE_TYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONTAINER') DROP TABLE CATISSUE_CONTAINER;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTION_SPEC_REQ') DROP TABLE CATISSUE_DISTRIBUTION_SPEC_REQ;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SITE') DROP TABLE CATISSUE_SITE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EMBEDDED_EVENT_PARAM') DROP TABLE CATISSUE_EMBEDDED_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_IN_OUT_EVENT_PARAM') DROP TABLE CATISSUE_IN_OUT_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_DISTRIBUTION_REL') DROP TABLE CATISSUE_COLL_DISTRIBUTION_REL;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISPOSAL_EVENT_PARAM') DROP TABLE CATISSUE_DISPOSAL_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_REQUIREMENT') DROP TABLE CATISSUE_SPECIMEN_REQUIREMENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_INSTITUTION') DROP TABLE CATISSUE_INSTITUTION;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ST_CONT_ST_TYPE_REL') DROP TABLE CATISSUE_ST_CONT_ST_TYPE_REL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_PROTOCOL') DROP TABLE CATISSUE_SPECIMEN_PROTOCOL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_FLUID_SPE_EVENT_PARAM') DROP TABLE CATISSUE_FLUID_SPE_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_BIOHAZARD') DROP TABLE CATISSUE_BIOHAZARD;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_QUANTITY') DROP TABLE CATISSUE_QUANTITY;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPUN_EVENT_PARAMETERS') DROP TABLE CATISSUE_SPUN_EVENT_PARAMETERS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_RECEIVED_EVENT_PARAM') DROP TABLE CATISSUE_RECEIVED_EVENT_PARAM;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_RACE') DROP TABLE CATISSUE_RACE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECI_ARRAY_CONTENT') DROP TABLE CATISSUE_SPECI_ARRAY_CONTENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ADDRESS') DROP TABLE CATISSUE_ADDRESS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORTED_PROBLEM') DROP TABLE CATISSUE_REPORTED_PROBLEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_ARRAY') DROP TABLE CATISSUE_SPECIMEN_ARRAY;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_ARRAY_TYPE') DROP TABLE CATISSUE_SPECIMEN_ARRAY_TYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTED_ITEM') DROP TABLE CATISSUE_DISTRIBUTED_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PARTICIPANT') DROP TABLE CATISSUE_PARTICIPANT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_CHAR') DROP TABLE CATISSUE_SPECIMEN_CHAR;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_EVENT_PARAM') DROP TABLE CATISSUE_SPECIMEN_EVENT_PARAM;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STOR_TYPE_SPEC_CLASS') DROP TABLE CATISSUE_STOR_TYPE_SPEC_CLASS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_PROT_EVENT') DROP TABLE CATISSUE_COLL_PROT_EVENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONTAINER_TYPE') DROP TABLE CATISSUE_CONTAINER_TYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CAPACITY') DROP TABLE CATISSUE_CAPACITY;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PART_MEDICAL_ID') DROP TABLE CATISSUE_PART_MEDICAL_ID;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STORAGE_CONTAINER') DROP TABLE CATISSUE_STORAGE_CONTAINER;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CELL_SPE_REVIEW_PARAM') DROP TABLE CATISSUE_CELL_SPE_REVIEW_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTION') DROP TABLE CATISSUE_DISTRIBUTION;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PROCEDURE_EVENT_PARAM') DROP TABLE CATISSUE_PROCEDURE_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DISTRIBUTION_PROTOCOL') DROP TABLE CATISSUE_DISTRIBUTION_PROTOCOL;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EXTERNAL_IDENTIFIER') DROP TABLE CATISSUE_EXTERNAL_IDENTIFIER;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DEPARTMENT') DROP TABLE CATISSUE_DEPARTMENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_FIXED_EVENT_PARAM') DROP TABLE CATISSUE_FIXED_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_THAW_EVENT_PARAMETERS') DROP TABLE CATISSUE_THAW_EVENT_PARAMETERS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_COLL_PROT_REG') DROP TABLE CATISSUE_COLL_PROT_REG;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_FROZEN_EVENT_PARAM') DROP TABLE CATISSUE_FROZEN_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_USER') DROP TABLE CATISSUE_USER;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_TIS_SPE_EVENT_PARAM') DROP TABLE CATISSUE_TIS_SPE_EVENT_PARAM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ST_CONT_COLL_PROT_REL') DROP TABLE CATISSUE_ST_CONT_COLL_PROT_REL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_STORTY_HOLDS_SPARRTY') DROP TABLE CATISSUE_STORTY_HOLDS_SPARRTY;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONT_HOLDS_SPARRTYPE') DROP TABLE CATISSUE_CONT_HOLDS_SPARRTYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ABS_SPECI_COLL_GROUP') DROP TABLE CATISSUE_ABS_SPECI_COLL_GROUP;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECI_COLL_REQ_GROUP') DROP TABLE CATISSUE_SPECI_COLL_REQ_GROUP;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_COLL_GROUP') DROP TABLE CATISSUE_SPECIMEN_COLL_GROUP;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_TYPE') DROP TABLE CATISSUE_SPECIMEN_TYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT_QUERY_LOG') DROP TABLE CATISSUE_AUDIT_EVENT_QUERY_LOG;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT') DROP TABLE CATISSUE_AUDIT_EVENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT_LOG') DROP TABLE CATISSUE_AUDIT_EVENT_LOG;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_AUDIT_EVENT_DETAILS') DROP TABLE CATISSUE_AUDIT_EVENT_DETAILS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_LABEL_COUNT') DROP TABLE CATISSUE_SPECIMEN_LABEL_COUNT;

--caTies
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_TEXTCONTENT') DROP TABLE CATISSUE_REPORT_TEXTCONTENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_IDENTIFIED_REPORT') DROP TABLE CATISSUE_IDENTIFIED_REPORT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONCEPT_REFERENT') DROP TABLE CATISSUE_CONCEPT_REFERENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_CONTENT') DROP TABLE CATISSUE_REPORT_CONTENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REVIEW_PARAMS') DROP TABLE CATISSUE_REVIEW_PARAMS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_BICONTENT') DROP TABLE CATISSUE_REPORT_BICONTENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_SECTION') DROP TABLE CATISSUE_REPORT_SECTION;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DEIDENTIFIED_REPORT') DROP TABLE CATISSUE_DEIDENTIFIED_REPORT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_QUARANTINE_PARAMS') DROP TABLE CATISSUE_QUARANTINE_PARAMS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PATHOLOGY_REPORT') DROP TABLE CATISSUE_PATHOLOGY_REPORT;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_XMLCONTENT') DROP TABLE CATISSUE_REPORT_XMLCONTENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_QUEUE') DROP TABLE CATISSUE_REPORT_QUEUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_REPORT_PARTICIP_REL') DROP TABLE CATISSUE_REPORT_PARTICIP_REL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONCEPT') DROP TABLE CATISSUE_CONCEPT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SEMANTIC_TYPE') DROP TABLE CATISSUE_SEMANTIC_TYPE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONCEPT_CLASSIFICATN') DROP TABLE CATISSUE_CONCEPT_CLASSIFICATN;
------ Consent Tracking related drop, create and add foreign key scripts.
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONSENT_TIER_RESPONSE') DROP TABLE CATISSUE_CONSENT_TIER_RESPONSE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONSENT_TIER_STATUS') DROP TABLE CATISSUE_CONSENT_TIER_STATUS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CONSENT_TIER') DROP TABLE CATISSUE_CONSENT_TIER;
---- Specimen Order
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_PATH_CASE_ORDER_ITEM') DROP TABLE CATISSUE_PATH_CASE_ORDER_ITEM;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_DERIEVED_SP_ORD_ITEM') DROP TABLE CATISSUE_DERIEVED_SP_ORD_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_NEW_SPEC_ORD_ITEM') DROP TABLE CATISSUE_NEW_SPEC_ORD_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EXISTING_SP_ORD_ITEM') DROP TABLE CATISSUE_EXISTING_SP_ORD_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN_ORDER_ITEM') DROP TABLE CATISSUE_SPECIMEN_ORDER_ITEM;
---- Specimen Array Order
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_NEW_SP_AR_ORDER_ITEM') DROP TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_EXIST_SP_AR_ORD_ITEM') DROP TABLE CATISSUE_EXIST_SP_AR_ORD_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SP_ARRAY_ORDER_ITEM') DROP TABLE CATISSUE_SP_ARRAY_ORDER_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ORDER_ITEM') DROP TABLE CATISSUE_ORDER_ITEM;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ORDER') DROP TABLE CATISSUE_ORDER;
--Specimen Model change
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_ABSTRACT_SPECIMEN') DROP TABLE CATISSUE_ABSTRACT_SPECIMEN;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SPECIMEN') DROP TABLE CATISSUE_SPECIMEN;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_CP_REQ_SPECIMEN') DROP TABLE CATISSUE_CP_REQ_SPECIMEN;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_fluid_req_specimen') DROP TABLE catissue_fluid_req_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_fluid_specimen') DROP TABLE catissue_fluid_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_cell_specimen') DROP TABLE catissue_cell_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_cell_req_specimen') DROP TABLE catissue_cell_req_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_tissue_specimen') DROP TABLE catissue_tissue_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_tissue_req_specimen') DROP TABLE catissue_tissue_req_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_mol_req_specimen') DROP TABLE catissue_mol_req_specimen;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'catissue_molecular_specimen') DROP TABLE catissue_molecular_specimen;


create table CATISSUE_PERMISSIBLE_VALUE (
   IDENTIFIER bigint not null identity,
   CONCEPT_CODE varchar(40),
   DEFINITION varchar(500),
   PARENT_IDENTIFIER bigint,
   VALUE varchar(225),
   PUBLIC_ID varchar(30),
   primary key (IDENTIFIER)
);
create table CATISSUE_CDE (
   PUBLIC_ID varchar(30) not null,
   LONG_NAME varchar(200),
   DEFINITION varchar(500),
   VERSION varchar(50),
   LAST_UPDATED smalldatetime,
   primary key (PUBLIC_ID)
);



create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER bigint not null identity,
   IP_ADDRESS varchar(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(500),
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER bigint not null identity,
   OBJECT_IDENTIFIER bigint,
   OBJECT_NAME varchar(50),
   EVENT_TYPE varchar(50),
   AUDIT_EVENT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER bigint not null identity,
   ELEMENT_NAME varchar(150),
   PREVIOUS_VALUE varchar(150),
   CURRENT_VALUE varchar(500),
   AUDIT_EVENT_LOG_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLL_COORDINATORS (
   COLLECTION_PROTOCOL_ID numeric(20) not null,
   USER_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_ID, USER_ID)
);
create table CATISSUE_CANCER_RESEARCH_GROUP (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL (
   IDENTIFIER numeric(20) not null,
   ALIQUOT_IN_SAME_CONTAINER numeric(1,0),
   UNSIGNED_CONSENT_DOC_URL varchar(500),
   CONSENTS_WAIVED numeric(1,0),
   CP_TYPE varchar(50) default NULL,
   PARENT_CP_ID numeric(20) default NULL,
   SEQUENCE_NUMBER integer,	
   STUDY_CALENDAR_EVENT_POINT DOUBLE PRECISION default NULL,
   primary key (IDENTIFIER)
);
create table CATISSUE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_TRANSFER_EVENT_PARAM (
   IDENTIFIER bigint not null,
   FROM_POSITION_DIMENSION_ONE integer,
   FROM_POSITION_DIMENSION_TWO integer,
   TO_POSITION_DIMENSION_ONE integer,
   TO_POSITION_DIMENSION_TWO integer,
   TO_STORAGE_CONTAINER_ID bigint,
   FROM_STORAGE_CONTAINER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_STOR_CONT_SPEC_CLASS (
   STORAGE_CONTAINER_ID bigint not null,
   SPECIMEN_CLASS varchar(50)
);
create table CATISSUE_COLL_EVENT_PARAM (
   IDENTIFIER bigint not null,
   COLLECTION_PROCEDURE varchar(50),
   CONTAINER varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_PASSWORD (
   IDENTIFIER bigint not null identity,
   PASSWORD varchar(255),
   UPDATE_DATE smalldatetime,
   USER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_BIOHZ_REL (
   BIOHAZARD_ID bigint not null,
   SPECIMEN_ID numeric(20) not null,
   primary key (SPECIMEN_ID, BIOHAZARD_ID)
);
create table CATISSUE_MOL_SPE_REVIEW_PARAM (
   IDENTIFIER bigint not null,
   GEL_IMAGE_URL varchar(255),
   QUALITY_INDEX varchar(50),
   LANE_NUMBER varchar(50),
   GEL_NUMBER integer,
   ABSORBANCE_AT_260 double precision,
   ABSORBANCE_AT_280 double precision,
   RATIO_28S_TO_18S double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_TYPE (
   IDENTIFIER bigint not null,
   DEFAULT_TEMPERATURE DOUBLE PRECISION,
   primary key (IDENTIFIER)
);
create table CATISSUE_CONTAINER (
   IDENTIFIER bigint not null identity,
   ACTIVITY_STATUS varchar(50),
   BARCODE varchar(255) unique,
   CAPACITY_ID bigint,
   COMMENTS varchar(500),
   "FULL" numeric(1,0),
   NAME varchar(255) unique not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_SITE (
   IDENTIFIER numeric(20) not null identity,
   NAME varchar(255) not null unique,
   TYPE varchar(50),
   EMAIL_ADDRESS varchar(255),
   USER_ID bigint,
   ACTIVITY_STATUS varchar(50),
   ADDRESS_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_EMBEDDED_EVENT_PARAM (
   IDENTIFIER bigint not null,
   EMBEDDING_MEDIUM varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_IN_OUT_EVENT_PARAM (
   IDENTIFIER bigint not null,
   STORAGE_STATUS varchar(100) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLL_DISTRIBUTION_REL (
   COLLECTION_PROTOCOL_ID numeric(20) not null,
   DISTRIBUTION_PROTOCOL_ID numeric(20) not null,
   primary key (COLLECTION_PROTOCOL_ID, DISTRIBUTION_PROTOCOL_ID)
);
create table CATISSUE_DISPOSAL_EVENT_PARAM (
   IDENTIFIER bigint not null,
   REASON varchar(255),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null identity,
   SPECIMEN_CLASS varchar(255) not null,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   QUANTITY_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_INSTITUTION (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_ST_CONT_ST_TYPE_REL (
   STORAGE_CONTAINER_ID bigint not null,
   STORAGE_TYPE_ID bigint not null,
   primary key (STORAGE_CONTAINER_ID, STORAGE_TYPE_ID)
);
create table CATISSUE_STOR_TYPE_HOLDS_TYPE (
   STORAGE_TYPE_ID bigint not null,
   HOLDS_STORAGE_TYPE_ID bigint not null,
   primary key (STORAGE_TYPE_ID, HOLDS_STORAGE_TYPE_ID)
);

create table CATISSUE_STORTY_HOLDS_SPARRTY (
   STORAGE_TYPE_ID bigint not null,
   SPECIMEN_ARRAY_TYPE_ID bigint not null,
   primary key (STORAGE_TYPE_ID, SPECIMEN_ARRAY_TYPE_ID)
);

create table CATISSUE_CONT_HOLDS_SPARRTYPE (
   STORAGE_CONTAINER_ID bigint not null,
   SPECIMEN_ARRAY_TYPE_ID bigint not null,
   primary key (STORAGE_CONTAINER_ID, SPECIMEN_ARRAY_TYPE_ID)
);

create table CATISSUE_SPECIMEN_PROTOCOL (
   IDENTIFIER numeric(20) not null identity,
   PRINCIPAL_INVESTIGATOR_ID bigint,
   TITLE varchar(255) not null unique,
   SHORT_TITLE varchar(255),
   IRB_IDENTIFIER varchar(255),
   START_DATE smalldatetime,
   END_DATE smalldatetime,
   ENROLLMENT integer,
   DESCRIPTION_URL varchar(255),
   ACTIVITY_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_FLUID_SPE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   CELL_COUNT double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_BIOHAZARD (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique,
   COMMENTS varchar(500),
   TYPE varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_QUANTITY (
   IDENTIFIER bigint not null identity,
   QUANTITY double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPUN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   GFORCE double precision,
   DURATION_IN_MINUTES integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_RECEIVED_EVENT_PARAM (
   IDENTIFIER bigint not null,
   RECEIVED_QUALITY varchar(255),
   primary key (IDENTIFIER)
);
create table CATISSUE_RACE (
   IDENTIFIER bigint not null identity,
   PARTICIPANT_ID bigint not null,
   RACE_NAME varchar(50),
   primary key (IDENTIFIER)
);
/*create table CATISSUE_COLL_SPECIMEN_REQ (
   COLLECTION_PROTOCOL_EVENT_ID bigint not null,
   SPECIMEN_REQUIREMENT_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_EVENT_ID, SPECIMEN_REQUIREMENT_ID)
);*/
create table CATISSUE_SPECI_ARRAY_CONTENT (
   IDENTIFIER bigint not null identity,
   CONC_IN_MICROGM_PER_MICROLTR double precision,
   INITIAL_QUANTITY double precision,
   POSITION_DIMENSION_ONE integer,
   POSITION_DIMENSION_TWO integer,
   SPECIMEN_ID numeric(20),
   SPECIMEN_ARRAY_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_ADDRESS (
   IDENTIFIER bigint not null identity,
   STREET varchar(255),
   CITY varchar(50),
   STATE varchar(50),
   COUNTRY varchar(50),
   ZIPCODE varchar(30),
   PHONE_NUMBER varchar(50),
   FAX_NUMBER varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORTED_PROBLEM (
   IDENTIFIER bigint not null identity,
   AFFILIATION varchar(255) not null,
   NAME_OF_REPORTER varchar(255) not null,
   REPORTERS_EMAIL_ID varchar(255) not null,
   MESSAGE_BODY varchar(500) not null,
   SUBJECT varchar(255),
   REPORTED_DATE smalldatetime,
   ACTIVITY_STATUS varchar(100),
   COMMENTS varchar(500),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_ARRAY (
   IDENTIFIER bigint not null,
   CREATED_BY_ID bigint,
   SPECIMEN_ARRAY_TYPE_ID bigint,
   DISTRIBUTION_ID bigint,
   AVAILABLE numeric(1,0),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_ARRAY_TYPE (
   IDENTIFIER bigint not null,
   SPECIMEN_CLASS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTED_ITEM (
   IDENTIFIER bigint not null identity,
   QUANTITY double precision,
   SPECIMEN_ID numeric(20),
   DISTRIBUTION_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_PARTICIPANT (
   IDENTIFIER bigint not null identity,
   LAST_NAME varchar(255),
   FIRST_NAME varchar(255),
   MIDDLE_NAME varchar(255),
   BIRTH_DATE smalldatetime,
   GENDER varchar(20),
   GENOTYPE varchar(50),
   ETHNICITY varchar(50),
   SOCIAL_SECURITY_NUMBER varchar(50) unique,
   ACTIVITY_STATUS varchar(50),
   DEATH_DATE smalldatetime,
   VITAL_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_CHAR (
   IDENTIFIER numeric(20) not null identity,
   TISSUE_SITE varchar(150),
   TISSUE_SIDE varchar(50),
   primary key (IDENTIFIER)
);
/*Ashish Gupta Bug id 2741---Added Association between SCG and Events*/
create table CATISSUE_SPECIMEN_EVENT_PARAM (
   IDENTIFIER bigint not null identity,
   SPECIMEN_COLL_GRP_ID numeric(20),
   SPECIMEN_ID numeric(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(500),
   primary key (IDENTIFIER)
);
create table CATISSUE_STOR_TYPE_SPEC_CLASS (
   STORAGE_TYPE_ID bigint not null,
   SPECIMEN_CLASS varchar(50)
);
create table CATISSUE_CONTAINER_TYPE (
   IDENTIFIER bigint not null identity,
   CAPACITY_ID bigint,
   NAME varchar(255) unique,
   ONE_DIMENSION_LABEL varchar(255),
   TWO_DIMENSION_LABEL varchar(255),
   COMMENTS varchar(500),
   ACTIVITY_STATUS VARCHAR(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_CAPACITY (
   IDENTIFIER bigint not null identity,
   ONE_DIMENSION_CAPACITY integer,
   TWO_DIMENSION_CAPACITY integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_PART_MEDICAL_ID (
   IDENTIFIER bigint not null identity,
   MEDICAL_RECORD_NUMBER varchar(255),
   SITE_ID numeric(20),
   PARTICIPANT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER (
   IDENTIFIER bigint not null,
   SITE_ID numeric(20),
   TEMPERATURE double precision,
   STORAGE_TYPE_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_CELL_SPE_REVIEW_PARAM (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PER double precision,
   VIABLE_CELL_PERCENTAGE double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION (
   IDENTIFIER bigint not null identity,
   TO_SITE_ID numeric(20),
   DISTRIBUTION_PROTOCOL_ID numeric(20),
   ACTIVITY_STATUS varchar(50),
   SPECIMEN_ID numeric(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(500),
   primary key (IDENTIFIER)
);
create table CATISSUE_PROCEDURE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   URL varchar(255) not null,
   NAME varchar(255) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION_PROTOCOL (
   IDENTIFIER numeric(20) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION_SPEC_REQ (
   IDENTIFIER bigint not null identity,
   SPECIMEN_CLASS varchar(255) not null,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   QUANTITY double precision,
   DISTRIBUTION_PROTOCOL_ID numeric(20),
   primary key (IDENTIFIER),
   CONSTRAINT FK_DISTRIBUTION_PROTOCOL FOREIGN KEY (DISTRIBUTION_PROTOCOL_ID) REFERENCES CATISSUE_DISTRIBUTION_PROTOCOL
);
create table CATISSUE_EXTERNAL_IDENTIFIER (
   IDENTIFIER bigint not null identity,
   NAME varchar(255),
   VALUE varchar(255),
   SPECIMEN_ID numeric(20),
   primary key (IDENTIFIER)
);

create table CATISSUE_DEPARTMENT (
   IDENTIFIER bigint not null identity,
   NAME varchar(255) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_FIXED_EVENT_PARAM (
   IDENTIFIER bigint not null,
   FIXATION_TYPE varchar(50) not null,
   DURATION_IN_MINUTES integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_THAW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLL_PROT_REG (
   IDENTIFIER numeric(20) not null identity,
   PROTOCOL_PARTICIPANT_ID varchar(255),
   REGISTRATION_DATE smalldatetime,
   PARTICIPANT_ID bigint,
   COLLECTION_PROTOCOL_ID numeric(20),
   ACTIVITY_STATUS varchar(50),
   CONSENT_SIGN_DATE datetime,
   CONSENT_DOC_URL varchar(500),
   CONSENT_WITNESS bigint,
   BARCODE varchar(255) unique,
   DATE_OFFSET integer,	
   primary key (IDENTIFIER)
);
create table CATISSUE_FROZEN_EVENT_PARAM (
   IDENTIFIER bigint not null,
   METHOD varchar(50),
   primary key (IDENTIFIER)
);

create table CATISSUE_USER (
   IDENTIFIER bigint not null identity,
   EMAIL_ADDRESS varchar(255),
   FIRST_NAME varchar(255),
   LAST_NAME varchar(255),
   LOGIN_NAME varchar(255) not null unique,
   START_DATE smalldatetime,
   ACTIVITY_STATUS varchar(50),
   DEPARTMENT_ID bigint,
   CANCER_RESEARCH_GROUP_ID bigint,
   INSTITUTION_ID bigint,
   ADDRESS_ID bigint,
   CSM_USER_ID bigint,
   STATUS_COMMENT varchar(500),
   FIRST_TIME_LOGIN numeric(1,0) default 1,
   primary key (IDENTIFIER)
);
create table CATISSUE_TIS_SPE_EVENT_PARAM (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PER double precision,
   NECROSIS_PERCENTAGE double precision,
   LYMPHOCYTIC_PERCENTAGE double precision,
   TOTAL_CELLULARITY_PERCENTAGE double precision,
   HISTOLOGICAL_QUALITY varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_ST_CONT_COLL_PROT_REL (
   STORAGE_CONTAINER_ID bigint not null,
   COLLECTION_PROTOCOL_ID numeric(20) not null,
   primary key (STORAGE_CONTAINER_ID, COLLECTION_PROTOCOL_ID)
);

create table CATISSUE_ABS_SPECI_COLL_GROUP (
   IDENTIFIER numeric(20) not null identity,
   CLINICAL_DIAGNOSIS varchar(150),
   CLINICAL_STATUS varchar(50),
   ACTIVITY_STATUS varchar(50),
   SITE_ID numeric(20),
   primary key (IDENTIFIER)
);

create table CATISSUE_COLL_PROT_EVENT (
   IDENTIFIER numeric(20) not null identity,
   CLINICAL_STATUS varchar(50),
   COLLECTION_POINT_LABEL varchar(255),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID numeric(20),
   LABELFORMAT varchar(255) default NULL,
   primary key (IDENTIFIER),
   unique (COLLECTION_PROTOCOL_ID,COLLECTION_POINT_LABEL),
   CONSTRAINT FK7AE7715948304401 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES catissue_collection_protocol,
   CONSTRAINT FK_PARENT_COLL_PROT_EVENT FOREIGN KEY (IDENTIFIER) REFERENCES catissue_abs_speci_coll_group
);

create table CATISSUE_SPECIMEN_COLL_GROUP (
   IDENTIFIER numeric(20) not null identity,
   NAME varchar(255) unique, 
   BARCODE varchar(255) unique, 
   COMMENTS varchar(2000),
   ENCOUNTER_TIMESTAMP datetime,
   COLLECTION_PROTOCOL_REG_ID numeric(20),
   SURGICAL_PATHOLOGY_NUMBER varchar(50),
   COLLECTION_PROTOCOL_EVENT_ID numeric(20),
   COLLECTION_STATUS varchar(50),
   DATE_OFFSET integer, 	
   primary key (IDENTIFIER),
   CONSTRAINT fkDebaf1677e07c4ac FOREIGN KEY( Collection_Protocol_reg_Id ) REFERENCES CATISSUE_COLL_PROT_REG( IdentIfier ),
   CONSTRAINT fk_Parent_spec_coll_Group FOREIGN KEY( IdentIfier ) REFERENCES CATISSUE_ABS_SPECI_COLL_GROUP( IdentIfier )
);
CREATE TABLE CATISSUE_ABSTRACT_SPECIMEN
(                                                                                                                 
      IDENTIFIER numeric(20) NOT NULL identity,    
	  SPECIMEN_CLASS varchar(50) NOT NULL,         
      SPECIMEN_TYPE varchar(50),                                                                                                                
      LINEAGE varchar(50),                                                                                                              
      PATHOLOGICAL_STATUS varchar(50),                                                                                                  
      PARENT_SPECIMEN_ID numeric(20),                                                                                                    
      SPECIMEN_CHARACTERISTICS_ID numeric(20),                                                                                      
      INITIAL_QUANTITY double precision,                                                                                                        
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK1674810456906F39 FOREIGN KEY (SPECIMEN_CHARACTERISTICS_ID) REFERENCES catissue_specimen_char                 
); 

CREATE TABLE CATISSUE_CP_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,         
     STORAGE_TYPE varchar(255) NOT NULL,      
	 COLLECTION_PROTOCOL_EVENT_ID numeric(20),
	 LABELFORMAT varchar(255) default NULL,
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK111110456906F39 FOREIGN KEY (COLLECTION_PROTOCOL_EVENT_ID) REFERENCES catissue_coll_prot_event,
	 CONSTRAINT FK_PARENT_CP_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_SPECIMEN
 ); 
 
 CREATE TABLE CATISSUE_MOL_REQ_SPECIMEN
 (                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,   
	 CONCENTRATION double precision,
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_MOL_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN                
 );
CREATE TABLE CATISSUE_FLUID_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,       
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_FLUID_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN
);
CREATE TABLE CATISSUE_CELL_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_CELL_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN
                
);
CREATE TABLE CATISSUE_TISSUE_REQ_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_TISSUE_REQ_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_CP_REQ_SPECIMEN               
);

CREATE TABLE CATISSUE_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,
     LABEL varchar(255) unique,                                                                                                               
     AVAILABLE numeric(1,0),                                                                                                         
     BARCODE varchar(255) unique,
     COMMENTS varchar(500),
     ACTIVITY_STATUS varchar(50),                                                                                              
     SPECIMEN_COLLECTION_GROUP_ID numeric(20),     
     REQ_SPECIMEN_ID numeric(20),     
     AVAILABLE_QUANTITY double precision,                                                                                                        
     CREATED_ON_DATE smalldatetime ,                                                                                                             
     COLLECTION_STATUS varchar(50),                                                                                                    
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK1674810433BF33C5 FOREIGN KEY (SPECIMEN_COLLECTION_GROUP_ID) REFERENCES catissue_specimen_coll_group,
     CONSTRAINT FK_REQ_SPECIMEN_ID FOREIGN KEY (REQ_SPECIMEN_ID) REFERENCES CATISSUE_CP_REQ_SPECIMEN,
 	 CONSTRAINT FK_PARENT_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_SPECIMEN
   ); 
   
   CREATE TABLE CATISSUE_MOLECULAR_SPECIMEN
   (                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,  
     CONCENTRATION double precision,     
     PRIMARY KEY  (IDENTIFIER),                                                                                                                     
     CONSTRAINT FK_MOLECULAR_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN             
   );

CREATE TABLE CATISSUE_FLUID_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_FLUID_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN                
);
CREATE TABLE CATISSUE_CELL_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_CELL_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN
);
CREATE TABLE CATISSUE_TISSUE_SPECIMEN
(                                                                                                                 
     IDENTIFIER numeric(20) NOT NULL identity,       
      PRIMARY KEY  (IDENTIFIER),                                                                                                                     
      CONSTRAINT FK_TISSUE_SPECIMEN FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN
);
create table CATISSUE_SPECIMEN_TYPE (
   SPECIMEN_ARRAY_TYPE_ID bigint not null,
   SPECIMEN_TYPE varchar(50)
);
create table CATISSUE_AUDIT_EVENT_QUERY_LOG (
   IDENTIFIER bigint not null identity,
   QUERY_DETAILS varchar(max),  
   AUDIT_EVENT_ID bigint,
   primary key (IDENTIFIER)
);

alter table CATISSUE_AUDIT_EVENT_QUERY_LOG add constraint FK62DC439DBC7298A9 foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT ;
alter table CATISSUE_COLL_COORDINATORS add constraint FKE490E33A48304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL ;
alter table CATISSUE_COLL_COORDINATORS  add constraint FKE490E33A2206F20F foreign key (USER_ID) references CATISSUE_USER ;
alter table CATISSUE_COLLECTION_PROTOCOL  add constraint FK32DC439DBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL  ;
alter table CATISSUE_COLLECTION_PROTOCOL  add constraint FK32DC439DBC7298B9 foreign key (PARENT_CP_ID) references CATISSUE_COLLECTION_PROTOCOL;
alter table CATISSUE_EVENT_PARAM  add constraint FK90C79AECBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_TRANSFER_EVENT_PARAM  add constraint FK71F9AC103C2DAC61 foreign key (TO_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_TRANSFER_EVENT_PARAM  add constraint FK71F9AC1099DF0A92 foreign key (FROM_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_TRANSFER_EVENT_PARAM  add constraint FK71F9AC10BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_STOR_CONT_SPEC_CLASS  add constraint FKE7F5E8C2B3DFB11D foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_COLL_EVENT_PARAM  add constraint FKF9888F91BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_PASSWORD  add constraint FKDE1F38972206F20F foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_SPECIMEN_BIOHZ_REL  add constraint FK7A3F5539F398D480 foreign key (BIOHAZARD_ID) references CATISSUE_BIOHAZARD  ;
alter table CATISSUE_SPECIMEN_BIOHZ_REL  add constraint FK7A3F553960773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_MOL_SPE_REVIEW_PARAM  add constraint FK5280ECEBC7298A9 foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_STORAGE_TYPE  add constraint FKE9A0629ABC7298A9 foreign key (IDENTIFIER) references CATISSUE_CONTAINER_TYPE  ;
alter table CATISSUE_CONTAINER  add constraint FK49B8DE5DAC76C0 foreign key (CAPACITY_ID) references CATISSUE_CAPACITY  ;
alter table CATISSUE_SITE  add constraint FKB024C3436CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS  ;
alter table CATISSUE_SITE  add constraint FKB024C3432206F20F foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_EMBEDDED_EVENT_PARAM  add constraint FKD356182FBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_IN_OUT_EVENT_PARAM  add constraint FK4F0FAEB9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_COLL_DISTRIBUTION_REL  add constraint FK1483BCB56B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL  ;
alter table CATISSUE_COLL_DISTRIBUTION_REL  add constraint FK1483BCB548304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL  ;
alter table CATISSUE_DISPOSAL_EVENT_PARAM  add constraint FK1BC818D6BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_ST_CONT_ST_TYPE_REL  add constraint FK703B902159A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_ST_CONT_ST_TYPE_REL  add constraint FK703B9021B3DFB11D foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_STOR_TYPE_HOLDS_TYPE  add constraint FK185C50B59A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_STOR_TYPE_HOLDS_TYPE  add constraint FK185C50B81236791 foreign key (HOLDS_STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_STORTY_HOLDS_SPARRTY  add constraint FK70F57E4459A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_STORTY_HOLDS_SPARRTY  add constraint FK70F57E44ECE89343 foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_CONT_HOLDS_SPARRTYPE  add constraint FKDC7E31E2ECE89343 foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_CONT_HOLDS_SPARRTYPE  add constraint FKDC7E31E2B3DFB11D foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_SPECIMEN_PROTOCOL add constraint FKB8481373870EB740 foreign key (PRINCIPAL_INVESTIGATOR_ID) references CATISSUE_USER  ;
alter table CATISSUE_FLUID_SPE_EVENT_PARAM  add constraint FK70565D20BC7298A9 foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_SPUN_EVENT_PARAMETERS  add constraint FK312D77BCBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_RECEIVED_EVENT_PARAM  add constraint FKA7139D06BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_RACE  add constraint FKB0242ECD87E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT  ;
/*alter table CATISSUE_COLL_SPECIMEN_REQ  add constraint FK860E6ABEBE10F0CE foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT  ;*/
/*alter table CATISSUE_COLL_SPECIMEN_REQ  add constraint FK860E6ABE53B01F66 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLL_PROT_EVENT  ;*/
alter table CATISSUE_SPECI_ARRAY_CONTENT  add constraint FKBEA9D458C4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY  ;
alter table CATISSUE_SPECI_ARRAY_CONTENT  add constraint FKBEA9D45860773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FKECBF8B3E64B129CC foreign key (CREATED_BY_ID) references CATISSUE_USER  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FKECBF8B3EF8278B6 foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FKECBF8B3EBC7298A9 foreign key (IDENTIFIER) references CATISSUE_CONTAINER  ;
alter table CATISSUE_SPECIMEN_ARRAY  add constraint FKECBF8B3EECE89343 foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_SPECIMEN_ARRAY_TYPE  add constraint FKD36E0B9BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_CONTAINER_TYPE  ;
alter table CATISSUE_DISTRIBUTED_ITEM  add constraint FKA7C3ED4B60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_DISTRIBUTED_ITEM  add constraint FKA7C3ED4BF8278B6 foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION  ;
alter table CATISSUE_SPECIMEN_EVENT_PARAM  add constraint FK753F33AD8CA560D1 foreign key (SPECIMEN_COLL_GRP_ID) references CATISSUE_SPECIMEN_COLL_GROUP;
alter table CATISSUE_SPECIMEN_EVENT_PARAM  add constraint FK753F33AD60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_ABSTRACT_SPECIMEN;
alter table CATISSUE_SPECIMEN_EVENT_PARAM  add constraint FK753F33AD2206F20F foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_STOR_TYPE_SPEC_CLASS  add constraint FK1BCF33BA59A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_CONTAINER_TYPE  add constraint FKCBBC9954DAC76C0 foreign key (CAPACITY_ID) references CATISSUE_CAPACITY  ;
alter table CATISSUE_PART_MEDICAL_ID  add constraint FK349E77F9A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_PART_MEDICAL_ID  add constraint FK349E77F987E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT  ;
alter table CATISSUE_STORAGE_CONTAINER  add constraint FK28429D01BC7298A9 foreign key (IDENTIFIER) references CATISSUE_CONTAINER  ;
alter table CATISSUE_STORAGE_CONTAINER  add constraint FK28429D01A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_STORAGE_CONTAINER  add constraint FK28429D0159A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE  ;
alter table CATISSUE_CELL_SPE_REVIEW_PARAM  add constraint FK52F40EDEBC7298A9 foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK542766802206F20F foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK542766806B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK542766801DBE834F foreign key (TO_SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_DISTRIBUTION  add constraint FK5427668060773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_PROCEDURE_EVENT_PARAM  add constraint FKEC6B4260BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_DISTRIBUTION_PROTOCOL  add constraint FKC8999977BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL  ;
alter table CATISSUE_EXTERNAL_IDENTIFIER  add constraint FK5CF2FA2160773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN  ;
alter table CATISSUE_FIXED_EVENT_PARAM  add constraint FKE0F1781BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_THAW_EVENT_PARAMETERS  add constraint FKD8890A48BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_COLL_PROT_REG  add constraint FK5EB25F1387E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT  ;
alter table CATISSUE_COLL_PROT_REG  add constraint FK5EB25F1348304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL  ;
alter table CATISSUE_FROZEN_EVENT_PARAM  add constraint FK52627245BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAM  ;
alter table CATISSUE_USER  add constraint FKB025CFC71792AD22 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION  ;
alter table CATISSUE_USER  add constraint FKB025CFC7FFA96920 foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP  ;
alter table CATISSUE_USER  add constraint FKB025CFC76CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS  ;
alter table CATISSUE_USER  add constraint FKB025CFC7F30C2528 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT  ;
alter table CATISSUE_TIS_SPE_EVENT_PARAM  add constraint FKBB9648F4BC7298A9 foreign key (IDENTIFIER) references CATISSUE_EVENT_PARAM  ;
alter table CATISSUE_ST_CONT_COLL_PROT_REL  add constraint FK3AE9FCA7B3DFB11D foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER  ;
alter table CATISSUE_ST_CONT_COLL_PROT_REL  add constraint FK3AE9FCA748304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL  ;
alter table CATISSUE_ABS_SPECI_COLL_GROUP add constraint FKDEBAF167A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE  ;
alter table CATISSUE_SPECIMEN_COLL_GROUP  add constraint FKDEBAF16753B01F66 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLL_PROT_EVENT  ;
alter table CATISSUE_SPECIMEN_TYPE  add constraint FKFF69C195ECE89343 foreign key (SPECIMEN_ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE  ;
alter table CATISSUE_PERMISSIBLE_VALUE  add constraint FK57DDCE153B5435E foreign key (PARENT_IDENTIFIER) references CATISSUE_PERMISSIBLE_VALUE  ;
alter table CATISSUE_PERMISSIBLE_VALUE  add constraint FK57DDCE1FC56C2B1 foreign key (PUBLIC_ID) references CATISSUE_CDE ;
alter table CATISSUE_AUDIT_EVENT  add constraint FKACAF697A2206F20F foreign key (USER_ID) references CATISSUE_USER  ;
alter table CATISSUE_AUDIT_EVENT_LOG  add constraint FK8BB672DF77F0B904 foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT  ;
alter table CATISSUE_AUDIT_EVENT_DETAILS  add constraint FK5C07745D34FFD77F foreign key (AUDIT_EVENT_LOG_ID) references CATISSUE_AUDIT_EVENT_LOG  ;

alter table CATISSUE_COLL_PROT_REG add constraint FK5EB25F13A0FF79D4 foreign key (CONSENT_WITNESS) references CATISSUE_USER;

/* Consent Tracking related drop, create and add foreign key scripts. */

create table CATISSUE_CONSENT_TIER_RESPONSE (
   IDENTIFIER bigint not null identity,
   RESPONSE varchar(255),
   CONSENT_TIER_ID bigint,
   COLL_PROT_REG_ID numeric(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_CONSENT_TIER_STATUS (
   IDENTIFIER bigint not null identity,
   CONSENT_TIER_ID bigint,
   STATUS varchar(255),
   SPECIMEN_ID numeric(20),
   SPECIMEN_COLL_GROUP_ID numeric(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_CONSENT_TIER (
   IDENTIFIER bigint not null identity,
   STATEMENT varchar(500),
   COLL_PROTOCOL_ID numeric(20),
   primary key (IDENTIFIER)
);

alter table CATISSUE_CONSENT_TIER_RESPONSE  add constraint FKFB1995FD4AD77FCB foreign key (COLL_PROT_REG_ID) references CATISSUE_COLL_PROT_REG (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_RESPONSE  add constraint FKFB1995FD17B9953 foreign key (CONSENT_TIER_ID) references CATISSUE_CONSENT_TIER (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS  add constraint FKF74E94AEF69249F7 foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS  add constraint FKF74E94AE60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER_STATUS  add constraint FKF74E94AE17B9953 foreign key (CONSENT_TIER_ID) references CATISSUE_CONSENT_TIER (IDENTIFIER);
alter table CATISSUE_CONSENT_TIER  add constraint FK51725303E36A4B4F foreign key (COLL_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

/* Specimen Order */

create table CATISSUE_PATH_CASE_ORDER_ITEM (
   IDENTIFIER bigint not null,
   PATHOLOGICAL_STATUS varchar(255),
   TISSUE_SITE varchar(255),
   SPECIMEN_COLL_GROUP_ID numeric(20),
   primary key (IDENTIFIER)
);

create table CATISSUE_DERIEVED_SP_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ID numeric(20),
   primary key (IDENTIFIER)
);


create table CATISSUE_NEW_SPEC_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_CLASS varchar(255),
   SPECIMEN_TYPE varchar(255),
   primary key (IDENTIFIER)
);

create table CATISSUE_EXISTING_SP_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ID numeric(20),
   primary key (IDENTIFIER)
);

create table CATISSUE_SPECIMEN_ORDER_ITEM (
   IDENTIFIER bigint not null,
   ARRAY_ORDER_ITEM_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_EXIST_SP_AR_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ARRAY_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_NEW_SP_AR_ORDER_ITEM (
   IDENTIFIER bigint not null,
   ARRAY_TYPE_ID bigint,
   NAME varchar(255),
   SPECIMEN_ARRAY_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_SP_ARRAY_ORDER_ITEM (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);

create table CATISSUE_ORDER_ITEM (
   IDENTIFIER bigint not null identity,
   DESCRIPTION varchar(500),
   DISTRIBUTED_ITEM_ID bigint,
   STATUS varchar(50),
   REQUESTED_QUANTITY double precision,
   ORDER_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_ORDER (
   IDENTIFIER bigint not null identity,
   COMMENTS varchar(500),
   DISTRIBUTION_PROTOCOL_ID numeric(20),
   NAME varchar(500),
   REQUESTED_DATE datetime,
   STATUS varchar(50),
   primary key (IDENTIFIER)
);


/* extra for catissue_distribution */
 alter table catissue_distribution add ORDER_ID bigint;
 alter table catissue_distributed_item add  SPECIMEN_ARRAY_ID bigint;    
/* extra finished */

alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint FKBD5029D5F69249F7 foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_PATH_CASE_ORDER_ITEM add constraint FKBD5029D5BC7298A9 foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);

alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint FK3742152BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);
alter table CATISSUE_DERIEVED_SP_ORD_ITEM add constraint FK3742152B60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

alter table CATISSUE_NEW_SPEC_ORD_ITEM add constraint FK_NW_SPEC_ODR_ITM foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint FKF8B855EEBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXISTING_SP_ORD_ITEM add constraint FKF8B855EE60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint FK48C3B39FBC7298A9 foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ORDER_ITEM add constraint FK48C3B39F83505A30 foreign key (ARRAY_ORDER_ITEM_ID) references CATISSUE_NEW_SP_AR_ORDER_ITEM (IDENTIFIER);


alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint FKE3823170BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add constraint FKE3823170C4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FKC5C92CCBCE5FBC3A foreign key (ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FKC5C92CCBBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add constraint FKC5C92CCBC4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

alter table CATISSUE_SP_ARRAY_ORDER_ITEM add constraint FK_SP_ARAY_ODR_ITM foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_ORDER_ITEM add constraint FKB501E88060975C0B foreign key (DISTRIBUTED_ITEM_ID) references CATISSUE_DISTRIBUTED_ITEM (IDENTIFIER);
alter table CATISSUE_ORDER_ITEM add constraint FKB501E880783867CC foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_ORDER add constraint FK543F22B26B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);

alter table CATISSUE_DISTRIBUTION add constraint FK54276680783867CC foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add constraint FKA7C3ED4BC4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY;


create table CATISSUE_SPECIMEN_LABEL_COUNT (
   LABEL_COUNT bigint not null,
   primary key (LABEL_COUNT)
);
INSERT INTO CATISSUE_SPECIMEN_LABEL_COUNT (LABEL_COUNT) VALUES ('0');

/****caTIES Realated Tables - start**********/

create table CATISSUE_REPORT_TEXTCONTENT (
   IDENTIFIER bigint not null,
   REPORT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_IDENTIFIED_REPORT (
   IDENTIFIER bigint not null,
   DEID_REPORT bigint,
   SCG_ID numeric(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_CONCEPT_REFERENT (
   IDENTIFIER bigint not null identity,
   CONCEPT_ID bigint,
   CONCEPT_CLASSIFICATION_ID bigint,
   DEIDENTIFIED_REPORT_ID bigint,
   END_OFFSET bigint,
   IS_MODIFIER numeric(1,0),
   IS_NEGATED numeric(1,0),
   START_OFFSET bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORT_CONTENT (
   IDENTIFIER bigint not null identity,
   REPORT_DATA varchar(max),
   primary key (IDENTIFIER)
);
create table CATISSUE_REVIEW_PARAMS (
   IDENTIFIER bigint not null identity,
   REVIEWER_ROLE varchar(100),
   REPORT_ID bigint,
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(4000),
   STATUS varchar(100),
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORT_BICONTENT (
   IDENTIFIER bigint not null,
   REPORT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORT_SECTION (
   IDENTIFIER bigint not null identity,
   DOCUMENT_FRAGMENT varchar(4000),
   END_OFFSET integer,
   NAME varchar(100),
   START_OFFSET integer,
   TEXT_CONTENT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_DEIDENTIFIED_REPORT (
   IDENTIFIER bigint not null,
   STATUS varchar(100),
   SCG_ID numeric(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_QUARANTINE_PARAMS (
   IDENTIFIER bigint not null identity,
   DEID_REPORT_ID bigint,
   IS_QUARANTINED numeric(1),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS varchar(4000),
   STATUS varchar(100),
   primary key (IDENTIFIER)
);
create table CATISSUE_PATHOLOGY_REPORT (
   IDENTIFIER bigint not null identity,
   ACTIVITY_STATUS varchar(100),
   REVIEW_FLAG numeric(1),
   SOURCE_ID numeric(20),
   REPORT_STATUS varchar(100),
   COLLECTION_DATE_TIME smalldatetime,
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORT_XMLCONTENT (
   IDENTIFIER bigint not null,
   REPORT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORT_QUEUE (
   IDENTIFIER bigint not null identity,
   STATUS varchar(50),
   SURGICAL_PATHOLOGY_NUMBER varchar(50),
   PARTICIPANT_NAME varchar(255),
   SITE_NAME varchar(255),
   REPORT_LOADED_DATE smalldatetime,
   REPORT_TEXT varchar(max),
   SPECIMEN_COLL_GRP_ID numeric(20),
   REPORT_COLLECTION_DATE smalldatetime,
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORT_PARTICIP_REL(
   PARTICIPANT_ID bigint,
   REPORT_ID bigint
);
create table CATISSUE_CONCEPT (
   IDENTIFIER bigint not null identity,
   CONCEPT_UNIQUE_ID varchar(30),
   NAME varchar(500),
   SEMANTIC_TYPE_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_SEMANTIC_TYPE (
   IDENTIFIER bigint not null identity,
   LABEL varchar(500),
   primary key (IDENTIFIER)
);

create table CATISSUE_CONCEPT_CLASSIFICATN (
   IDENTIFIER bigint not null identity,
   NAME varchar(500),
   primary key (IDENTIFIER)
);


alter table CATISSUE_REPORT_TEXTCONTENT add constraint FKD74882FD91092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_TEXTCONTENT add constraint FKD74882FDBC7298A9 foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint FK6A2246DCBC7298A9 foreign key (IDENTIFIER) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint FK6A2246DC752DD177 foreign key (DEID_REPORT) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
alter table CATISSUE_IDENTIFIED_REPORT add constraint FK6A2246DC91741663 foreign key (SCG_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint FK799CCA7E9F96B363 foreign key (DEIDENTIFIED_REPORT_ID) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
alter table CATISSUE_REVIEW_PARAMS add constraint FK5311FFF62206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_REVIEW_PARAMS add constraint FK5311FFF691092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_BICONTENT add constraint FK8A9A4EE391092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_BICONTENT add constraint FK8A9A4EE3BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
alter table CATISSUE_DEIDENTIFIED_REPORT add constraint FKCDD0DF7BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_DEIDENTIFIED_REPORT add constraint FKCDD0DF7B91741663 foreign key (SCG_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_QUARANTINE_PARAMS add constraint FK3C12AE3B2206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_QUARANTINE_PARAMS add constraint FK3C12AE3B3EEC14E3 foreign key (DEID_REPORT_ID) references CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
alter table CATISSUE_PATHOLOGY_REPORT add constraint FK904EC9F040DCD7BF foreign key (SOURCE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_REPORT_XMLCONTENT add constraint FK4597C9F1BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REPORT_CONTENT (IDENTIFIER);
alter table CATISSUE_REPORT_XMLCONTENT add constraint FK4597C9F191092806 foreign key (REPORT_ID) references CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);
alter table CATISSUE_REPORT_QUEUE add constraint FK214246228CA560D1 foreign key (SPECIMEN_COLL_GRP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_CONCEPT add constraint FKC1A3C8CC7F0C2C7 foreign key (SEMANTIC_TYPE_ID) references CATISSUE_SEMANTIC_TYPE (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint FK799CCA7EA9816272 foreign key (CONCEPT_ID) references CATISSUE_CONCEPT (IDENTIFIER);
alter table CATISSUE_CONCEPT_REFERENT add constraint FK799CCA7E72C371DD foreign key (CONCEPT_CLASSIFICATION_ID) references CATISSUE_CONCEPT_CLASSIFICATN (IDENTIFIER);


/****caTIES Realated Tables - end**********/

/* Suite 1.1 model changes */
create table CATISSUE_ABSTRACT_POSITION (
	IDENTIFIER bigint NOT NULL identity,
	POSITION_DIMENSION_ONE INTEGER,
	POSITION_DIMENSION_TWO INTEGER,
	primary key (IDENTIFIER)
);

create table CATISSUE_SPECIMEN_POSITION(
	IDENTIFIER bigint NOT NULL identity,
	SPECIMEN_ID numeric(20),
	CONTAINER_ID bigint,
	primary key (IDENTIFIER),
	CONSTRAINT FK_SPECIMEN_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_SPECIMEN FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN,
	CONSTRAINT FK_STORAGE_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_STORAGE_CONTAINER
);

create table CATISSUE_CONTAINER_POSITION(
	IDENTIFIER bigint NOT NULL identity,
	PARENT_CONTAINER_ID bigint,
	CONTAINER_ID bigint,
	primary key (IDENTIFIER),
	CONSTRAINT FK_CONTAINER_POSITION FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_ABSTRACT_POSITION,
	CONSTRAINT FK_CONTAINER FOREIGN KEY (CONTAINER_ID) REFERENCES CATISSUE_CONTAINER,
	CONSTRAINT FK_OCCUPIED_CONTAINER FOREIGN KEY (PARENT_CONTAINER_ID) REFERENCES CATISSUE_CONTAINER
);



/**Added a workaround so that edit of Container,specimen should work. NEED TO REMOVE **/
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_SPECIMEN ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_SPECIMEN ADD STORAGE_CONTAINER_IDENTIFIER bigint;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_ONE integer;
ALTER TABLE CATISSUE_CONTAINER ADD POSITION_DIMENSION_TWO integer;
ALTER TABLE CATISSUE_CONTAINER ADD PARENT_CONTAINER_ID bigint;
ALTER TABLE CATISSUE_SPECIMEN_ARRAY ADD STORAGE_CONTAINER_ID bigint;

/* For specimen Model change*/



/** MSR changes : Start **/

CREATE TABLE CATISSUE_SITE_USERS (
   SITE_ID numeric(20) ,
   USER_ID bigint ,
   PRIMARY KEY (SITE_ID, USER_ID)
);

CREATE TABLE CATISSUE_SITE_CP(
   SITE_ID numeric(20) ,
   COLLECTION_PROTOCOL_ID numeric(20) ,
   PRIMARY KEY (SITE_ID,COLLECTION_PROTOCOL_ID)
 );

CREATE TABLE CATISSUE_USER_CP(
  USER_ID bigint ,
  COLLECTION_PROTOCOL_ID numeric(20) ,
  PRIMARY KEY (USER_ID,COLLECTION_PROTOCOL_ID)
 );

ALTER TABLE CATISSUE_SITE_USERS ADD CONSTRAINT FK1 FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_USERS ADD CONSTRAINT FK2 FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);

ALTER TABLE CATISSUE_SITE_CP ADD CONSTRAINT FK3 FOREIGN KEY (SITE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);
ALTER TABLE CATISSUE_SITE_CP ADD CONSTRAINT FK4 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

ALTER TABLE CATISSUE_USER_CP ADD CONSTRAINT FK5 FOREIGN KEY (USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);
ALTER TABLE CATISSUE_USER_CP ADD CONSTRAINT FK6 FOREIGN KEY (COLLECTION_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);

/** MSR changes : End **/

