-- SET storage_engine=InnoDB;
-- SET FOREIGN_KEY_CHECKS=0;

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_OBJECT_TYPE_INFO') DROP TABLE DYEXTN_OBJECT_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_COLUMN_PROPERTIES') DROP TABLE DYEXTN_COLUMN_PROPERTIES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_USERDEFINED_DE') DROP TABLE DYEXTN_USERDEFINED_DE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CONSTRAINT_PROPERTIES') DROP TABLE DYEXTN_CONSTRAINT_PROPERTIES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_PERMISSIBLE_VALUE') DROP TABLE DYEXTN_PERMISSIBLE_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CHECK_BOX') DROP TABLE DYEXTN_CHECK_BOX;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_TABLE_PROPERTIES') DROP TABLE DYEXTN_TABLE_PROPERTIES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ENTITY_MAP_CONDNS') DROP TABLE DYEXTN_ENTITY_MAP_CONDNS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_INTEGER_CONCEPT_VALUE') DROP TABLE DYEXTN_INTEGER_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_STRING_CONCEPT_VALUE') DROP TABLE DYEXTN_STRING_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_BOOLEAN_TYPE_INFO') DROP TABLE DYEXTN_BOOLEAN_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_BOOLEAN_CONCEPT_VALUE') DROP TABLE DYEXTN_BOOLEAN_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DE_FILE_ATTR_RECORD_VALUES') DROP TABLE DE_FILE_ATTR_RECORD_VALUES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ABSTRACT_METADATA') DROP TABLE DYEXTN_ABSTRACT_METADATA;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_STRING_TYPE_INFO') DROP TABLE DYEXTN_STRING_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_SHORT_CONCEPT_VALUE') DROP TABLE DYEXTN_SHORT_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_FLOAT_TYPE_INFO') DROP TABLE DYEXTN_FLOAT_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_FILE_UPLOAD') DROP TABLE DYEXTN_FILE_UPLOAD;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_BARR_CONCEPT_VALUE') DROP TABLE DYEXTN_BARR_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ENTITY') DROP TABLE DYEXTN_ENTITY;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_INTEGER_TYPE_INFO') DROP TABLE DYEXTN_INTEGER_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_TAGGED_VALUE') DROP TABLE DYEXTN_TAGGED_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DE_OBJECT_ATTR_RECORD_VALUES') DROP TABLE DE_OBJECT_ATTR_RECORD_VALUES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_COMBOBOX') DROP TABLE DYEXTN_COMBOBOX;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CADSR_VALUE_DOMAIN_INFO') DROP TABLE DYEXTN_CADSR_VALUE_DOMAIN_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_PRIMITIVE_ATTRIBUTE') DROP TABLE DYEXTN_PRIMITIVE_ATTRIBUTE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ASSOCIATION') DROP TABLE DYEXTN_ASSOCIATION;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ENTITY_MAP') DROP TABLE DYEXTN_ENTITY_MAP;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CADSRDE') DROP TABLE DYEXTN_CADSRDE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DOUBLE_TYPE_INFO') DROP TABLE DYEXTN_DOUBLE_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_SELECT_CONTROL') DROP TABLE DYEXTN_SELECT_CONTROL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ENTITY_GROUP_REL') DROP TABLE DYEXTN_ENTITY_GROUP_REL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DATABASE_PROPERTIES') DROP TABLE DYEXTN_DATABASE_PROPERTIES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_FILE_TYPE_INFO') DROP TABLE DYEXTN_FILE_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_FILE_EXTENSIONS') DROP TABLE DYEXTN_FILE_EXTENSIONS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_LONG_TYPE_INFO') DROP TABLE DYEXTN_LONG_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_FLOAT_CONCEPT_VALUE') DROP TABLE DYEXTN_FLOAT_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_TEXTFIELD') DROP TABLE DYEXTN_TEXTFIELD;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ROLE') DROP TABLE DYEXTN_ROLE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_RULE') DROP TABLE DYEXTN_RULE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DATE_TYPE_INFO') DROP TABLE DYEXTN_DATE_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ATTRIBUTE_TYPE_INFO') DROP TABLE DYEXTN_ATTRIBUTE_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ENTITY_MAP_RECORD') DROP TABLE DYEXTN_ENTITY_MAP_RECORD;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ASSO_DISPLAY_ATTR') DROP TABLE DYEXTN_ASSO_DISPLAY_ATTR;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_TEXTAREA') DROP TABLE DYEXTN_TEXTAREA;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ENTITY_GROUP') DROP TABLE DYEXTN_ENTITY_GROUP;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DATA_ELEMENT') DROP TABLE DYEXTN_DATA_ELEMENT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DOUBLE_CONCEPT_VALUE') DROP TABLE DYEXTN_DOUBLE_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_LIST_BOX') DROP TABLE DYEXTN_LIST_BOX;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CONTAINMENT_CONTROL') DROP TABLE DYEXTN_CONTAINMENT_CONTROL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CONTROL') DROP TABLE DYEXTN_CONTROL;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_LONG_CONCEPT_VALUE') DROP TABLE DYEXTN_LONG_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_FORM_CONTEXT') DROP TABLE DYEXTN_FORM_CONTEXT;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ATTRIBUTE') DROP TABLE DYEXTN_ATTRIBUTE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_RULE_PARAMETER') DROP TABLE DYEXTN_RULE_PARAMETER;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DATE_CONCEPT_VALUE') DROP TABLE DYEXTN_DATE_CONCEPT_VALUE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_VIEW') DROP TABLE DYEXTN_VIEW;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_BYTE_ARRAY_TYPE_INFO') DROP TABLE DYEXTN_BYTE_ARRAY_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_SEMANTIC_PROPERTY') DROP TABLE DYEXTN_SEMANTIC_PROPERTY;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_ATTRIBUTE_RECORD') DROP TABLE DYEXTN_ATTRIBUTE_RECORD;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DATA_GRID') DROP TABLE DYEXTN_DATA_GRID;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DE_COLL_ATTR_RECORD_VALUES') DROP TABLE DE_COLL_ATTR_RECORD_VALUES;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_NUMERIC_TYPE_INFO') DROP TABLE DYEXTN_NUMERIC_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_SHORT_TYPE_INFO') DROP TABLE DYEXTN_SHORT_TYPE_INFO;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_CONTAINER') DROP TABLE DYEXTN_CONTAINER;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_RADIOBUTTON') DROP TABLE DYEXTN_RADIOBUTTON;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DYEXTN_DATEPICKER') DROP TABLE DYEXTN_DATEPICKER;


--SET FOREIGN_KEY_CHECKS=1;

create table DYEXTN_OBJECT_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_COLUMN_PROPERTIES (
   IDENTIFIER bigint not null,
   PRIMITIVE_ATTRIBUTE_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_USERDEFINED_DE (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_CONSTRAINT_PROPERTIES (
   IDENTIFIER bigint not null,
   SOURCE_ENTITY_KEY varchar(255),
   TARGET_ENTITY_KEY varchar(255),
   ASSOCIATION_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_PERMISSIBLE_VALUE (
   IDENTIFIER bigint not null identity,
   DESCRIPTION varchar(255),
   ATTRIBUTE_TYPE_INFO_ID bigint,
   USER_DEF_DE_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_CHECK_BOX (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_TABLE_PROPERTIES (
   IDENTIFIER bigint not null,
   ENTITY_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_ENTITY_MAP_CONDNS (
   IDENTIFIER numeric(20) not null identity,
   STATIC_RECORD_ID bigint,
   TYPE_ID bigint,
   FORM_CONTEXT_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_INTEGER_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE integer,
   primary key (IDENTIFIER)
);
create table DYEXTN_STRING_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_BOOLEAN_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_BOOLEAN_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE tinyint default NULL,
   primary key (IDENTIFIER)
);
create table DE_FILE_ATTR_RECORD_VALUES (
   IDENTIFIER bigint not null identity,
   CONTENT_TYPE varchar(255),
   FILE_CONTENT VARBINARY(MAX),
   FILE_NAME varchar(255),
   RECORD_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_ABSTRACT_METADATA (
   IDENTIFIER numeric(20) not null identity,
   CREATED_DATE datetime,
   DESCRIPTION varchar(8000),
   LAST_UPDATED datetime,
   NAME varchar(8000),
   PUBLIC_ID varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_STRING_TYPE_INFO (
   IDENTIFIER bigint not null,
   MAX_SIZE integer,
   primary key (IDENTIFIER)
);
create table DYEXTN_SHORT_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE smallint,
   primary key (IDENTIFIER)
);
create table DYEXTN_FLOAT_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_FILE_UPLOAD (
   IDENTIFIER bigint not null,
   NO_OF_COLUMNS integer,
   primary key (IDENTIFIER)
);
create table DYEXTN_BARR_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_ENTITY (
   IDENTIFIER numeric(20) not null,
   DATA_TABLE_STATE integer,
   IS_ABSTRACT tinyint default NULL,
   PARENT_ENTITY_ID numeric(20),
   INHERITANCE_STRATEGY integer,
   DISCRIMINATOR_COLUMN_NAME varchar(255),
   DISCRIMINATOR_VALUE varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_INTEGER_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_TAGGED_VALUE (
   IDENTIFIER bigint not null identity,
   T_KEY varchar(255),
   T_VALUE varchar(255),
   ABSTRACT_METADATA_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DE_OBJECT_ATTR_RECORD_VALUES (
   IDENTIFIER bigint not null identity,
   CLASS_NAME varchar(255),
   OBJECT_CONTENT VARBINARY(MAX),
   RECORD_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_COMBOBOX (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_CADSR_VALUE_DOMAIN_INFO (
   IDENTIFIER bigint not null identity,
   DATATYPE varchar(255),
   NAME varchar(255),
   TYPE varchar(255),
   PRIMITIVE_ATTRIBUTE_ID numeric(20),
   primary key (IDENTIFIER)
);


create table DYEXTN_PRIMITIVE_ATTRIBUTE (
   IDENTIFIER numeric(20) not null,
   IS_COLLECTION tinyint CONSTRAINT [DF_DYEXTN_PRIMITIVE_ATTRIBUTE_IS_COLLECTION] DEFAULT (NULL),
   IS_IDENTIFIED tinyint default NULL,
   IS_PRIMARY_KEY tinyint default NULL,
   IS_NULLABLE tinyint default NULL,
   primary key (IDENTIFIER)
);


create table DYEXTN_ASSOCIATION (
   IDENTIFIER numeric(20) not null,
   DIRECTION varchar(255),
   TARGET_ENTITY_ID numeric(20),
   SOURCE_ROLE_ID bigint,
   TARGET_ROLE_ID bigint,
   IS_SYSTEM_GENERATED tinyint default NULL,
   primary key (IDENTIFIER)
);
create table DYEXTN_ENTITY_MAP (
   IDENTIFIER bigint not null identity,
   CONTAINER_ID bigint,
   STATUS varchar(10),
   STATIC_ENTITY_ID numeric(20),
   CREATED_DATE datetime,
   CREATED_BY varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_CADSRDE (
   IDENTIFIER bigint not null,
   PUBLIC_ID varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_DOUBLE_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_SELECT_CONTROL (
   IDENTIFIER bigint not null,
   SEPARATOR_STRING varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_ENTITY_GROUP_REL (
   ENTITY_GROUP_ID numeric(20) not null,
   ENTITY_ID numeric(20) not null,
   primary key (ENTITY_ID, ENTITY_GROUP_ID)
);
create table DYEXTN_DATABASE_PROPERTIES (
   IDENTIFIER bigint not null identity,
   NAME varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_FILE_TYPE_INFO (
   IDENTIFIER bigint not null,
   MAX_FILE_SIZE float,
   primary key (IDENTIFIER)
);
create table DYEXTN_FILE_EXTENSIONS (
   IDENTIFIER bigint not null identity,
   FILE_EXTENSION varchar(255),
   ATTRIBUTE_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_LONG_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_FLOAT_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE float,
   primary key (IDENTIFIER)
);
create table DYEXTN_TEXTFIELD (
   IDENTIFIER bigint not null,
   NO_OF_COLUMNS integer,
   IS_PASSWORD tinyint default NULL,
   IS_URL tinyint default NULL,
   primary key (IDENTIFIER)
);
create table DYEXTN_ROLE (
   IDENTIFIER bigint not null identity,
   ASSOCIATION_TYPE varchar(255),
   MAX_CARDINALITY integer,
   MIN_CARDINALITY integer,
   NAME varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_RULE (
   IDENTIFIER bigint not null identity,
   NAME varchar(255),
   ATTRIBUTE_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_DATE_TYPE_INFO (
   IDENTIFIER bigint not null,
   FORMAT varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_ATTRIBUTE_TYPE_INFO (
   IDENTIFIER bigint not null identity,
   PRIMITIVE_ATTRIBUTE_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_ENTITY_MAP_RECORD (
   IDENTIFIER bigint not null identity,
   FORM_CONTEXT_ID bigint,
   STATIC_ENTITY_RECORD_ID bigint,
   STATUS varchar(10),
   DYNAMIC_ENTITY_RECORD_ID bigint,
   MODIFIED_DATE datetime,
   CREATED_DATE datetime,
   CREATED_BY varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_ASSO_DISPLAY_ATTR (
   IDENTIFIER bigint not null identity,
   SEQUENCE_NUMBER integer,
   DISPLAY_ATTRIBUTE_ID numeric(20),
   SELECT_CONTROL_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_TEXTAREA (
   IDENTIFIER bigint not null,
   TEXTAREA_COLUMNS integer,
   TEXTAREA_ROWS integer,
   primary key (IDENTIFIER)
);
create table DYEXTN_ENTITY_GROUP (
   IDENTIFIER numeric(20) not null,
   LONG_NAME varchar(255),
   SHORT_NAME varchar(255),
   VERSION varchar(255),
   IS_SYSTEM_GENERATED tinyint default NULL,
   primary key (IDENTIFIER)
);
create table DYEXTN_DATA_ELEMENT (
   IDENTIFIER bigint not null identity,
   ATTRIBUTE_TYPE_INFO_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_DOUBLE_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE double precision,
   primary key (IDENTIFIER)
);
create table DYEXTN_LIST_BOX (
   IDENTIFIER bigint not null,
   MULTISELECT tinyint default NULL,
   primary key (IDENTIFIER)
);
create table DYEXTN_CONTAINMENT_CONTROL (
   IDENTIFIER bigint not null,
   DISPLAY_CONTAINER_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_CONTROL (
   IDENTIFIER bigint not null identity,
   CAPTION varchar(255),
   CSS_CLASS varchar(255),
   HIDDEN tinyint default NULL,
   NAME varchar(255),
   SEQUENCE_NUMBER integer,
   TOOLTIP varchar(255),
   ABSTRACT_ATTRIBUTE_ID numeric(20),
   CONTAINER_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_LONG_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_FORM_CONTEXT (
   IDENTIFIER bigint not null identity,
   IS_INFINITE_ENTRY tinyint default NULL,
   ENTITY_MAP_ID bigint,
   STUDY_FORM_LABEL varchar(255),
   NO_OF_ENTRIES integer,
   primary key (IDENTIFIER)
);
create table DYEXTN_ATTRIBUTE (
   IDENTIFIER numeric(20) not null,
   ENTIY_ID numeric(20),
   primary key (IDENTIFIER)
);
create table DYEXTN_RULE_PARAMETER (
   IDENTIFIER bigint not null identity,
   NAME varchar(255),
   VALUE varchar(255),
   RULE_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_DATE_CONCEPT_VALUE (
   IDENTIFIER bigint not null,
   VALUE datetime,
   primary key (IDENTIFIER)
);
create table DYEXTN_VIEW (
   IDENTIFIER bigint not null identity,
   NAME varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_BYTE_ARRAY_TYPE_INFO (
   IDENTIFIER bigint not null,
   CONTENT_TYPE varchar(255),
   primary key (IDENTIFIER)
);
create table DYEXTN_SEMANTIC_PROPERTY (
   IDENTIFIER bigint not null identity,
   CONCEPT_CODE varchar(255),
   TERM varchar(255),
   THESAURAS_NAME varchar(255),
   SEQUENCE_NUMBER integer,
   CONCEPT_DEFINITION varchar(255),
   ABSTRACT_METADATA_ID numeric(20),
   ABSTRACT_VALUE_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_ATTRIBUTE_RECORD (
   IDENTIFIER bigint not null identity,
   ENTITY_ID numeric(20),
   ATTRIBUTE_ID numeric(20),
   RECORD_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_DATA_GRID (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DE_COLL_ATTR_RECORD_VALUES (
   IDENTIFIER bigint not null identity,
   RECORD_VALUE varchar(8000),
   COLLECTION_ATTR_RECORD_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_NUMERIC_TYPE_INFO (
   IDENTIFIER bigint not null,
   MEASUREMENT_UNITS varchar(255),
   DECIMAL_PLACES integer,
   NO_DIGITS integer,
   primary key (IDENTIFIER)
);
create table DYEXTN_SHORT_TYPE_INFO (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_CONTAINER (
   IDENTIFIER numeric(20) not null identity,
   BUTTON_CSS varchar(255),
   CAPTION varchar(255),
   ENTITY_ID numeric(20),
   MAIN_TABLE_CSS varchar(255),
   REQUIRED_FIELD_INDICATOR varchar(255),
   REQUIRED_FIELD_WARNING_MESSAGE varchar(255),
   TITLE_CSS varchar(255),
   BASE_CONTAINER_ID numeric(20),
   ENTITY_GROUP_ID numeric(20),
   VIEW_ID bigint,
   primary key (IDENTIFIER)
);
create table DYEXTN_RADIOBUTTON (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table DYEXTN_DATEPICKER (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);

alter table DYEXTN_OBJECT_TYPE_INFO add constraint FK74819FB0BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3FBC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3FB4C15A36 foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_USERDEFINED_DE add constraint FK630761FFBC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT;
alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD8BC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD8927B15B9 foreign key (ASSOCIATION_ID) references DYEXTN_ASSOCIATION;
alter table DYEXTN_PERMISSIBLE_VALUE add constraint FK136264E08C8D972A foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_PERMISSIBLE_VALUE add constraint FK136264E03D51114B foreign key (USER_DEF_DE_ID) references DYEXTN_USERDEFINED_DE;
alter table DYEXTN_CHECK_BOX add constraint FK4EFF9257BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_TABLE_PROPERTIES add constraint FKE608E08179F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_TABLE_PROPERTIES add constraint FKE608E081BC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
alter table DYEXTN_ENTITY_MAP_CONDNS add constraint FK2A9D602969F17C26 foreign key (FORM_CONTEXT_ID) references DYEXTN_FORM_CONTEXT;
alter table DYEXTN_INTEGER_CONCEPT_VALUE add constraint FKFBA33B3CBC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_STRING_CONCEPT_VALUE add constraint FKADE7D889BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_BOOLEAN_TYPE_INFO add constraint FK28F1809FBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_BOOLEAN_CONCEPT_VALUE add constraint FK57B6C4A6BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DE_FILE_ATTR_RECORD_VALUES add constraint FKE68334E7E150DFC9 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
alter table DYEXTN_STRING_TYPE_INFO add constraint FKDA35FE02BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_SHORT_CONCEPT_VALUE add constraint FKC1945ABABC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_FLOAT_TYPE_INFO add constraint FK7E1C0693BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_FILE_UPLOAD add constraint FK2FAD41E7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_BARR_CONCEPT_VALUE add constraint FK89D27DF7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_ENTITY add constraint FK8B243640450711A2 foreign key (PARENT_ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ENTITY add constraint FK8B243640BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_INTEGER_TYPE_INFO add constraint FK5F9CB235BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_TAGGED_VALUE add constraint FKF79D055B7D7A9B8E foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA;
alter table DE_OBJECT_ATTR_RECORD_VALUES add constraint FK504EADC4E150DFC9 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
alter table DYEXTN_COMBOBOX add constraint FKABBC649ABC7298A9 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_CADSR_VALUE_DOMAIN_INFO add constraint FK1C9AA364B4C15A36 foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_PRIMITIVE_ATTRIBUTE add constraint FKA9F765C7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_ASSOCIATION add constraint FK104684243AC5160 foreign key (SOURCE_ROLE_ID) references DYEXTN_ROLE;
alter table DYEXTN_ASSOCIATION add constraint FK10468424F60C84D6 foreign key (TARGET_ROLE_ID) references DYEXTN_ROLE;
alter table DYEXTN_ASSOCIATION add constraint FK104684246315C5C9 foreign key (TARGET_ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ASSOCIATION add constraint FK10468424BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_CADSRDE add constraint FK588A2509BC7298A9 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT;
alter table DYEXTN_DOUBLE_TYPE_INFO add constraint FKC83869C2BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_SELECT_CONTROL add constraint FKDFEBB657BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_ENTITY_GROUP_REL add constraint FK5A0D835A992A67D7 foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP;
alter table DYEXTN_ENTITY_GROUP_REL add constraint FK5A0D835A79F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_FILE_TYPE_INFO add constraint FKA00F0EDBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_FILE_EXTENSIONS add constraint FKD49834FA4D87D1BE foreign key (ATTRIBUTE_ID) references DYEXTN_FILE_TYPE_INFO;
alter table DYEXTN_LONG_TYPE_INFO add constraint FK257281EDBC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_FLOAT_CONCEPT_VALUE add constraint FK6785309ABC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_TEXTFIELD add constraint FKF9AFC850BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_RULE add constraint FKC27E0994D87D1BE foreign key (ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_DATE_TYPE_INFO add constraint FKFBA549FBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_ATTRIBUTE_TYPE_INFO add constraint FK62596D53B4C15A36 foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_ENTITY_MAP_RECORD add constraint FK43A4501369F17C26 foreign key (FORM_CONTEXT_ID) references DYEXTN_FORM_CONTEXT;
alter table DYEXTN_ASSO_DISPLAY_ATTR add constraint FKD12FD3823B3AAE3B foreign key (DISPLAY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_ASSO_DISPLAY_ATTR add constraint FKD12FD382F7AA8E80 foreign key (SELECT_CONTROL_ID) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_TEXTAREA add constraint FK946EE257BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_ENTITY_GROUP add constraint FK105DE7A0BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_DATA_ELEMENT add constraint FKB1153E48C8D972A foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_DOUBLE_CONCEPT_VALUE add constraint FKB94E6449BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_LIST_BOX add constraint FK208395A7BC7298A9 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_CONTAINMENT_CONTROL add constraint FK3F9D4AD3F7798636 foreign key (DISPLAY_CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_CONTAINMENT_CONTROL add constraint FK3F9D4AD3BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_CONTROL add constraint FK70FB5E80A67822BB foreign key (ABSTRACT_ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_CONTROL add constraint FK70FB5E809C6A9B9 foreign key (CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_LONG_CONCEPT_VALUE add constraint FK3E1A6EF4BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_FORM_CONTEXT add constraint FKE56CCDB111B8FADA foreign key (ENTITY_MAP_ID) references DYEXTN_ENTITY_MAP;
alter table DYEXTN_ATTRIBUTE add constraint FK37F1E2FFB15CD09F foreign key (ENTIY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ATTRIBUTE add constraint FK37F1E2FFBC7298A9 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_RULE_PARAMETER add constraint FK22567363871AAD3E foreign key (RULE_ID) references DYEXTN_RULE;
alter table DYEXTN_DATE_CONCEPT_VALUE add constraint FK45F598A6BC7298A9 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_BYTE_ARRAY_TYPE_INFO add constraint FK18BDA73BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_SEMANTIC_PROPERTY add constraint FKD2A0B5B13BAB5E46 foreign key (ABSTRACT_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_SEMANTIC_PROPERTY add constraint FKD2A0B5B17D7A9B8E foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_ATTRIBUTE_RECORD add constraint FK9B20ED9179F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ATTRIBUTE_RECORD add constraint FK9B20ED914D87D1BE foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_DATA_GRID add constraint FK233EB73EBC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DE_COLL_ATTR_RECORD_VALUES add constraint FK847DA577355836BC foreign key (COLLECTION_ATTR_RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
alter table DYEXTN_NUMERIC_TYPE_INFO add constraint FK4DEC9544BC7298A9 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_SHORT_TYPE_INFO add constraint FK99540B3BC7298A9 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E4A1257067 foreign key (BASE_CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E479F466F7 foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E4992A67D7 foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E445DEFCF5 foreign key (VIEW_ID) references DYEXTN_VIEW;
alter table DYEXTN_RADIOBUTTON add constraint FK16F5BA90BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_DATEPICKER add constraint FKFEADD199BC7298A9 foreign key (IDENTIFIER) references DYEXTN_CONTROL;

