--SET storage_engine=InnoDB;

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_INTERFACE_COLUMN_DATA') DROP TABLE CATISSUE_INTERFACE_COLUMN_DATA;
CREATE TABLE CATISSUE_INTERFACE_COLUMN_DATA
(
      IDENTIFIER bigint not null identity,
      TABLE_ID bigint not null,
      COLUMN_NAME varchar(50),
      ATTRIBUTE_TYPE varchar(30)
);
alter table CATISSUE_INTERFACE_COLUMN_DATA add constraint pk_CAT_INTERFACE_CLM_DATA_ID primary key (IDENTIFIER);

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_QUERY_TABLE_DATA') DROP TABLE CATISSUE_QUERY_TABLE_DATA;
CREATE TABLE CATISSUE_QUERY_TABLE_DATA
(
      TABLE_ID bigint not null identity, 
      TABLE_NAME varchar(50),
      DISPLAY_NAME varchar(50),
      ALIAS_NAME varchar(50),
      PRIVILEGE_ID numeric(1,0),
      FOR_SQI tinyint default NULL
);
alter table CATISSUE_QUERY_TABLE_DATA add constraint pk_CAT_QUERY_TBL_DATA_TBL_ID primary key (TABLE_ID);


--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_TABLE_RELATION') DROP TABLE CATISSUE_TABLE_RELATION;
CREATE TABLE CATISSUE_TABLE_RELATION
(
      RELATIONSHIP_ID bigint identity,
      PARENT_TABLE_ID bigint,
      CHILD_TABLE_ID bigint,
      TABLES_IN_PATH varchar(50)
);
alter table CATISSUE_TABLE_RELATION add constraint pk_CAT_TBL_REL_RELTIONSHIP_ID primary key (RELATIONSHIP_ID);


--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_SEARCH_DISPLAY_DATA') DROP TABLE CATISSUE_SEARCH_DISPLAY_DATA;
CREATE TABLE CATISSUE_SEARCH_DISPLAY_DATA
(
      RELATIONSHIP_ID bigint not null,
      COL_ID bigint not null,
      DISPLAY_NAME varchar(50),
      DEFAULT_VIEW_ATTRIBUTE bit DEFAULT 0,
      ATTRIBUTE_ORDER numeric(5,0)
);

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_RELATED_TABLES_MAP') DROP TABLE CATISSUE_RELATED_TABLES_MAP;
CREATE TABLE CATISSUE_RELATED_TABLES_MAP
(
      FIRST_TABLE_ID bigint,      
      SECOND_TABLE_ID bigint,
      FIRST_TABLE_JOIN_COLUMN varchar(50),
      SECOND_TABLE_JOIN_COLUMN varchar(50)
);

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATISSUE_QUERY_EDITLINK_COLS') DROP TABLE CATISSUE_QUERY_EDITLINK_COLS;
CREATE TABLE CATISSUE_QUERY_EDITLINK_COLS
(
      TABLE_ID bigint not null, 
      COL_ID bigint not null
);