Create View VIEW_CATISSUE_CONT_BARCODE With Schemabinding 
As Select BARCODE from @@schema@@.CATISSUE_CONTAINER Where BARCODE is not null;
Create Unique Clustered Index UQ_CATISSUE_CONT_BARCODE on VIEW_CATISSUE_CONT_BARCODE (BARCODE);

Create View VIEW_CATISSUE_PARTICIPANT_SSN With Schemabinding 
As Select SOCIAL_SECURITY_NUMBER from @@schema@@.CATISSUE_PARTICIPANT Where SOCIAL_SECURITY_NUMBER is not null;
Create Unique Clustered Index UQ_CATISSUE_PARTICIPANT_SSN on VIEW_CATISSUE_PARTICIPANT_SSN (SOCIAL_SECURITY_NUMBER);

Create View VIEW_CAT_COLL_PROT_REG_BARC With Schemabinding 
As Select BARCODE from @@schema@@.CATISSUE_COLL_PROT_REG Where BARCODE is not null;
Create Unique Clustered Index UQ_CAT_COLL_PROT_REG_BARC on VIEW_CAT_COLL_PROT_REG_BARC (BARCODE);

Create View VIEW_CAT_COLL_PROT_EVE_ID_LBL With Schemabinding 
As Select COLLECTION_PROTOCOL_ID,COLLECTION_POINT_LABEL from @@schema@@.CATISSUE_COLL_PROT_EVENT Where COLLECTION_PROTOCOL_ID is not null and COLLECTION_POINT_LABEL is not null;
Create Unique Clustered Index UQ_CAT_COL_PROT_EVE_ID_LBL on VIEW_CAT_COLL_PROT_EVE_ID_LBL (COLLECTION_PROTOCOL_ID,COLLECTION_POINT_LABEL);

Create View VIEW_CAT_SPEC_COLL_GRP_NAME With Schemabinding 
As Select NAME from @@schema@@.CATISSUE_SPECIMEN_COLL_GROUP Where NAME is not null;
Create Unique Clustered Index UQ_CAT_SPEC_COLL_GRP_NAME on VIEW_CAT_SPEC_COLL_GRP_NAME (NAME);

Create View VIEW_CAT_SPEC_COLL_GRP_BARC With Schemabinding 
As Select BARCODE from @@schema@@.CATISSUE_SPECIMEN_COLL_GROUP Where BARCODE is not null;
Create Unique Clustered Index UQ_CAT_SPEC_COLL_GRP_BARC on VIEW_CAT_SPEC_COLL_GRP_BARC (BARCODE);

Create View VIEW_CATISSUE_CONT_TYPE_NAME With Schemabinding 
As Select NAME from @@schema@@.CATISSUE_CONTAINER_TYPE Where NAME is not null;
Create Unique Clustered Index UQ_CATISSUE_CONT_TYPE_NAME on VIEW_CATISSUE_CONT_TYPE_NAME (NAME);

Create View VIEW_CATISSUE_SPECIMEN_LBL With Schemabinding 
As Select LABEL from @@schema@@.CATISSUE_SPECIMEN Where LABEL is not null;
Create Unique Clustered Index UQ_CATISSUE_SPECIMEN_LBL on VIEW_CATISSUE_SPECIMEN_LBL (LABEL);

Create View VIEW_CATISSUE_SPECIMEN_BARC With Schemabinding 
As Select BARCODE from @@schema@@.CATISSUE_SPECIMEN Where BARCODE is not null;
Create Unique Clustered Index UQ_CATISSUE_SPECIMEN_BARC on VIEW_CATISSUE_SPECIMEN_BARC (BARCODE);

Create View VIEW_CSM_PROT_ELE_OB_ATT_APP With Schemabinding 
As Select OBJECT_ID , ATTRIBUTE , APPLICATION_ID from @@schema@@.CSM_PROTECTION_ELEMENT Where OBJECT_ID is not null and ATTRIBUTE is not null and APPLICATION_ID is not null;
Create Unique Clustered Index UQ_CSM_PROT_ELE_OB_ATT_APP on VIEW_CSM_PROT_ELE_OB_ATT_APP (OBJECT_ID , ATTRIBUTE , APPLICATION_ID);

Create View VIEW_CSM_PROT_ELE_NME_ATT_APP With Schemabinding 
As Select PROTECTION_ELEMENT_NAME,ATTRIBUTE,APPLICATION_ID from @@schema@@.CSM_PROTECTION_ELEMENT Where PROTECTION_ELEMENT_NAME is not null and ATTRIBUTE is not null and APPLICATION_ID is not null;
Create Unique Clustered Index UQ_CSM_PROT_ELE_NME_ATT_APP on VIEW_CSM_PROT_ELE_NME_ATT_APP (PROTECTION_ELEMENT_NAME,ATTRIBUTE,APPLICATION_ID);

Create View VIEW_CAT_PRT_MED_ID_RC_SITE With Schemabinding 
As Select MEDICAL_RECORD_NUMBER,SITE_ID from @@schema@@.CATISSUE_PART_MEDICAL_ID Where MEDICAL_RECORD_NUMBER is not null and SITE_ID is not null;
Create Unique Clustered Index UQ_CAT_PRT_MED_ID_RC_SITE on VIEW_CAT_PRT_MED_ID_RC_SITE (MEDICAL_RECORD_NUMBER,SITE_ID);

Create View VIEW_CATE_ROOT_CATE_CLS_ID With Schemabinding 
As Select ROOT_CATEGORIAL_CLASS_ID from @@schema@@.CATEGORY Where ROOT_CATEGORIAL_CLASS_ID is not null ;
Create Unique Clustered Index UQ_CATE_ROOT_CATE_CLS_ID on VIEW_CATE_ROOT_CATE_CLS_ID (ROOT_CATEGORIAL_CLASS_ID);

Create View VIEW_QUERY_CONSTRAINTS_ID With Schemabinding 
As Select CONSTRAINTS_ID from @@schema@@.QUERY Where CONSTRAINTS_ID is not null ;
Create Unique Clustered Index UQ_QUERY_CONSTRAINTS_ID on VIEW_QUERY_CONSTRAINTS_ID (CONSTRAINTS_ID);

Create View VIEW_QRY_PARAM_QRY_NAME With Schemabinding 
As Select QUERY_NAME from @@schema@@.QUERY_PARAMETERIZED_QUERY Where QUERY_NAME is not null ;
Create Unique Clustered Index UQ_QRY_PARAM_QRY_NAME on VIEW_QRY_PARAM_QRY_NAME (QUERY_NAME);

Create View VIEW_QUERY_CONST_GRAPH_ID With Schemabinding 
As Select QUERY_JOIN_GRAPH_ID from @@schema@@.QUERY_CONSTRAINTS Where QUERY_JOIN_GRAPH_ID is not null ;
Create Unique Clustered Index UQ_QUERY_CONST_GRAPH_ID on VIEW_QUERY_CONST_GRAPH_ID (QUERY_JOIN_GRAPH_ID);
