ALTER TABLE csm_migrate_user ADD TARGET_IDP_NAME varchar2(100 Byte);
ALTER TABLE csm_migrate_user ADD MIGRATION_STATUS varchar2(100 Byte);
ALTER TABLE csm_migrate_user RENAME COLUMN WUSTLKEY to MIGRATED_LOGIN_NAME;

UPDATE csm_migrate_user SET MIGRATION_STATUS='MIGRATED' WHERE MIGRATED_LOGIN_NAME IS NOT NULL;
UPDATE csm_migrate_user SET MIGRATION_STATUS='DO_NOT_MIGRATE' WHERE MIGRATED_LOGIN_NAME IS NULL;

UPDATE csm_migrate_user SET TARGET_IDP_NAME='WUSTLKEY_IDP';

ALTER TABLE csm_migrate_user MODIFY (MIGRATION_STATUS varchar2(100 Byte) NOT NULL);

