CREATE TABLESPACE "CATISSUE_CORE" LOGGING DATAFILE '\opt7\catissuecore\CATISSUECORE01.dbf' SIZE 100M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE USER CATISSUE_CORE PROFILE "DEFAULT" IDENTIFIED BY CATISSUE_CORE DEFAULT TABLESPACE "CATISSUE_CORE" TEMPORARY TABLESPACE "TEMP" QUOTA UNLIMITED ON "CATISSUE_CORE";
GRANT CONNECT, RESOURCE TO CATISSUE_CORE;
GRANT DBA TO CATISSUE_CORE;
ALTER USER CATISSUE_CORE DEFAULT ROLE  ALL;