Alter table CATISSUE_DISTRIBUTION ADD column SPECIMEN_ID bigint;
alter table CATISSUE_DISTRIBUTION add index FK5427668060773DB2 (SPECIMEN_ID), add constraint FK5427668060773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

Alter table CATISSUE_DISTRIBUTION ADD column EVENT_TIMESTAMP datetime;

Alter table CATISSUE_DISTRIBUTION ADD column USER_ID bigint;
alter table CATISSUE_DISTRIBUTION add index FK542766802206F20F (USER_ID), add constraint FK542766802206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);

Alter table CATISSUE_DISTRIBUTION ADD column COMMENTS text;

update CATISSUE_DISTRIBUTION set EVENT_TIMESTAMP = (select EVENT_TIMESTAMP from CATISSUE_SPECIMEN_EVENT_PARAM where CATISSUE_DISTRIBUTION.identifier = CATISSUE_SPECIMEN_EVENT_PARAM.identifier);
update CATISSUE_DISTRIBUTION set USER_ID = (select USER_ID from CATISSUE_SPECIMEN_EVENT_PARAM where CATISSUE_DISTRIBUTION.identifier = CATISSUE_SPECIMEN_EVENT_PARAM.identifier);
update CATISSUE_DISTRIBUTION set COMMENTS = (select COMMENTS from CATISSUE_SPECIMEN_EVENT_PARAM where CATISSUE_DISTRIBUTION.identifier = CATISSUE_SPECIMEN_EVENT_PARAM.identifier);