//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.23 at 10:44:28 GMT+05:30 
//


package edu.wustl.common.cde.xml;


/**
 * Java content class for XMLCDE_CACHE element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/prg/XML/CDE22AUG05/CDECONFIG.xsd line 2)
 * <p>
 * <pre>
 * &lt;element name="XMLCDE_CACHE" type="{}XMLCDECacheType"/>
 * </pre>
 * 
 */
public interface XMLCDECACHE
    extends javax.xml.bind.Element, edu.wustl.common.cde.xml.XMLCDECacheType
{


}
