//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.23 at 10:44:28 GMT+05:30 
//


package edu.wustl.common.cde.xml;


/**
 * Java content class for XMLPermissibleValueType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/prg/XML/CDE22AUG05/CDECONFIG.xsd line 21)
 * <p>
 * <pre>
 * &lt;complexType name="XMLPermissibleValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evsTerminology" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="conceptCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentConceptCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="depthOfHierarchyTree" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XMLPermissibleValueType {


    /**
     * Gets the value of the depthOfHierarchyTree property.
     * 
     */
    int getDepthOfHierarchyTree();

    /**
     * Sets the value of the depthOfHierarchyTree property.
     * 
     */
    void setDepthOfHierarchyTree(int value);

    /**
     * Gets the value of the evsTerminology property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getEvsTerminology();

    /**
     * Sets the value of the evsTerminology property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setEvsTerminology(java.lang.String value);

    /**
     * Gets the value of the parentConceptCode property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getParentConceptCode();

    /**
     * Sets the value of the parentConceptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setParentConceptCode(java.lang.String value);

    /**
     * Gets the value of the conceptCode property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getConceptCode();

    /**
     * Sets the value of the conceptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setConceptCode(java.lang.String value);

}
