ALTER TABLE CATISSUE_ADDRESS
TYPE = INNODB;

ALTER TABLE CATISSUE_AUDIT_EVENT
TYPE = INNODB;

ALTER TABLE CATISSUE_AUDIT_EVENT_DETAILS
TYPE = INNODB;

ALTER TABLE CATISSUE_AUDIT_EVENT_LOG
TYPE = INNODB;

ALTER TABLE CATISSUE_AUDIT_EVENT_QUERY_LOG
TYPE = INNODB;

ALTER TABLE CATISSUE_BIOHAZARD
TYPE = INNODB;

ALTER TABLE CATISSUE_CANCER_RESEARCH_GROUP
TYPE = INNODB;

ALTER TABLE CATISSUE_CAPACITY
TYPE = INNODB;

ALTER TABLE CATISSUE_CDE
TYPE = INNODB;

ALTER TABLE CATISSUE_CELL_SPE_REVIEW_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_COLLECTION_PROTOCOL
TYPE = INNODB;

ALTER TABLE CATISSUE_COLL_COORDINATORS
TYPE = INNODB;

ALTER TABLE CATISSUE_COLL_DISTRIBUTION_REL
TYPE = INNODB;

ALTER TABLE CATISSUE_COLL_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_COLL_PROT_EVENT
TYPE = INNODB;

ALTER TABLE CATISSUE_COLL_PROT_REG
TYPE = INNODB;

ALTER TABLE CATISSUE_CONTAINER
TYPE = INNODB;

ALTER TABLE CATISSUE_CONTAINER_TYPE
TYPE = INNODB;

ALTER TABLE CATISSUE_CONT_HOLDS_SPARRTYPE
TYPE = INNODB;

ALTER TABLE CATISSUE_DEPARTMENT
TYPE = INNODB;

ALTER TABLE CATISSUE_DISPOSAL_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_DISTRIBUTED_ITEM
TYPE = INNODB;

ALTER TABLE CATISSUE_DISTRIBUTION
TYPE = INNODB;

ALTER TABLE CATISSUE_DISTRIBUTION_PROTOCOL
TYPE = INNODB;

ALTER TABLE CATISSUE_DISTRIBUTION_SPE_REQ
TYPE = INNODB;

ALTER TABLE CATISSUE_EMBEDDED_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_EXTERNAL_IDENTIFIER
TYPE = INNODB;

ALTER TABLE CATISSUE_FIXED_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_FLUID_SPE_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_FROZEN_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_INSTITUTION
TYPE = INNODB;

ALTER TABLE CATISSUE_INTERFACE_COLUMN_DATA
TYPE = INNODB;

ALTER TABLE CATISSUE_IN_OUT_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_MOL_SPE_REVIEW_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_PARTICIPANT
TYPE = INNODB;

ALTER TABLE CATISSUE_PART_MEDICAL_ID
TYPE = INNODB;

ALTER TABLE CATISSUE_PASSWORD
TYPE = INNODB;


ALTER TABLE CATISSUE_PERMISSIBLE_VALUE
TYPE = INNODB;

ALTER TABLE CATISSUE_PROCEDURE_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_QUANTITY
TYPE = INNODB;

ALTER TABLE CATISSUE_QUERY_EDITLINK_COLS
TYPE = INNODB;

ALTER TABLE CATISSUE_QUERY_TABLE_DATA
TYPE = INNODB;

ALTER TABLE CATISSUE_RACE
TYPE = INNODB;

ALTER TABLE CATISSUE_RECEIVED_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_RELATED_TABLES_MAP
TYPE = INNODB;

ALTER TABLE CATISSUE_REPORTED_PROBLEM
TYPE = INNODB;

ALTER TABLE CATISSUE_SEARCH_DISPLAY_DATA
TYPE = INNODB;

ALTER TABLE CATISSUE_SITE
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_ARRAY
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_ARRAY_TYPE
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_BIOHZ_REL
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_CHAR
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_PROTOCOL
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_REQUIREMENT
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECIMEN_TYPE
TYPE = INNODB;

ALTER TABLE CATISSUE_SPECI_ARRAY_CONTENT
TYPE = INNODB;

ALTER TABLE CATISSUE_SPUN_EVENT_PARAMETERS
TYPE = INNODB;

ALTER TABLE CATISSUE_STORAGE_CONTAINER
TYPE = INNODB;

ALTER TABLE CATISSUE_STORAGE_TYPE
TYPE = INNODB;

ALTER TABLE CATISSUE_STORTY_HOLDS_SPARRTY
TYPE = INNODB;

ALTER TABLE CATISSUE_STOR_CONT_SPEC_CLASS
TYPE = INNODB;

ALTER TABLE CATISSUE_STOR_TYPE_HOLDS_TYPE
TYPE = INNODB;

ALTER TABLE CATISSUE_STOR_TYPE_SPEC_CLASS
TYPE = INNODB;

ALTER TABLE CATISSUE_ST_CONT_COLL_PROT_REL
TYPE = INNODB;

ALTER TABLE CATISSUE_ST_CONT_ST_TYPE_REL
TYPE = INNODB;

ALTER TABLE CATISSUE_TABLE_RELATION
TYPE = INNODB;

ALTER TABLE CATISSUE_THAW_EVENT_PARAMETERS
TYPE = INNODB;

ALTER TABLE CATISSUE_TIS_SPE_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_TRANSFER_EVENT_PARAM
TYPE = INNODB;

ALTER TABLE CATISSUE_USER
TYPE = INNODB;

/* Ordering system  related alter table script */

/* Specimen Order */
create table CATISSUE_PATH_CASE_ORDER_ITEM (
   IDENTIFIER bigint not null,
   PATHOLOGICAL_STATUS varchar(255),
   TISSUE_SITE varchar(255),
   SPECIMEN_COLL_GROUP_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;

create table CATISSUE_DERIEVED_SP_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;

create table CATISSUE_NEW_SPEC_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_CLASS varchar(255),
   SPECIMEN_TYPE varchar(255),
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;

create table CATISSUE_EXISTING_SP_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;


create table CATISSUE_SPECIMEN_ORDER_ITEM (
   IDENTIFIER bigint not null,
   ARRAY_ORDER_ITEM_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;

/* Specimen Array Order  */


create table CATISSUE_NEW_SP_AR_ORDER_ITEM (
   IDENTIFIER bigint not null,
   ARRAY_TYPE_ID bigint,
   NAME varchar(255),
   SPECIMEN_ARRAY_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;

create table CATISSUE_EXIST_SP_AR_ORD_ITEM (
   IDENTIFIER bigint not null,
   SPECIMEN_ARRAY_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;

create table CATISSUE_SP_ARRAY_ORDER_ITEM (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;


create table CATISSUE_ORDER_ITEM (
   IDENTIFIER bigint not null auto_increment,
   DESCRIPTION text,
   DISTRIBUTED_ITEM_ID bigint,
   STATUS varchar(50),
   REQUESTED_QUANTITY double precision,
   ORDER_ID bigint,
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;


create table CATISSUE_ORDER (
   IDENTIFIER bigint not null auto_increment,
   COMMENTS text,
   DISTRIBUTION_PROTOCOL_ID bigint,
   NAME text,
   REQUESTED_DATE datetime,
   STATUS varchar(50),
   primary key (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;



/* extra for catissue_distribution */
 alter table catissue_distribution add column `ORDER_ID` bigint   NULL;
 alter table catissue_distributed_item add column `SPECIMEN_ARRAY_ID` bigint   NULL;  
/* extra finished */
 
alter table CATISSUE_PATH_CASE_ORDER_ITEM add index FKBD5029D5F69249F7 (SPECIMEN_COLL_GROUP_ID), add constraint FKBD5029D5F69249F7 foreign key (SPECIMEN_COLL_GROUP_ID) references CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
alter table CATISSUE_PATH_CASE_ORDER_ITEM add index FKBD5029D5BC7298A9 (IDENTIFIER), add constraint FKBD5029D5BC7298A9 foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);

alter table CATISSUE_DERIEVED_SP_ORD_ITEM add index FK3742152BBC7298A9 (IDENTIFIER), add constraint FK3742152BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_NEW_SPEC_ORD_ITEM (IDENTIFIER);
alter table CATISSUE_DERIEVED_SP_ORD_ITEM add index FK3742152B60773DB2 (SPECIMEN_ID), add constraint FK3742152B60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

alter table CATISSUE_NEW_SPEC_ORD_ITEM add index FK_NEW_SPECIMEN_ORDER_ITEM (IDENTIFIER), add constraint FK_NEW_SPECIMEN_ORDER_ITEM foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_EXISTING_SP_ORD_ITEM add index FKF8B855EEBC7298A9 (IDENTIFIER), add constraint FKF8B855EEBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXISTING_SP_ORD_ITEM add index FKF8B855EE60773DB2 (SPECIMEN_ID), add constraint FKF8B855EE60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);

alter table CATISSUE_SPECIMEN_ORDER_ITEM add index FK48C3B39FBC7298A9 (IDENTIFIER), add constraint FK48C3B39FBC7298A9 foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_SPECIMEN_ORDER_ITEM add index FK48C3B39F83505A30 (ARRAY_ORDER_ITEM_ID), add constraint FK48C3B39F83505A30 foreign key (ARRAY_ORDER_ITEM_ID) references CATISSUE_NEW_SP_AR_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add index FKE3823170BC7298A9 (IDENTIFIER), add constraint FKE3823170BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_EXIST_SP_AR_ORD_ITEM add index FKE3823170C4A3C438 (SPECIMEN_ARRAY_ID), add constraint FKE3823170C4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add index FKC5C92CCBCE5FBC3A (ARRAY_TYPE_ID), add constraint FKC5C92CCBCE5FBC3A foreign key (ARRAY_TYPE_ID) references CATISSUE_SPECIMEN_ARRAY_TYPE (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add index FKC5C92CCBBC7298A9 (IDENTIFIER), add constraint FKC5C92CCBBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SP_ARRAY_ORDER_ITEM (IDENTIFIER);
alter table CATISSUE_NEW_SP_AR_ORDER_ITEM add index FKC5C92CCBC4A3C438 (SPECIMEN_ARRAY_ID), add constraint FKC5C92CCBC4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

alter table CATISSUE_SP_ARRAY_ORDER_ITEM add index FK_SP_ARRAY_ORDER_ITEM (IDENTIFIER), add constraint FK_SP_ARRAY_ORDER_ITEM foreign key (IDENTIFIER) references CATISSUE_ORDER_ITEM (IDENTIFIER);

alter table CATISSUE_ORDER_ITEM add index FKB501E88060975C0B (DISTRIBUTED_ITEM_ID), add constraint FKB501E88060975C0B foreign key (DISTRIBUTED_ITEM_ID) references CATISSUE_DISTRIBUTED_ITEM (IDENTIFIER);
alter table CATISSUE_ORDER_ITEM add index FKB501E880783867CC (ORDER_ID), add constraint FKB501E880783867CC foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);

alter table CATISSUE_ORDER add index FK543F22B26B1F36E7 (DISTRIBUTION_PROTOCOL_ID), add constraint FK543F22B26B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);

alter table CATISSUE_DISTRIBUTION add index FK54276680783867CC (ORDER_ID), add constraint FK54276680783867CC foreign key (ORDER_ID) references CATISSUE_ORDER (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add index FKA7C3ED4BC4A3C438 (SPECIMEN_ARRAY_ID), add constraint FKA7C3ED4BC4A3C438 foreign key (SPECIMEN_ARRAY_ID) references CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);


/*TODO Check Inserting into distribution_item*/

INSERT INTO CATISSUE_DISTRIBUTED_ITEM
           (QUANTITY,SPECIMEN_ID,DISTRIBUTION_ID,SPECIMEN_ARRAY_ID)
SELECT 1, NULL, DISTRIBUTION_ID, IDENTIFIER FROM CATISSUE_SPECIMEN_ARRAY where DISTRIBUTION_ID IS NOT NULL;


/* Ordering System------ */

/* csm_catissuecore.sql */

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Order',
       'Order Object',
       'edu.wustl.catissuecore.domain.OrderDetails',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'OrderItem',
       'OrderItem Object',
       'edu.wustl.catissuecore.domain.OrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Derived Specimen Order Item',
       'Derived Specimen Order Item Object',
       'edu.wustl.catissuecore.domain.DerivedSpecimenOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Existing Specimen Array Order Item',
       'Existing Specimen Array Order Item Object',
       'edu.wustl.catissuecore.domain.ExistingSpecimenArrayOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Existing Specimen Order Item',
       'Existing Specimen Order Item Object',
       'edu.wustl.catissuecore.domain.ExistingSpecimenOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'New Specimen Array Order Item',
       'New Specimen Array Order Item Object',
       'edu.wustl.catissuecore.domain.NewSpecimenArrayOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'New Specimen Order Item',
       'New Specimen Order Item Object',
       'edu.wustl.catissuecore.domain.NewSpecimenOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Pathological Case Order Item',
       'Pathological Case Order Item Object',
       'edu.wustl.catissuecore.domain.PathologicalCaseOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Specimen Array Order Item',
       'Specimen Array Order Item Object',
       'edu.wustl.catissuecore.domain.SpecimenArrayOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Specimen Order Item',
       'Specimen Order Item Object',
       'edu.wustl.catissuecore.domain.SpecimenOrderItem',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;
/* ------------Ordering System Permissions----Ashish 4/1/06 */

INSERT INTO CSM_ROLE
           (ROLE_NAME,
            ROLE_DESCRIPTION,
            APPLICATION_ID)
VALUES     ('CREATE_ONLY',
            'Create only role',
            1);

INSERT INTO CSM_ROLE_PRIVILEGE
SELECT MAX(B.ROLE_PRIVILEGE_ID) + 1,
       MAX(A.ROLE_ID),
       1,
       '2007-01-04'
FROM   CSM_ROLE_PRIVILEGE B,
       CSM_ROLE A;

INSERT INTO CSM_PROTECTION_GROUP
           (PROTECTION_GROUP_NAME,
            APPLICATION_ID)
VALUES     ('SCIENTIST_PROTECTION_GROUP',
            1);

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Order' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'OrderItem' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Derived Specimen Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Array Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Array Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Pathological Case Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Array Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       MAX(PG.PROTECTION_GROUP_ID),
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Order Item' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE,
       CSM_PROTECTION_GROUP PG;

INSERT INTO CSM_USER_GROUP_ROLE_PG
SELECT MAX(USER_GROUP_ROLE_PG_ID) + 1,
       NULL,
       4,
       12,
       MAX(PG.PROTECTION_GROUP_ID),
       '2007-01-04'
FROM   CSM_PROTECTION_GROUP PG,
       CSM_USER_GROUP_ROLE_PG;

INSERT INTO `CSM_PROTECTION_ELEMENT`(PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'edu.wustl.catissuecore.action.RequestListAction',
       'edu.wustl.catissuecore.action.RequestListAction',
       'edu.wustl.catissuecore.action.RequestListAction',
       NULL,
       NULL,
       1,
       '2007-01-04'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'edu.wustl.catissuecore.action.RequestListAction' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'edu.wustl.catissuecore.action.RequestListAction' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'edu.wustl.catissuecore.action.RequestListAction' limit 1),
       '2007-01-04'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Order' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Order' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Order' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'OrderItem' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'OrderItem' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'OrderItem' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Derived Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Derived Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Derived Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Existing Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'New Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Pathological Case Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Pathological Case Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Pathological Case Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Array Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       2,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       3,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Specimen Order Item' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;
/* cde_dummydata_common.sql */
/******Ordering System******/

INSERT INTO CATISSUE_CDE
VALUES     ('4284',
            'Request Status',
            'Statuses for the ordered requests',
            1.0,
            NULL);

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5000,
            'All',
            NULL,
            '4284');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5001,
            'New',
            NULL,
            '4284');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5002,
            'Pending',
            NULL,
            '4284');

INSERT INTO CATISSUE_CDE
VALUES     ('4285',
            'Requested Items Status',
            'Statuses for the individual elements in the ordered request',
            1.0,
            NULL);

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5005,
            'New',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5006,
            'Pending - Protocol Review',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5007,
            'Pending - For Distribution',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5012,
            'Distributed',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5008,
            'Pending - Specimen Preparation',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5009,
            'Rejected - Inappropriate Request',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5010,
            'Rejected - Specimen Unavailable',
            NULL,
            '4285');

INSERT INTO CATISSUE_PERMISSIBLE_VALUE
           (IDENTIFIER,
            VALUE,
            PARENT_IDENTIFIER,
            PUBLIC_ID)
VALUES     (5011,
            'Rejected - Unable to Create',
            NULL,
            '4285');
/* initDB_inser_Common.sql */
/*Ordering System*/

INSERT INTO CATISSUE_QUERY_TABLE_DATA
           (TABLE_ID,
            TABLE_NAME,
            DISPLAY_NAME,
            ALIAS_NAME,
            PRIVILEGE_ID)
VALUES     (76,
            'CATISSUE_ORDER',
            'Order',
            'OrderDetails',
            2);

/* extra for catissue_distribution */
/*
--alter table catissue_distribution add column `ORDER_ID` bigint   NULL;
--alter table catissue_distributed_item add column `SPECIMEN_ARRAY_ID` bigint   NULL;  
*/

/* extra finished */
/* ordering changes finish */

/* Consent Tracking------- */

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Consent Tier','ConsentTier Object','edu.wustl.catissuecore.domain.ConsentTier',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Consent Tier Response','Consent Tier Response Object','edu.wustl.catissuecore.domain.ConsentTierResponse',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) SELECT MAX(PROTECTION_ELEMENT_ID)+1,'Consent Tier Status','Consent Tier Status Object','edu.wustl.catissuecore.domain.ConsentTierStatus',NULL,NULL,1,'2006-11-27' FROM CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Response' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,1,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,2,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status' limit 1),'2006-11-27' FROM CSM_PG_PE;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='Consent Tier Status' limit 1),'2006-11-27' FROM CSM_PG_PE;

/* CONSENT TRACKING */

CREATE TABLE CATISSUE_CONSENT_TIER_RESPONSE(
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   RESPONSE VARCHAR(20),
   CONSENT_TIER_ID BIGINT,
   COLL_PROT_REG_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE CATISSUE_CONSENT_TIER_STATUS (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   CONSENT_TIER_ID BIGINT,
   STATUS VARCHAR(255),
   SPECIMEN_ID BIGINT,
   SPECIMEN_COLL_GROUP_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE CATISSUE_CONSENT_TIER (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   STATEMENT TEXT,
   COLL_PROTOCOL_ID BIGINT,
   PRIMARY KEY (IDENTIFIER)
)ENGINE=InnoDB DEFAULT CHARSET = utf8;
/*TODO*/
ALTER TABLE CATISSUE_CONSENT_TIER_RESPONSE ADD INDEX catissue_coll_prot_reg(COLL_PROT_REG_ID), ADD CONSTRAINT FK_coll_prot_reg FOREIGN KEY (COLL_PROT_REG_ID) REFERENCES CATISSUE_COLL_PROT_REG (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_RESPONSE ADD INDEX FKFB1995FD17B9953 (CONSENT_TIER_ID), ADD CONSTRAINT FKFB1995FD17B9953 FOREIGN KEY (CONSENT_TIER_ID) REFERENCES CATISSUE_CONSENT_TIER (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS ADD INDEX FKF74E94AEF69249F7 (SPECIMEN_COLL_GROUP_ID), ADD CONSTRAINT FKF74E94AEF69249F7 FOREIGN KEY (SPECIMEN_COLL_GROUP_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS ADD INDEX FKF74E94AE60773DB2 (SPECIMEN_ID), ADD CONSTRAINT FKF74E94AE60773DB2 FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER_STATUS ADD INDEX FKF74E94AE17B9953 (CONSENT_TIER_ID), ADD CONSTRAINT FKF74E94AE17B9953 FOREIGN KEY (CONSENT_TIER_ID) REFERENCES CATISSUE_CONSENT_TIER (IDENTIFIER);
ALTER TABLE CATISSUE_CONSENT_TIER ADD INDEX FK51725303E36A4B4F (COLL_PROTOCOL_ID), ADD CONSTRAINT FK51725303E36A4B4F FOREIGN KEY (COLL_PROTOCOL_ID) REFERENCES CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);


/**--------- caTissue tables changed for consent tracking----------- **/

/** ALTER TABLE CATISSUE_COLL_PROT_REG DROP FOREIGN KEY FK5EB25F13A0FF79D4; **/
ALTER TABLE CATISSUE_COLLECTION_PROTOCOL ADD COLUMN UNSIGNED_CONSENT_DOC_URL TEXT;
ALTER TABLE CATISSUE_COLL_PROT_REG ADD COLUMN (CONSENT_SIGN_DATE DATETIME,CONSENT_DOC_URL TEXT,CONSENT_WITNESS BIGINT);
ALTER TABLE CATISSUE_COLL_PROT_REG ADD INDEX FK5EB25F13A0FF79D4 (CONSENT_WITNESS), ADD CONSTRAINT FK5EB25F13A0FF79D4 FOREIGN KEY (CONSENT_WITNESS) REFERENCES CATISSUE_USER (IDENTIFIER);

/* ----bug 3003-----Ashish ---7/12/06----- */
ALTER TABLE CATISSUE_ORDER_ITEM MODIFY DESCRIPTION TEXT;

/* ------Added association ---Ashish 7/12/06 ----- */
/*
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM DROP FOREIGN KEY FKC5C92CCBC4A3C438;
-- ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD COLUMN SPECIMEN_ARRAY_ID BIGINT;
--ALTER TABLE CATISSUE_NEW_SP_AR_ORDER_ITEM ADD INDEX FKC5C92CCBC4A3C438 (SPECIMEN_ARRAY_ID), ADD CONSTRAINT FKC5C92CCBC4A3C438 FOREIGN KEY (SPECIMEN_ARRAY_ID) REFERENCES CATISSUE_SPECIMEN_ARRAY (IDENTIFIER);

*/
/* New Table entry For ConsentWithdrawal ---------- Mandar : 18-Jan-07 -------------start */

INSERT INTO CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID, FOR_SQI) VALUES ( 79, 'CATISSUE_RETURN_EVENT_PARAM', 'Return Event Parameters', 'ReturnEventParameters',2,2);

CREATE TABLE CATISSUE_RETURN_EVENT_PARAM 
(
   IDENTIFIER BIGINT NOT NULL,
   PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE CATISSUE_RETURN_EVENT_PARAM ADD INDEX FKD8890A48BC7298A91 (IDENTIFIER), ADD CONSTRAINT FKD8890A48BC7298A91 FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_SPECIMEN_EVENT_PARAM (IDENTIFIER);

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE) SELECT MAX(PROTECTION_ELEMENT_ID)+1,'ReturnEventParameters','ReturnEventParameters Class','edu.wustl.catissuecore.domain.ReturnEventParameters',NULL,NULL,1,'2007-01-17' FROM CSM_PROTECTION_ELEMENT;
INSERT INTO CSM_PG_PE SELECT MAX(PG_PE_ID)+1,3,(SELECT PROTECTION_ELEMENT_ID FROM CSM_PROTECTION_ELEMENT WHERE PROTECTION_ELEMENT_NAME='ReturnEventParameters' limit 1),'2006-11-27' FROM CSM_PG_PE;


/* ------------------------New Column Entry For ConsentWaived ---------- Mandar : 25-Jan-07 -------------end */

ALTER TABLE CATISSUE_COLLECTION_PROTOCOL ADD COLUMN CONSENTS_WAIVED BIT;
UPDATE CATISSUE_COLLECTION_PROTOCOL SET  CONSENTS_WAIVED=0 WHERE  CONSENTS_WAIVED IS NULL;

/* ------------------------New Column Entry For Participant ---------- Sachin : 13-Mar-07 -------------start */

ALTER TABLE CATISSUE_PARTICIPANT ADD COLUMN MARITAL_STATUS VARCHAR(50);

/*TODO To Comment*/
/***caTIES Realated Tables - start**********/

CREATE TABLE CATISSUE_REPORT_TEXTCONTENT (
  IDENTIFIER BIGINT NOT NULL,
  REPORT_ID  BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_IDENTIFIED_REPORT (
  IDENTIFIER  BIGINT NOT NULL,
  DEID_REPORT BIGINT,
  SCG_ID      BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_CONCEPT_REFERENT (
  IDENTIFIER                BIGINT NOT NULL AUTO_INCREMENT,
  CONCEPT_ID                BIGINT,
  CONCEPT_CLASSIFICATION_ID BIGINT,
  DEIDENTIFIED_REPORT_ID    BIGINT,
  END_OFFSET                BIGINT,
  IS_MODIFIER               BIT,
  IS_NEGATED                BIT,
  START_OFFSET              BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REPORT_CONTENT (
  IDENTIFIER  BIGINT NOT NULL AUTO_INCREMENT,
  REPORT_DATA TEXT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REVIEW_PARAMS (
  IDENTIFIER      BIGINT NOT NULL AUTO_INCREMENT,
  REVIEWER_ROLE   VARCHAR(100),
  REPORT_ID       BIGINT,
  EVENT_TIMESTAMP DATETIME,
  USER_ID         BIGINT,
  COMMENTS        TEXT,
  STATUS          VARCHAR(100),
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REPORT_BICONTENT (
  IDENTIFIER BIGINT NOT NULL,
  REPORT_ID  BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REPORT_SECTION (
  IDENTIFIER        BIGINT NOT NULL AUTO_INCREMENT,
  DOCUMENT_FRAGMENT TEXT,
  END_OFFSET        INTEGER,
  NAME              VARCHAR(100),
  START_OFFSET      INTEGER,
  TEXT_CONTENT_ID   BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_DEIDENTIFIED_REPORT (
  IDENTIFIER BIGINT NOT NULL,
  STATUS     VARCHAR(100),
  SCG_ID     BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_QUARANTINE_PARAMS (
  IDENTIFIER      BIGINT NOT NULL AUTO_INCREMENT,
  DEID_REPORT_ID  BIGINT,
  IS_QUARANTINED  BIT,
  EVENT_TIMESTAMP DATETIME,
  USER_ID         BIGINT,
  COMMENTS        TEXT,
  STATUS          VARCHAR(100),
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_PATHOLOGY_REPORT (
  IDENTIFIER           BIGINT NOT NULL AUTO_INCREMENT,
  ACTIVITY_STATUS      VARCHAR(100),
  REVIEW_FLAG          BIT,
  SOURCE_ID            BIGINT,
  REPORT_STATUS        VARCHAR(100),
  COLLECTION_DATE_TIME DATE,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REPORT_XMLCONTENT (
  IDENTIFIER BIGINT NOT NULL,
  REPORT_ID  BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REPORT_QUEUE (
  IDENTIFIER                BIGINT NOT NULL AUTO_INCREMENT,
  STATUS                    VARCHAR(50),
  SURGICAL_PATHOLOGY_NUMBER VARCHAR(50),
  PARTICIPANT_NAME          VARCHAR(255),
  SITE_NAME                 VARCHAR(255),
  REPORT_LOADED_DATE        DATE,
  REPORT_TEXT               TEXT,
  SPECIMEN_COLL_GRP_ID      BIGINT,
  REPORT_COLLECTION_DATE    DATE,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_REPORT_PARTICIP_REL (
  PARTICIPANT_ID BIGINT,
  REPORT_ID      BIGINT) ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_CONCEPT (
  IDENTIFIER        BIGINT NOT NULL AUTO_INCREMENT,
  CONCEPT_UNIQUE_ID VARCHAR(30),
  NAME              TEXT,
  SEMANTIC_TYPE_ID  BIGINT,
  PRIMARY KEY( IDENTIFIER ))ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_SEMANTIC_TYPE (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  LABEL      TEXT,
  PRIMARY KEY( IDENTIFIER )) ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CATISSUE_CONCEPT_CLASSIFICATN (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  NAME       TEXT,
  PRIMARY KEY( IDENTIFIER )) ENGINE=InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE CATISSUE_REPORT_TEXTCONTENT ADD INDEX FKD74882FD91092806( REPORT_ID),
                                        ADD CONSTRAINT FKD74882FD91092806 FOREIGN KEY( REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_REPORT_TEXTCONTENT ADD INDEX FKD74882FDBC7298A9( IDENTIFIER),
                                        ADD CONSTRAINT FKD74882FDBC7298A9 FOREIGN KEY( IDENTIFIER) REFERENCES CATISSUE_REPORT_CONTENT (IDENTIFIER);

ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD INDEX FK6A2246DCBC7298A9( IDENTIFIER),
                                       ADD CONSTRAINT FK6A2246DCBC7298A9 FOREIGN KEY( IDENTIFIER) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD INDEX FK6A2246DC752DD177( DEID_REPORT),
                                       ADD CONSTRAINT FK6A2246DC752DD177 FOREIGN KEY( DEID_REPORT) REFERENCES CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);
/*TODO*/
ALTER TABLE CATISSUE_IDENTIFIED_REPORT ADD INDEX FK6A2246DC91741663( SCG_ID),
                                       ADD CONSTRAINT FK6A2246DC91741663 FOREIGN KEY( SCG_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);

ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD INDEX FK799CCA7E9F96B363( DEIDENTIFIED_REPORT_ID),
                                      ADD CONSTRAINT FK799CCA7E9F96B363 FOREIGN KEY( DEIDENTIFIED_REPORT_ID) REFERENCES CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_REVIEW_PARAMS ADD INDEX FK5311FFF62206F20F( USER_ID),
                                   ADD CONSTRAINT FK5311FFF62206F20F FOREIGN KEY( USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);

ALTER TABLE CATISSUE_REVIEW_PARAMS ADD INDEX FK5311FFF691092806( REPORT_ID),
                                   ADD CONSTRAINT FK5311FFF691092806 FOREIGN KEY( REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_REPORT_BICONTENT ADD INDEX FK8A9A4EE391092806( REPORT_ID),
                                      ADD CONSTRAINT FK8A9A4EE391092806 FOREIGN KEY( REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_REPORT_BICONTENT ADD INDEX FK8A9A4EE3BC7298A9( IDENTIFIER),
                                      ADD CONSTRAINT FK8A9A4EE3BC7298A9 FOREIGN KEY( IDENTIFIER) REFERENCES CATISSUE_REPORT_CONTENT (IDENTIFIER);

ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT ADD INDEX FKCDD0DF7BBC7298A9( IDENTIFIER),
                                         ADD CONSTRAINT FKCDD0DF7BBC7298A9 FOREIGN KEY( IDENTIFIER) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_DEIDENTIFIED_REPORT ADD INDEX FKCDD0DF7B91741663( SCG_ID),
                                         ADD CONSTRAINT FKCDD0DF7B91741663 FOREIGN KEY( SCG_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);

ALTER TABLE CATISSUE_QUARANTINE_PARAMS ADD INDEX FK3C12AE3B2206F20F( USER_ID),
                                       ADD CONSTRAINT FK3C12AE3B2206F20F FOREIGN KEY( USER_ID) REFERENCES CATISSUE_USER (IDENTIFIER);

ALTER TABLE CATISSUE_QUARANTINE_PARAMS ADD INDEX FK3C12AE3B3EEC14E3( DEID_REPORT_ID),
                                       ADD CONSTRAINT FK3C12AE3B3EEC14E3 FOREIGN KEY( DEID_REPORT_ID) REFERENCES CATISSUE_DEIDENTIFIED_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_PATHOLOGY_REPORT ADD INDEX FK904EC9F040DCD7BF( SOURCE_ID),
                                      ADD CONSTRAINT FK904EC9F040DCD7BF FOREIGN KEY( SOURCE_ID) REFERENCES CATISSUE_SITE (IDENTIFIER);

ALTER TABLE CATISSUE_REPORT_XMLCONTENT ADD INDEX FK4597C9F1BC7298A9( IDENTIFIER),
                                       ADD CONSTRAINT FK4597C9F1BC7298A9 FOREIGN KEY( IDENTIFIER) REFERENCES CATISSUE_REPORT_CONTENT (IDENTIFIER);

ALTER TABLE CATISSUE_REPORT_XMLCONTENT ADD INDEX FK4597C9F191092806( REPORT_ID),
                                       ADD CONSTRAINT FK4597C9F191092806 FOREIGN KEY( REPORT_ID) REFERENCES CATISSUE_PATHOLOGY_REPORT (IDENTIFIER);

ALTER TABLE CATISSUE_REPORT_QUEUE ADD INDEX FK214246228CA560D1( SPECIMEN_COLL_GRP_ID),
                                  ADD CONSTRAINT FK214246228CA560D1 FOREIGN KEY( SPECIMEN_COLL_GRP_ID) REFERENCES CATISSUE_SPECIMEN_COLL_GROUP (IDENTIFIER);

ALTER TABLE CATISSUE_CONCEPT ADD INDEX FKC1A3C8CC7F0C2C7( SEMANTIC_TYPE_ID),
                             ADD CONSTRAINT FKC1A3C8CC7F0C2C7 FOREIGN KEY( SEMANTIC_TYPE_ID) REFERENCES CATISSUE_SEMANTIC_TYPE (IDENTIFIER);

ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD INDEX FK799CCA7EA9816272( CONCEPT_ID),
                                      ADD CONSTRAINT FK799CCA7EA9816272 FOREIGN KEY( CONCEPT_ID) REFERENCES CATISSUE_CONCEPT (IDENTIFIER);

ALTER TABLE CATISSUE_CONCEPT_REFERENT ADD INDEX FK799CCA7E72C371DD( CONCEPT_CLASSIFICATION_ID),
                                      ADD CONSTRAINT FK799CCA7E72C371DD FOREIGN KEY( CONCEPT_CLASSIFICATION_ID) REFERENCES CATISSUE_CONCEPT_CLASSIFICATN (IDENTIFIER);

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'IdentifiedSurgicalPathologyReport',
       'IdentifiedSurgicalPathologyReport Object',
       'edu.wustl.catissuecore.domain.pathology.IdentifiedSurgicalPathologyReport',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'DeidentifiedSurgicalPathologyReport',
       'DeidentifiedSurgicalPathologyReport Object',
       'edu.wustl.catissuecore.domain.pathology.DeidentifiedSurgicalPathologyReport',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'ReportLoaderQueue',
       'ReportLoaderQueue Object',
       'edu.wustl.catissuecore.domain.pathology.ReportLoaderQueue',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Review Comments',
       'PathologyReportReviewParameter Object',
       'edu.wustl.catissuecore.domain.pathology.PathologyReportReviewParameter',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Quarantine Comments',
       'QuarantineEventParameter Object',
       'edu.wustl.catissuecore.domain.pathology.QuarantineEventParameter',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       20,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'IdentifiedSurgicalPathologyReport' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       20,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'DeidentifiedSurgicalPathologyReport' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       20,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'ReportLoaderQueue' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       20,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Review Comments' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       20,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Quarantine Comments' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

DELETE FROM CATISSUE_QUERY_TABLE_DATA
WHERE       TABLE_ID = 26;

DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA
WHERE       IDENTIFIER = 44;

DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA
WHERE       IDENTIFIER = 45;

DELETE FROM CATISSUE_INTERFACE_COLUMN_DATA
WHERE       IDENTIFIER = 46;

DELETE FROM CATISSUE_TABLE_RELATION
WHERE       RELATIONSHIP_ID = 47;

DELETE FROM CATISSUE_RELATED_TABLES_MAP
WHERE       FIRST_TABLE_ID = 26
            AND SECOND_TABLE_ID = 35;

UPDATE CATISSUE_INTERFACE_COLUMN_DATA
SET    COLUMN_NAME = 'SURGICAL_PATHOLOGY_NUMBER'
WHERE  IDENTIFIER = 215;

/*ALTER TABLE CATISSUE_CLINICAL_REPORT DROP FOREIGN KEY FK54A4264515246F7; */

/*ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP DROP FOREIGN KEY FKDEBAF1674CE21DDA; */

/* Don't drop used in another script */
/* DROP TABLE CATISSUE_CLINICAL_REPORT; */

/*ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP DROP COLUMN CLINICAL_REPORT_ID; */

/*ALTER TABLE CATISSUE_SPECIMEN_COLL_GROUP ADD COLUMN SURGICAL_PATHOLOGY_NUMBER VARCHAR(50);*/

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'IdentifiedSurgicalPathologyReport',
       'IdentifiedSurgicalPathologyReport Object',
       'edu.wustl.catissuecore.domain.pathology.IdentifiedSurgicalPathologyReport',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'DeidentifiedSurgicalPathologyReport',
       'DeidentifiedSurgicalPathologyReport Object',
       'edu.wustl.catissuecore.domain.pathology.DeidentifiedSurgicalPathologyReport',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'ReportLoaderQueue',
       'ReportLoaderQueue Object',
       'edu.wustl.catissuecore.domain.pathology.ReportLoaderQueue',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Review Comments',
       'PathologyReportReviewParameter Object',
       'edu.wustl.catissuecore.domain.pathology.PathologyReportReviewParameter',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Quarantine Comments',
       'QuarantineEventParameter Object',
       'edu.wustl.catissuecore.domain.pathology.QuarantineEventParameter',
       NULL,
       NULL,
       1,
       '2006-11-27'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
	    'edu.wustl.catissuecore.action.ConflictViewAction',
            'edu.wustl.catissuecore.action.ConflictViewAction',
            'edu.wustl.catissuecore.action.ConflictViewAction',
	    NULL,
	    NULL,
            1,
'2006-11-27' 
FROM CSM_PROTECTION_ELEMENT;






INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'IdentifiedSurgicalPathologyReport' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'DeidentifiedSurgicalPathologyReport' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'ReportLoaderQueue' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Review Comments' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE
SELECT MAX(PG_PE_ID) + 1,
       1,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  PROTECTION_ELEMENT_NAME = 'Quarantine Comments' limit 1),
       '2006-11-27'
FROM   CSM_PG_PE;

INSERT INTO CSM_PG_PE 
SELECT MAX(PG_PE_ID) +1 ,
        1,
        (select PROTECTION_ELEMENT_ID
	from csm_protection_element 
	where PROTECTION_ELEMENT_NAME='edu.wustl.catissuecore.action.ConflictViewAction' LIMIT 1),
        '2006-11-27'
FROM CSM_PG_PE;

insert into CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID) values ( 90, 'CATISSUE_REVIEW_PARAMS', 'Pathology Report Review Parameter', 'PathologyReportReviewParameter', 2);
insert into CATISSUE_QUERY_TABLE_DATA  ( TABLE_ID, TABLE_NAME, DISPLAY_NAME, ALIAS_NAME, PRIVILEGE_ID) values ( 91, 'CATISSUE_QUARANTINE_PARAMS', 'Quarantine Event Parameter', 'QuarantineEventParameter', 2);



/*caTIES Realated Tables end*/
/*Query Wizard start */

INSERT INTO CSM_PROTECTION_ELEMENT 
           (PROTECTION_ELEMENT_NAME,
            PROTECTION_ELEMENT_DESCRIPTION,
            OBJECT_ID,
            APPLICATION_ID)
VALUES     ('edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction',
            'edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction',
            'edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction',
            1);

INSERT INTO CSM_PG_PE
           (PROTECTION_GROUP_ID,
            PROTECTION_ELEMENT_ID)
VALUES     (24,
            (SELECT PROTECTION_ELEMENT_ID
             FROM   CSM_PROTECTION_ELEMENT
             WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.querysuite.AddToLimitSetAction' limit 1));

INSERT INTO CSM_PROTECTION_ELEMENT
           (PROTECTION_ELEMENT_NAME,
            PROTECTION_ELEMENT_DESCRIPTION,
            OBJECT_ID,
            APPLICATION_ID)
VALUES     ('edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction',
            'edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction',
            'edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction',
            1);

INSERT INTO CSM_PG_PE
           (PROTECTION_GROUP_ID,
            PROTECTION_ELEMENT_ID)
VALUES     (24,
            (SELECT PROTECTION_ELEMENT_ID
             FROM   CSM_PROTECTION_ELEMENT
             WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.querysuite.ViewSearchResultsAction' limit 1));

INSERT INTO CSM_PROTECTION_ELEMENT
           (PROTECTION_ELEMENT_NAME,
            PROTECTION_ELEMENT_DESCRIPTION,
            OBJECT_ID,
            APPLICATION_ID)
VALUES     ('edu.wustl.catissuecore.action.querysuite.PathFinderAction',
            'edu.wustl.catissuecore.action.querysuite.PathFinderAction',
            'edu.wustl.catissuecore.action.querysuite.PathFinderAction',
            1);

INSERT INTO CSM_PG_PE
           (PROTECTION_GROUP_ID,
            PROTECTION_ELEMENT_ID)
VALUES     (24,
            (SELECT PROTECTION_ELEMENT_ID
             FROM   CSM_PROTECTION_ELEMENT
             WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.querysuite.PathFinderAction' limit 1));

INSERT INTO CSM_PROTECTION_ELEMENT
           (PROTECTION_ELEMENT_NAME,
            PROTECTION_ELEMENT_DESCRIPTION,
            OBJECT_ID,
            APPLICATION_ID)
VALUES     ('edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction',
            'edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction',
            'edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction',
            1);

INSERT INTO CSM_PG_PE
           (PROTECTION_GROUP_ID,
            PROTECTION_ELEMENT_ID)
VALUES     (24,
            (SELECT MAX(PROTECTION_ELEMENT_ID)
             FROM   CSM_PROTECTION_ELEMENT
             WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.querysuite.GetDagViewDataAction' limit 1));


/* LOCAL EXTENSION  */

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'Local Extensions',
       'Local Extensions class',
       'edu.common.dynamicextensions.domain.integration.EntityMap',
       NULL,
       NULL,
       1,
       '2007-01-17'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction',
       'edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction',
       'edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction',
       NULL,
       NULL,
       1,
       '2007-01-17'
FROM   CSM_PROTECTION_ELEMENT;
/* LOCAL EXTENSION  */

INSERT INTO `CSM_PG_PE`
SELECT MAX(PG_PE_ID) + 1,
       17,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  OBJECT_ID = 'edu.common.dynamicextensions.domain.integration.EntityMap' limit 1),
       '0000-00-00'
FROM   CSM_PG_PE;

INSERT INTO `CSM_PG_PE`
SELECT MAX(PG_PE_ID) + 1,
       17,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.annotations.LoadAnnotationDefinitionAction' limit 1),
       '0000-00-00'
FROM   CSM_PG_PE;


/* changes for making Action a secureAction  :kalpana*/

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction',
       'edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction',
       'edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction',
       NULL,
       NULL,
       1,
       '2007-12-25'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction',
       'edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction',
       'edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction',
       NULL,
       NULL,
       1,
       '2007-12-25'
FROM   CSM_PROTECTION_ELEMENT;

INSERT INTO `CSM_PROTECTION_ELEMENT` (PROTECTION_ELEMENT_ID,PROTECTION_ELEMENT_NAME,PROTECTION_ELEMENT_DESCRIPTION,OBJECT_ID,
ATTRIBUTE,PROTECTION_ELEMENT_TYPE,APPLICATION_ID,UPDATE_DATE)
SELECT MAX(PROTECTION_ELEMENT_ID) + 1,
       'edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction',
       'edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction',
       'edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction',
       NULL,
       NULL,
       1,
       '2007-12-25'
FROM   CSM_PROTECTION_ELEMENT;



INSERT INTO `CSM_PG_PE`
SELECT MAX(PG_PE_ID) + 1,
       19,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.bulkOperations.BulkTransferEventsAction' limit 1),
       '2007-12-25'
FROM   CSM_PG_PE;

INSERT INTO `CSM_PG_PE`
SELECT MAX(PG_PE_ID) + 1,
       19,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.MultipleSpecimenFlexInitAction' limit 1),
      '2007-12-25'
FROM   CSM_PG_PE;

INSERT INTO `CSM_PG_PE`
SELECT MAX(PG_PE_ID) + 1,
       19,
       (SELECT PROTECTION_ELEMENT_ID
        FROM   CSM_PROTECTION_ELEMENT
        WHERE  OBJECT_ID = 'edu.wustl.catissuecore.action.bulkOperations.BulkDisposalEventsAction' limit 1),
       '2007-12-25'
FROM   CSM_PG_PE;

/*kalpana end */

/* Supriya :Changes to run Query on SCG in simple search Added metadata related to Abstract SCG.*/

INSERT INTO CATISSUE_QUERY_TABLE_DATA values (92, 'CATISSUE_ABS_SPECI_COLL_GROUP', 'Abstract Specimen Coll Group', 'AbstractScg',2,NULL) ;


UPDATE catissue_interface_column_data SET table_id = 92 WHERE identifier IN (210,211,212,213);


INSERT INTO catissue_interface_column_data (IDENTIFIER,TABLE_ID,COLUMN_NAME,ATTRIBUTE_TYPE) VALUES (330,92,'IDENTIFIER','bigint');


INSERT INTO catissue_table_relation values(131,35,92,NULL);


INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER) VALUES (131, 210, 'Clinical Diagnosis',1,7);

INSERT INTO CATISSUE_SEARCH_DISPLAY_DATA (RELATIONSHIP_ID, COL_ID, DISPLAY_NAME, DEFAULT_VIEW_ATTRIBUTE,ATTRIBUTE_ORDER) VALUES (131, 211, 'Clinical Status',1,8);


UPDATE CATISSUE_RELATED_TABLES_MAP SET second_table_id = 92 WHERE second_table_id = 35 AND first_table_id=3;


INSERT INTO CATISSUE_RELATED_TABLES_MAP VALUES ( 92 , 35 , 'IDENTIFIER','IDENTIFIER');


 

/*Supriya end*/



/* TODO Added in next script SCG_DbUpgrade */

/* TODO Added in next script CSMUpgrade_3_to_3.2 */
