<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Test" targetNamespace="http://wsrf.globus.org/tests/performance/basic/bindings" xmlns:porttype="http://wsrf.globus.org/tests/performance/basic" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://wsrf.globus.org/tests/performance/basic" location="basic_perf_test_port_type.wsdl"/>
  <wsdl:binding name="TestPortTypeSOAPBinding" type="porttype:TestPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="resourceDispatch">
      <soap:operation soapAction="http://wsrf.globus.org/tests/performance/basic/TestPortType/resourceDispatchRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="baseline">
      <soap:operation soapAction="http://wsrf.globus.org/tests/performance/basic/TestPortType/baselineRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
