//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.08.04 at 10:54:25 AM GMT+05:30
//


package edu.wustl.catissuecore.sop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="eventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="entityGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unique_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventType", propOrder = {
    "barcode",
    "order",
    "entityGroupName",
    "uniqueId",
    "activity"
})
public class EventType {

    protected String barcode;
    protected long order;
    @XmlElement(required = true)
    protected String entityGroupName;
    @XmlElement(name = "unique_id", required = true)
    protected String uniqueId;
    protected String activity;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the barcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * Sets the value of the barcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBarcode(String value) {
        this.barcode = value;
    }

    /**
     * Gets the value of the order property.
     *
     */
    public long getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     *
     */
    public void setOrder(long value) {
        this.order = value;
    }

    /**
     * Gets the value of the entityGroupName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEntityGroupName() {
        return entityGroupName;
    }

    /**
     * Sets the value of the entityGroupName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEntityGroupName(String value) {
        this.entityGroupName = value;
    }

    /**
     * Gets the value of the uniqueId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUniqueId(String value) {
        this.uniqueId = value;
    }

    /**
     * Gets the value of the activity property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
