CREATE SEQUENCE DYEXTN_FRM_CONTROL_SEQ;
ALTER TABLE DYEXTN_CONTAINER MODIFY CAPTION varchar2(800);
ALTER TABLE DYEXTN_CONTROL MODIFY CAPTION varchar2(800);
ALTER TABLE DYEXTN_CONTROL ADD (HEADING varchar2(255));
CREATE TABLE DYEXTN_FORM_CTRL_NOTES (
   IDENTIFIER number(19,0) not null, 
   NOTE varchar2(255), 
   FORM_CONTROL_ID number(19,0), 
   INSERTION_ORDER number(10,0), 
   primary key (IDENTIFIER)
);
ALTER TABLE DYEXTN_FORM_CTRL_NOTES add constraint FK7A0DA06B41D885B1 foreign key (FORM_CONTROL_ID) references DYEXTN_CONTROL;
ALTER TABLE DYEXTN_USERDEFINED_DE ADD (IS_ORDERED number(1,0) default 1);
