//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.05.30 at 01:53:00 PM GMT+05:30
//


package edu.wustl.catissuecore.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attributeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="attributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributeNames" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tableColumn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attributeDataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attributeType", propOrder = {
    "attributeNames",
    "tableColumn",
    "attributeDataType",
    "primaryKey"
})
public class AttributeType {

    @XmlElement(required = true)
    protected String attributeNames;
    @XmlElement(required = true)
    protected String tableColumn;
    @XmlElement(required = true)
    protected String attributeDataType;
    protected boolean primaryKey;

    /**
     * Gets the value of the attributeNames property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAttributeNames() {
        return attributeNames;
    }

    /**
     * Sets the value of the attributeNames property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAttributeNames(String value) {
        this.attributeNames = value;
    }

    /**
     * Gets the value of the tableColumn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTableColumn() {
        return tableColumn;
    }

    /**
     * Sets the value of the tableColumn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTableColumn(String value) {
        this.tableColumn = value;
    }

    /**
     * Gets the value of the attributeDataType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAttributeDataType() {
        return attributeDataType;
    }

    /**
     * Sets the value of the attributeDataType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAttributeDataType(String value) {
        this.attributeDataType = value;
    }

    /**
     * Gets the value of the primaryKey property.
     *
     */
    public boolean isPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     *
     */
    public void setPrimaryKey(boolean value) {
        this.primaryKey = value;
    }

}
