//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.05.30 at 01:53:00 PM GMT+05:30
//


package edu.wustl.catissuecore.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for staticMetaDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="staticMetaDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entities" type="{}entitiesType"/>
 *         &lt;element name="associations" type="{}associationsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "staticMetaDataType", propOrder = {
    "entities",
    "associations"
})
public class StaticMetaDataType {

    @XmlElement(required = true)
    protected EntitiesType entities;
    @XmlElement(required = true)
    protected AssociationsType associations;

    /**
     * Gets the value of the entities property.
     *
     * @return
     *     possible object is
     *     {@link EntitiesType }
     *
     */
    public EntitiesType getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     *
     * @param value
     *     allowed object is
     *     {@link EntitiesType }
     *
     */
    public void setEntities(EntitiesType value) {
        this.entities = value;
    }

    /**
     * Gets the value of the associations property.
     *
     * @return
     *     possible object is
     *     {@link AssociationsType }
     *
     */
    public AssociationsType getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     *
     * @param value
     *     allowed object is
     *     {@link AssociationsType }
     *
     */
    public void setAssociations(AssociationsType value) {
        this.associations = value;
    }

}
