<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Portions of this file Copyright 1999-2005 University of Chicago
  Portions of this file Copyright 1999-2005 The University of Southern California.
  
  This file or a portion of this file is licensed under the
  terms of the Globus Toolkit Public License, found at
  http://www.globus.org/toolkit/download/license.html.
  If you redistribute this file, with or without
  modifications, you must include this notice in the file.
-->
<definitions targetNamespace="http://wsrf.globus.org/types/profiling/wsdl"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <import location="timestamp.xsd" 
    namespace="http://wsrf.globus.org/types/profiling"/> 
  
</definitions>
