DELETE FROM DYEXTN_STRING_TYPE_INFO WHERE identifier IN (308,321,315);

INSERT INTO DYEXTN_FILE_TYPE_INFO (Identifier) VALUES(308);

INSERT INTO DYEXTN_FILE_TYPE_INFO (Identifier) VALUES(321);

INSERT INTO DYEXTN_FILE_TYPE_INFO (Identifier) VALUES(315);

INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1208);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1226);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1317);
INSERT INTO DYEXTN_TAGGED_VALUE VALUES (DYEXTN_TAGGED_VALUE_SEQ.NEXTVAL,'MetadataEntityGroup', 'MetadataEntityGroup', 1436);


