#
#  Foreign keys for table csm_group
#

ALTER TABLE `CSM_GROUP`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_pg_pe
#

ALTER TABLE `CSM_PG_PE`
  ADD FOREIGN KEY (`PROTECTION_ELEMENT_ID`) REFERENCES `CSM_PROTECTION_ELEMENT` (`PROTECTION_ELEMENT_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PROTECTION_GROUP_ID`) REFERENCES `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_protection_element
#

ALTER TABLE `CSM_PROTECTION_ELEMENT`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_protection_group
#

ALTER TABLE `CSM_PROTECTION_GROUP`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PARENT_PROTECTION_GROUP_ID`) REFERENCES `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`);


#
#  Foreign keys for table csm_role
#

ALTER TABLE `CSM_ROLE`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_role_privilege
#

ALTER TABLE `CSM_ROLE_PRIVILEGE`
  ADD FOREIGN KEY (`PRIVILEGE_ID`) REFERENCES `CSM_PRIVILEGE` (`PRIVILEGE_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`ROLE_ID`) REFERENCES `CSM_ROLE` (`ROLE_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_user_group
#

ALTER TABLE `CSM_USER_GROUP`
  ADD FOREIGN KEY (`GROUP_ID`) REFERENCES `CSM_GROUP` (`GROUP_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`USER_ID`) REFERENCES `CSM_USER` (`USER_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_user_group_role_pg
#

ALTER TABLE `CSM_USER_GROUP_ROLE_PG`
  ADD FOREIGN KEY (`GROUP_ID`) REFERENCES `CSM_GROUP` (`GROUP_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PROTECTION_GROUP_ID`) REFERENCES `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`ROLE_ID`) REFERENCES `CSM_ROLE` (`ROLE_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`USER_ID`) REFERENCES `CSM_USER` (`USER_ID`) ON DELETE CASCADE;


#
#  Foreign keys for table csm_user_pe
#

ALTER TABLE `CSM_USER_PE`
  ADD FOREIGN KEY (`USER_ID`) REFERENCES `CSM_USER` (`USER_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PROTECTION_ELEMENT_ID`) REFERENCES `CSM_PROTECTION_ELEMENT` (`PROTECTION_ELEMENT_ID`) ON DELETE CASCADE;


#!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
#!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
#!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;