<definitions name="servicetoolbeans" targetNamespace="gov.nih.nci.cagrid.servicetoolbeans"
    xmlns:tns="gov.nih.nci.cagrid.beans/servicetoolbeans" xmlns="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <schema targetNamespace="gov.nih.nci.cagrid.servicetoolbeans/beans"
            xmlns:tns="gov.nih.nci.cagrid.servicetoolbeans/beans"
            xmlns:deployment="gme://gov.nih.nci.cagrid.introduce/1/Deployment"
            xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="gme://gov.nih.nci.cagrid.introduce/1/Deployment"
                schemaLocation="./Deployment.xsd"/>
                <import namespace="gme://gov.nih.nci.cagrid.introduce/1/DeploymentValidator"
                schemaLocation="./DeploymentValidator.xsd"/>
        </schema>
    </types>
</definitions>
