IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATEGORIAL_CLASS') DROP TABLE CATEGORIAL_CLASS;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATEGORIAL_ATTRIBUTE') DROP TABLE CATEGORIAL_ATTRIBUTE;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CATEGORY') DROP TABLE CATEGORY;

create table CATEGORIAL_CLASS (
   ID bigint not null identity,
   DE_ENTITY_ID bigint,
   PATH_FROM_PARENT_ID bigint,
   PARENT_CATEGORIAL_CLASS_ID bigint,
   primary key (ID)
);

create table CATEGORIAL_ATTRIBUTE (
   ID bigint not null identity,
   CATEGORIAL_CLASS_ID bigint,
   DE_CATEGORY_ATTRIBUTE_ID bigint,
   DE_SOURCE_CLASS_ATTRIBUTE_ID bigint,
   primary key (ID)
);

create table CATEGORY (
   ID bigint not null identity,
   DE_ENTITY_ID bigint,
   PARENT_CATEGORY_ID bigint,
   ROOT_CATEGORIAL_CLASS_ID bigint unique,
   primary key (ID)
);
alter table CATEGORIAL_CLASS add constraint FK9651EF32D8D56A33 foreign key (PARENT_CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS ;
alter table CATEGORIAL_ATTRIBUTE add constraint FK31F77B56E8CBD948 foreign key (CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS ;
alter table CATEGORY add constraint FK31A8ACFE2D0F63E7 foreign key (PARENT_CATEGORY_ID) references CATEGORY ;
alter table CATEGORY add constraint FK31A8ACFE211D9A6B foreign key (ROOT_CATEGORIAL_CLASS_ID) references CATEGORIAL_CLASS ;
