alter table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS drop foreign key FK1A13AD3DBC7298A9;
alter table CATISSUE_QUERY_INTERFACE_COLUMN_DATA drop foreign key FK7C0448FAF947634C;
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION drop foreign key FK9FAF7E1B48304401;
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION drop foreign key FK9FAF7E1B87E5ADC7;
alter table CATISSUE_PERMISSIBLE_VALUE drop foreign key FK57DDCE153B5435E;
alter table CATISSUE_PERMISSIBLE_VALUE drop foreign key FK57DDCE1FC56C2B1;
alter table CATISSUE_COLLECTION_PROTOCOL drop foreign key FK32DC439DBC7298A9;
alter table CATISSUE_TISSUE_SPECIMEN drop foreign key FKB9860FA6BC7298A9;
alter table CATISSUE_CELL_SPECIMEN_REQUIREMENT drop foreign key FK4407C9ADBC7298A9;
alter table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT drop foreign key FKD0AC7D37BC7298A9;
alter table CATISSUE_STORAGE_TYPE drop foreign key FKE9A0629A5F7CB0FE;
alter table CATISSUE_SITE drop foreign key FKB024C3436CD94566;
alter table CATISSUE_SITE drop foreign key FKB024C3432206F20F;
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop foreign key FK4645C5AC3C2DAC61;
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop foreign key FK4645C5ACBC7298A9;
alter table CATISSUE_TRANSFER_EVENT_PARAMETER drop foreign key FK4645C5AC99DF0A92;
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP drop foreign key FK108D68F860773DB2;
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP drop foreign key FK108D68F8F398D480;
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT drop foreign key FK20ECDAF1BE10F0CE;
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT drop foreign key FK20ECDAF153B01F66;
alter table CATISSUE_FLUID_SPECIMEN drop foreign key FK461E42F9BC7298A9;
alter table CATISSUE_AUDIT_EVENT drop foreign key FKACAF697A2206F20F;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK92169759DCC1E13B;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK92169759A7F77D13;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK921697594CE21DDA;
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP drop foreign key FK9216975953B01F66;
alter table CATISSUE_SPECIMEN_PROTOCOL drop foreign key FKB8481373870EB740;
alter table CATISSUE_SPUN_EVENT_PARAMETERS drop foreign key FK312D77BCBC7298A9;
alter table CATISSUE_FLUID_SPECIMEN_REQUIREMENT drop foreign key FK3F2563DDBC7298A9;
alter table CATISSUE_DISPOSAL_EVENT_PARAMETERS drop foreign key FK66A78F21BC7298A9;
alter table CATISSUE_CLINICAL_REPORT drop foreign key FK54A4264DEED9EFB;
alter table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS drop foreign key FKE42CFF45BC7298A9;
alter table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER drop foreign key FK88A378F9BC7298A9;
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION drop foreign key FKE2E444726B1F36E7;
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION drop foreign key FKE2E4447248304401;
alter table CATISSUE_COLLECTION_COORDINATORS drop foreign key FK96FACDC848304401;
alter table CATISSUE_COLLECTION_COORDINATORS drop foreign key FK96FACDC82206F20F;
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT drop foreign key FK9FE639CB6B1F36E7;
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT drop foreign key FK9FE639CBBE10F0CE;
alter table CATISSUE_DISTRIBUTED_ITEM drop foreign key FKA7C3ED4B60773DB2;
alter table CATISSUE_DISTRIBUTED_ITEM drop foreign key FKA7C3ED4BF8278B6;
alter table CATISSUE_RECEIVED_EVENT_PARAMETERS drop foreign key FKC3D728F1BC7298A9;
alter table CATISSUE_FROZEN_EVENT_PARAMETERS drop foreign key FKDD06C312BC7298A9;
alter table CATISSUE_AUDIT_EVENT_LOG drop foreign key FK8BB672DF77F0B904;
alter table CATISSUE_PROCEDURE_EVENT_PARAMETERS drop foreign key FK6612CBD7BC7298A9;
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER drop foreign key FKD081FCDFA7F77D13;
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER drop foreign key FKD081FCDF87E5ADC7;
alter table CATISSUE_STORAGE_CONTAINER_DETAILS drop foreign key FK66CE30E4B3DFB11D;
alter table CATISSUE_MOLECULAR_SPECIMEN drop foreign key FKDD4D1353BC7298A9;
alter table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS drop foreign key FKD9ABD790BC7298A9;
alter table CATISSUE_SIGNUP_USER drop foreign key FK924187161792AD22;
alter table CATISSUE_SIGNUP_USER drop foreign key FK92418716FFA96920;
alter table CATISSUE_SIGNUP_USER drop foreign key FK92418716F30C2528;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D015F7CB0FE;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D01A7F77D13;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D0159A3CE5C;
alter table CATISSUE_STORAGE_CONTAINER drop foreign key FK28429D01DB097B2E;
alter table CATISSUE_DISTRIBUTION drop foreign key FK542766806B1F36E7;
alter table CATISSUE_DISTRIBUTION drop foreign key FK542766801DBE834F;
alter table CATISSUE_DISTRIBUTION drop foreign key FK54276680BC7298A9;
alter table CATISSUE_DISTRIBUTION drop foreign key FK54276680FB9AE97E;
alter table CATISSUE_EMBEDDED_EVENT_PARAMETERS drop foreign key FK1AE03F68BC7298A9;
alter table CATISSUE_AUDIT_EVENT_DETAILS drop foreign key FK5C07745D34FFD77F;
alter table CATISSUE_COLLECTION_PROTOCOL_EVENT drop foreign key FKF6A1375848304401;
alter table CATISSUE_DISTRIBUTION_PROTOCOL drop foreign key FKC8999977BC7298A9;
alter table CATISSUE_REVIEW_EVENT_PARAMETERS drop foreign key FK621FE55ABC7298A9;
alter table CATISSUE_EXTERNAL_IDENTIFIER drop foreign key FK5CF2FA2160773DB2;
alter table CATISSUE_THAW_EVENT_PARAMETERS drop foreign key FKD8890A48BC7298A9;
alter table CATISSUE_FIXED_EVENT_PARAMETERS drop foreign key FK82DC0356BC7298A9;
alter table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS drop foreign key FKE2FE9B3BBC7298A9;
alter table CATISSUE_SPECIMEN drop foreign key FK1674810456906F39;
alter table CATISSUE_SPECIMEN drop foreign key FK1674810433BF33C5;
alter table CATISSUE_SPECIMEN drop foreign key FK16748104B189E99D;
alter table CATISSUE_SPECIMEN drop foreign key FK1674810432B31EAB;
alter table CATISSUE_USER drop foreign key FKB025CFC71792AD22;
alter table CATISSUE_USER drop foreign key FKB025CFC7FFA96920;
alter table CATISSUE_USER drop foreign key FKB025CFC76CD94566;
alter table CATISSUE_USER drop foreign key FKB025CFC7F30C2528;
alter table CATISSUE_CELL_SPECIMEN drop foreign key FKCD8EE0C9BC7298A9;
alter table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT drop foreign key FK67C6950ABC7298A9;
alter table CATISSUE_COLLECTION_EVENT_PARAMETERS drop foreign key FKFB1108D4BC7298A9;
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS drop foreign key FK2C72A2AA60773DB2;
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS drop foreign key FK2C72A2AA2206F20F;
drop table if exists CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS;
drop table if exists CATISSUE_QUERY_INTERFACE_COLUMN_DATA;
drop table if exists CATISSUE_COLLECTION_PROTOCOL_REGISTRATION;
drop table if exists CATISSUE_CANCER_RESEARCH_GROUP;
drop table if exists CATISSUE_PERMISSIBLE_VALUE;
drop table if exists CATISSUE_COLLECTION_PROTOCOL;
drop table if exists CATISSUE_SPECIMEN_CHARACTERISTICS;
drop table if exists CATISSUE_TISSUE_SPECIMEN;
drop table if exists CATISSUE_CELL_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_STORAGE_TYPE;
drop table if exists CATISSUE_SITE;
drop table if exists CATISSUE_TRANSFER_EVENT_PARAMETER;
drop table if exists CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP;
drop table if exists CATISSUE_CDE;
drop table if exists CATISSUE_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_INSTITUTION;
drop table if exists CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_FLUID_SPECIMEN;
drop table if exists CATISSUE_AUDIT_EVENT;
drop table if exists CATISSUE_SPECIMEN_COLLECTION_GROUP;
drop table if exists CATISSUE_SPECIMEN_PROTOCOL;
drop table if exists CATISSUE_BIOHAZARD;
drop table if exists CATISSUE_SPUN_EVENT_PARAMETERS;
drop table if exists CATISSUE_FLUID_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_DISPOSAL_EVENT_PARAMETERS;
drop table if exists CATISSUE_CLINICAL_REPORT;
drop table if exists CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS;
drop table if exists CATISSUE_ADDRESS;
drop table if exists CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER;
drop table if exists CATISSUE_REPORTED_PROBLEM;
drop table if exists CATISSUE_COLLECTION_DISTRIBUTION_RELATION;
drop table if exists CATISSUE_COLLECTION_COORDINATORS;
drop table if exists CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_DISTRIBUTED_ITEM;
drop table if exists CATISSUE_RECEIVED_EVENT_PARAMETERS;
drop table if exists CATISSUE_PARTICIPANT;
drop table if exists CATISSUE_FROZEN_EVENT_PARAMETERS;
drop table if exists CATISSUE_AUDIT_EVENT_LOG;
drop table if exists CATISSUE_PROCEDURE_EVENT_PARAMETERS;
drop table if exists CATISSUE_QUERY_INTERFACE_TABLE_DATA;
drop table if exists CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER;
drop table if exists CATISSUE_STORAGE_CONTAINER_DETAILS;
drop table if exists CATISSUE_MOLECULAR_SPECIMEN;
drop table if exists CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS;
drop table if exists CATISSUE_SIGNUP_USER;
drop table if exists CATISSUE_STORAGE_CONTAINER;
drop table if exists CATISSUE_DISTRIBUTION;
drop table if exists CATISSUE_EMBEDDED_EVENT_PARAMETERS;
drop table if exists CATISSUE_AUDIT_EVENT_DETAILS;
drop table if exists CATISSUE_COLLECTION_PROTOCOL_EVENT;
drop table if exists CATISSUE_DISTRIBUTION_PROTOCOL;
drop table if exists CATISSUE_REVIEW_EVENT_PARAMETERS;
drop table if exists CATISSUE_DEPARTMENT;
drop table if exists CATISSUE_EXTERNAL_IDENTIFIER;
drop table if exists CATISSUE_THAW_EVENT_PARAMETERS;
drop table if exists CATISSUE_FIXED_EVENT_PARAMETERS;
drop table if exists CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS;
drop table if exists CATISSUE_SPECIMEN;
drop table if exists CATISSUE_USER;
drop table if exists CATISSUE_CELL_SPECIMEN;
drop table if exists CATISSUE_STORAGE_CONTAINER_CAPACITY;
drop table if exists CATISSUE_TISSUE_SPECIMEN_REQUIREMENT;
drop table if exists CATISSUE_COLLECTION_EVENT_PARAMETERS;
drop table if exists CATISSUE_SPECIMEN_EVENT_PARAMETERS;
create table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PERCENTAGE double precision,
   NECROSIS_PERCENTAGE double precision,
   LYMPHOCYTIC_PERCENTAGE double precision,
   TOTAL_CELLULARITY_PERCENTAGE double precision,
   HISTOLOGICAL_QUALITY varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_QUERY_INTERFACE_COLUMN_DATA (
   IDENTIFIER bigint not null auto_increment,
   TABLE_ID bigint,
   COLUMN_NAME varchar(50),
   DISPLAY_NAME varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION (
   IDENTIFIER bigint not null auto_increment,
   PROTOCOL_PARTICIPANT_IDENTIFIER varchar(50),
   REGISTRATION_DATE date,
   PARTICIPANT_ID bigint,
   COLLECTION_PROTOCOL_ID bigint,
   ACTIVITY_STATUS varchar(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_CANCER_RESEARCH_GROUP (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_PERMISSIBLE_VALUE (
   IDENTIFIER varchar(30) not null,
   CONCEPT_CODE varchar(20),
   DEFINITION text,
   EVS_CODE text,
   PARENT_IDENTIFIER varchar(30),
   VALUE varchar(100),
   PUBLIC_ID varchar(30),
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_CHARACTERISTICS (
   IDENTIFIER bigint not null auto_increment,
   TISSUE_SITE varchar(150),
   TISSUE_SIDE varchar(50),
   PATHOLOGICAL_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_TISSUE_SPECIMEN (
   IDENTIFIER bigint not null,
   QUANTITY_IN_GRAM double precision,
   AVAILABLE_QUANTITY_IN_GRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_CELL_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_CELL_COUNT integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_MICRO_GRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_TYPE (
   IDENTIFIER bigint not null auto_increment,
   TYPE varchar(50) not null unique,
   DEFAULT_TEMPERATURE_IN_CENTIGRADE double precision,
   ONE_DIMENSION_LABEL varchar(50),
   TWO_DIMENSION_LABEL varchar(50),
   STORAGE_CONTAINER_CAPACITY_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SITE (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   TYPE varchar(50),
   EMAIL_ADDRESS varchar(150),
   USER_ID bigint,
   ACTIVITY_STATUS varchar(50),
   ADDRESS_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_TRANSFER_EVENT_PARAMETER (
   IDENTIFIER bigint not null,
   FROM_POSITION_DIMENSION_ONE integer,
   FROM_POSITION_DIMENSION_TWO integer,
   TO_POSITION_DIMENSION_ONE integer,
   TO_POSITION_DIMENSION_TWO integer,
   TO_STORAGE_CONTAINER_ID bigint,
   FROM_STORAGE_CONTAINER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP (
   BIOHAZARD_ID bigint not null,
   SPECIMEN_ID bigint not null,
   primary key (SPECIMEN_ID, BIOHAZARD_ID)
);
create table CATISSUE_CDE (
   PUBLIC_ID varchar(30) not null,
   LONG_NAME varchar(200),
   DEFINITION text,
   VERSION varchar(50),
   primary key (PUBLIC_ID)
);
create table CATISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null auto_increment,
   SPECIMEN_TYPE varchar(50),
   TISSUE_SITE varchar(150),
   PATHOLOGY_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_INSTITUTION (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT (
   SPECIMEN_REQUIREMENT_ID bigint not null,
   COLLECTION_PROTOCOL_EVENT_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_EVENT_ID, SPECIMEN_REQUIREMENT_ID)
);
create table CATISSUE_FLUID_SPECIMEN (
   IDENTIFIER bigint not null,
   QUANTITY_IN_MILILITER double precision,
   AVAILABLE_QUANTITY_IN_MILILITER double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER bigint not null auto_increment,
   IP_ADDRESS varchar(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS text,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_COLLECTION_GROUP (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_DIAGNOSIS varchar(150),
   CLINICAL_STATUS varchar(50),
   ACTIVITY_STATUS varchar(50),
   SITE_ID bigint,
   COLLECTION_PROTOCOL_EVENT_ID bigint,
   CLINICAL_REPORT_ID bigint,
   COLLECTION_PROTOCOL_REGISTRATION_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_PROTOCOL (
   IDENTIFIER bigint not null auto_increment,
   PRINCIPAL_INVESTIGATOR_ID bigint,
   TITLE varchar(50) not null unique,
   SHORT_TITLE varchar(50),
   IRB_IDENTIFIER varchar(50),
   START_DATE date,
   END_DATE date,
   ENROLLMENT integer,
   DESCRIPTION_URL varchar(200),
   ACTIVITY_STATUS varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_BIOHAZARD (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50),
   COMMENTS text,
   TYPE varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPUN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   GFORCE double precision,
   DURATION_IN_MINUTES integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_FLUID_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_MILILITER double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISPOSAL_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   REASON varchar(50) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_CLINICAL_REPORT (
   IDENTIFIER bigint not null auto_increment,
   SURGICAL_PATHOLOGICAL_NUMBER varchar(50),
   PARTICIPENT_MEDICAL_IDENTIFIER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS (
   IDENTIFIER bigint not null,
   GEL_IMAGE_URL varchar(200),
   QUALITY_INDEX varchar(50),
   LANE_NUMBER varchar(50),
   GEL_NUMBER integer,
   ABSORBANCE_AT_260 double precision,
   ABSORBANCE_AT_280 double precision,
   RATIO_28S_TO_18S double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_ADDRESS (
   IDENTIFIER bigint not null auto_increment,
   STREET varchar(50),
   CITY varchar(50),
   STATE varchar(50),
   COUNTRY varchar(50),
   ZIPCODE varchar(30),
   PHONE_NUMBER varchar(50),
   FAX_NUMBER varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER (
   IDENTIFIER bigint not null,
   STORAGE_STATUS varchar(100) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_REPORTED_PROBLEM (
   SYSTEM_IDENTIFIER bigint not null auto_increment,
   AFFILIATION varchar(200) not null,
   NAME_OF_REPORTER varchar(200) not null,
   REPORTERS_EMAIL_ID varchar(50) not null,
   MESSAGE_BODY varchar(200) not null,
   SUBJECT varchar(100),
   REPORTED_DATE date,
   ACTIVITY_STATUS varchar(100),
   COMMENTS text,
   primary key (SYSTEM_IDENTIFIER)
);
create table CATISSUE_COLLECTION_DISTRIBUTION_RELATION (
   COLLECTION_PROTOCOL_ID bigint not null,
   DISTRIBUTION_PROTOCOL_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_ID, DISTRIBUTION_PROTOCOL_ID)
);
create table CATISSUE_COLLECTION_COORDINATORS (
   USER_ID bigint not null,
   COLLECTION_PROTOCOL_ID bigint not null,
   primary key (COLLECTION_PROTOCOL_ID, USER_ID)
);
create table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT (
   SPECIMEN_REQUIREMENT_ID bigint not null,
   DISTRIBUTION_PROTOCOL_ID bigint not null,
   primary key (DISTRIBUTION_PROTOCOL_ID, SPECIMEN_REQUIREMENT_ID)
);
create table CATISSUE_DISTRIBUTED_ITEM (
   IDENTIFIER bigint not null auto_increment,
   QUANTITY double precision,
   SPECIMEN_ID bigint,
   DISTRIBUTION_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_RECEIVED_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   RECEIVED_QUALITY varchar(255),
   primary key (IDENTIFIER)
);
create table CATISSUE_PARTICIPANT (
   IDENTIFIER bigint not null auto_increment,
   LAST_NAME varchar(50),
   FIRST_NAME varchar(50),
   MIDDLE_NAME varchar(50),
   BIRTH_DATE date,
   GENDER varchar(20),
   GENOTYPE varchar(50),
   RACE varchar(50),
   ETHNICITY varchar(50),
   SOCIAL_SECURITY_NUMBER varchar(50) unique,
   ACTIVITY_STATUS varchar(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_FROZEN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   METHOD varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER bigint not null auto_increment,
   OBJECT_IDENTIFIER bigint,
   OBJECT_NAME varchar(50),
   EVENT_TYPE varchar(50),
   AUDIT_EVENT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_PROCEDURE_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   URL varchar(200) not null,
   NAME varchar(50) not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_QUERY_INTERFACE_TABLE_DATA (
   TABLE_ID bigint not null auto_increment,
   DISPLAY_NAME varchar(50),
   TABLE_NAME varchar(50),
   ALIAS_NAME varchar(50),
   primary key (TABLE_ID)
);
create table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER (
   IDENTIFIER bigint not null auto_increment,
   MEDICAL_RECORD_NUMBER varchar(50),
   SITE_ID bigint,
   PARTICIPANT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER_DETAILS (
   IDENTIFIER bigint not null auto_increment,
   PARAMETER_NAME varchar(50),
   VALUE varchar(50),
   STORAGE_CONTAINER_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_MOLECULAR_SPECIMEN (
   IDENTIFIER bigint not null,
   CONCENTRATION_IN_MICROGRAM_PER_MICROLITER double precision,
   QUANTITY_IN_MICROGRAM double precision,
   AVAILABLE_QUANTITY_IN_MICROGRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   CELL_COUNT double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_SIGNUP_USER (
   IDENTIFIER bigint not null auto_increment,
   FIRST_NAME varchar(50),
   LAST_NAME varchar(50),
   LOGIN_NAME varchar(50) not null unique,
   EMAIL_ADDRESS varchar(50) not null unique,
   START_DATE date,
   ACTIVITY_STATUS varchar(50),
   DEPARTMENT_ID bigint,
   STREET varchar(50),
   CITY varchar(50),
   STATE varchar(50),
   COUNTRY varchar(50),
   ZIPCODE varchar(30),
   PHONE_NUMBER varchar(50),
   FAX_NUMBER varchar(50),
   CANCER_RESEARCH_GROUP_ID bigint,
   INSTITUTION_ID bigint,
   STATUS_COMMENT text,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER (
   IDENTIFIER bigint not null auto_increment,
   CONTAINER_NUMBER integer,
   TEMPERATURE double precision,
   IS_CONTAINER_FULL bit,
   BARCODE varchar(50) unique,
   ACTIVITY_STATUS varchar(30),
   STORAGE_TYPE_ID bigint,
   SITE_ID bigint,
   PARENT_CONTAINER_ID bigint,
   STORAGE_CONTAINER_CAPACITY_ID bigint,
   POSITION_DIMENSION_ONE integer,
   POSITION_DIMENSION_TWO integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION (
   IDENTIFIER bigint not null,
   TO_SITE_ID bigint,
   FROM_SITE_ID bigint,
   DISTRIBUTION_PROTOCOL_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_EMBEDDED_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   EMBEDDING_MEDIUM varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER bigint not null auto_increment,
   ELEMENT_NAME varchar(50),
   PREVIOUS_VALUE varchar(50),
   CURRENT_VALUE varchar(50),
   AUDIT_EVENT_LOG_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_PROTOCOL_EVENT (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_STATUS varchar(50),
   STUDY_CALENDAR_EVENT_POINT double precision,
   COLLECTION_PROTOCOL_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_DISTRIBUTION_PROTOCOL (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_REVIEW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_DEPARTMENT (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_EXTERNAL_IDENTIFIER (
   IDENTIFIER bigint not null auto_increment,
   NAME varchar(50),
   VALUE varchar(50),
   SPECIMEN_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_THAW_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);
create table CATISSUE_FIXED_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   FIXATION_TYPE varchar(50) not null,
   DURATION_IN_MINUTES integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS (
   IDENTIFIER bigint not null,
   NEOPLASTIC_CELLULARITY_PERCENTAGE double precision,
   VIABLE_CELL_PERCENTAGE double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN (
   IDENTIFIER bigint not null auto_increment,
   TYPE varchar(50),
   AVAILABLE bit,
   POSITION_DIMENSION_ONE integer,
   POSITION_DIMENSION_TWO integer,
   BARCODE varchar(50) unique,
   COMMENTS varchar(200),
   ACTIVITY_STATUS varchar(50),
   PARENT_SPECIMEN_ID bigint,
   STORAGE_CONTAINER_IDENTIFIER bigint,
   SPECIMEN_COLLECTION_GROUP_ID bigint,
   SPECIMEN_CHARACTERISTICS_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_USER (
   IDENTIFIER bigint not null,
   ACTIVITY_STATUS varchar(50),
   DEPARTMENT_ID bigint,
   CANCER_RESEARCH_GROUP_ID bigint,
   INSTITUTION_ID bigint,
   ADDRESS_ID bigint,
   STATUS_COMMENT text,
   primary key (IDENTIFIER)
);
create table CATISSUE_CELL_SPECIMEN (
   IDENTIFIER bigint not null,
   QUANTITY_IN_CELL_COUNT integer,
   AVAILABLE_QUANTITY_IN_CELL_COUNT integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_STORAGE_CONTAINER_CAPACITY (
   IDENTIFIER bigint not null auto_increment,
   ONE_DIMENSION_CAPACITY integer,
   TWO_DIMENSION_CAPACITY integer,
   primary key (IDENTIFIER)
);
create table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT (
   IDENTIFIER bigint not null,
   QUANTITY_IN_GRAM double precision,
   primary key (IDENTIFIER)
);
create table CATISSUE_COLLECTION_EVENT_PARAMETERS (
   IDENTIFIER bigint not null,
   COLLECTION_PROCEDURE varchar(50),
   CONTAINER varchar(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_SPECIMEN_EVENT_PARAMETERS (
   IDENTIFIER bigint not null auto_increment,
   SPECIMEN_ID bigint,
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS text,
   primary key (IDENTIFIER)
);
alter table CATISSUE_TISSUE_SPECIMEN_REVIEW_EVENT_PARAMETERS add index FK1A13AD3DBC7298A9 (IDENTIFIER), add constraint FK1A13AD3DBC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_QUERY_INTERFACE_COLUMN_DATA add index FK7C0448FAF947634C (TABLE_ID), add constraint FK7C0448FAF947634C foreign key (TABLE_ID) references CATISSUE_QUERY_INTERFACE_TABLE_DATA (TABLE_ID);
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION add index FK9FAF7E1B48304401 (COLLECTION_PROTOCOL_ID), add constraint FK9FAF7E1B48304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL_REGISTRATION add index FK9FAF7E1B87E5ADC7 (PARTICIPANT_ID), add constraint FK9FAF7E1B87E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT (IDENTIFIER);
alter table CATISSUE_PERMISSIBLE_VALUE add index FK57DDCE153B5435E (PARENT_IDENTIFIER), add constraint FK57DDCE153B5435E foreign key (PARENT_IDENTIFIER) references CATISSUE_PERMISSIBLE_VALUE (IDENTIFIER);
alter table CATISSUE_PERMISSIBLE_VALUE add index FK57DDCE1FC56C2B1 (PUBLIC_ID), add constraint FK57DDCE1FC56C2B1 foreign key (PUBLIC_ID) references CATISSUE_CDE (PUBLIC_ID);
alter table CATISSUE_COLLECTION_PROTOCOL add index FK32DC439DBC7298A9 (IDENTIFIER), add constraint FK32DC439DBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL (IDENTIFIER);
alter table CATISSUE_TISSUE_SPECIMEN add index FKB9860FA6BC7298A9 (IDENTIFIER), add constraint FKB9860FA6BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN_REQUIREMENT add index FK4407C9ADBC7298A9 (IDENTIFIER), add constraint FK4407C9ADBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT add index FKD0AC7D37BC7298A9 (IDENTIFIER), add constraint FKD0AC7D37BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_STORAGE_TYPE add index FKE9A0629A5F7CB0FE (STORAGE_CONTAINER_CAPACITY_ID), add constraint FKE9A0629A5F7CB0FE foreign key (STORAGE_CONTAINER_CAPACITY_ID) references CATISSUE_STORAGE_CONTAINER_CAPACITY (IDENTIFIER);
alter table CATISSUE_SITE add index FKB024C3436CD94566 (ADDRESS_ID), add constraint FKB024C3436CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS (IDENTIFIER);
alter table CATISSUE_SITE add index FKB024C3432206F20F (USER_ID), add constraint FKB024C3432206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add index FK4645C5AC3C2DAC61 (TO_STORAGE_CONTAINER_ID), add constraint FK4645C5AC3C2DAC61 foreign key (TO_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add index FK4645C5ACBC7298A9 (IDENTIFIER), add constraint FK4645C5ACBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_TRANSFER_EVENT_PARAMETER add index FK4645C5AC99DF0A92 (FROM_STORAGE_CONTAINER_ID), add constraint FK4645C5AC99DF0A92 foreign key (FROM_STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP add index FK108D68F860773DB2 (SPECIMEN_ID), add constraint FK108D68F860773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN_BIOHAZARD_RELATIONSHIP add index FK108D68F8F398D480 (BIOHAZARD_ID), add constraint FK108D68F8F398D480 foreign key (BIOHAZARD_ID) references CATISSUE_BIOHAZARD (IDENTIFIER);
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT add index FK20ECDAF1BE10F0CE (SPECIMEN_REQUIREMENT_ID), add constraint FK20ECDAF1BE10F0CE foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_COLLECTION_SPECIMEN_REQUIREMENT add index FK20ECDAF153B01F66 (COLLECTION_PROTOCOL_EVENT_ID), add constraint FK20ECDAF153B01F66 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLLECTION_PROTOCOL_EVENT (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN add index FK461E42F9BC7298A9 (IDENTIFIER), add constraint FK461E42F9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT add index FKACAF697A2206F20F (USER_ID), add constraint FKACAF697A2206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK92169759DCC1E13B (COLLECTION_PROTOCOL_REGISTRATION_ID), add constraint FK92169759DCC1E13B foreign key (COLLECTION_PROTOCOL_REGISTRATION_ID) references CATISSUE_COLLECTION_PROTOCOL_REGISTRATION (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK92169759A7F77D13 (SITE_ID), add constraint FK92169759A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK921697594CE21DDA (CLINICAL_REPORT_ID), add constraint FK921697594CE21DDA foreign key (CLINICAL_REPORT_ID) references CATISSUE_CLINICAL_REPORT (IDENTIFIER);
alter table CATISSUE_SPECIMEN_COLLECTION_GROUP add index FK9216975953B01F66 (COLLECTION_PROTOCOL_EVENT_ID), add constraint FK9216975953B01F66 foreign key (COLLECTION_PROTOCOL_EVENT_ID) references CATISSUE_COLLECTION_PROTOCOL_EVENT (IDENTIFIER);
alter table CATISSUE_SPECIMEN_PROTOCOL add index FKB8481373870EB740 (PRINCIPAL_INVESTIGATOR_ID), add constraint FKB8481373870EB740 foreign key (PRINCIPAL_INVESTIGATOR_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_SPUN_EVENT_PARAMETERS add index FK312D77BCBC7298A9 (IDENTIFIER), add constraint FK312D77BCBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN_REQUIREMENT add index FK3F2563DDBC7298A9 (IDENTIFIER), add constraint FK3F2563DDBC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_DISPOSAL_EVENT_PARAMETERS add index FK66A78F21BC7298A9 (IDENTIFIER), add constraint FK66A78F21BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_CLINICAL_REPORT add index FK54A4264DEED9EFB (PARTICIPENT_MEDICAL_IDENTIFIER_ID), add constraint FK54A4264DEED9EFB foreign key (PARTICIPENT_MEDICAL_IDENTIFIER_ID) references CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN_REVIEW_PARAMETERS add index FKE42CFF45BC7298A9 (IDENTIFIER), add constraint FKE42CFF45BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_CHECKIN_CHECKOUT_EVENT_PARAMETER add index FK88A378F9BC7298A9 (IDENTIFIER), add constraint FK88A378F9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION add index FKE2E444726B1F36E7 (DISTRIBUTION_PROTOCOL_ID), add constraint FKE2E444726B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_DISTRIBUTION_RELATION add index FKE2E4447248304401 (COLLECTION_PROTOCOL_ID), add constraint FKE2E4447248304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_COORDINATORS add index FK96FACDC848304401 (COLLECTION_PROTOCOL_ID), add constraint FK96FACDC848304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_COLLECTION_COORDINATORS add index FK96FACDC82206F20F (USER_ID), add constraint FK96FACDC82206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT add index FK9FE639CB6B1F36E7 (DISTRIBUTION_PROTOCOL_ID), add constraint FK9FE639CB6B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_SPECIMEN_REQUIREMENT add index FK9FE639CBBE10F0CE (SPECIMEN_REQUIREMENT_ID), add constraint FK9FE639CBBE10F0CE foreign key (SPECIMEN_REQUIREMENT_ID) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add index FKA7C3ED4B60773DB2 (SPECIMEN_ID), add constraint FKA7C3ED4B60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_DISTRIBUTED_ITEM add index FKA7C3ED4BF8278B6 (DISTRIBUTION_ID), add constraint FKA7C3ED4BF8278B6 foreign key (DISTRIBUTION_ID) references CATISSUE_DISTRIBUTION (IDENTIFIER);
alter table CATISSUE_RECEIVED_EVENT_PARAMETERS add index FKC3D728F1BC7298A9 (IDENTIFIER), add constraint FKC3D728F1BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_FROZEN_EVENT_PARAMETERS add index FKDD06C312BC7298A9 (IDENTIFIER), add constraint FKDD06C312BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_LOG add index FK8BB672DF77F0B904 (AUDIT_EVENT_ID), add constraint FK8BB672DF77F0B904 foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT (IDENTIFIER);
alter table CATISSUE_PROCEDURE_EVENT_PARAMETERS add index FK6612CBD7BC7298A9 (IDENTIFIER), add constraint FK6612CBD7BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER add index FKD081FCDFA7F77D13 (SITE_ID), add constraint FKD081FCDFA7F77D13 foreign key (SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_PARTICIPANT_MEDICAL_IDENTIFIER add index FKD081FCDF87E5ADC7 (PARTICIPANT_ID), add constraint FKD081FCDF87E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER_DETAILS add index FK66CE30E4B3DFB11D (STORAGE_CONTAINER_ID), add constraint FK66CE30E4B3DFB11D foreign key (STORAGE_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_MOLECULAR_SPECIMEN add index FKDD4D1353BC7298A9 (IDENTIFIER), add constraint FKDD4D1353BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_FLUID_SPECIMEN_REVIEW_EVENT_PARAMETERS add index FKD9ABD790BC7298A9 (IDENTIFIER), add constraint FKD9ABD790BC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_SIGNUP_USER add index FK924187161792AD22 (INSTITUTION_ID), add constraint FK924187161792AD22 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION (IDENTIFIER);
alter table CATISSUE_SIGNUP_USER add index FK92418716FFA96920 (CANCER_RESEARCH_GROUP_ID), add constraint FK92418716FFA96920 foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP (IDENTIFIER);
alter table CATISSUE_SIGNUP_USER add index FK92418716F30C2528 (DEPARTMENT_ID), add constraint FK92418716F30C2528 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D015F7CB0FE (STORAGE_CONTAINER_CAPACITY_ID), add constraint FK28429D015F7CB0FE foreign key (STORAGE_CONTAINER_CAPACITY_ID) references CATISSUE_STORAGE_CONTAINER_CAPACITY (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D01A7F77D13 (SITE_ID), add constraint FK28429D01A7F77D13 foreign key (SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D0159A3CE5C (STORAGE_TYPE_ID), add constraint FK28429D0159A3CE5C foreign key (STORAGE_TYPE_ID) references CATISSUE_STORAGE_TYPE (IDENTIFIER);
alter table CATISSUE_STORAGE_CONTAINER add index FK28429D01DB097B2E (PARENT_CONTAINER_ID), add constraint FK28429D01DB097B2E foreign key (PARENT_CONTAINER_ID) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK542766806B1F36E7 (DISTRIBUTION_PROTOCOL_ID), add constraint FK542766806B1F36E7 foreign key (DISTRIBUTION_PROTOCOL_ID) references CATISSUE_DISTRIBUTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK542766801DBE834F (TO_SITE_ID), add constraint FK542766801DBE834F foreign key (TO_SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK54276680BC7298A9 (IDENTIFIER), add constraint FK54276680BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION add index FK54276680FB9AE97E (FROM_SITE_ID), add constraint FK54276680FB9AE97E foreign key (FROM_SITE_ID) references CATISSUE_SITE (IDENTIFIER);
alter table CATISSUE_EMBEDDED_EVENT_PARAMETERS add index FK1AE03F68BC7298A9 (IDENTIFIER), add constraint FK1AE03F68BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_DETAILS add index FK5C07745D34FFD77F (AUDIT_EVENT_LOG_ID), add constraint FK5C07745D34FFD77F foreign key (AUDIT_EVENT_LOG_ID) references CATISSUE_AUDIT_EVENT_LOG (IDENTIFIER);
alter table CATISSUE_COLLECTION_PROTOCOL_EVENT add index FKF6A1375848304401 (COLLECTION_PROTOCOL_ID), add constraint FKF6A1375848304401 foreign key (COLLECTION_PROTOCOL_ID) references CATISSUE_COLLECTION_PROTOCOL (IDENTIFIER);
alter table CATISSUE_DISTRIBUTION_PROTOCOL add index FKC8999977BC7298A9 (IDENTIFIER), add constraint FKC8999977BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL (IDENTIFIER);
alter table CATISSUE_REVIEW_EVENT_PARAMETERS add index FK621FE55ABC7298A9 (IDENTIFIER), add constraint FK621FE55ABC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_EXTERNAL_IDENTIFIER add index FK5CF2FA2160773DB2 (SPECIMEN_ID), add constraint FK5CF2FA2160773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_THAW_EVENT_PARAMETERS add index FKD8890A48BC7298A9 (IDENTIFIER), add constraint FKD8890A48BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_FIXED_EVENT_PARAMETERS add index FK82DC0356BC7298A9 (IDENTIFIER), add constraint FK82DC0356BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN_REVIEW_PARAMETERS add index FKE2FE9B3BBC7298A9 (IDENTIFIER), add constraint FKE2FE9B3BBC7298A9 foreign key (IDENTIFIER) references CATISSUE_REVIEW_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK1674810456906F39 (SPECIMEN_CHARACTERISTICS_ID), add constraint FK1674810456906F39 foreign key (SPECIMEN_CHARACTERISTICS_ID) references CATISSUE_SPECIMEN_CHARACTERISTICS (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK1674810433BF33C5 (SPECIMEN_COLLECTION_GROUP_ID), add constraint FK1674810433BF33C5 foreign key (SPECIMEN_COLLECTION_GROUP_ID) references CATISSUE_SPECIMEN_COLLECTION_GROUP (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK16748104B189E99D (PARENT_SPECIMEN_ID), add constraint FK16748104B189E99D foreign key (PARENT_SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN add index FK1674810432B31EAB (STORAGE_CONTAINER_IDENTIFIER), add constraint FK1674810432B31EAB foreign key (STORAGE_CONTAINER_IDENTIFIER) references CATISSUE_STORAGE_CONTAINER (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC71792AD22 (INSTITUTION_ID), add constraint FKB025CFC71792AD22 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC7FFA96920 (CANCER_RESEARCH_GROUP_ID), add constraint FKB025CFC7FFA96920 foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC76CD94566 (ADDRESS_ID), add constraint FKB025CFC76CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS (IDENTIFIER);
alter table CATISSUE_USER add index FKB025CFC7F30C2528 (DEPARTMENT_ID), add constraint FKB025CFC7F30C2528 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT (IDENTIFIER);
alter table CATISSUE_CELL_SPECIMEN add index FKCD8EE0C9BC7298A9 (IDENTIFIER), add constraint FKCD8EE0C9BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT add index FK67C6950ABC7298A9 (IDENTIFIER), add constraint FK67C6950ABC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_REQUIREMENT (IDENTIFIER);
alter table CATISSUE_COLLECTION_EVENT_PARAMETERS add index FKFB1108D4BC7298A9 (IDENTIFIER), add constraint FKFB1108D4BC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_EVENT_PARAMETERS (IDENTIFIER);
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS add index FK2C72A2AA60773DB2 (SPECIMEN_ID), add constraint FK2C72A2AA60773DB2 foreign key (SPECIMEN_ID) references CATISSUE_SPECIMEN (IDENTIFIER);
alter table CATISSUE_SPECIMEN_EVENT_PARAMETERS add index FK2C72A2AA2206F20F (USER_ID), add constraint FK2C72A2AA2206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
