#Update Specimen requirement tables

ALTER TABLE CATISSUE_SPECIMEN_REQUIREMENT ADD COLUMN SPECIMEN_CLASS varchar(255);
ALTER TABLE CATISSUE_SPECIMEN_REQUIREMENT ADD COLUMN QUANTITY double;

UPDATE CATISSUE_SPECIMEN_REQUIREMENT,CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT set SPECIMEN_CLASS = 'Molecular' , QUANTITY = QUANTITY_IN_MICRO_GRAM where CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT.IDENTIFIER = CATISSUE_SPECIMEN_REQUIREMENT.IDENTIFIER;

UPDATE CATISSUE_SPECIMEN_REQUIREMENT,CATISSUE_TISSUE_SPECIMEN_REQUIREMENT set SPECIMEN_CLASS = 'Tissue' , QUANTITY = QUANTITY_IN_GRAM where CATISSUE_TISSUE_SPECIMEN_REQUIREMENT.IDENTIFIER = CATISSUE_SPECIMEN_REQUIREMENT.IDENTIFIER;

UPDATE CATISSUE_SPECIMEN_REQUIREMENT,CATISSUE_CELL_SPECIMEN_REQUIREMENT SET SPECIMEN_CLASS = 'Cell' , QUANTITY = QUANTITY_IN_CELL_COUNT where CATISSUE_CELL_SPECIMEN_REQUIREMENT.IDENTIFIER = CATISSUE_SPECIMEN_REQUIREMENT.IDENTIFIER;

UPDATE CATISSUE_SPECIMEN_REQUIREMENT,CATISSUE_FLUID_SPECIMEN_REQUIREMENT SET SPECIMEN_CLASS = 'Fluid' , QUANTITY = QUANTITY_IN_MILILITER where CATISSUE_FLUID_SPECIMEN_REQUIREMENT.IDENTIFIER = CATISSUE_SPECIMEN_REQUIREMENT.IDENTIFIER;


drop table CATISSUE_FLUID_SPECIMEN_REQUIREMENT;
drop table CATISSUE_CELL_SPECIMEN_REQUIREMENT;
drop table CATISSUE_MOLECULAR_SPECIMEN_REQUIREMENT;
drop table CATISSUE_TISSUE_SPECIMEN_REQUIREMENT;



#Update Specimen tables

ALTER TABLE CATISSUE_SPECIMEN ADD COLUMN SPECIMEN_CLASS varchar(255);
ALTER TABLE CATISSUE_SPECIMEN ADD COLUMN QUANTITY double;
ALTER TABLE CATISSUE_SPECIMEN ADD COLUMN AVAILABLE_QUANTITY double;
ALTER TABLE CATISSUE_SPECIMEN ADD COLUMN CONCENTRATION double;


UPDATE CATISSUE_SPECIMEN, CATISSUE_MOLECULAR_SPECIMEN SET SPECIMEN_CLASS = 'Molecular' , QUANTITY = QUANTITY_IN_MICROGRAM, 
AVAILABLE_QUANTITY = AVAILABLE_QUANTITY_IN_MICROGRAM, 
CONCENTRATION = CONCENTRATION_IN_MICROGRAM_PER_MICROLITER 
where CATISSUE_MOLECULAR_SPECIMEN.IDENTIFIER = CATISSUE_SPECIMEN.IDENTIFIER;

UPDATE CATISSUE_SPECIMEN, CATISSUE_TISSUE_SPECIMEN SET SPECIMEN_CLASS = 'Tissue' , QUANTITY = QUANTITY_IN_GRAM,
AVAILABLE_QUANTITY = AVAILABLE_QUANTITY_IN_GRAM 
where CATISSUE_TISSUE_SPECIMEN.IDENTIFIER = CATISSUE_SPECIMEN.IDENTIFIER;

UPDATE CATISSUE_SPECIMEN, CATISSUE_CELL_SPECIMEN SET SPECIMEN_CLASS = 'Cell' , QUANTITY = QUANTITY_IN_CELL_COUNT,
AVAILABLE_QUANTITY = AVAILABLE_QUANTITY_IN_CELL_COUNT 
where CATISSUE_CELL_SPECIMEN.IDENTIFIER = CATISSUE_SPECIMEN.IDENTIFIER;

UPDATE CATISSUE_SPECIMEN, CATISSUE_FLUID_SPECIMEN SET SPECIMEN_CLASS = 'Fluid' , QUANTITY = QUANTITY_IN_MILILITER,
AVAILABLE_QUANTITY = AVAILABLE_QUANTITY_IN_MILILITER  
where CATISSUE_FLUID_SPECIMEN.IDENTIFIER = CATISSUE_SPECIMEN.IDENTIFIER;

drop table CATISSUE_FLUID_SPECIMEN;
drop table CATISSUE_CELL_SPECIMEN;
drop table CATISSUE_MOLECULAR_SPECIMEN;
drop table CATISSUE_TISSUE_SPECIMEN;

