//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.16 at 07:41:18 GMT
//


package edu.wustl.cider.jaxb.domain;


/**
 * Java content class for CollectionProtocolType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/G:/specimen_new.xsd line 85)
 * <p>
 * <pre>
 * &lt;complexType name="CollectionProtocolType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrincipalInvestigator" type="{}PrincipalInvestigatorType" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface CollectionProtocolType {


    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTitle();

    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTitle(java.lang.String value);

    /**
     * Gets the value of the principalInvestigator property.
     *
     * @return
     *     possible object is
     *     {@link generated.PrincipalInvestigatorType}
     */
    PrincipalInvestigatorType getPrincipalInvestigator();

    /**
     * Sets the value of the principalInvestigator property.
     *
     * @param value
     *     allowed object is
     *     {@link generated.PrincipalInvestigatorType}
     */
    void setPrincipalInvestigator(PrincipalInvestigatorType value);

}
