//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.16 at 07:41:18 GMT
//


package edu.wustl.cider.jaxb.domain;


/**
 * Java content class for CollectionProtocolRegistrationType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/G:/specimen_new.xsd line 10)
 * <p>
 * <pre>
 * &lt;complexType name="CollectionProtocolRegistrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CollectionProtocol" type="{}CollectionProtocolType" minOccurs="0"/>
 *         &lt;element name="SCGCollection" type="{}SCGCollectionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface CollectionProtocolRegistrationType {


    /**
     * Gets the value of the collectionProtocol property.
     *
     * @return
     *     possible object is
     *     {@link CollectionProtocolType}
     */
    CollectionProtocolType getCollectionProtocol();

    /**
     * Sets the value of the collectionProtocol property.
     *
     * @param value
     *     allowed object is
     *     {@link CollectionProtocolType}
     */
    void setCollectionProtocol(CollectionProtocolType value);

    /**
     * Gets the value of the scgCollection property.
     *
     * @return
     *     possible object is
     *     {@link SCGCollectionType}
     */
    SCGCollectionType getSCGCollection();

    /**
     * Sets the value of the scgCollection property.
     *
     * @param value
     *     allowed object is
     *     {@link SCGCollectionType}
     */
    void setSCGCollection(SCGCollectionType value);

}
