//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.16 at 07:41:18 GMT
//


package edu.wustl.cider.jaxb.domain;


/**
 * Java content class for ParticipantType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/G:/specimen_new.xsd line 4)
 * <p>
 * <pre>
 * &lt;complexType name="ParticipantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Empi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CollectionProtocolRegistration" type="{}CollectionProtocolRegistrationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface ParticipantType {


    /**
     * Gets the value of the collectionProtocolRegistration property.
     *
     * @return
     *     possible object is
     *     {@link generated.CollectionProtocolRegistrationType}
     */
    CollectionProtocolRegistrationType getCollectionProtocolRegistration();

    /**
     * Sets the value of the collectionProtocolRegistration property.
     *
     * @param value
     *     allowed object is
     *     {@link generated.CollectionProtocolRegistrationType}
     */
    void setCollectionProtocolRegistration(CollectionProtocolRegistrationType value);

    /**
     * Gets the value of the empi property.
     *
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getEmpi();

    /**
     * Sets the value of the empi property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setEmpi(java.lang.String value);

}
