//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 07:41:18 GMT 
//


package edu.wustl.cider.jaxb.domain;


/**
 * Java content class for SpecimenCharacteristicsType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/G:/specimen_new.xsd line 80)
 * <p>
 * <pre>
 * &lt;complexType name="SpecimenCharacteristicsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TissueSite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SpecimenCharacteristicsType {


    /**
     * Gets the value of the tissueSite property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTissueSite();

    /**
     * Sets the value of the tissueSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTissueSite(java.lang.String value);

}
