//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 11:16:21 CST 
//


package edu.wustl.cider.jaxb.domain;


/**
 * Java content class for SpecimenMessageType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Users/pkalantri/Documents/caTissue/specimen_new.xsd line 5)
 * <p>
 * <pre>
 * &lt;complexType name="SpecimenMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="messageTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Participant" type="{}ParticipantType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SpecimenMessageType {


    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link edu.wustl.cider.jaxb.domain.ParticipantType}
     */
    edu.wustl.cider.jaxb.domain.ParticipantType getParticipant();

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.wustl.cider.jaxb.domain.ParticipantType}
     */
    void setParticipant(edu.wustl.cider.jaxb.domain.ParticipantType value);

    /**
     * Gets the value of the messageTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getMessageTimeStamp();

    /**
     * Sets the value of the messageTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setMessageTimeStamp(java.util.Calendar value);

}
