//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 11:16:21 CST 
//


package edu.wustl.cider.jaxb.domain;


/**
 * Java content class for SpecimenMessage element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Users/pkalantri/Documents/caTissue/specimen_new.xsd line 4)
 * <p>
 * <pre>
 * &lt;element name="SpecimenMessage" type="{}SpecimenMessageType"/>
 * </pre>
 * 
 */
public interface SpecimenMessage
    extends javax.xml.bind.Element, edu.wustl.cider.jaxb.domain.SpecimenMessageType
{


}
